In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import akita_utils_forplotting as utils
import numpy as np
import pandas as pd
import sys, os, psutil, time
import matplotlib.pyplot as plt
import pysam
    
from skimage.transform import resize


#from optparse import OptionParser


nt = ['A', 'T', 'C', 'G']

2024-12-05 22:40:23.204754: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pollard/home/shzhang/miniconda3/envs/dchic1/lib/R/library
2024-12-05 22:40:23.204789: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-12-05 22:40:31.278942: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pollard/home/shzhang/miniconda3/envs/dchic1/lib/R/library
2024-12-05 22:40:31.278974: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-12-05 22:40:31.278993: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bueno.gladstone.internal): /proc/driver/nvidia/version does not exist
2024-12-05 22:40:31.280905: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 sequence (InputLayer)          [(None, 1048576, 4)  0           []
                                ]

 stochastic_reverse_complement   ((None, 1048576, 4)  0          ['sequence[0][0]']
 (StochasticReverseComplement)  , ())

 stochastic_shift (StochasticSh  (None, 1048576, 4)  0           ['stochastic_reverse_complement[0
 ift)                                                            ][0]']

 re_lu (ReLU)                   (None, 1048576, 4)   0           ['stochastic_shift[0][0]']

 conv1d (Conv1D)                (None, 1048576, 96)  4224        ['re_lu[0][0]']

 batch_normalization (BatchNorm  (None, 1048576, 96)  384        ['conv1d[0][0]']
 alization)

 max_pooling1d (MaxPooling1D)   (None, 524288, 96)   0           ['batch_normalization[0][0]']

 re_lu_1 (ReLU)                 (None, 524288, 96)   0           ['max_pooling1d[0][0]']

 conv1d_1 (Conv1D)              (None, 524288, 96)   46080       ['re_lu_1[0][0]']

 batch_normalization_1 (BatchNo  (None, 524288, 96)  384         ['conv1d_1[0][0]']
 rmalization)

 max_pooling1d_1 (MaxPooling1D)  (None, 262144, 96)  0           ['batch_normalization_1[0][0]']

 re_lu_2 (ReLU)                 (None, 262144, 96)   0           ['max_pooling1d_1[0][0]']

 conv1d_2 (Conv1D)              (None, 262144, 96)   46080       ['re_lu_2[0][0]']

 batch_normalization_2 (BatchNo  (None, 262144, 96)  384         ['conv1d_2[0][0]']
 rmalization)

 max_pooling1d_2 (MaxPooling1D)  (None, 131072, 96)  0           ['batch_normalization_2[0][0]']

 re_lu_3 (ReLU)                 (None, 131072, 96)   0           ['max_pooling1d_2[0][0]']

 conv1d_3 (Conv1D)              (None, 131072, 96)   46080       ['re_lu_3[0][0]']

 batch_normalization_3 (BatchNo  (None, 131072, 96)  384         ['conv1d_3[0][0]']
 rmalization)

 max_pooling1d_3 (MaxPooling1D)  (None, 65536, 96)   0           ['batch_normalization_3[0][0]']

 re_lu_4 (ReLU)                 (None, 65536, 96)    0           ['max_pooling1d_3[0][0]']

 conv1d_4 (Conv1D)              (None, 65536, 96)    46080       ['re_lu_4[0][0]']

 batch_normalization_4 (BatchNo  (None, 65536, 96)   384         ['conv1d_4[0][0]']
 rmalization)

 max_pooling1d_4 (MaxPooling1D)  (None, 32768, 96)   0           ['batch_normalization_4[0][0]']

 re_lu_5 (ReLU)                 (None, 32768, 96)    0           ['max_pooling1d_4[0][0]']

 conv1d_5 (Conv1D)              (None, 32768, 96)    46080       ['re_lu_5[0][0]']

 batch_normalization_5 (BatchNo  (None, 32768, 96)   384         ['conv1d_5[0][0]']
 rmalization)

 max_pooling1d_5 (MaxPooling1D)  (None, 16384, 96)   0           ['batch_normalization_5[0][0]']

 re_lu_6 (ReLU)                 (None, 16384, 96)    0           ['max_pooling1d_5[0][0]']

 conv1d_6 (Conv1D)              (None, 16384, 96)    46080       ['re_lu_6[0][0]']

 batch_normalization_6 (BatchNo  (None, 16384, 96)   384         ['conv1d_6[0][0]']
 rmalization)

 max_pooling1d_6 (MaxPooling1D)  (None, 8192, 96)    0           ['batch_normalization_6[0][0]']

 re_lu_7 (ReLU)                 (None, 8192, 96)     0           ['max_pooling1d_6[0][0]']

 conv1d_7 (Conv1D)              (None, 8192, 96)     46080       ['re_lu_7[0][0]']

 batch_normalization_7 (BatchNo  (None, 8192, 96)    384         ['conv1d_7[0][0]']
 rmalization)

 max_pooling1d_7 (MaxPooling1D)  (None, 4096, 96)    0           ['batch_normalization_7[0][0]']

 re_lu_8 (ReLU)                 (None, 4096, 96)     0           ['max_pooling1d_7[0][0]']

 conv1d_8 (Conv1D)              (None, 4096, 96)     46080       ['re_lu_8[0][0]']

 batch_normalization_8 (BatchNo  (None, 4096, 96)    384         ['conv1d_8[0][0]']
 rmalization)

 max_pooling1d_8 (MaxPooling1D)  (None, 2048, 96)    0           ['batch_normalization_8[0][0]']

 re_lu_9 (ReLU)                 (None, 2048, 96)     0           ['max_pooling1d_8[0][0]']

 conv1d_9 (Conv1D)              (None, 2048, 96)     46080       ['re_lu_9[0][0]']

 batch_normalization_9 (BatchNo  (None, 2048, 96)    384         ['conv1d_9[0][0]']
 rmalization)

 max_pooling1d_9 (MaxPooling1D)  (None, 1024, 96)    0           ['batch_normalization_9[0][0]']

 re_lu_10 (ReLU)                (None, 1024, 96)     0           ['max_pooling1d_9[0][0]']

 conv1d_10 (Conv1D)             (None, 1024, 96)     46080       ['re_lu_10[0][0]']

 batch_normalization_10 (BatchN  (None, 1024, 96)    384         ['conv1d_10[0][0]']
 ormalization)

 max_pooling1d_10 (MaxPooling1D  (None, 512, 96)     0           ['batch_normalization_10[0][0]']
 )

 re_lu_11 (ReLU)                (None, 512, 96)      0           ['max_pooling1d_10[0][0]']

 conv1d_11 (Conv1D)             (None, 512, 48)      13824       ['re_lu_11[0][0]']

 batch_normalization_11 (BatchN  (None, 512, 48)     192         ['conv1d_11[0][0]']
 ormalization)

 re_lu_12 (ReLU)                (None, 512, 48)      0           ['batch_normalization_11[0][0]']

 conv1d_12 (Conv1D)             (None, 512, 96)      4608        ['re_lu_12[0][0]']

 batch_normalization_12 (BatchN  (None, 512, 96)     384         ['conv1d_12[0][0]']
 ormalization)

 dropout (Dropout)              (None, 512, 96)      0           ['batch_normalization_12[0][0]']

 add (Add)                      (None, 512, 96)      0           ['max_pooling1d_10[0][0]',
                                                                  'dropout[0][0]']

 re_lu_13 (ReLU)                (None, 512, 96)      0           ['add[0][0]']

 conv1d_13 (Conv1D)             (None, 512, 48)      13824       ['re_lu_13[0][0]']

 batch_normalization_13 (BatchN  (None, 512, 48)     192         ['conv1d_13[0][0]']
 ormalization)

 re_lu_14 (ReLU)                (None, 512, 48)      0           ['batch_normalization_13[0][0]']

 conv1d_14 (Conv1D)             (None, 512, 96)      4608        ['re_lu_14[0][0]']

 batch_normalization_14 (BatchN  (None, 512, 96)     384         ['conv1d_14[0][0]']
 ormalization)

 dropout_1 (Dropout)            (None, 512, 96)      0           ['batch_normalization_14[0][0]']

 add_1 (Add)                    (None, 512, 96)      0           ['add[0][0]',
                                                                  'dropout_1[0][0]']

 re_lu_15 (ReLU)                (None, 512, 96)      0           ['add_1[0][0]']

 conv1d_15 (Conv1D)             (None, 512, 48)      13824       ['re_lu_15[0][0]']

 batch_normalization_15 (BatchN  (None, 512, 48)     192         ['conv1d_15[0][0]']
 ormalization)

 re_lu_16 (ReLU)                (None, 512, 48)      0           ['batch_normalization_15[0][0]']

 conv1d_16 (Conv1D)             (None, 512, 96)      4608        ['re_lu_16[0][0]']

 batch_normalization_16 (BatchN  (None, 512, 96)     384         ['conv1d_16[0][0]']
 ormalization)

 dropout_2 (Dropout)            (None, 512, 96)      0           ['batch_normalization_16[0][0]']

 add_2 (Add)                    (None, 512, 96)      0           ['add_1[0][0]',
                                                                  'dropout_2[0][0]']

 re_lu_17 (ReLU)                (None, 512, 96)      0           ['add_2[0][0]']

 conv1d_17 (Conv1D)             (None, 512, 48)      13824       ['re_lu_17[0][0]']

 batch_normalization_17 (BatchN  (None, 512, 48)     192         ['conv1d_17[0][0]']
 ormalization)

 re_lu_18 (ReLU)                (None, 512, 48)      0           ['batch_normalization_17[0][0]']

 conv1d_18 (Conv1D)             (None, 512, 96)      4608        ['re_lu_18[0][0]']

 batch_normalization_18 (BatchN  (None, 512, 96)     384         ['conv1d_18[0][0]']
 ormalization)

 dropout_3 (Dropout)            (None, 512, 96)      0           ['batch_normalization_18[0][0]']

 add_3 (Add)                    (None, 512, 96)      0           ['add_2[0][0]',
                                                                  'dropout_3[0][0]']

 re_lu_19 (ReLU)                (None, 512, 96)      0           ['add_3[0][0]']

 conv1d_19 (Conv1D)             (None, 512, 48)      13824       ['re_lu_19[0][0]']

 batch_normalization_19 (BatchN  (None, 512, 48)     192         ['conv1d_19[0][0]']
 ormalization)

 re_lu_20 (ReLU)                (None, 512, 48)      0           ['batch_normalization_19[0][0]']

 conv1d_20 (Conv1D)             (None, 512, 96)      4608        ['re_lu_20[0][0]']

 batch_normalization_20 (BatchN  (None, 512, 96)     384         ['conv1d_20[0][0]']
 ormalization)

 dropout_4 (Dropout)            (None, 512, 96)      0           ['batch_normalization_20[0][0]']

 add_4 (Add)                    (None, 512, 96)      0           ['add_3[0][0]',
                                                                  'dropout_4[0][0]']

 re_lu_21 (ReLU)                (None, 512, 96)      0           ['add_4[0][0]']

 conv1d_21 (Conv1D)             (None, 512, 48)      13824       ['re_lu_21[0][0]']

 batch_normalization_21 (BatchN  (None, 512, 48)     192         ['conv1d_21[0][0]']
 ormalization)

 re_lu_22 (ReLU)                (None, 512, 48)      0           ['batch_normalization_21[0][0]']

 conv1d_22 (Conv1D)             (None, 512, 96)      4608        ['re_lu_22[0][0]']

 batch_normalization_22 (BatchN  (None, 512, 96)     384         ['conv1d_22[0][0]']
 ormalization)

 dropout_5 (Dropout)            (None, 512, 96)      0           ['batch_normalization_22[0][0]']

 add_5 (Add)                    (None, 512, 96)      0           ['add_4[0][0]',
                                                                  'dropout_5[0][0]']

 re_lu_23 (ReLU)                (None, 512, 96)      0           ['add_5[0][0]']

 conv1d_23 (Conv1D)             (None, 512, 48)      13824       ['re_lu_23[0][0]']

 batch_normalization_23 (BatchN  (None, 512, 48)     192         ['conv1d_23[0][0]']
 ormalization)

 re_lu_24 (ReLU)                (None, 512, 48)      0           ['batch_normalization_23[0][0]']

 conv1d_24 (Conv1D)             (None, 512, 96)      4608        ['re_lu_24[0][0]']

 batch_normalization_24 (BatchN  (None, 512, 96)     384         ['conv1d_24[0][0]']
 ormalization)

 dropout_6 (Dropout)            (None, 512, 96)      0           ['batch_normalization_24[0][0]']

 add_6 (Add)                    (None, 512, 96)      0           ['add_5[0][0]',
                                                                  'dropout_6[0][0]']

 re_lu_25 (ReLU)                (None, 512, 96)      0           ['add_6[0][0]']

 conv1d_25 (Conv1D)             (None, 512, 48)      13824       ['re_lu_25[0][0]']

 batch_normalization_25 (BatchN  (None, 512, 48)     192         ['conv1d_25[0][0]']
 ormalization)

 re_lu_26 (ReLU)                (None, 512, 48)      0           ['batch_normalization_25[0][0]']

 conv1d_26 (Conv1D)             (None, 512, 96)      4608        ['re_lu_26[0][0]']

 batch_normalization_26 (BatchN  (None, 512, 96)     384         ['conv1d_26[0][0]']
 ormalization)

 dropout_7 (Dropout)            (None, 512, 96)      0           ['batch_normalization_26[0][0]']

 add_7 (Add)                    (None, 512, 96)      0           ['add_6[0][0]',
                                                                  'dropout_7[0][0]']

 re_lu_27 (ReLU)                (None, 512, 96)      0           ['add_7[0][0]']

 conv1d_27 (Conv1D)             (None, 512, 64)      30720       ['re_lu_27[0][0]']

 batch_normalization_27 (BatchN  (None, 512, 64)     256         ['conv1d_27[0][0]']
 ormalization)

 re_lu_28 (ReLU)                (None, 512, 64)      0           ['batch_normalization_27[0][0]']

 one_to_two (OneToTwo)          (None, 512, 512, 64  0           ['re_lu_28[0][0]']
                                )

 concat_dist2d (ConcatDist2D)   (None, 512, 512, 65  0           ['one_to_two[0][0]']
                                )

 re_lu_29 (ReLU)                (None, 512, 512, 65  0           ['concat_dist2d[0][0]']
                                )

 conv2d (Conv2D)                (None, 512, 512, 48  28080       ['re_lu_29[0][0]']
                                )

 batch_normalization_28 (BatchN  (None, 512, 512, 48  192        ['conv2d[0][0]']
 ormalization)                  )

 symmetrize2d (Symmetrize2D)    (None, 512, 512, 48  0           ['batch_normalization_28[0][0]']
                                )

 re_lu_30 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d[0][0]']
                                )

 conv2d_1 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_30[0][0]']
                                )

 batch_normalization_29 (BatchN  (None, 512, 512, 24  96         ['conv2d_1[0][0]']
 ormalization)                  )

 re_lu_31 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_29[0][0]']
                                )

 conv2d_2 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_31[0][0]']
                                )

 batch_normalization_30 (BatchN  (None, 512, 512, 48  192        ['conv2d_2[0][0]']
 ormalization)                  )

 dropout_8 (Dropout)            (None, 512, 512, 48  0           ['batch_normalization_30[0][0]']
                                )

 add_8 (Add)                    (None, 512, 512, 48  0           ['symmetrize2d[0][0]',
                                )                                 'dropout_8[0][0]']

 symmetrize2d_1 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_8[0][0]']
                                )

 re_lu_32 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_1[0][0]']
                                )

 conv2d_3 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_32[0][0]']
                                )

 batch_normalization_31 (BatchN  (None, 512, 512, 24  96         ['conv2d_3[0][0]']
 ormalization)                  )

 re_lu_33 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_31[0][0]']
                                )

 conv2d_4 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_33[0][0]']
                                )

 batch_normalization_32 (BatchN  (None, 512, 512, 48  192        ['conv2d_4[0][0]']
 ormalization)                  )

 dropout_9 (Dropout)            (None, 512, 512, 48  0           ['batch_normalization_32[0][0]']
                                )

 add_9 (Add)                    (None, 512, 512, 48  0           ['symmetrize2d_1[0][0]',
                                )                                 'dropout_9[0][0]']

 symmetrize2d_2 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_9[0][0]']
                                )

 re_lu_34 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_2[0][0]']
                                )

 conv2d_5 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_34[0][0]']
                                )

 batch_normalization_33 (BatchN  (None, 512, 512, 24  96         ['conv2d_5[0][0]']
 ormalization)                  )

 re_lu_35 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_33[0][0]']
                                )

 conv2d_6 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_35[0][0]']
                                )

 batch_normalization_34 (BatchN  (None, 512, 512, 48  192        ['conv2d_6[0][0]']
 ormalization)                  )

 dropout_10 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_34[0][0]']
                                )

 add_10 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_2[0][0]',
                                )                                 'dropout_10[0][0]']

 symmetrize2d_3 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_10[0][0]']
                                )

 re_lu_36 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_3[0][0]']
                                )

 conv2d_7 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_36[0][0]']
                                )

 batch_normalization_35 (BatchN  (None, 512, 512, 24  96         ['conv2d_7[0][0]']
 ormalization)                  )

 re_lu_37 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_35[0][0]']
                                )

 conv2d_8 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_37[0][0]']
                                )

 batch_normalization_36 (BatchN  (None, 512, 512, 48  192        ['conv2d_8[0][0]']
 ormalization)                  )

 dropout_11 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_36[0][0]']
                                )

 add_11 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_3[0][0]',
                                )                                 'dropout_11[0][0]']

 symmetrize2d_4 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_11[0][0]']
                                )

 re_lu_38 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_4[0][0]']
                                )

 conv2d_9 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_38[0][0]']
                                )

 batch_normalization_37 (BatchN  (None, 512, 512, 24  96         ['conv2d_9[0][0]']
 ormalization)                  )

 re_lu_39 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_37[0][0]']
                                )

 conv2d_10 (Conv2D)             (None, 512, 512, 48  1152        ['re_lu_39[0][0]']
                                )

 batch_normalization_38 (BatchN  (None, 512, 512, 48  192        ['conv2d_10[0][0]']

 ormalization)                  )

 dropout_12 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_38[0][0]']
                                )

 add_12 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_4[0][0]',
                                )                                 'dropout_12[0][0]']

 symmetrize2d_5 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_12[0][0]']
                                )

 re_lu_40 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_5[0][0]']
                                )

 conv2d_11 (Conv2D)             (None, 512, 512, 24  10368       ['re_lu_40[0][0]']
                                )

 batch_normalization_39 (BatchN  (None, 512, 512, 24  96         ['conv2d_11[0][0]']
 ormalization)                  )

 re_lu_41 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_39[0][0]']
                                )

 conv2d_12 (Conv2D)             (None, 512, 512, 48  1152        ['re_lu_41[0][0]']
                                )

 batch_normalization_40 (BatchN  (None, 512, 512, 48  192        ['conv2d_12[0][0]']
 ormalization)                  )

 dropout_13 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_40[0][0]']
                                )

 add_13 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_5[0][0]',
                                )                                 'dropout_13[0][0]']

 symmetrize2d_6 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_13[0][0]']
                                )

 cropping2d (Cropping2D)        (None, 448, 448, 48  0           ['symmetrize2d_6[0][0]']
                                )

 upper_tri (UpperTri)           (None, 99681, 48)    0           ['cropping2d[0][0]']

 dense (Dense)                  (None, 99681, 5)     245         ['upper_tri[0][0]']

 switch_reverse_triu (SwitchRev  (None, 99681, 5)    0           ['dense[0][0]',
 erseTriu)                                                        'stochastic_reverse_complement[0
                                                                 ][1]']

==================================================================================================
Total params: 751,653
Trainable params: 746,149
Non-trainable params: 5,504
__________________________________________________________________________________________________
None
model_strides [2048]
target_lengths [99681]
target_crops [-49585]
model successfully loaded

In [3]:
import h5py
import pyBigWig
import intervaltree
import basenji
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

# hic imports
import cooler
from cooltools.lib.numutils import observed_over_expected, adaptive_coarsegrain
from cooltools.lib.numutils import interpolate_bad_singletons, set_diag, interp_nan
from astropy.convolution import Gaussian2DKernel
from astropy.convolution import convolve

import collections

In [4]:
import cooltools.lib.plotting
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.ticker import EngFormatter
import seaborn as sns
from pybedtools import BedTool
import math

In [5]:
#REMEMBER!!!!!!! +1MB SEQUENCE GOES IN, BUT MAKES PREDICTION FOR 917504BP
#1MB CORRESPONDS TO 512, 2048 BP BINS THAT GETS CUT DOWN TO 448 BINS

In [6]:
def format_ticks(ax, x=True, y=True, rotate=True):
    if y:
        ax.yaxis.set_major_formatter(bp_formatter)
    if x:
        ax.xaxis.set_major_formatter(bp_formatter)
        ax.xaxis.tick_bottom()
    if rotate:
        ax.tick_params(axis='x',rotation=45)
        
def save_figures_to_pdf(output_pdf_path, figures):
    with PdfPages(output_pdf_path) as pdf:
        for fig in figures:
            pdf.savefig(fig)

In [7]:
def read_fasta(fa):
    #read in fasta and return sequence only 
    seq=''
    with open(fa, "r") as fa_file:
        for line in fa_file:
            if not (line.startswith('>')):
                seq += line.strip()
    fa_file.close()                
    return(seq)

In [8]:
#TOTAL AKITA INPUT LENGTH 

akita_seq_len=1048576


#HG38 REF FA
hg38_file = '/pollard/home/shzhang/akita/run_akita/refs/hg38.fa'
fasta_hg38 = pysam.Fastafile(hg38_file)

#GENCODE
gene_annot = pd.read_csv('/pollard/data/genetics/GENCODE/release32/gencode.v32.genes_only.bed', sep = '\t', names = ['CHROM', 'start_gene', 'end_gene', 'Gene'])
gene_annot[gene_annot.CHROM != 'chrM']

      CHROM  start_gene  end_gene         Gene
0      chr1       11869     14409      DDX11L1
1      chr1       14404     29570       WASH7P
2      chr1       17369     17436    MIR6859-1
3      chr1       29554     31109  MIR1302-2HG
4      chr1       30366     30503    MIR1302-2
...     ...         ...       ...          ...
60567  chrY    57184101  57197337         IL9R
60568  chrY    57190738  57208756   AJ271736.1
60569  chrY    57201143  57203357       WASIR1
60570  chrY    57207346  57212230       WASH6P
60571  chrY    57212184  57214397     DDX11L16

[60572 rows x 4 columns]

In [9]:
data_dir='/pollard/data/projects/shzhang/mdanderson/'
patient_data_dir=f'{data_dir}by_patient_20240529/'

In [10]:
meta=pd.read_csv(f'{data_dir}meta_sv2.csv')
meta['tumor_id']=meta['tumor'].str.split('-').str.get(0)
meta

,Patient,Tumor_Type,Timepoint,normal,tumor,gender,tumor_id
0,Patient1,DDLPS,baseline,226294-WG01,226295-WG01,XX,226295
1,Patient1,DDLPS,On_treatment,226294-WG01,226296-WG01,XX,226296
2,Patient1,DDLPS,Surgery,226294-WG01,226298-WG01,XX,226298
3,Patient1,DDLPS,Surgery,226294-WG01,226297-WG01,XX,226297
4,Patient2,DDLPS,baseline,226299-WG01,226300-WG01,XX,226300
...,...,...,...,...,...,...,...
67,Patient23,DDLPS,baseline,227190-WG01,227180-WG01,XX,227180
68,Patient23,DDLPS,On_treatment,227190-WG01,227181-WG01,XX,227181
69,Patient23,DDLPS,Surgery,227190-WG01,227182-WG01,XX,227182
70,Patient24,UPS,baseline,227191-WG01,227183-WG01,XX,227183
71,Patient24,UPS,On_treatment,227191-WG01,227184-WG01,XX,227184

In [11]:
meta[meta['Patient']=='Patient6']

,Patient,Tumor_Type,Timepoint,normal,tumor,gender,tumor_id
18,Patient6,DDLPS,On_treatment,226317-WG01,226318-WG01,XX,226318
19,Patient6,DDLPS,Surgery,226317-WG01,226319-WG01,XX,226319
20,Patient6,DDLPS,Relapse,226317-WG01,226320-WG01,XX,226320

In [12]:
#read in COSMIC gene information 
cosmic=pd.read_csv('/pollard/home/shzhang/data/COSMIC_census_2023.csv')
cosmic['chr'] = 'chr' + cosmic['Genome Location'].str.split(':').str[0]
cosmic['coords'] = cosmic['Genome Location'].str.split(':').str[1]
cosmic['start'] = cosmic['coords'].str.split('-').str[0]
cosmic['end'] = cosmic['coords'].str.split('-').str[1]
cosmic

,Gene Symbol,Name,Entrez GeneId,Genome Location,Tier,Hallmark,Chr Band,Somatic,Germline,Tumour Types(Somatic),...,Role in Cancer,Mutation Types,Translocation Partner,Other Germline Mut,Other Syndrome,Synonyms,chr,coords,start,end
0,A1CF,APOBEC1 complementation factor,29974.0,10:50799421-50885675,2,NaN,11.23,yes,NaN,melanoma,...,oncogene,Mis,NaN,NaN,NaN,"29974,A1CF,ACF,ACF64,ACF65,APOBEC1CF,ASP,ENSG0...",chr10,50799421-50885675,50799421,50885675
1,ABI1,abl-interactor 1,10006.0,10:26746593-26860935,1,Yes,12.10,yes,NaN,AML,...,"TSG, fusion",T,KMT2A,NaN,NaN,"10006,ABI-1,ABI1,E3B1,ENSG00000136754.17,Q8IZP...",chr10,26746593-26860935,26746593,26860935
2,ABL1,v-abl Abelson murine leukemia viral oncogene h...,25.0,9:130713946-130885683,1,Yes,34.12,yes,NaN,"CML, ALL, T-ALL",...,"oncogene, fusion","T, Mis","BCR, ETV6, NUP214",NaN,NaN,"25,ABL,ABL1,ENSG00000097007.17,JTK7,P00519,c-A...",chr9,130713946-130885683,130713946,130885683
3,ABL2,"c-abl oncogene 2, non-receptor tyrosine kinase",27.0,1:179099327-179229601,1,NaN,25.20,yes,NaN,AML,...,"oncogene, fusion",T,ETV6,NaN,NaN,"27,ABL2,ABLL,ARG,ENSG00000143322.19,P42684",chr1,179099327-179229601,179099327,179229601
4,ACKR3,atypical chemokine receptor 3,57007.0,2:236569641-236582358,1,Yes,37.30,yes,NaN,lipoma,...,"oncogene, fusion",T,HMGA2,NaN,NaN,"57007,ACKR3,CMKOR1,CXCR7,ENSG00000144476.5,GPR...",chr2,236569641-236582358,236569641,236582358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,ZNF429,zinc finger protein 429,353088.0,19:21505564-21538078,2,NaN,12.00,yes,NaN,GBM,...,NaN,Mis,NaN,NaN,NaN,"353088,ENSG00000197013.9,Q86V71,ZNF429",chr19,21505564-21538078,21505564,21538078
732,ZNF479,zinc finger protein 479,90827.0,7:57119614-57139864,2,NaN,11.20,yes,NaN,"lung cancer, bladder carcinoma, prostate carci...",...,NaN,Mis,NaN,NaN,NaN,"90827,ENSG00000185177.12,KR19,Q96JC4,ZNF479",chr7,57119614-57139864,57119614,57139864
733,ZNF521,zinc finger protein 521,25925.0,18:25061926-25352152,1,NaN,11.20,yes,NaN,ALL,...,"oncogene, fusion",T,PAX5,NaN,NaN,"25925,EHZF,ENSG00000198795.10,Evi3,Q96K83,ZNF521",chr18,25061926-25352152,25061926,25352152
734,ZNRF3,zinc and ring finger 3,84133.0,22:28883592-29057487,2,NaN,12.10,yes,NaN,"colorectal cancer, adrenocortical carcinoma, g...",...,TSG,"N, F, Mis",NaN,NaN,NaN,"84133,BK747E2.3,ENSG00000183579.15,FLJ22057,KI...",chr22,28883592-29057487,28883592,29057487
735,ZRSR2,"zinc finger (CCCH type), RNA-binding motif and...",8233.0,X:15790472-15823260,1,Yes,22.20,yes,NaN,"MDS, CLL",...,TSG,"F, S, Mis",NaN,NaN,NaN,"8233,ENSG00000169249.12,Q15696,U2AF1-RS2,U2AF1...",chrX,15790472-15823260,15790472,15823260

In [13]:
#np.unique(cosmic['Gene Symbol'])

In [14]:
#drop rows without coords
cosmic_subset = cosmic[(cosmic['start'].notna()) & (cosmic['start'] != '') & 
                 (cosmic['end'].notna()) & (cosmic['end'] != '')]

single_cols = ['chr', 'start', 'end', 'Gene Symbol']
cosmic_subset = cosmic_subset[single_cols]

cosmic_BED=BedTool.from_dataframe(cosmic_subset.astype({'start': int, 'end': int}))
#cosmic_BED=BedTool.from_dataframe(cosmic_subset)

In [15]:
cosmic_subset[cosmic_subset['Gene Symbol']=='TNFRSF14']

      chr    start      end Gene Symbol
683  chr1  2556366  2563829    TNFRSF14

In [16]:
#ok, what we want to do is plot the changes at every breakpoint
#we also want to figure out which bin the gene is in, so we can make a note of that
#we also want to get the bin at which the boundaries change, so we can also make a note of that

In [17]:
#write separate plotting function so this isn't too messy
#for plotting post akita predictions 

def plot_complex_pred(mat_list, label_list, bkpt_bin_list, gene_start_bin_list, gene_end_bin_list, gene_name_start_list, gene_name_end_list, gene_len):

    #order of lists is REF_left, REF_right, ALT
     
    fig=plt.figure(figsize=(7.5,6))
    target_index = 0
    vmin=-2; vmax=2

    plt.subplot(121) 
    im = plt.matshow(mat_list[1], fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    
    for g in gene_start_bin_list:
        plt.axvline(x = g, color = 'limegreen', linestyle = '--', linewidth=1, label = 'gene start')
    for g in gene_end_bin_list:
        plt.axvline(x = g, color = 'forestgreen', linestyle = '--', linewidth=1, label = 'gene end')
    for g in bkpt_bin_list:
        plt.axvline(x = g, color = 'blue', linestyle = 'dotted', linewidth=1, label = 'other bkpts ')
        
    # Add gene name annotations
    for gene_name, start_bin in zip(gene_name_start_list, gene_start_bin_list):
        plt.text(
            x=start_bin, y=1.2 * mat_list[1].shape[0],  # Position annotation near the top of the matrix
            s=gene_name,
            color='limegreen', fontsize=10, rotation=45, ha='right'
        )
    for gene_name, end_bin in zip(gene_name_end_list, gene_end_bin_list):
        plt.text(
            x=end_bin, y=1.2 * mat_list[1].shape[0],  # Position annotation near the top of the matrix
            s=gene_name,
            color='forestgreen', fontsize=10, rotation=45, ha='right'
        )
    
    
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    plt.title(label_list[0], y=1.15)
    
    plt.subplot(122) 
    im = plt.matshow(mat_list[0], fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    gene_len_n_bin=math.floor(gene_len/2048)
    plt.axvline(x = 224-(gene_len_n_bin/2), color = 'limegreen', linestyle = '--', linewidth=1, label = 'gene start')
    plt.axvline(x = 224+(gene_len_n_bin/2), color = 'forestgreen', linestyle = '--', linewidth=1, label = 'gene end')


    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    plt.title(label_list[1], y=1.15)

    
    
    fig.suptitle(label_list[2], fontsize=16, y=0.90)

        
    plt.tight_layout()
    plt.subplots_adjust(top=0.75)
    return(fig)

In [30]:
#make akita predictions for each walk and plot 
def pred_akita_genecenter_COSMIC(fa_dir, fa_name, patient_num):
    bed_name=fa_name.replace('fa', 'bed')
    name_parts = bed_name.rsplit('_', 2)


    #read in corresponding fa sequence
    seq=read_fasta(f'{fa_dir}{fa_name}')
    
    try:

        #read in bed file and figure out where to center the file 
        bed=pd.read_csv(f'{patient_data_dir}walks_bed/' + bed_name, sep='\t', header=None)
        bed.columns = ['chr', 'start', 'end', 'strand', 'cn', '5']
        bed['chr'] = bed['chr'].astype('str') 
        bed['span']=abs(bed['end']-bed['start']) 
        bed['span_cumsum'] = bed['span'].cumsum().astype(int)
        bed['bed_idx']=bed.index
    
        print('bed file', bed)
        walks_BED=BedTool.from_dataframe(bed[['chr', 'start', 'end', 'strand', 'cn', 'span', 'span_cumsum', 'bed_idx']])

        
        #overlap walks bed with COSMIC gene list 
        genes_in_map_BED = walks_BED.intersect(cosmic_BED, wa = True, wb = True)


        
        if genes_in_map_BED == '':
            #only want to visualize if gene is in the fasta 
            pass

        else:
            genes_in_map = (genes_in_map_BED.to_dataframe()
                        .rename(columns = {'strand': 'span', 'itemRgb': 'gene_chrom', 'name': 'strand', 
                                           'score': 'cn', 'thickStart': 'span_cumsum', 'thickEnd': 'bed_idx',
                                           'blockCount':'gene_start', 'blockSizes': 'gene_end', 
                                           'blockStarts':'gene_name'}))
            genes_in_map=genes_in_map[['chrom', 'start', 'end', 'strand', 'cn', 'span', 'span_cumsum', 'bed_idx',
                                       'gene_chrom', 'gene_start', 'gene_end','gene_name']]
            
            #print(genes_in_map)
            
            
            
            figures=[]
            #loop through each gene, center it, plot 
            for gene in range(0, len(genes_in_map)):
            #for gene in range(0, 2):



                gene_intersect_row=genes_in_map.loc[gene]
                print('gene', gene_intersect_row.gene_name)
                #print('gene_row', gene_row)

 
                try:
        
        
                    #get row in original bed that corresponds to gene row
                    gene_row_idx=bed[((bed['chr']==gene_intersect_row['chrom']) 
                                      & (bed['start']==gene_intersect_row.start)
                                     & (bed['end']==gene_intersect_row['end']))].index.values[0] 
                
                    #get gene info 
                    gene_len=abs(gene_intersect_row.gene_end-gene_intersect_row.gene_start)
                    gene_mid_coord=np.floor(gene_intersect_row.gene_start + (gene_len/2))
                    
                   
                    
                    #get first, last rows, and subsets of bed before and after bkpt 
                    first_row=bed.iloc[0,:]
                    last_row=bed.iloc[(len(bed)-1), :]
                    gene_row=bed.iloc[gene_row_idx, :]
                    bed_to_gene=bed.iloc[0:(gene_row_idx),:]
                                      

                    #get relevant lengths
                    total_span=np.sum(bed['span'])
                    left_to_gene_mid_coord_span=gene_mid_coord-gene_row['start']
                    #gene_mid_coord_to_right=gene_row['end']-gene_mid_coord
                    left_to_gene_span=int(np.sum(bed_to_gene['span']) + left_to_gene_mid_coord_span)
                    gene_to_right_span=total_span-left_to_gene_span 

                    #print(left_to_gene_span)

                    # left sequence 
                    if left_to_gene_span>=utils.half_patch_size:
                        ALT_left=seq[(left_to_gene_span - utils.half_patch_size ):left_to_gene_span]
                        
                        #for gene annot
                        left_start=left_to_gene_span - utils.half_patch_size 

                    else:   
                        #need to pad left from reference 
                        diff_len=utils.half_patch_size-left_to_gene_span
                        #print('diff len', diff_len)

                        first_row_idx=first_row.start
                        ALT_fromref_left=fasta_hg38.fetch(first_row.chr, first_row_idx-diff_len, first_row_idx).upper()

                        ALT_left=ALT_fromref_left + seq[0:len_left_to_bkpt]
                        
                        #for gene annot
                        left_start=-diff_len


                    # right sequence 
                    if gene_to_right_span>utils.half_patch_size:
                        ALT_right=seq[left_to_gene_span: (left_to_gene_span + utils.half_patch_size)]

                    else:
                        #need to pad right from reference        
                        diff_len=utils.half_patch_size-gene_to_right_span

                        last_row_idx=last_row.end
                        ALT_fromref_right=fasta_hg38.fetch(last_row.chr, last_row_idx, last_row_idx + diff_len).upper()

                        ALT_right=seq[left_to_gene_span:total_span] + ALT_fromref_right


                    ALT_seq = ALT_left + ALT_right
                    
                    #print('left start', left_start)
                    
                    #########################
                    #finally, get the REF -- center at the gene 
                    left_ref_coords=[gene_intersect_row.gene_chrom, gene_mid_coord-utils.half_patch_size, 
                                                  gene_mid_coord+utils.half_patch_size]


                    REF_seq_gene=fasta_hg38.fetch(left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]).upper()


                    ####################
                    
                    if REF_seq_gene==ALT_seq:
                        #want where breakpoints and genes differ 
                        pass
                    


                    else:
                        
                        #check sequence lengths, and then run akita 
                        assert len(REF_seq_gene) == utils.seq_length, 'REF_seq_left is not right length'
                        assert len(ALT_seq) == utils.seq_length, 'ALT_seq is not right length'



                        #this is where akita is actually run, output vector size is (99681,)
                        REF_gene_vec,  ALT_vec = utils.vector_from_seq(REF_seq_gene),  utils.vector_from_seq(ALT_seq)
                        REF_gene_mat,  ALT_mat = utils.mat_from_vector(REF_gene_vec), utils.mat_from_vector(ALT_vec)


                        #order is REF_left, REF_right, ALT
                        mat_list=[REF_gene_mat, ALT_mat]

                        
                        
                        #######################

                        #we want to get indices of the breakpoints, if others are in the window 


                        span_cumsum_list=np.array(bed['span_cumsum'].tolist())
                        bkpt_pos_from_left_all= span_cumsum_list-left_start


                        #subset to those less than akita window size
                        bkpt_pos_from_left=bkpt_pos_from_left_all[(bkpt_pos_from_left_all>0) & (bkpt_pos_from_left_all<utils.MB)]
                        #print(bkpt_pos_from_left)

                        #get the bin index
                        bkpt_pos_from_left=bkpt_pos_from_left.tolist()
                        bkpt_bin_list_all=[utils.get_bin(bkpt) for bkpt in bkpt_pos_from_left]
                        bkpt_bin_list = [bkpt for bkpt in bkpt_bin_list_all if 0 < bkpt <= 448]



                        ########################
                        #finally, get the positions of the gene(s)

                        gene_start_bin_list=[]
                        gene_end_bin_list=[]
                        gene_name_start_list=[]
                        gene_name_end_list=[]


                        #check the start of the gene 
                        for g in range(0, len(genes_in_map)):
                            gene_annot_row=genes_in_map.loc[g]
                            bed_g_idx=gene_annot_row['bed_idx']
                            bed_g_row=bed.iloc[bed_g_idx, :]
                            bed_to_gene=bed.iloc[0:(bed_g_idx),:]


                            #check that start coord is in the bed
                            if (gene_annot_row['gene_start']>bed_g_row.start & gene_annot_row['gene_start']<bed_g_row.end):
                                len_to_gene_start_row=gene_annot_row['gene_start'] - (bed_g_row.start) 
                                left_to_gene_start=np.sum(bed_to_gene['span']) + len_to_gene_start_row
                                gene_start_pos_window=utils.get_bin(left_to_gene_start - left_start)
                                if (gene_start_pos_window>0) & (gene_start_pos_window<448):
                                    gene_start_bin_list.append(gene_start_pos_window)
                                    gene_name_start_list.append(gene_annot_row['gene_name'])


                            #check that end coord is in bed
                            if (gene_annot_row['gene_end']>bed_g_row.start & gene_annot_row['gene_end']<bed_g_row.end):
                                len_to_gene_end_row=gene_annot_row['gene_end'] - (bed_g_row.start) 
                                left_to_gene_end=np.sum(bed_to_gene['span']) + len_to_gene_end_row
                                gene_end_pos_window=utils.get_bin(left_to_gene_end - left_start)
                            if (gene_end_pos_window>0) & (gene_end_pos_window<448):
                                gene_end_bin_list.append(gene_end_pos_window)
                                gene_name_end_list.append(gene_annot_row['gene_name'])


                        ####################

                        #get label list 
                        label_list=[f'Row {gene_row_idx}, centered at {gene_intersect_row.gene_name}', 
                                    'REF at {} \n {}:{}-{}'.format(gene_intersect_row.gene_name, left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]), 
                                    f'{fa_name[:-3]}']

                        #print(label_list)

                        # plot!
                        fig=plot_complex_pred(mat_list, label_list, bkpt_bin_list, gene_start_bin_list, gene_end_bin_list, gene_name_start_list, gene_name_end_list, gene_len)
                        figures.append(fig)

                except:
                    print('error!!!! in row index', gene)
                    
                    
            if len(figures)>0:                    
                print(f'saving to {fig_dir}patient_{patient_num}/{bed_name[:-4]}_breakpoints.pdf')
                save_figures_to_pdf(f'{fig_dir}patient_{patient_num}/{bed_name[:-4]}_plot.pdf', figures)
            plt.close('all')

                            
    except:
        print('error in file', fa_name)

In [37]:
#make akita predictions for each walk and plot 
def get_variant_genecenter_region(fa_dir, fa_name, patient_num):

    bed_name=fa_name.replace('fa', 'bed')
    name_parts = bed_name.rsplit('_', 2)
    #read in corresponding fa sequence
    seq=read_fasta(f'{fa_dir}{fa_name}')
    
   

    try:

        #read in bed file and figure out where to center the file 
        bed=pd.read_csv(f'{patient_data_dir}walks_bed/' + bed_name, sep='\t', header=None)
        bed.columns = ['chr', 'start', 'end', 'strand', 'cn', '5']
        bed['chr'] = bed['chr'].astype('str') 
        bed['span']=abs(bed['end']-bed['start']) 
        bed['span_cumsum'] = bed['span'].cumsum().astype(int)
        bed['bed_idx']=bed.index
    
        #print('bed file', bed)
        walks_BED=BedTool.from_dataframe(bed[['chr', 'start', 'end', 'strand', 'cn', 'span', 'span_cumsum', 'bed_idx']])

        
        #overlap walks bed with COSMIC gene list 
        genes_in_map_BED = walks_BED.intersect(cosmic_BED, wa = True, wb = True)
        
        if genes_in_map_BED == '':
            #only want to visualize if gene is in the fasta 
            pass

        else:
            genes_in_map = (genes_in_map_BED.to_dataframe()
                        .rename(columns = {'strand': 'span', 'itemRgb': 'gene_chrom', 'name': 'strand', 
                                           'score': 'cn', 'thickStart': 'span_cumsum', 'thickEnd': 'bed_idx',
                                           'blockCount':'gene_start', 'blockSizes': 'gene_end', 
                                           'blockStarts':'gene_name'}))
            genes_in_map=genes_in_map[['chrom', 'start', 'end', 'strand', 'cn', 'span', 'span_cumsum', 'bed_idx',
                                       'gene_chrom', 'gene_start', 'gene_end','gene_name']]
            
            
            
            list_of_regions=[]
            #loop through each gene, center it, plot 
            for gene in range(0, len(genes_in_map)):
            #for gene in range(0, 2):



                gene_intersect_row=genes_in_map.loc[gene]
                print('gene', gene_intersect_row.gene_name)
                #print('gene_row', gene_row)

 
                try:
        
        
                    #get row in original bed that corresponds to gene row
                    gene_row_idx=bed[((bed['chr']==gene_intersect_row['chrom']) 
                                      & (bed['start']==gene_intersect_row.start)
                                     & (bed['end']==gene_intersect_row['end']))].index.values[0] 
                
                    #get gene info 
                    gene_len=abs(gene_intersect_row.gene_end-gene_intersect_row.gene_start)
                    gene_mid_coord=np.floor(gene_intersect_row.gene_start + (gene_len/2))
                    
                   
                    
                    #get first, last rows, and subsets of bed before and after bkpt 
                    first_row=bed.iloc[0,:]
                    last_row=bed.iloc[(len(bed)-1), :]
                    gene_row=bed.iloc[gene_row_idx, :]
                    bed_to_gene=bed.iloc[0:(gene_row_idx),:]
                                      

                    #get relevant lengths
                    total_span=np.sum(bed['span'])
                    left_to_gene_mid_coord_span=gene_mid_coord-gene_row['start']
                    #gene_mid_coord_to_right=gene_row['end']-gene_mid_coord
                    left_to_gene_span=int(np.sum(bed_to_gene['span']) + left_to_gene_mid_coord_span)
                    gene_to_right_span=total_span-left_to_gene_span 

                    #print(left_to_gene_span)

                    # left sequence 
                    if left_to_gene_span>=utils.half_patch_size:
                        ALT_left=seq[(left_to_gene_span - utils.half_patch_size ):left_to_gene_span]
                        
                        #for gene annot
                        left_start=left_to_gene_span - utils.half_patch_size 

                    else:   
                        #need to pad left from reference 
                        diff_len=utils.half_patch_size-left_to_gene_span
                        #print('diff len', diff_len)

                        first_row_idx=first_row.start
                        ALT_fromref_left=fasta_hg38.fetch(first_row.chr, first_row_idx-diff_len, first_row_idx).upper()

                        ALT_left=ALT_fromref_left + seq[0:len_left_to_bkpt]
                        
                        #for gene annot
                        left_start=-diff_len


                    # right sequence 
                    if gene_to_right_span>utils.half_patch_size:
                        ALT_right=seq[left_to_gene_span: (left_to_gene_span + utils.half_patch_size)]

                    else:
                        #need to pad right from reference        
                        diff_len=utils.half_patch_size-gene_to_right_span

                        last_row_idx=last_row.end
                        ALT_fromref_right=fasta_hg38.fetch(last_row.chr, last_row_idx, last_row_idx + diff_len).upper()

                        ALT_right=seq[left_to_gene_span:total_span] + ALT_fromref_right


                    ALT_seq = ALT_left + ALT_right
                    
                    #print('left start', left_start)
                    
                    #########################
                    #finally, get the REF -- center at the gene 
                    left_ref_coords=[gene_intersect_row.gene_chrom, gene_mid_coord-utils.half_patch_size, 
                                                  gene_mid_coord+utils.half_patch_size]


                    REF_seq_gene=fasta_hg38.fetch(left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]).upper()


                    ####################
                    
                    if REF_seq_gene==ALT_seq:
                        #want where breakpoints and genes differ 
                        pass
                    

                    else:
                        print('we have a gene!')
                        
                        #check sequence lengths, and then extract gene information 
                        assert len(REF_seq_gene) == utils.seq_length, 'REF_seq_left is not right length'
                        assert len(ALT_seq) == utils.seq_length, 'ALT_seq is not right length'


                        
                        #file row index, chr, start, end, gene 
                        coords=[patient_num, fa_name, gene_row_idx, gene_row.chr, gene_row.start, gene_row.end, gene_intersect_row.gene_name]
                        list_of_regions.append(coords)
                except:
                    print('error!!!! in row index', gene)
                    
                    
            col_names = ["patient", "walk_file", "walk_file_row_idx", "chr", "start", "end", 'COSMIC_gene']
            if len(list_of_regions)>0:     
                region_df = pd.DataFrame(list_of_regions, columns=col_names)
                return(region_df)
            
            else:
                return(pd.DataFrame(columns=col_names))


                            
    except:
        print('error in file', fa_name)

In [40]:
fig_dir='/pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/'


walks_df_list=[]
#run for all patients
for patient_num in range(1,25):
#for patient_num in range(1,3):
    print('running patient ', patient_num)
    dir_patient=f'{patient_data_dir}patient_{patient_num}/walks_fasta/'
    dir_files=os.listdir(dir_patient)
    
    #run for all walks in patient 
    for f in range (0, len(dir_files)):
    #for f in range (0,5):

        print('running file ', dir_files[f])
        walk_df=get_variant_genecenter_region(fa_dir=dir_patient, fa_name=dir_files[f], patient_num=patient_num)
        walks_df_list.append(walk_df)
        
        

# Concatenate all DataFrames
final_walks_df = pd.concat(walks_df_list, ignore_index=True)

running patient  1
running file  226296-WG01_walk_5_MYCL_containing.fa
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
gene TFG
gene CBLB
running file  226298-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
we have a gene!
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
we have a gene!
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226297-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226298-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
we have a gene!
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
we have a gene!
gene CAMTA1
gene PRDM16
gene ARID1A
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene SETDB1
we have a gene!
gene MLLT11
we have a gene!
gene ARNT
we have a gene!
gene SSX4
we have a gene!
gene WAS
we have a gene!
gene SSX2
we have a gene!
gene FOXO4
we have a gene!
gene IRS4
we have a gene!
gene DCAF12L2
we have a gene!
gene ZRSR2
we have a gene!
gene EIF1AX
we have a gene!
gene FAM47C
we have a gene!
gene BCOR
we have a gene!
gene DDX3X
we have a gene!
gene ARAF
we have a gene!
gene SSX1
we have a gene!
gene GATA1
we have a gene!
gene TFE3
we have a gene!
gene SMC1A
we have a gene!
gene AMER1
we have a gene!
gene MSN
we have a gene!
gene MED12
we have a gene!
gene NONO
we have a gene!
gene ZMYM3
we have a gene!
gene BTK
we have a gene!
gene ELF4
we have a gene!
gene PHF6
we have a gene!
gene TMSB4X
we have a gene!
gene USP9X
we have a gene!
gene KDM5C
we have a gene!
gene AR
we have a gene!
gene SEPT6
we have a gene!
gene STAG2
we have a gene!
gene GPC3
we have a gene!
gene KDM6A
we have a gene!
gene RBM10
we have a gene!
gene ATRX
we have a gene!
gene BCORL1
we have a gene!
gene CRLF2
we have a gene!
gene P2RY8
we have a gene!
running file  226296-WG01_walk_4_MYCL_containing.fa
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
running file  226296-WG01_walk_1_MYCN_containing.fa
gene FGFR1OP
gene AFDN
gene QKI
gene MYB
gene BCLAF1
gene TNFAIP3
gene EZR
gene ECT2L
gene LATS1
gene ARID1B
gene ESR1
gene SGK1
gene PCBP1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226296-WG01_walk_2_MYCN_containing.fa
gene MYCN
gene PCBP1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene TMEM127
gene CTNNA2
gene ATF1
we have a gene!
running file  226297-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226296-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene SETDB1
we have a gene!
gene MLLT11
gene ARNT
we have a gene!
running file  226295-WG01_walk_1_MYCL_containing.fa
gene SETDB1
we have a gene!
gene MLLT11
gene ARNT
we have a gene!
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226298-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene EML4
we have a gene!
running file  226295-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene TMEM127
running file  226298-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
we have a gene!
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
we have a gene!
gene CAMTA1
gene PRDM16
gene ARID1A
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene SETDB1
we have a gene!
gene MLLT11
we have a gene!
gene ARNT
we have a gene!
gene S100A7
we have a gene!
gene TPM3
we have a gene!
gene MUC1
we have a gene!
gene LMNA
we have a gene!
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene FCRL4
we have a gene!
running file  226297-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene ACKR3
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene SF3B1
gene CUL3
gene ERBB4
gene PAX3
running file  226296-WG01_walk_3_MYCL_containing.fa
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
running file  226296-WG01_walk_2_MYCL_containing.fa
gene SETDB1
we have a gene!
gene MLLT11
gene ARNT
we have a gene!
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL

gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
running file  226295-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
we have a gene!
gene IKBKB
we have a gene!
gene HOOK3
gene KAT6A
we have a gene!
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226297-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
we have a gene!
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
we have a gene!
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
running file  226297-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
gene MYCL
gene JUN
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene ARID1A
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene PTPRC
gene AKT3
gene RGS7
running file  226296-WG01_walk_2_MYC_containing.fa
gene ARHGEF10
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene NCOA2
gene PREX2
gene CNBD1
gene UBR5
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
running file  226295-WG01_walk_2_MYCN_containing.fa
gene TMEM127
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226295-WG01_walk_2_MYCL_containing.fa
gene SETDB1
we have a gene!
gene MLLT11
gene ARNT
we have a gene!
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226296-WG01_walk_1_MYC_containing.fa
gene CTNNA1
gene ARHGAP26
gene ACSL6
gene AFF4
gene APC
gene RAD17
gene IL6ST
gene MAP3K1
gene PIK3R1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene UBR5
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
running patient  2
running file  226301-WG01_walk_4_MDM2_containing.fa
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
we have a gene!
gene HOXC13
gene HOXC11
gene COL2A1
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
we have a gene!
gene KMT2D
gene CEBPA
gene BCL3
gene CD79A
gene CIC
gene CBLC
gene CEP89
we have a gene!
gene LSM14A
gene AKT2
gene ERCC2
gene CCNE1
we have a gene!
gene ZNF429
we have a gene!
gene PRKACA
gene DNAJB1
gene BRD4
gene TPM4
gene CRTC1
gene ELL
gene JAK3
gene LYL1
we have a gene!
gene KEAP1
gene CALR
gene DNM2
gene SMARCA4
gene FSTL3
gene CD209
gene STK11
gene TCF3
gene GNA11
gene MAP2K2
gene SH3GL1
gene MLLT1
gene VAV1
gene MUC16
running file  226300-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226301-WG01_walk_2_MYCN_containing.fa
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226301-WG01_walk_3_MYC_containing.fa
gene RECQL4
gene FAM135B
gene MYC
gene EIF3E
we have a gene!
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
we have a gene!
gene CSMD3
gene RSPO2
we have a gene!
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene UBR5
gene CNBD1
gene NCOA2
gene PREX2
we have a gene!
gene CCNE1
running file  226301-WG01_walk_2_MDM2_containing.fa
gene ALDH2
error!!!! in row index 0
gene PTPN11
we have a gene!
gene SH2B3
we have a gene!
gene USP44
gene CHST11
gene BTG1
we have a gene!
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
running file  226301-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene CDC73
we have a gene!
running file  226300-WG01_walk_1_MYC_containing.fa
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene RAD21
gene EXT1
gene CSMD3
we have a gene!
gene CSMD3
we have a gene!
gene SSX4
we have a gene!
gene WAS
we have a gene!
gene SSX2
we have a gene!
gene SSX1
we have a gene!
gene GATA1
we have a gene!
gene TFE3
we have a gene!
gene SMC1A
we have a gene!
gene KDM5C
we have a gene!
gene AMER1
we have a gene!
gene MSN
we have a gene!
gene AR
we have a gene!
gene FOXO4
we have a gene!
gene IRS4
we have a gene!
gene DCAF12L2
we have a gene!
gene MED12
we have a gene!
gene NONO
we have a gene!
gene ZMYM3
we have a gene!
gene BTK
we have a gene!
gene ELF4
we have a gene!
gene PHF6
we have a gene!
gene SEPT6
we have a gene!
gene STAG2
we have a gene!
gene GPC3
we have a gene!
gene ATRX
we have a gene!
gene BCORL1
we have a gene!
gene RPL10
we have a gene!
gene ATP2B3
we have a gene!
gene FLNA
we have a gene!
gene MTCP1
we have a gene!
running file  226300-WG01_walk_3_MDM2_containing.fa
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene CYLD
we have a gene!
gene FUS
gene IL21R
gene PALB2
gene PRKCB
we have a gene!
gene MYH11
running file  226302-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene ERC1
gene WIF1
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226301-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene ARID2
running file  226300-WG01_walk_1_MYCN_containing.fa
gene RANBP2
gene RGPD3
gene AFF3
error!!!! in row index 2
gene PAX8
gene TMEM127
gene CTNNA2
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene WDCP

we have a gene!
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene MYCN
running file  226302-WG01_walk_1_MYCL_containing.fa
gene PDGFRB
gene CD74
gene ITK
gene PWWP2A
gene NPM1
gene FGFR4
gene ACSL6
gene AFF4
gene CTNNA1
gene ARHGAP26
gene CSF1R
gene EBF1
gene TLX3
gene FLT4
gene NSD1
gene PRRX1
gene DDR2
gene PBX1
we have a gene!
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
we have a gene!
gene BCL9
gene ARNT
gene SDHC
we have a gene!
gene PDE4DIP
gene MUC1
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene EPS15
gene ATP1A1
gene ARID1A
we have a gene!
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  226300-WG01_walk_3_MYCN_containing.fa
gene WDCP
error!!!! in row index 0
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene MYCN
running file  226302-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene ERC1
gene WIF1
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226301-WG01_walk_1_MYCL_containing.fa
gene SETDB1
we have a gene!
gene MLLT11
we have a gene!
gene ARNT
we have a gene!
gene PDE4DIP
gene BCL9
we have a gene!
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226300-WG01_walk_4_MDM2_containing.fa
gene MDM2
error!!!! in row index 0
gene SOX21
gene ERCC5
gene GPC5
running file  226301-WG01_walk_3_MDM2_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene COL2A1
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
we have a gene!
gene KMT2D
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
we have a gene!
gene WIF1
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene BTG1
we have a gene!
running file  226300-WG01_walk_4_KRAS_containing.fa
gene ARID2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 6
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226300-WG01_walk_2_MYCL_containing.fa
gene CDC73
we have a gene!
gene CDC73
we have a gene!
gene CDC73
we have a gene!
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226300-WG01_walk_2_MDM2_containing.fa
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene CREB3L1
we have a gene!
gene CREB3L1
we have a gene!
gene DDB2
we have a gene!
gene CLP1
we have a gene!
gene CTNND1
gene SDHAF2
we have a gene!
gene FEN1
we have a gene!
gene MEN1
we have a gene!
gene MALAT1
gene CCND1
we have a gene!
gene FADD
we have a gene!
gene NUMA1
we have a gene!
gene NUMA1
we have a gene!
gene FADD
we have a gene!
gene CCND1
we have a gene!
gene MEN1
we have a gene!
gene MALAT1
gene FEN1
we have a gene!
gene SDHAF2
we have a gene!
gene CLP1
we have a gene!
gene CTNND1
gene DDB2
we have a gene!
gene CREB3L1
we have a gene!
gene CREB3L1
we have a gene!
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
running file  226300-WG01_walk_3_MYC_containing.fa
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene RAD21
gene EXT1
gene CSMD3
we have a gene!
gene CSMD3
we have a gene!
gene IL2
we have a gene!
gene FAT4
gene RAP1GDS1
running file  226300-WG01_walk_1_MYCL_containing.fa
gene C15orf65
we have a gene!
gene MYO5A
we have a gene!
gene MYO5A
we have a gene!
gene SETDB1
we have a gene!
gene MLLT11
we have a gene!
gene ARNT
we have a gene!
gene PBX1
gene DDR2
we have a gene!
gene FCGR2B
we have a gene!
gene SDHC
we have a gene!
gene FCRL4
we have a gene!
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene LMNA
we have a gene!
gene MUC1
we have a gene!
gene TPM3
we have a gene!
gene S100A7
we have a gene!
gene SETDB1
we have a gene!
gene MLLT11
we have a gene!
gene ARNT
we have a gene!
gene PDE4DIP
we have a gene!
gene PDE4DIP
we have a gene!
gene BCL9
we have a gene!
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226302-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226301-WG01_walk_1_MDM2_containing.fa
gene BTG1
we have a gene!
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene COL2A1
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
we have a gene!
gene KMT2D
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
we have a gene!
gene WIF1
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene BTG1
we have a gene!
running file  226303-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226300-WG01_walk_2_MYCN_containing.fa
gene MYCN
gene WDCP
we have a gene!
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
running file  226300-WG01_walk_4_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226300-WG01_walk_2_KRAS_containing.fa
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene ARID2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 10
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226302-WG01_walk_2_MYCL_containing.fa

gene TPR
gene ABL2
gene PRRX1
gene DDR2
gene PBX1
we have a gene!
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
we have a gene!
gene BCL9
gene ARNT
gene SDHC
we have a gene!
gene PDE4DIP
gene MUC1
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene EPS15
gene ATP1A1
gene ARID1A
we have a gene!
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  226303-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226300-WG01_walk_6_MDM2_containing.fa
gene SRC
gene MAFB
gene TOP1
gene PLCG1
gene PTPRT
we have a gene!
gene PTPRT
we have a gene!
gene PTPRT
we have a gene!
gene PTPRT
we have a gene!
gene PTPRT
we have a gene!
gene PTPRT
we have a gene!
gene SDC4
gene SALL4
we have a gene!
gene NFATC2
we have a gene!
gene GNAS
gene SS18L1
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
running file  226301-WG01_walk_5_MYC_containing.fa
gene MYC
gene EIF3E
we have a gene!
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
we have a gene!
gene CSMD3
gene RSPO2
we have a gene!
running file  226300-WG01_walk_2_MYC_containing.fa
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene RAD21
gene EXT1
gene CSMD3
we have a gene!
gene CSMD3
we have a gene!
gene TET2
we have a gene!
gene LEF1
gene IL2
we have a gene!
gene FAT4
gene CASP3
we have a gene!
running file  226300-WG01_walk_5_MDM2_containing.fa
gene MDM2
error!!!! in row index 0
gene CYLD
we have a gene!
gene HERPUD1
gene CBFB
gene RFWD3
gene CTCF
gene CDH1
gene CDH11
gene ZFHX3
gene MAF
running file  226302-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene PCM1
we have a gene!
gene ARHGEF10
we have a gene!
running file  226301-WG01_walk_2_MYC_containing.fa
gene RECQL4
gene FAM135B
gene MYC
gene EIF3E
we have a gene!
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
we have a gene!
gene CSMD3
gene RSPO2
we have a gene!
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene UBR5
gene CNBD1
gene NCOA2
gene PREX2
we have a gene!
running file  226300-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
gene KRAS
gene ETNK1
gene PPFIBP1
gene ARID2
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene ARID2
running file  226302-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene ERCC3
gene CXCR4
we have a gene!
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226301-WG01_walk_5_MDM2_containing.fa
gene NCOR2
gene POLE
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene TBX3
we have a gene!
gene TBX3
we have a gene!
gene ALDH2
we have a gene!
gene PTPN11
we have a gene!
gene SH2B3
we have a gene!
gene USP44
gene CHST11
gene BTG1
we have a gene!
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
gene CCND1
we have a gene!
running file  226301-WG01_walk_4_MYC_containing.fa
gene RECQL4
gene FAM135B
gene MYC
gene EIF3E
we have a gene!
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
we have a gene!
gene CSMD3
gene RSPO2
we have a gene!
running file  226300-WG01_walk_1_MDM2_containing.fa
gene BTG1
we have a gene!
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene BAP1
gene MLH1
gene CTNNB1
gene NCKIPSD
gene RHOA
gene MYD88
gene SETD2
gene PBRM1
gene CACNA1D
gene MITF
gene FHIT
gene FOXP1
gene CCR4
gene TGFBR2
gene XPC
gene FBLN2
we have a gene!
gene RAF1
we have a gene!
gene FBLN2
we have a gene!
gene PPARG
we have a gene!
gene VHL
we have a gene!
gene FANCD2
we have a gene!
gene SRGAP3
we have a gene!
running file  226301-WG01_walk_6_MDM2_containing.fa
gene BTG1
we have a gene!
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene HMGA2
we have a gene!
gene WIF1
gene GNAS
gene SS18L1
we have a gene!
gene SALL4
we have a gene!
gene NFATC2
we have a gene!
gene SDC4
running file  226301-WG01_walk_7_MDM2_containing.fa
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
we have a gene!
gene WIF1
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene BTG1
we have a gene!
running file  226300-WG01_walk_4_MYC_containing.fa
gene CSMD3
we have a gene!
gene RAD21
gene EXT1
gene CSMD3
we have a gene!
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
running file  226303-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226301-WG01_walk_1_KRAS_containing.fa
gene ARID2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 3
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226301-WG01_walk_1_MYCN_containing.fa
gene ERCC3
error!!!! in row index 0
gene PAX8
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226300-WG01_walk_3_KRAS_containing.fa
gene PTPRB
we have a gene!
gene WIF1
we have a gene!
gene WIF1
we have a gene!
gene ARID2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 9
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226303-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226301-WG01_walk_1_MYC_containing.fa
gene RFWD3
gene ZFHX3
gene CBFB
gene CTCF
gene CDH1
gene CDH11
gene CYLD
gene HERPUD1
gene NCOA2
gene PREX2
we have a gene!
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene UBR5
gene CNBD1

gene RSPO2
we have a gene!
gene MYC
gene EIF3E
we have a gene!
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
we have a gene!
gene CSMD3
gene RECQL4
gene FAM135B
running file  226303-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226301-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene BCL9
we have a gene!
gene PDE4DIP
running patient  3
running file  226305-WG01_walk_2_MDM2_containing.fa
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226306-WG01_walk_4_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226305-WG01_walk_2_MYCL_containing.fa
gene JAK1
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
we have a gene!
gene SDHB
gene CAMTA1
gene PRDM16
we have a gene!
gene TNFRSF14
gene SKI
running file  226306-WG01_walk_4_MYCN_containing.fa
gene ASPSCR1
we have a gene!
gene RNF213
we have a gene!
gene CANT1
gene SEPT9
we have a gene!
gene H3F3B
we have a gene!
gene SRSF2
we have a gene!
gene RNF43
gene PPM1D
gene CD79B
gene DDX5
gene PRKAR1A
gene COL1A1
gene KAT7
gene SPOP
gene HLF
gene CLTC
gene BRIP1
gene AXIN2
gene MSI2
gene CCR7
gene RARA
gene ETV4
gene SMARCE1
gene STAT3
gene STAT5B
gene BRCA1
gene IKZF3
we have a gene!
gene MYCN
we have a gene!
running file  226305-WG01_walk_1_MYCN_containing.fa
gene SET
gene RALGDS
gene BRD3
gene NOTCH1
gene CNTRL
gene PPP6C
gene ABL1
gene NUP214
gene TSC1
gene FNBP1
gene KLF4
gene TNC
gene TAL2
we have a gene!
gene NR4A3
we have a gene!
gene XPA
we have a gene!
gene PTCH1
gene FANCC
we have a gene!
gene OMD
gene WNK2
we have a gene!
gene SYK
gene GNAQ
gene FANCG
gene PAX5
gene ERCC3
gene PAX8
we have a gene!
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
running file  226307-WG01_walk_2_MYCN_containing.fa
gene CTNNA2
error!!!! in row index 0
gene CTNNA2
we have a gene!
gene PCBP1
gene DCTN1
gene XPO1
we have a gene!
gene BCL11A
gene REL
we have a gene!
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
we have a gene!
gene STRN
gene EML4
we have a gene!
gene ALK
gene BIRC6
gene ASXL2
gene NCOA1
we have a gene!
gene DNMT3A
gene WDCP
we have a gene!
gene NCOA1
we have a gene!
gene MYCN
running file  226307-WG01_walk_4_MYCL_containing.fa
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene MPL
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
running file  226308-WG01_walk_3_MYCL_containing.fa
gene RPL5
we have a gene!
gene BCL10
gene FUBP1
gene JAK1
gene JUN
gene CDKN2C
we have a gene!
gene EPS15
gene STIL
gene TAL1
gene MUTYH
gene MPL
gene MYCL
we have a gene!
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene SFPQ
we have a gene!
gene LCK
running file  226305-WG01_walk_3_MYCN_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
gene CXCR4
gene ERCC3
gene PAX8
we have a gene!
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
running file  226307-WG01_walk_3_MYCN_containing.fa
gene BCL9
gene PDE4DIP
we have a gene!
gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
we have a gene!
gene TPM3
we have a gene!
gene XPO1
we have a gene!
gene XPO1
we have a gene!
gene BCL11A
gene REL
we have a gene!
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
we have a gene!
gene STRN
gene EML4
we have a gene!
gene ALK
gene BIRC6
gene ASXL2
gene NCOA1
we have a gene!
gene DNMT3A
gene WDCP
we have a gene!
gene NCOA1
we have a gene!
gene MYCN
running file  226305-WG01_walk_1_KRAS_containing.fa
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226305-WG01_walk_4_MYCL_containing.fa
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
running file  226306-WG01_walk_1_MYC_containing.fa
gene RECQL4
we have a gene!
gene FAM135B
we have a gene!
gene NDRG1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene IKBKB
we have a gene!
gene HOOK3
gene FGFR1
gene NSD3
gene ANK1
we have a gene!
gene KAT6A
we have a gene!
gene LEPROTL1
we have a gene!
gene WRN
gene NRG1
running file  226305-WG01_walk_2_MYC_containing.fa
gene FGFR1
we have a gene!
gene IKBKB
gene NSD3
we have a gene!
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
running file  226306-WG01_walk_2_KRAS_containing.fa
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 5
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226305-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FGFR1
we have a gene!
gene IKBKB
gene NSD3
we have a gene!
gene ANK1
gene HOOK3
gene KAT6A
gene WRN
we have a gene!
gene NRG1
gene LEPROTL1
we have a gene!
gene WRN
we have a gene!
running file  226306-WG01_walk_2_MYCL_containing.fa

gene RPL5
gene BCL10
gene FUBP1
we have a gene!
gene JAK1
gene MUTYH
we have a gene!
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene CDKN2C
gene EPS15
gene JUN
we have a gene!
gene MUTYH
we have a gene!
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MDS2
gene ARID1A
running file  226306-WG01_walk_3_MDM2_containing.fa
gene CXCR4
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
running file  226306-WG01_walk_1_KRAS_containing.fa
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226306-WG01_walk_4_MYC_containing.fa
gene NDRG1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
running file  226307-WG01_walk_2_MYCL_containing.fa
gene MTOR
gene FUBP1
gene JAK1
we have a gene!
gene JUN
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene MPL
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
running file  226307-WG01_walk_3_MYCL_containing.fa
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
we have a gene!
gene SIX2
we have a gene!
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene BCL11A
gene REL
we have a gene!
gene XPO1
we have a gene!
running file  226306-WG01_walk_3_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226306-WG01_walk_1_MYCL_containing.fa
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MDS2
gene ARID1A
gene MUTYH
we have a gene!
gene RPL5
gene BCL10
gene FUBP1
we have a gene!
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226305-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
we have a gene!
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
we have a gene!
gene SDHB
gene CAMTA1
gene PRDM16
we have a gene!
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JAK1
running file  226305-WG01_walk_5_MYC_containing.fa
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
running file  226306-WG01_walk_3_MYCN_containing.fa
gene MYCN
we have a gene!
gene WDCP
we have a gene!
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
running file  226306-WG01_walk_2_MDM2_containing.fa
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226307-WG01_walk_5_MYCL_containing.fa
gene NRAS
gene TENT5C
gene TRIM33
we have a gene!
gene NOTCH2
we have a gene!
gene ATP1A1
gene RBM15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene N4BP2
gene RHOH
gene PHOX2B
running file  226307-WG01_walk_1_MYCL_containing.fa
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
we have a gene!
gene FUBP1
gene BCL10
we have a gene!
gene RPL5
we have a gene!
running file  226305-WG01_walk_5_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
running file  226306-WG01_walk_3_MYC_containing.fa
gene RECQL4
we have a gene!
gene FAM135B
we have a gene!
gene NDRG1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene IKBKB
we have a gene!
gene HOOK3
gene FGFR1
gene NSD3
gene ANK1
we have a gene!
gene KAT6A
we have a gene!
gene PCM1
we have a gene!
running file  226305-WG01_walk_4_MYC_containing.fa
gene FGFR1
error!!!! in row index 0
gene IKBKB
gene NSD3
error!!!! in row index 2
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
running file  226308-WG01_walk_1_MYCN_containing.fa
gene SIX2
gene EPAS1
gene MSH6
gene EML4
we have a gene!
gene FBXO11
gene MSH2
gene STRN
we have a gene!
gene BIRC6
we have a gene!
gene BIRC6
we have a gene!
gene ALK
gene WDCP
we have a gene!
gene ASXL2
gene NCOA1
gene DNMT3A
gene MYCN
running file  226306-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
we have a gene!
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
we have a gene!
gene SDHB
gene CAMTA1
gene PRDM16
we have a gene!
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MDS2
gene ARID1A
running file  226306-WG01_walk_1_MYCN_containing.fa
gene MYCN
we have a gene!
gene WDCP
we have a gene!
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
gene CXCR4
gene CDKN2A
gene MLLT3
gene CD274
gene PDCD1LG2
gene JAK2
gene NFIB
gene PSIP1
gene PTPRD
running file  226306-WG01_walk_2_MYC_containing.fa
gene PCM1
error!!!! in row index 0
gene LEPROTL1
we have a gene!
gene WRN
gene NRG1
gene FGFR1
gene NSD3
gene ANK1
we have a gene!
gene KAT6A
we have a gene!
gene IKBKB
we have a gene!
gene HOOK3
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene NDRG1
gene FAM135B
we have a gene!
gene RECQL4
we have a gene!
running file  226305-WG01_walk_3_MYC_containing.fa
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FGFR1
we have a gene!
gene IKBKB
gene NSD3
we have a gene!
gene ANK1
gene HOOK3
gene KAT6A
running file  226306-WG01_walk_2_MYCN_containing.fa
gene FANCG
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
gene WDCP
we have a gene!
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
we have a gene!
running file  226305-WG01_walk_2_KRAS_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B

gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226305-WG01_walk_1_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226308-WG01_walk_1_MYCL_containing.fa
gene RPL5
we have a gene!
gene BCL10
gene FUBP1
gene JAK1
gene JUN
gene CDKN2C
we have a gene!
gene EPS15
gene STIL
gene TAL1
gene MUTYH
gene MPL
gene MYCL
we have a gene!
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene SFPQ
we have a gene!
gene LCK
we have a gene!
gene ARID1A
we have a gene!
gene ID3
we have a gene!
gene MDS2
we have a gene!
gene PAX7
we have a gene!
gene ARHGEF10L
we have a gene!
gene SDHB
we have a gene!
gene POU5F1
we have a gene!
gene DAXX
we have a gene!
gene HMGA1
we have a gene!
gene FANCE
we have a gene!
gene SRSF3
we have a gene!
gene CDKN1A
we have a gene!
gene PIM1
gene TFEB
we have a gene!
gene CCND3
we have a gene!
gene TFEB
we have a gene!
running file  226306-WG01_walk_1_MDM2_containing.fa
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene H3F3A
gene FH
gene AKT3
gene RGS7
running file  226305-WG01_walk_3_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226307-WG01_walk_1_MYCN_containing.fa
gene CTNNA2
we have a gene!
gene CTNNA2
we have a gene!
gene PCBP1
gene DCTN1
gene XPO1
we have a gene!
gene BCL11A
gene REL
we have a gene!
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
we have a gene!
gene STRN
gene EML4
we have a gene!
gene ALK
gene BIRC6
gene ASXL2
gene NCOA1
we have a gene!
gene DNMT3A
gene WDCP
we have a gene!
gene NCOA1
we have a gene!
gene MYCN
running file  226305-WG01_walk_2_MYCN_containing.fa
gene RPL5
we have a gene!
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene CDC73
gene PTPRC
gene PAX8
we have a gene!
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
running file  226308-WG01_walk_2_MYCL_containing.fa
gene PAX7
we have a gene!
gene ARHGEF10L
error!!!! in row index 1
gene ID3
we have a gene!
gene MDS2
we have a gene!
gene ARID1A
we have a gene!
gene LCK
we have a gene!
gene SFPQ
we have a gene!
gene MYCL
we have a gene!
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
we have a gene!
gene EPS15
gene JUN
gene JAK1
gene BCL10
gene FUBP1
gene RPL5
we have a gene!
running file  226305-WG01_walk_4_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene PAX8
we have a gene!
gene ERCC3
gene FANCG
gene PAX5
running file  226305-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
we have a gene!
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
we have a gene!
gene SDHB
gene CAMTA1
gene PRDM16
we have a gene!
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JAK1
gene FUBP1
we have a gene!
gene BCL10
running patient  4
running file  226315-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226314-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
we have a gene!
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  226315-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226315-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene KAT6A
gene RECQL4
gene FAM135B
running file  226315-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene BCL9
gene PDE4DIP
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene MUC1
gene PBX1
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
running file  226314-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226314-WG01_walk_1_MYCN_containing.fa

gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226315-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226315-WG01_walk_2_MYCL_containing.fa
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene MUC1
gene PBX1
gene BCL9
gene PDE4DIP
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running patient  5
running file  226311-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226309-WG01_walk_2_MYCL_containing.fa
gene RPL5
gene BCL10
gene FUBP1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226312-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
we have a gene!
gene NCOA1
gene DNMT3A
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226312-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226311-WG01_walk_2_MYCN_containing.fa
gene CCR4
gene BAP1
gene VHL
gene PPARG
gene RAF1
gene MLH1
gene CTNNB1
gene NCKIPSD
gene RHOA
gene SRGAP3
gene FANCD2
gene XPC
gene TGFBR2
gene MYD88
gene SETD2
gene PBRM1
gene CACNA1D
gene FBLN2
gene MYCN
running file  226309-WG01_walk_1_KRAS_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226309-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene FAM135B
gene NDRG1
we have a gene!
gene NDRG1
we have a gene!
gene MYC
we have a gene!
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene UBR5
we have a gene!
gene COX6C
gene PABPC1
gene CDH17
gene NBN
gene RUNX1T1
gene CNBD1
gene HEY1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene NCOA2
gene PREX2
gene KAT6A
running file  226311-WG01_walk_1_KRAS_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226311-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226311-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JAK1
gene BCL10
gene FUBP1
gene RPL5
running file  226309-WG01_walk_1_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226309-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene FUBP1
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226309-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226311-WG01_walk_1_MYC_containing.fa
gene RECQL4
we have a gene!
gene FAM135B
gene MYC
gene RAD21
gene NDRG1
gene EXT1
gene CSMD3
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RUNX1T1
gene UBR5
gene CNBD1
gene RSPO2
running file  226311-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR

gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JAK1
gene BCL10
gene FUBP1
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene PDE4DIP
gene MUC1
gene PBX1
gene FGFR1OP
gene AFDN
gene QKI
running file  226311-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene CXCR4
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene AFF3
gene PAX8
gene ACVR1
gene LRP1B
gene ACVR2A
running file  226311-WG01_walk_1_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226309-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226312-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226312-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226312-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226309-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene DCTN1
we have a gene!
gene CTNNA2
running patient  6
running file  226319-WG01_walk_1_MYCN_containing.fa
gene FOXA1
gene NKX2-1
gene CCNB1IP1
gene PRKD1
gene ARHGAP5
gene BAZ1A
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
running file  226319-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene BTG1
we have a gene!
running file  226318-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene COL2A1
gene PRPF40B
gene SMARCD1
we have a gene!
gene ARID2
gene KMT2D
running file  226318-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226318-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226319-WG01_walk_2_MYCN_containing.fa
gene REL
error!!!! in row index 0
gene REL
error!!!! in row index 1
gene SIX2
gene EPAS1
gene MSH6
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene ACVR1B
we have a gene!
gene ACVR1B
we have a gene!
gene ACVR1B
we have a gene!
gene CDK4
we have a gene!
running file  226318-WG01_walk_1_MYCL_containing.fa
gene BCL10
gene RPL5
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226318-WG01_walk_1_MDM2_containing.fa
gene APOBEC3B
gene ISX
gene PDGFB
gene MYH9
gene MRTFA
gene EP300
we have a gene!
gene LRIG3
we have a gene!
gene ACVR1B
we have a gene!
gene ACVR1B
we have a gene!
gene ACVR1B
we have a gene!
gene ACVR1B
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene IL2
gene FAT4
gene FBXW7
gene BCL11A
we have a gene!
running file  226319-WG01_walk_1_MYCL_containing.fa
gene TPR
gene ABL2
gene CDC73
gene PTPRC
gene TPM3
we have a gene!
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene SDHC
gene DDR2
gene MUC1
gene PBX1
gene S100A7
we have a gene!
gene SETDB1
gene MLLT11
gene BCL9
gene ARNT
gene PDE4DIP
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226318-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226318-WG01_walk_1_MYC_containing.fa
gene ARHGEF10
gene PCM1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226319-WG01_walk_2_MYCL_containing.fa
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226319-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN

gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running patient  7
running file  226324-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226322-WG01_walk_3_MDM2_containing.fa
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226322-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene FAM135B
error!!!! in row index 1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene ARHGEF10
we have a gene!
running file  226322-WG01_walk_3_MYCN_containing.fa
gene EPAS1
we have a gene!
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
running file  226323-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene BCL9
gene PDE4DIP
we have a gene!
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene MUC1
gene PBX1
gene RGS7
running file  226325-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226322-WG01_walk_1_KRAS_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CHST11
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene KRAS
gene ETNK1
gene PPFIBP1
gene CDKN1B
gene ETV6
gene PTPN6
gene CHD4
gene ZNF384
gene CCND2
we have a gene!
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 45
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 47
running file  226325-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226323-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226322-WG01_walk_2_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
we have a gene!
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
gene EPAS1
we have a gene!
gene MSH6
we have a gene!
gene FBXO11
we have a gene!
gene MSH2
we have a gene!
running file  226322-WG01_walk_1_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CHST11
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene KRAS
gene ETNK1
gene PPFIBP1
gene CDKN1B
gene ETV6
gene PTPN6
gene CHD4
gene ZNF384
gene CCND2
we have a gene!
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 45
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 47
running file  226325-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226325-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226322-WG01_walk_2_MYCL_containing.fa
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
we have a gene!
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene EPS15
gene CARS
we have a gene!
running file  226323-WG01_walk_1_KRAS_containing.fa
gene KDM5A
error!!!! in row index 0
gene CCND2
gene ERC1
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226322-WG01_walk_3_KRAS_containing.fa
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1

gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226322-WG01_walk_2_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene PHOX2B
we have a gene!
running file  226323-WG01_walk_1_MDM2_containing.fa
gene KDM5A
error!!!! in row index 0
gene CCND2
gene ERC1
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226324-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226322-WG01_walk_1_MYCL_containing.fa
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
we have a gene!
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene EPS15
gene TNFRSF14
gene SKI
gene RPL22
gene MTOR
gene PRDM2
gene CAMTA1
gene PRDM16
running file  226324-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene ERC1
gene TBX3
gene SETD1B
gene ZCCHC8
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226322-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
we have a gene!
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
gene EPAS1
we have a gene!
gene MSH6
we have a gene!
gene FBXO11
we have a gene!
gene MSH2
we have a gene!
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
running file  226322-WG01_walk_3_MYC_containing.fa
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
we have a gene!
running file  226325-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226322-WG01_walk_2_MDM2_containing.fa
gene CDKN1B
gene ETV6
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226322-WG01_walk_2_KRAS_containing.fa
gene CDKN1B
gene ETV6
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226323-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226324-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226324-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene ERC1
gene TBX3
gene SETD1B
gene ZCCHC8
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running patient  8
running file  226327-WG01_walk_4_MYC_containing.fa
gene RECQL4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene NCOA2
gene PREX2
gene CNBD1
running file  226328-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226328-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  226327-WG01_walk_2_MYCL_containing.fa
gene JUN
gene CDKN2C
gene JAK1
gene EPS15
gene MYCL
gene MPL
gene MUTYH
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  226329-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226328-WG01_walk_3_MYCN_containing.fa

gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRIG3
we have a gene!
gene LRIG3
we have a gene!
running file  226328-WG01_walk_1_MYCN_containing.fa
gene SETBP1
we have a gene!
gene SETBP1
we have a gene!
gene SETBP1
we have a gene!
gene LRIG3
we have a gene!
gene LRIG3
we have a gene!
gene LRIG3
we have a gene!
gene LRIG3
we have a gene!
gene SMAD2
we have a gene!
gene SMAD2
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene SMAD2
we have a gene!
gene SMAD2
we have a gene!
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  226328-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226329-WG01_walk_1_MYCN_containing.fa
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226328-WG01_walk_1_KRAS_containing.fa
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
running file  226327-WG01_walk_1_KRAS_containing.fa
gene PPFIBP1
gene KRAS
we have a gene!
gene ETNK1
gene CDKN1B
we have a gene!
gene ETV6
we have a gene!
gene ETV6
we have a gene!
gene PTPN6
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene ZNF384
gene ERC1
running file  226328-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene ATP1A1
gene NOTCH2
we have a gene!
running file  226327-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
we have a gene!
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene WRN
we have a gene!
gene NRG1
gene NSD3
gene LEPROTL1
gene PCM1
gene ARHGEF10
we have a gene!
running file  226327-WG01_walk_2_MYC_containing.fa
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
we have a gene!
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene WRN
we have a gene!
gene NRG1
gene NSD3
gene LEPROTL1
gene PCM1
gene ARHGEF10
we have a gene!
running file  226329-WG01_walk_2_MYCL_containing.fa
gene MYCL
gene JUN
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  226329-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226327-WG01_walk_3_MYC_containing.fa
gene RECQL4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
we have a gene!
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene WRN
we have a gene!
gene NRG1
gene NSD3
gene JUN
gene CDKN2C
gene JAK1
gene EPS15
running file  226327-WG01_walk_1_MYCN_containing.fa
gene RANBP2
gene RGPD3
gene AFF3
we have a gene!
gene PAX8
gene AFF3
we have a gene!
gene TMEM127
gene CTNNA2
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene BIRC6
we have a gene!
gene BIRC6
we have a gene!
gene ALK
we have a gene!
gene ALK
we have a gene!
gene ASXL2
we have a gene!
gene DNMT3A
we have a gene!
gene WDCP
gene NCOA1
we have a gene!
gene MYCN
running file  226329-WG01_walk_3_MYCL_containing.fa
gene MYCL
gene JUN
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
running file  226329-WG01_walk_1_MYCL_containing.fa
gene NOTCH2
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene MYCL
gene JUN
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  226328-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226327-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene MYCL
gene MPL
gene MUTYH
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene JUN
gene CDKN2C
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene FUBP1
running file  226328-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene LEPROTL1
gene FGFR1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ARHGEF10
running patient  9
running file  226336-WG01_walk_2_MYCL_containing.fa
gene BCL9
gene ARNT
we have a gene!
gene PDE4DIP
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226337-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene ARHGEF10
running file  226336-WG01_walk_1_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene NAB2
gene GLI1
gene DDIT3
gene CDK4

gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene HOXC13
gene HOXC11
gene COL2A1
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene ERBB3
we have a gene!
gene ARID2
gene SMAD4
gene KDSR
gene SS18
gene SETBP1
gene SMAD2
gene BCL2
gene DCC
gene MALT1
gene ZNF521
running file  226338-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226336-WG01_walk_3_MYCL_containing.fa
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226338-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene PCBP1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226336-WG01_walk_3_MYCN_containing.fa
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226336-WG01_walk_1_KRAS_containing.fa
gene PPFIBP1
we have a gene!
gene PTPN6
gene CDKN1B
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene ERC1
we have a gene!
running file  226337-WG01_walk_1_MYCL_containing.fa
gene NTRK1
error!!!! in row index 0
gene PRCC
error!!!! in row index 1
gene LMNA
gene MUC1
error!!!! in row index 3
gene S100A7
we have a gene!
gene TPM3
gene SETDB1
gene MLLT11
gene ARNT
we have a gene!
gene BCL9
gene PDE4DIP
gene NOTCH2
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene EPS15
gene ATP1A1
gene MUTYH
gene MPL
gene ID3
gene MYCL
we have a gene!
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
running file  226338-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CCND2
gene KDM5A
error!!!! in row index 44
gene ERC1
running file  226336-WG01_walk_2_MDM2_containing.fa
gene PPFIBP1
we have a gene!
gene ARID2
gene HOXC13
gene HOXC11
gene COL2A1
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene ERBB3
we have a gene!
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226338-WG01_walk_1_MYCL_containing.fa
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene ARNT
gene MUC1
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene MYCL
gene JUN
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARID1A
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  226337-WG01_walk_3_MYCN_containing.fa
gene SIX2
error!!!! in row index 0
gene EPAS1
we have a gene!
gene EML4
we have a gene!
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene MYCN
we have a gene!
running file  226338-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226338-WG01_walk_2_MYCL_containing.fa
gene FUBP1
gene MYCL
gene JUN
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARID1A
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  226338-WG01_walk_2_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226336-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene BARD1
gene ATIC
gene ERBB4
gene ACSL3
gene PAX3
gene ACKR3
gene CUL3
we have a gene!
running file  226337-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
running file  226336-WG01_walk_2_MYCN_containing.fa
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226336-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226336-WG01_walk_1_MYCL_containing.fa

gene BCL9
gene ARNT
we have a gene!
gene PDE4DIP
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226337-WG01_walk_1_MYCN_containing.fa
gene MYCN
we have a gene!
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene EML4
we have a gene!
gene SIX2
we have a gene!
gene EPAS1
we have a gene!
gene MSH6
gene FBXO11
gene MSH2
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene CXCR4
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene ACVR1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene HOXD11
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene COL3A1
gene SF3B1
gene ITGAV
gene PMS1
gene FEV
gene BARD1
gene ATIC
gene ERBB4
gene ACSL3
gene PAX3
running file  226338-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CCND2
gene KDM5A
error!!!! in row index 44
gene ERC1
running file  226336-WG01_walk_2_KRAS_containing.fa
gene PPFIBP1
we have a gene!
gene PTPN6
gene CDKN1B
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 10
gene ERC1
we have a gene!
running file  226337-WG01_walk_3_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene GNAS
gene SALL4
we have a gene!
gene SDC4
we have a gene!
gene NFATC2
we have a gene!
gene PTK6
we have a gene!
running file  226337-WG01_walk_2_MYCL_containing.fa
gene BCL9
gene PDE4DIP
gene NOTCH2
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene EPS15
gene ATP1A1
gene MUTYH
gene MPL
gene ID3
gene MYCL
we have a gene!
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
running file  226337-WG01_walk_1_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene HOXC13
gene HOXC11
gene COL2A1
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene ERBB3
we have a gene!
gene ARID2
running file  226337-WG01_walk_2_MYCN_containing.fa
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
we have a gene!
gene EPAS1
we have a gene!
gene EML4
we have a gene!
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene MYCN
we have a gene!
running patient  10
running file  226330-WG01_walk_1_MYCN_containing.fa
gene ACKR3
gene HOXD11
gene FEV
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
we have a gene!
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene CXCR4
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene AFF3
gene PAX8
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226330-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226330-WG01_walk_1_MYC_containing.fa
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene TCEA1
gene LYN
gene RUNX1T1
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
we have a gene!
gene NSD3
we have a gene!
gene NRG1
we have a gene!
gene WRN
we have a gene!
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
running file  226334-WG01_walk_2_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene CHST11
gene NAB2
we have a gene!
gene GLI1
gene DDIT3
gene CDK4
gene NACA
we have a gene!
gene STAT6
we have a gene!
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene ERBB3
we have a gene!
gene HOXC13
gene HOXC11
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 39
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226333-WG01_walk_3_MYCL_containing.fa
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene SFPQ
we have a gene!
gene THRAP3
gene CSF3R
running file  226334-WG01_walk_2_MYC_containing.fa
gene BCL11A
gene REL
gene XPO1
gene MSH6
gene FBXO11
gene MSH2
gene NCOA2
we have a gene!
gene HEY1
gene NBN
gene CDH17
gene RUNX1T1
gene CNBD1
gene COX6C
gene PABPC1
we have a gene!
gene EIF3E
gene RAD21
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene MYC
gene NDRG1
gene FAM135B
gene RECQL4
running file  226332-WG01_walk_2_KRAS_containing.fa
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 5
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226334-WG01_walk_1_KRAS_containing.fa
gene PHF6
we have a gene!
gene GPC3
we have a gene!
gene PPP6C
we have a gene!
gene TNC
we have a gene!
gene CNTRL
we have a gene!
gene TCL1A
we have a gene!
gene DICER1
we have a gene!
gene TRIP11
we have a gene!
gene GOLGA5
we have a gene!
gene BCL11B
we have a gene!
gene HSP90AA1
we have a gene!
gene CHST11
we have a gene!
gene NAB2
we have a gene!
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene NACA
we have a gene!
gene STAT6
we have a gene!
gene LRIG3
we have a gene!
gene WIF1
we have a gene!
gene HMGA2
we have a gene!
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene BTG1
we have a gene!
gene USP44
we have a gene!
gene ERBB3
we have a gene!
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene KRAS
we have a gene!
gene COL2A1
we have a gene!
gene PRPF40B
we have a gene!
gene SMARCD1
we have a gene!
gene ATF1
we have a gene!
gene ACVR1B
we have a gene!
gene ETNK1
we have a gene!
gene PPFIBP1
we have a gene!
gene ARID2
we have a gene!
gene KMT2D
we have a gene!
gene PTPN6
we have a gene!
gene CDKN1B
we have a gene!
gene KDM5A
error!!!! in row index 40
gene CCND2
we have a gene!
gene CHD4
we have a gene!
gene ZNF384
we have a gene!
gene ETV6
we have a gene!
gene ERC1
we have a gene!
running file  226332-WG01_walk_1_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D

gene ERBB3
gene MDM2
gene PTPRB
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
we have a gene!
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
we have a gene!
running file  226333-WG01_walk_1_MYCN_containing.fa
gene SIX2
we have a gene!
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene FBXO11
gene MSH2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene WDCP
we have a gene!
gene ASXL2
we have a gene!
gene NCOA1
gene DNMT3A
gene MYCN
running file  226334-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene KAT6A
gene NCOA2
we have a gene!
gene PREX2
gene NCOA2
we have a gene!
gene HEY1
gene NBN
gene CDH17
gene RUNX1T1
gene CNBD1
gene COX6C
gene PABPC1
we have a gene!
gene EIF3E
gene RAD21
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene MYC
gene NDRG1
gene FAM135B
gene KDSR
gene BCL2
gene MALT1
running file  226330-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226330-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226330-WG01_walk_2_MYC_containing.fa
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene TCEA1
gene LYN
gene RUNX1T1
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
we have a gene!
gene NSD3
we have a gene!
gene NRG1
we have a gene!
gene WRN
we have a gene!
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
running file  226330-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226332-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226333-WG01_walk_4_MYCL_containing.fa
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
running file  226332-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226332-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene ATP1A1
running file  226332-WG01_walk_1_KRAS_containing.fa
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 5
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226332-WG01_walk_1_MYCN_containing.fa
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226334-WG01_walk_1_MDM2_containing.fa
gene PHF6
we have a gene!
error!!!! in row index 0
gene GPC3
we have a gene!
error!!!! in row index 1
gene PPP6C
we have a gene!
error!!!! in row index 2
gene TNC
we have a gene!
error!!!! in row index 3
gene CNTRL
we have a gene!
error!!!! in row index 4
gene TCL1A
we have a gene!
error!!!! in row index 5
gene DICER1
we have a gene!
error!!!! in row index 6
gene TRIP11
we have a gene!
error!!!! in row index 7
gene GOLGA5
we have a gene!
error!!!! in row index 8
gene BCL11B
we have a gene!
error!!!! in row index 9
gene HSP90AA1
we have a gene!
error!!!! in row index 10
gene CHST11
we have a gene!
error!!!! in row index 11
gene NAB2
we have a gene!
error!!!! in row index 12
gene GLI1
we have a gene!
error!!!! in row index 13
gene DDIT3
we have a gene!
error!!!! in row index 14
gene CDK4
we have a gene!
error!!!! in row index 15
gene NACA
we have a gene!
error!!!! in row index 16
gene STAT6
we have a gene!
error!!!! in row index 17
gene LRIG3
we have a gene!
error!!!! in row index 18
gene WIF1
we have a gene!
error!!!! in row index 19
gene HMGA2
we have a gene!
error!!!! in row index 20
gene MDM2
we have a gene!
error!!!! in row index 21
gene PTPRB
we have a gene!
error!!!! in row index 22
gene BTG1
we have a gene!
error!!!! in row index 23
gene USP44
we have a gene!
error!!!! in row index 24
gene ERBB3
we have a gene!
error!!!! in row index 25
gene HOXC13
we have a gene!
error!!!! in row index 26
gene HOXC11
we have a gene!
error!!!! in row index 27
gene KRAS
we have a gene!
error!!!! in row index 28
gene COL2A1
we have a gene!
error!!!! in row index 29
gene PRPF40B
we have a gene!
error!!!! in row index 30
gene SMARCD1
we have a gene!
error!!!! in row index 31
gene ATF1
we have a gene!
error!!!! in row index 32
gene ACVR1B
we have a gene!
error!!!! in row index 33
gene ETNK1
we have a gene!
error!!!! in row index 34
gene PPFIBP1
we have a gene!
error!!!! in row index 35
gene ARID2
we have a gene!
error!!!! in row index 36
gene KMT2D
we have a gene!
error!!!! in row index 37
gene PTPN6
we have a gene!
error!!!! in row index 38
gene CDKN1B
we have a gene!
error!!!! in row index 39
gene KDM5A
error!!!! in row index 40
gene CCND2
we have a gene!
error!!!! in row index 41
gene CHD4
we have a gene!
error!!!! in row index 42
gene ZNF384
we have a gene!
error!!!! in row index 43
gene ETV6
we have a gene!
error!!!! in row index 44
gene ERC1
we have a gene!
error!!!! in row index 45
running file  226333-WG01_walk_1_MYCL_containing.fa
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene SFPQ
we have a gene!
gene THRAP3
gene CSF3R
gene SIX2
we have a gene!
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene FBXO11
gene MSH2
running file  226333-WG01_walk_2_MYCL_containing.fa

gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene SFPQ
we have a gene!
gene THRAP3
gene CSF3R
gene LCK
running file  226334-WG01_walk_1_MYCN_containing.fa
gene TET1
error!!!! in row index 0
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
gene EPAS1
we have a gene!
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
running file  226334-WG01_walk_2_KRAS_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene CHST11
gene NAB2
we have a gene!
gene GLI1
gene DDIT3
gene CDK4
gene NACA
we have a gene!
gene STAT6
we have a gene!
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene ERBB3
we have a gene!
gene HOXC13
gene HOXC11
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 39
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226330-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226332-WG01_walk_1_MYCL_containing.fa
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226333-WG01_walk_2_MYCN_containing.fa
gene SIX2
we have a gene!
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene FBXO11
gene MSH2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene WDCP
we have a gene!
gene ASXL2
we have a gene!
gene NCOA1
gene DNMT3A
gene MYCN
running file  226334-WG01_walk_2_MYCN_containing.fa
gene SIX2
gene EPAS1
we have a gene!
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
running patient  11
running file  226346-WG01_walk_2_MYCL_containing.fa
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene CDC73
gene PTPRC
gene ABL2
we have a gene!
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226345-WG01_walk_3_MYC_containing.fa
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
running file  226346-WG01_walk_1_MDM2_containing.fa
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene PAX3
we have a gene!
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ACVR1
gene COL3A1
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  226346-WG01_walk_3_KRAS_containing.fa
gene ARID2
we have a gene!
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
running file  226346-WG01_walk_2_KRAS_containing.fa
gene FLT4
we have a gene!
gene ITK
gene PWWP2A
gene NPM1
gene FGFR4
gene EBF1
gene TLX3
gene NSD1
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
running file  226345-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
we have a gene!
gene ERC1
running file  226346-WG01_walk_1_MYCL_containing.fa
gene AKT3
gene FH
we have a gene!
gene RGS7
we have a gene!
gene RGS7
we have a gene!
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene CDC73
gene PTPRC
gene ABL2
we have a gene!
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226346-WG01_walk_2_MDM2_containing.fa
gene TERT
we have a gene!
gene TERT
we have a gene!
gene FEV
we have a gene!
gene TFG
we have a gene!
gene CBLB
gene GATA2
gene RPN1
gene CNBP
gene POLQ
gene STAG1
we have a gene!
gene FOXL2
we have a gene!
gene PIK3CB
we have a gene!
gene ATR
we have a gene!
gene PAX3
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  226346-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226346-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226345-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  226346-WG01_walk_3_MYCL_containing.fa
gene SIRPA
error!!!! in row index 0
gene CRNKL1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226345-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH

gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226345-WG01_walk_1_MYCN_containing.fa
gene SF3B1
we have a gene!
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  226345-WG01_walk_2_MYC_containing.fa
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
running file  226346-WG01_walk_1_MYCN_containing.fa
gene PAX3
we have a gene!
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ACVR1
gene COL3A1
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  226345-WG01_walk_1_MYC_containing.fa
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
running file  226346-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ACVR1
gene COL3A1
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  226346-WG01_walk_1_KRAS_containing.fa
gene ARID2
we have a gene!
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene ZNF384
gene ERC1
running patient  12
running file  226342-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226342-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene PHOX2B
gene N4BP2
gene RHOH
gene FGFR3
gene SLC34A2
gene NSD2
running file  226342-WG01_walk_1_KRAS_containing.fa
gene LRIG3
we have a gene!
gene LATS1
we have a gene!
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene NACA
we have a gene!
gene NACA
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226342-WG01_walk_1_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
we have a gene!
gene LRIG3
we have a gene!
gene CHST11
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene TBX3
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226340-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226341-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226340-WG01_walk_2_MYC_containing.fa
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226341-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226341-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226342-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
gene HEY1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
we have a gene!
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene KAT6A
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226340-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1

gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226340-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226342-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226343-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226343-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene LEPROTL1
gene PCM1
gene WRN
running file  226343-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226343-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene NACA
we have a gene!
running file  226340-WG01_walk_1_MYC_containing.fa
gene HEY1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene NRG1
we have a gene!
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene KAT6A
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226340-WG01_walk_1_KRAS_containing.fa
gene BCLAF1
gene TNFAIP3
we have a gene!
gene ECT2L
we have a gene!
gene PRDM1
we have a gene!
gene FOXO3
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226343-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226341-WG01_walk_1_MYC_containing.fa
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene KAT6A
gene PRDM1
we have a gene!
gene TNFAIP3
we have a gene!
gene ECT2L
we have a gene!
running patient  13
running file  226350-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226350-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226350-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226350-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226351-WG01_walk_1_MDM2_containing.fa
gene HIST1H3B
gene HIST1H4I
gene HLA-A
gene POU5F1
gene DAXX
gene CCND3
gene NFKBIE
gene DEK
gene TRIM27
gene HMGA1
gene FANCE
gene CDKN1A
gene SRSF3
gene PIM1
gene TFEB
gene HSP90AB1
gene CCNC
gene PRDM1
gene MYB
gene BCLAF1
gene TNFAIP3
gene IRF4
error!!!! in row index 21
gene BMP5
gene FOXO3
gene ROS1
gene GOPC
gene RSPO3
gene PTPRK
gene ECT2L
gene EPHA7
gene SGK1
gene MDM2
we have a gene!
running file  226349-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226349-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
we have a gene!
running file  226348-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226351-WG01_walk_1_MYC_containing.fa

gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226351-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
we have a gene!
running file  226350-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226351-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226348-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene MYCN
running file  226351-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226349-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
running file  226348-WG01_walk_1_KRAS_containing.fa
gene CDK4
we have a gene!
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  226348-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene CDKN2C
gene EPS15
we have a gene!
gene EPS15
we have a gene!
running file  226349-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226349-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226349-WG01_walk_1_MDM2_containing.fa
gene CDK4
error!!!! in row index 0
gene MDM2
we have a gene!
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
we have a gene!
gene MDM2
we have a gene!
running patient  14
running file  226355-WG01_walk_2_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226355-WG01_walk_3_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226356-WG01_walk_1_MYC_containing.fa
gene ARHGEF10
gene PCM1
we have a gene!
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226355-WG01_walk_1_MDM2_containing.fa
gene MDM2
error!!!! in row index 0
gene MDM2
error!!!! in row index 1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene CDC73
gene PTPRC
gene CDK4
we have a gene!
gene CDK4
we have a gene!
running file  226355-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226356-WG01_walk_1_KRAS_containing.fa
gene HMGA2
we have a gene!
gene WIF1
gene LRIG3
we have a gene!
gene CDK4
we have a gene!
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 11
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  226356-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene PRRX1
we have a gene!
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ABL2
gene CDC73
gene PTPRC
running file  226354-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2

gene KMT2D
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene BTG1
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene BTG1
we have a gene!
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 53
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226356-WG01_walk_2_KRAS_containing.fa
gene CDK4
we have a gene!
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  226354-WG01_walk_3_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226354-WG01_walk_4_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226355-WG01_walk_2_MYCL_containing.fa
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene ID3
we have a gene!
gene MYCL
we have a gene!
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
we have a gene!
gene ARID1A
gene MPL
gene MUTYH
we have a gene!
gene STIL
gene TAL1
gene CDKN2C
we have a gene!
gene EPS15
we have a gene!
gene EPS15
we have a gene!
gene JUN
gene JAK1
we have a gene!
gene ITGAV
we have a gene!
gene COL3A1
gene PMS1
we have a gene!
running file  226355-WG01_walk_3_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene USP44
we have a gene!
running file  226354-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226355-WG01_walk_4_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226355-WG01_walk_3_KRAS_containing.fa
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 19
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226354-WG01_walk_3_MYCN_containing.fa
gene REL
error!!!! in row index 0
gene BCL11A
we have a gene!
gene REL
we have a gene!
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226356-WG01_walk_1_MDM2_containing.fa
gene MDM2
error!!!! in row index 0
gene PTPRB
gene BTG1
we have a gene!
gene USP44
we have a gene!
gene CHST11
we have a gene!
gene CHST11
we have a gene!
gene CHST11
we have a gene!
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226354-WG01_walk_1_MYCL_containing.fa
gene PRDM2
we have a gene!
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
we have a gene!
gene AKT3
we have a gene!
running file  226354-WG01_walk_2_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226355-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene NPM1
we have a gene!
running file  226356-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene PRRX1
we have a gene!
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ABL2
gene CDC73
gene PTPRC
gene FH
gene AKT3
gene RGS7
running file  226354-WG01_walk_3_MYCL_containing.fa
gene PRDM2
we have a gene!
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
running file  226354-WG01_walk_2_KRAS_containing.fa
gene NPM1
we have a gene!
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 18
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226354-WG01_walk_4_MYCL_containing.fa
gene PRDM2
we have a gene!
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
running file  226354-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene BTG1
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene BTG1
we have a gene!
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 53
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226355-WG01_walk_1_MYCL_containing.fa
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene ID3
we have a gene!
gene MYCL
we have a gene!
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
we have a gene!
gene ARID1A
gene MPL
gene MUTYH
we have a gene!
gene STIL
gene TAL1
gene CDKN2C
we have a gene!
gene EPS15
we have a gene!
gene EPS15
we have a gene!
gene JUN
gene JAK1
we have a gene!
gene ITGAV
we have a gene!
gene COL3A1
gene PMS1
we have a gene!
gene TLX1
we have a gene!
running file  226355-WG01_walk_1_MYC_containing.fa

gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene LATS2
gene CDX2
gene CYSLTR2
gene ZMYM2
gene FLT3
gene BRCA2
gene LHFPL6
gene FOXO1
gene RB1
gene NBEA
gene LCP1
running file  226355-WG01_walk_3_MYCL_containing.fa
gene CDKN2C
we have a gene!
gene EPS15
we have a gene!
gene STIL
gene TAL1
gene MPL
gene MUTYH
we have a gene!
gene ID3
we have a gene!
gene MYCL
we have a gene!
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
we have a gene!
gene ARID1A
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
running file  226354-WG01_walk_2_MYCL_containing.fa
gene PRDM2
we have a gene!
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
running file  226356-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226355-WG01_walk_1_KRAS_containing.fa
gene H3F3B
gene SRSF2
gene CANT1
gene ASPSCR1
gene SEPT9
gene RNF213
gene CCR7
gene TAF15
gene MLLT6
gene LASP1
gene CDK12
gene RARA
gene ETV4
gene RNF43
gene PPM1D
gene CD79B
gene DDX5
gene PRKAR1A
gene NF1
gene SUZ12
gene ERBB2
gene SMARCE1
gene STAT3
gene STAT5B
gene BRCA1
gene COL1A1
gene KAT7
gene SPOP
gene HLF
gene CLTC
gene BRIP1
gene AXIN2
gene IKZF3
gene MSI2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 36
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226355-WG01_walk_1_MYCN_containing.fa
gene SOX2
gene EIF4A2
gene ETV5
gene BCL6
gene MUC4
gene TFRC
gene TBL1XR1
gene PIK3CA
gene MAP3K13
gene IGF2BP2
gene MB21D2
gene LPP
gene TP63
gene FOXL2
gene TFG
gene GATA2
gene RPN1
gene CNBP
gene GMPS
gene MECOM
gene CBLB
gene POLQ
gene STAG1
gene PIK3CB
gene ATR
gene WWTR1
gene MLF1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226354-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PMS2
gene RAC1
gene HNRNPA2B1
we have a gene!
gene CARD11
we have a gene!
gene ETV1
gene MACC1
running patient  15
running file  226359-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
we have a gene!
gene LRIG3
gene PTPRB
gene MDM2
we have a gene!
running file  226358-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226360-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226358-WG01_walk_1_MYCL_containing.fa
gene PRRX1
error!!!! in row index 0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226359-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
we have a gene!
gene LRIG3
gene PTPRB
gene MDM2
we have a gene!
running file  226358-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene RECQL4
we have a gene!
running file  226358-WG01_walk_1_MYCN_containing.fa
gene MYCN
we have a gene!
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226358-WG01_walk_1_KRAS_containing.fa
gene CD274
gene PDCD1LG2
gene CDKN2A
gene FANCG
gene JAK2
gene NFIB
gene PSIP1
gene MLLT3
gene PAX5
gene PTPRD
gene BIRC3
we have a gene!
gene BIRC3
we have a gene!
gene BIRC3
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene HMGA2
we have a gene!
gene CDK4
we have a gene!
gene CDK4
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 35
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226360-WG01_walk_1_MDM2_containing.fa
gene MDM2
we have a gene!
gene PTPRB
we have a gene!
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226360-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1

gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
running file  226359-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226360-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226358-WG01_walk_2_KRAS_containing.fa
gene SDHD
gene POU2AF1
gene PAFAH1B2
gene BCL9L
gene FOXR1
gene KCNJ5
gene ATM
gene DDX10
gene ZBTB16
gene CBL
gene DDX6
gene ARHGEF12
gene FLI1
gene KMT2A
gene CDK4
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 32
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226359-WG01_walk_2_KRAS_containing.fa
gene KCNJ5
gene FLI1
gene SDHD
gene POU2AF1
gene PAFAH1B2
gene BCL9L
gene FOXR1
gene ATM
gene DDX10
gene ZBTB16
gene CBL
gene DDX6
gene ARHGEF12
gene KMT2A
gene CDK4
we have a gene!
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 22
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  226359-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene H3F3A
gene FH
gene AKT3
gene RGS7
running file  226360-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
we have a gene!
gene SDHD
gene POU2AF1
gene PAFAH1B2
gene BCL9L
gene FOXR1
gene ATM
gene DDX10
gene ZBTB16
gene CBL
gene DDX6
gene ARHGEF12
gene KMT2A
gene KCNJ5
gene FLI1
running file  226359-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running patient  16
running file  226363-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226362-WG01_walk_4_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226363-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226362-WG01_walk_3_MYC_containing.fa
gene CDH17
gene COX6C
gene PABPC1
gene UBR5
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene MYC
gene RECQL4
we have a gene!
gene NDRG1
gene FAM135B
running file  226362-WG01_walk_1_MYCL_containing.fa
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene RPL5
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene ID3
gene MDS2
gene ARID1A
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene MTOR
gene PRDM2
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene PRDM2
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene ID3
gene MDS2
gene ARID1A
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene FUBP1
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene PTPN13
gene RAP1GDS1
gene AFF1
gene TET2
we have a gene!
gene LEF1
gene IL2
gene FCGR2B
gene PRRX1
we have a gene!
gene SDHC
gene DDR2
gene PBX1
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene FCRL4
gene TPM3
gene LMNA
we have a gene!
gene MUC1
gene S100A7
we have a gene!
gene SETDB1
gene MLLT11
gene ARNT
running file  226362-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene CXCR4
gene ERCC3
we have a gene!
gene LRP1B
gene ACVR2A
gene TPR
gene ABL2
gene PRRX1
we have a gene!
running file  226362-WG01_walk_2_MYCL_containing.fa
gene MAF
gene RFWD3
error!!!! in row index 1
gene CBFA2T3
gene FANCA
gene CBFB
we have a gene!
gene CTCF
gene CDH1
gene ZFHX3
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene ID3
gene MDS2
gene ARID1A
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226362-WG01_walk_2_KRAS_containing.fa
gene SEPT5
gene DGCR8
gene LZTR1
gene SMARCB1
gene CLTCL1
gene MAPK1
gene BCR
gene MN1
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 10
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226363-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene COL2A1
gene ARID2
running file  226362-WG01_walk_3_KRAS_containing.fa

gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226362-WG01_walk_1_KRAS_containing.fa
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 11
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226362-WG01_walk_3_MYCN_containing.fa
gene ACVR1
gene CXCR4
gene ERCC3
we have a gene!
gene LRP1B
gene ACVR2A
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226362-WG01_walk_1_MYCN_containing.fa
gene MAF
gene RFWD3
error!!!! in row index 1
gene CBFA2T3
gene FANCA
gene CBFB
we have a gene!
gene CTCF
gene CDH1
gene ZFHX3
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene ID3
gene MDS2
gene ARID1A
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226363-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226363-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226362-WG01_walk_3_MYCL_containing.fa
gene MSN
error!!!! in row index 0
gene MYCL
we have a gene!
gene JUN
we have a gene!
gene MPL
we have a gene!
gene MUTYH
we have a gene!
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene CDKN2C
we have a gene!
gene JAK1
we have a gene!
gene EPS15
we have a gene!
running file  226362-WG01_walk_2_MYC_containing.fa
gene RECQL4
we have a gene!
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene COX6C
gene PABPC1
gene UBR5
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
running file  226362-WG01_walk_1_MYC_containing.fa
gene RECQL4
we have a gene!
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene COX6C
gene PABPC1
gene UBR5
gene CDH17
gene HEY1
gene NBN
gene RUNX1T1
gene CNBD1
running patient  17
running file  226367-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ERC1
gene ALDH2
gene SH2B3
gene PTPN11
we have a gene!
gene TBX3
gene PTPN11
we have a gene!
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226367-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene FGFR1
gene NSD3
gene ANK1
we have a gene!
gene KAT6A
we have a gene!
gene IKBKB
we have a gene!
gene HOOK3
we have a gene!
gene KAT6A
we have a gene!
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
running file  226366-WG01_walk_2_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene PTPRB
gene BTG1
gene USP44
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
we have a gene!
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226366-WG01_walk_1_MYCL_containing.fa
gene SKI
we have a gene!
gene TNFRSF14
we have a gene!
gene MTOR
gene PRDM2
gene CAMTA1
gene CASP9
gene SPEN
gene SDHB
we have a gene!
gene ID3
gene PAX7
gene LCK
we have a gene!
gene ARHGEF10L
gene SDHB
we have a gene!
gene MDS2
gene ARID1A
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene JUN
gene BCL10
gene RPL5
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene BTG2
running file  226366-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HOOK3
we have a gene!
gene IKBKB
gene ANK1
we have a gene!
gene KAT6A
running file  226365-WG01_walk_2_MYCL_containing.fa
gene SDHA
error!!!! in row index 0
gene TERT
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene BCL10
gene FUBP1
gene RPL5
gene RBM15
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
we have a gene!
gene ATP1A1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene ELF3
gene CDC73
gene PTPRC
gene BTG2
we have a gene!
running file  226366-WG01_walk_2_MYCL_containing.fa
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene ID3
gene PAX7
gene LCK
we have a gene!
gene ARHGEF10L
gene SDHB
we have a gene!
gene MDS2
gene ARID1A
gene CASP9
gene SPEN
gene SDHB
we have a gene!
gene MTOR
gene PRDM2
gene CAMTA1
gene RPL22
we have a gene!
gene PRDM16
we have a gene!
gene TNFRSF14
we have a gene!
gene SKI
running file  226367-WG01_walk_1_MYCL_containing.fa
gene H3F3A
gene FH
gene AKT3
gene RGS7
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
we have a gene!
gene STIL
gene TAL1
gene CDKN2C
we have a gene!
gene MUTYH
gene MPL
gene MYCL
we have a gene!
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene TNFRSF14
gene ID3

gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  226366-WG01_walk_1_KRAS_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene PTPRB
gene BTG1
gene USP44
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
we have a gene!
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226365-WG01_walk_1_KRAS_containing.fa
gene POLE
error!!!! in row index 0
gene NCOR2
gene POLE
we have a gene!
gene SETD1B
gene ZCCHC8
gene HNF1A
we have a gene!
gene BCL7A
gene CLIP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
we have a gene!
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene COL2A1
gene ARID2
gene KMT2D
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 38
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226365-WG01_walk_1_MYCN_containing.fa
gene GNAQ
we have a gene!
gene GNAQ
we have a gene!
gene GNAQ
we have a gene!
gene FANCG
we have a gene!
gene PAX5
gene CDKN2A
gene NFIB
gene PSIP1
gene MLLT3
gene PTPRD
we have a gene!
gene PCBP1
gene CXCR4
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226366-WG01_walk_3_MDM2_containing.fa
gene TBX3
gene SETD1B
gene ZCCHC8
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene PTPRB
gene BTG1
gene USP44
running file  226366-WG01_walk_1_MDM2_containing.fa
gene HIST1H3B
gene HIST1H4I
gene HLA-A
gene POU5F1
gene DAXX
gene DEK
gene TRIM27
gene HMGA1
gene FANCE
gene CDKN1A
gene SRSF3
gene PIM1
gene MDM2
gene PTPRB
gene BTG1
gene USP44
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
we have a gene!
gene ARID2
gene KMT2D
gene ERBB3
gene CASP9
gene SPEN
gene SDHB
we have a gene!
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDH10
gene FOXA1
gene NKX2-1
gene NIN
gene KTN1
gene BAZ1A
gene ARHGAP5
gene CCNB1IP1
gene PRKD1
running file  226365-WG01_walk_1_MYCL_containing.fa
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene PDE4DIP
gene MUC1
gene PBX1
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
we have a gene!
gene ATP1A1
gene RPL5
gene RBM15
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene ARHGEF10L
gene SDHB
we have a gene!
gene MDS2
gene ARID1A
gene SPEN
we have a gene!
gene CASP9
we have a gene!
gene PRDM2
we have a gene!
gene MTOR
gene PRDM2
we have a gene!
gene CAMTA1
we have a gene!
gene CAMTA1
we have a gene!
gene CAMTA1
we have a gene!
gene CAMTA1
we have a gene!
gene RPL22
we have a gene!
gene PRDM16
we have a gene!
gene TNFRSF14
we have a gene!
gene SKI
we have a gene!
running file  226366-WG01_walk_1_MYCN_containing.fa
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene CXCR4
gene RANBP2
gene RGPD3
gene ERCC3
gene PAX8
gene LRP1B
gene TMEM127
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226366-WG01_walk_3_MYCL_containing.fa
gene HIST1H3B
gene HIST1H4I
gene HLA-A
gene POU5F1
gene DAXX
gene DEK
gene TRIM27
gene HMGA1
gene FANCE
gene CDKN1A
gene SRSF3
gene PIM1
gene MDM2
gene PTPRB
gene BTG1
gene USP44
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
we have a gene!
gene ARID2
gene KMT2D
gene ERBB3
gene CASP9
gene SPEN
gene SDHB
we have a gene!
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDH10
gene FOXA1
gene NKX2-1
gene NIN
gene KTN1
gene BAZ1A
gene ARHGAP5
gene CCNB1IP1
gene PRKD1
running file  226365-WG01_walk_2_MDM2_containing.fa
gene ITK
gene PWWP2A
gene NPM1
gene EBF1
gene TLX3
gene PDGFRB
gene CD74
gene ARHGAP26
we have a gene!
gene CSF1R
gene CTNNA1
gene ARHGAP26
we have a gene!
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
we have a gene!
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene SETD1B
gene ZCCHC8
gene HNF1A
we have a gene!
gene BCL7A
gene CLIP1
running file  226366-WG01_walk_2_MYCN_containing.fa
gene CDKN2A
gene FANCG
gene NFIB
gene PSIP1
gene MLLT3
gene PAX5
gene PTPRD
we have a gene!
gene CXCR4
gene RANBP2
gene RGPD3
gene ERCC3
gene PAX8
gene LRP1B
gene TMEM127
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226367-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
we have a gene!
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene STRN
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226367-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ERC1
gene ALDH2
gene SH2B3
gene PTPN11
we have a gene!
gene TBX3
gene PTPN11
we have a gene!
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226365-WG01_walk_1_MDM2_containing.fa
gene POLE
error!!!! in row index 0
gene NCOR2
gene POLE
we have a gene!
gene SETD1B
gene ZCCHC8
gene HNF1A
we have a gene!
gene BCL7A
gene CLIP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
we have a gene!
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene COL2A1
gene ARID2
gene KMT2D
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 38
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226365-WG01_walk_3_MYCL_containing.fa
gene SALL4
we have a gene!
gene NFATC2
we have a gene!
gene SDC4
gene PTPRT
we have a gene!
gene PTPRT
we have a gene!
gene TOP1
we have a gene!
gene PLCG1
we have a gene!
gene PTPRT
we have a gene!
gene MAFB
we have a gene!
gene TOP1
we have a gene!
gene SRC
gene ASXL1
we have a gene!
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH

gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene ARHGEF10L
gene SDHB
we have a gene!
gene MDS2
gene ARID1A
gene SPEN
we have a gene!
gene CASP9
we have a gene!
gene PRDM2
we have a gene!
gene MTOR
gene PRDM2
we have a gene!
gene CAMTA1
we have a gene!
gene CAMTA1
we have a gene!
gene CAMTA1
we have a gene!
gene CAMTA1
we have a gene!
gene RPL22
we have a gene!
gene PRDM16
we have a gene!
gene TNFRSF14
we have a gene!
gene SKI
we have a gene!
running file  226365-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
running patient  18
running file  227171-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene FSTL3
gene CD209
gene LYL1
gene STK11
gene TCF3
gene GNA11
gene MAP2K2
gene SH3GL1
gene MLLT1
gene KEAP1
gene CALR
gene PRKACA
gene DNAJB1
gene BRD4
gene TPM4
gene VAV1
gene MUC16
gene DNM2
gene SMARCA4
gene CRTC1
gene ELL
gene JAK3
running file  227171-WG01_walk_2_KRAS_containing.fa
gene ERBB3
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 3
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227170-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227171-WG01_walk_2_MDM2_containing.fa
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene BCL3
gene CD79A
gene CIC
gene CBLC
gene AKT2
gene ERCC2
gene ARHGAP35
gene ERBB3
we have a gene!
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene CDK4
we have a gene!
gene PRDM1
gene FOXO3
we have a gene!
gene CDK4
we have a gene!
gene NAB2
gene GLI1
we have a gene!
gene DDIT3
we have a gene!
gene NACA
gene STAT6
gene ERBB3
we have a gene!
gene BCL3
gene CD79A
gene CIC
gene CBLC
gene AKT2
gene ERCC2
gene ARHGAP35
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  227171-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  227169-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  227170-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  227169-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
running file  227170-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene WIF1
we have a gene!
gene HMGA2
running file  227169-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227171-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227171-WG01_walk_1_KRAS_containing.fa
gene KLK2
we have a gene!
gene TFPT
we have a gene!
gene PPP2R1A
gene ZNF331
gene CNOT3
we have a gene!
gene ERBB3
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227169-WG01_walk_1_KRAS_containing.fa
gene MAFB
gene TOP1
gene SDC4
gene SALL4
gene GNAS
gene SS18L1
gene PTK6
gene ASXL1
gene SRC
gene PLCG1
gene NFATC2
gene PTPRT
gene CRNKL1
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 17
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227169-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  227171-WG01_walk_1_MDM2_containing.fa
gene CYSLTR2
gene RB1
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  227170-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  227169-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A

gene CAMTA1
gene PRDM16
running file  227170-WG01_walk_1_KRAS_containing.fa
gene HOXC13
we have a gene!
gene HOXC11
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running patient  19
running file  227173-WG01_walk_2_MDM2_containing.fa
gene BIRC3
we have a gene!
gene CLP1
gene FEN1
gene MEN1
gene SDHAF2
gene MALAT1
gene CCND1
gene FADD
gene NUMA1
gene CTNND1
gene EED
gene FAT3
gene MAML2
gene PICALM
gene WT1
gene LMO2
gene CREB3L1
gene DDB2
gene EXT2
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  227172-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
we have a gene!
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene ACKR3
gene CASP8
we have a gene!
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene CUL3
gene ERBB4
gene PAX3
running file  227172-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene NCOA2
gene PREX2
gene KAT6A
gene HEY1
gene MYC
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
running file  227173-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  227173-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene PCBP1
gene CXCR4
gene HOXD11
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
we have a gene!
gene EML4
we have a gene!
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene ACKR3
gene CASP8
we have a gene!
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene CUL3
gene ERBB4
gene PAX3
running file  227172-WG01_walk_1_MDM2_containing.fa
gene RSPO3
error!!!! in row index 0
gene ETV1
gene MACC1
gene HOXA11
gene HNRNPA2B1
gene HOXA13
gene HOXA9
gene FKBP9
gene JAZF1
gene PTPRK
we have a gene!
gene PTPRK
we have a gene!
gene MYB
we have a gene!
gene SGK1
we have a gene!
gene BCLAF1
we have a gene!
gene BCLAF1
we have a gene!
gene TNFAIP3
gene ECT2L
gene LATS1
we have a gene!
gene MDM2
we have a gene!
running file  227173-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene NCOA2
gene PREX2
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227173-WG01_walk_3_MDM2_containing.fa
gene BTG1
we have a gene!
gene USP44
we have a gene!
gene TBX3
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
we have a gene!
gene SETD1B
gene ZCCHC8
we have a gene!
gene BCL7A
gene CLIP1
we have a gene!
gene NCOR2
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  227172-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  227172-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  227173-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene AKT3
gene RGS7
running file  227173-WG01_walk_1_MDM2_containing.fa
gene BIRC3
error!!!! in row index 0
gene CLP1
gene FEN1
gene MEN1
gene SDHAF2
gene MALAT1
gene CCND1
gene FADD
gene NUMA1
gene CTNND1
gene EED
gene FAT3
gene MAML2
gene PICALM
gene WT1
gene LMO2
gene CREB3L1
gene DDB2
gene EXT2
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene PMS2
we have a gene!
gene RAC1
we have a gene!
gene CARD11
running patient  20
running file  227176-WG01_walk_2_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  227175-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene FBXW7
gene IL2
gene PTPN13
gene RAP1GDS1
gene TET2
gene LEF1
gene FAT4
gene AFF1
gene FIP1L1
gene CHIC2
gene KIT
gene KDR
gene PDGFRA
gene FGFR3
gene SLC34A2
gene PHOX2B
gene NSD2
gene N4BP2
gene RHOH
gene TEC
running file  227176-WG01_walk_1_KRAS_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227175-WG01_walk_4_MDM2_containing.fa
gene HNF1A
we have a gene!
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
we have a gene!
running file  227175-WG01_walk_1_KRAS_containing.fa

gene POLE
we have a gene!
gene NCOR2
we have a gene!
gene SETD1B
we have a gene!
gene ZCCHC8
gene BCL7A
we have a gene!
gene CLIP1
gene HNF1A
we have a gene!
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  227175-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  227176-WG01_walk_1_MYCN_containing.fa
gene FEV
gene ACKR3
gene BARD1
gene ATIC
gene ACSL3
gene CUL3
gene ERBB4
gene PAX3
gene IDH1
we have a gene!
gene CREB1
we have a gene!
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
we have a gene!
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  227176-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene SDHB
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
running file  227175-WG01_walk_1_MYC_containing.fa
gene TLX1
gene NFKB2
gene SUFU
gene NT5C2
gene TCF7L2
gene VTI1A
gene SHTN1
gene CYP2C8
gene CPEB3
we have a gene!
gene CPEB3
we have a gene!
gene NUTM2D
gene BMPR1A
gene PTEN
gene FAS
gene NUTM2B
gene KAT6B
gene PRF1
gene CCDC6
gene TET1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227175-WG01_walk_4_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227175-WG01_walk_1_MYCL_containing.fa
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
gene FCRL4
we have a gene!
gene FCGR2B
gene PRRX1
we have a gene!
gene SDHC
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
we have a gene!
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene ARHGEF10L
we have a gene!
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
running file  227175-WG01_walk_4_MYCL_containing.fa
gene ARHGEF10L
error!!!! in row index 0
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
we have a gene!
gene ARHGEF10L
error!!!! in row index 6
gene MDS2
gene ARID1A
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
running file  227175-WG01_walk_2_MYCN_containing.fa
gene CASP8
gene CD28
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene CTNNA2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  227175-WG01_walk_1_MDM2_containing.fa
gene POLE
we have a gene!
gene NCOR2
we have a gene!
gene SETD1B
we have a gene!
gene ZCCHC8
gene BCL7A
we have a gene!
gene CLIP1
gene HNF1A
we have a gene!
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
we have a gene!
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  227175-WG01_walk_3_MDM2_containing.fa
gene SETD1B
we have a gene!
gene ZCCHC8
gene BCL7A
we have a gene!
gene CLIP1
gene HNF1A
we have a gene!
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
we have a gene!
running file  227176-WG01_walk_2_KRAS_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  227176-WG01_walk_1_MYC_containing.fa
gene MYC
gene RECQL4
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
error!!!! in row index 8
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
we have a gene!
gene HOOK3
we have a gene!
gene ANK1
we have a gene!
gene KAT6A
we have a gene!
gene LEPROTL1
gene FGFR1
gene PCM1
gene WRN
gene NRG1
gene NSD3
running file  227175-WG01_walk_2_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene PRF1
gene CCDC6
gene TET1
gene NUTM2B
gene KAT6B
running file  227176-WG01_walk_1_MYCL_containing.fa
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene SDHB
error!!!! in row index 13
gene MDS2
gene ARID1A
gene EPS15
gene JUN
gene JAK1
gene FUBP1
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
we have a gene!
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene SDHC
gene DDR2
gene ABL2
gene PBX1
running file  227175-WG01_walk_3_MYC_containing.fa
gene FGFR1
error!!!! in row index 0
gene NSD3
error!!!! in row index 1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227175-WG01_walk_3_MYCL_containing.fa
gene FCRL4
error!!!! in row index 0
gene FCGR2B
gene PRRX1
we have a gene!
gene SDHC
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5

gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
we have a gene!
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene ARHGEF10L
we have a gene!
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
running file  227176-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene SDHB
we have a gene!
gene MDS2
gene ARID1A
gene EPS15
gene JUN
gene JAK1
running file  227175-WG01_walk_3_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  227176-WG01_walk_2_MYCN_containing.fa
gene IDH1
error!!!! in row index 0
gene CREB1
error!!!! in row index 1
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
we have a gene!
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  227175-WG01_walk_2_MDM2_containing.fa
gene SETD1B
we have a gene!
gene ZCCHC8
gene BCL7A
we have a gene!
gene CLIP1
gene HNF1A
we have a gene!
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
we have a gene!
running file  227175-WG01_walk_2_MYCL_containing.fa
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
gene FCRL4
we have a gene!
gene FCGR2B
gene PRRX1
we have a gene!
gene SDHC
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
we have a gene!
gene PRCC
we have a gene!
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene MYCL
gene JUN
gene THRAP3
we have a gene!
gene CSF3R
we have a gene!
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
we have a gene!
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene ARHGEF10L
we have a gene!
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
running file  227175-WG01_walk_5_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  227176-WG01_walk_1_MDM2_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227176-WG01_walk_2_MYC_containing.fa
gene MYC
gene RECQL4
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
error!!!! in row index 8
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
we have a gene!
gene HOOK3
we have a gene!
gene ANK1
we have a gene!
gene KAT6A
we have a gene!
running file  227176-WG01_walk_3_MYC_containing.fa
gene MYC
gene RECQL4
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
error!!!! in row index 8
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running patient  21
running file  227178-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  227177-WG01_walk_1_KRAS_containing.fa
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene CDKN1B
gene KRAS
gene ETV6
we have a gene!
gene ETNK1
gene PPFIBP1
running file  227177-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  227177-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  227178-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
we have a gene!
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene CUL3
we have a gene!
gene ACKR3
gene CUL3
we have a gene!
running file  227177-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene FUBP1
running file  227178-WG01_walk_1_MDM2_containing.fa
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  227178-WG01_walk_2_MDM2_containing.fa
gene PTPRB
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene BTG1
gene USP44
running file  227177-WG01_walk_2_KRAS_containing.fa
gene PTPN6
gene KDM5A
error!!!! in row index 1
gene CCND2
gene CHD4
gene ZNF384
gene ERC1
gene CDKN1B
gene KRAS
gene ETV6
we have a gene!
gene ETNK1
gene PPFIBP1
running file  227178-WG01_walk_2_KRAS_containing.fa

gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
gene MDM2
we have a gene!
gene MDM2
we have a gene!
running file  227178-WG01_walk_1_KRAS_containing.fa
gene CDK4
error!!!! in row index 0
gene CDK4
error!!!! in row index 1
gene CDK4
error!!!! in row index 2
gene CDK4
error!!!! in row index 3
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227178-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227177-WG01_walk_1_MYC_containing.fa
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene TCEA1
we have a gene!
gene PLAG1
we have a gene!
gene LYN
we have a gene!
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
we have a gene!
gene PLAG1
we have a gene!
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227177-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running patient  22
running file  227179-WG01_walk_1_KRAS_containing.fa
gene LSM14A
we have a gene!
gene WT1
gene LMO2
gene EXT2
we have a gene!
gene MYOD1
gene FANCF
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene CCNE1
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene KMT2D
gene ARID2
we have a gene!
gene PTPN6
gene CDKN1B
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene CCND2
gene KDM5A
error!!!! in row index 26
gene ERC1
running file  227179-WG01_walk_1_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  227179-WG01_walk_1_MYC_containing.fa
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227179-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  227179-WG01_walk_1_MDM2_containing.fa
gene MDM2
error!!!! in row index 0
gene MDM2
error!!!! in row index 1
gene MDM2
error!!!! in row index 2
gene MDM2
error!!!! in row index 3
gene HOXD11
we have a gene!
gene FEV
we have a gene!
gene HOXD13
we have a gene!
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene COL3A1
gene SF3B1
gene ITGAV
gene PMS1
gene ERBB4
gene ACVR1
gene LRP1B
we have a gene!
gene ACVR2A
gene LRP1B
we have a gene!
gene LRP1B
we have a gene!
gene CXCR4
we have a gene!
gene ERCC3
running file  227179-WG01_walk_2_MDM2_containing.fa
gene LSM14A
we have a gene!
gene WT1
gene LMO2
gene EXT2
we have a gene!
gene MYOD1
gene FANCF
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene MDM2
we have a gene!
gene CCNE1
we have a gene!
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene KMT2D
gene ARID2
we have a gene!
gene PTPN6
gene CDKN1B
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene CCND2
gene KDM5A
error!!!! in row index 26
gene ERC1
running file  227179-WG01_walk_2_KRAS_containing.fa
gene KDM5A
error!!!! in row index 0
gene ERC1
gene CCND2
gene PTPN6
gene CDKN1B
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
running file  227179-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running patient  23
running file  227182-WG01_walk_1_KRAS_containing.fa
gene CCND2
gene PTPN6
we have a gene!
gene CHD4
we have a gene!
gene ZNF384
we have a gene!
gene CDKN1B
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
running file  227181-WG01_walk_1_KRAS_containing.fa
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227182-WG01_walk_2_KRAS_containing.fa
gene PTPN6
we have a gene!
gene CHD4
we have a gene!
gene ZNF384
we have a gene!
gene CDKN1B
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ACVR1B
we have a gene!
gene ACVR1B
we have a gene!
gene CDK4
we have a gene!
gene CDK4
we have a gene!
running file  227182-WG01_walk_1_MYCL_containing.fa
gene FH
gene AKT3
gene RGS7
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  227182-WG01_walk_2_MYCL_containing.fa
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR

gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  227182-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
we have a gene!
gene NCOA1
we have a gene!
gene ASXL2
gene DNMT3A
we have a gene!
gene ALK
gene BIRC6
we have a gene!
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
we have a gene!
running file  227182-WG01_walk_3_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  227180-WG01_walk_2_MYCN_containing.fa
gene TMEM127
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
running file  227180-WG01_walk_1_MYCL_containing.fa
gene FH
gene AKT3
gene RGS7
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  227181-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene MYC
gene RAD21
gene NDRG1
gene EXT1
gene CSMD3
gene FAM135B
running file  227180-WG01_walk_1_MYCN_containing.fa
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
we have a gene!
gene TMEM127
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
running file  227180-WG01_walk_1_KRAS_containing.fa
gene HMGA2
error!!!! in row index 0
gene HMGA2
error!!!! in row index 1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227180-WG01_walk_2_MYCL_containing.fa
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  227180-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene MYC
gene RAD21
gene NDRG1
gene EXT1
gene CSMD3
gene FAM135B
gene CHST11
we have a gene!
running file  227181-WG01_walk_2_MYCN_containing.fa
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene CTNNA2
gene AFF3
gene PAX8
we have a gene!
gene BIRC6
we have a gene!
gene ALK
gene WDCP
we have a gene!
gene ASXL2
gene NCOA1
gene DNMT3A
gene MYCN
running file  227181-WG01_walk_1_MYCL_containing.fa
gene CLP1
error!!!! in row index 0
gene CTNND1
error!!!! in row index 1
gene FEN1
gene MEN1
gene SDHAF2
we have a gene!
gene MALAT1
gene CCND1
we have a gene!
gene FADD
we have a gene!
gene NUMA1
we have a gene!
gene EED
gene PICALM
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  227181-WG01_walk_1_MYCN_containing.fa
gene MYCN
gene WDCP
we have a gene!
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
we have a gene!
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene CTNNA2
gene AFF3
gene PAX8
we have a gene!
gene ERCC3
running file  227181-WG01_walk_2_MYCL_containing.fa
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene FH
gene AKT3
gene RGS7
running patient  24
running file  227183-WG01_walk_1_MYC_containing.fa
gene RECQL4
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene FKBP9
we have a gene!
gene JAZF1
we have a gene!
gene JAZF1
we have a gene!
gene HOXA11
gene HOXA13
gene HOXA9
gene JAZF1
we have a gene!
gene HNRNPA2B1
we have a gene!
running file  227184-WG01_walk_2_KRAS_containing.fa
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
we have a gene!
gene CHD4
we have a gene!
gene ZNF384
we have a gene!
running file  227183-WG01_walk_3_KRAS_containing.fa
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
we have a gene!
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
we have a gene!
gene PTPN6
gene KDM5A
error!!!! in row index 21
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227183-WG01_walk_1_MDM2_containing.fa
gene CTNNB1
gene NCKIPSD
gene RHOA
gene SETD2
gene MLH1
gene MYD88
gene CCR4
gene TGFBR2
gene CHST11
gene BTG1
gene USP44
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
we have a gene!
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
we have a gene!
gene PTPN6
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227184-WG01_walk_1_MDM2_containing.fa
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene COL2A1
we have a gene!
gene ARID2
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
we have a gene!
gene CHD4
we have a gene!
gene ZNF384
we have a gene!
gene CCND2
we have a gene!
gene ERC1
we have a gene!
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 32
running file  227183-WG01_walk_4_MYCL_containing.fa

gene TP53
error!!!! in row index 0
gene PER1
error!!!! in row index 1
gene GAS7
gene MAP2K4
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
running file  227183-WG01_walk_3_MYCL_containing.fa
gene ELF3
error!!!! in row index 0
gene SDHC
we have a gene!
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene ATP1A1
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene FUBP1
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene MTOR
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
running file  227184-WG01_walk_2_MYCN_containing.fa
gene CXCR4
gene RANBP2
gene RGPD3
gene ERCC3
gene AFF3
error!!!! in row index 4
gene PAX8
gene LRP1B
gene TMEM127
gene PCBP1
gene DCTN1
gene CTNNA2
gene REL
we have a gene!
gene XPO1
gene BCL11A
we have a gene!
gene MSH6
we have a gene!
gene FBXO11
we have a gene!
gene MSH2
we have a gene!
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
running file  227183-WG01_walk_2_KRAS_containing.fa
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
we have a gene!
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
we have a gene!
gene PTPN6
gene KDM5A
error!!!! in row index 22
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227183-WG01_walk_3_MYC_containing.fa
gene RECQL4
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene FKBP9
we have a gene!
running file  227184-WG01_walk_1_MYCN_containing.fa
gene TMEM127
gene PCBP1
gene DCTN1
gene CTNNA2
gene REL
we have a gene!
gene XPO1
gene BCL11A
we have a gene!
gene MSH6
we have a gene!
gene FBXO11
we have a gene!
gene MSH2
we have a gene!
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ATP1A1
gene PDE4DIP
we have a gene!
gene SETDB1
gene MLLT11
gene ARNT
running file  227184-WG01_walk_1_MYCL_containing.fa
gene RPL22
gene CAMTA1
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene ID3
gene PAX7
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene LCK
we have a gene!
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene CDKN2C
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ATP1A1
gene PDE4DIP
we have a gene!
gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
gene TPM3
we have a gene!
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
we have a gene!
gene MUC1
gene SDHC
we have a gene!
gene SDHC
we have a gene!
gene FCGR2B
we have a gene!
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
gene CDC73
gene PTPRC
gene ELF3
we have a gene!
running file  227183-WG01_walk_2_MYCN_containing.fa
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  227183-WG01_walk_1_KRAS_containing.fa
gene CTNNB1
gene NCKIPSD
gene RHOA
gene SETD2
gene MLH1
gene MYD88
gene CCR4
gene TGFBR2
gene CHST11
gene BTG1
gene USP44
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
we have a gene!
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
we have a gene!
gene PTPN6
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227184-WG01_walk_1_MYC_containing.fa
gene MYC
gene RECQL4
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene COX6C
gene PABPC1
gene UBR5
gene NBN
gene CDH17
gene RUNX1T1
gene CNBD1
gene HEY1
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene HOOK3
we have a gene!
running file  227184-WG01_walk_3_MYCL_containing.fa
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene LCK
we have a gene!
gene ARID1A
gene ID3
gene PAX7
gene ARHGEF10L
we have a gene!
gene MDS2
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene RPL22
gene CAMTA1
gene TNFRSF14
gene SKI
gene PRDM16
running file  227184-WG01_walk_1_KRAS_containing.fa
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
we have a gene!
gene CDK4
we have a gene!
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene COL2A1
we have a gene!
gene ARID2
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
we have a gene!
gene CHD4
we have a gene!
gene ZNF384
we have a gene!
gene CCND2
we have a gene!
gene ERC1
we have a gene!
gene ERC1
we have a gene!
gene KDM5A
error!!!! in row index 32
running file  227184-WG01_walk_3_MYC_containing.fa
gene FKBP9
we have a gene!
gene MYC
gene RECQL4
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227183-WG01_walk_1_MYCL_containing.fa
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene FUBP1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene ATP1A1
gene PDE4DIP
gene MUC1
gene SDHC
we have a gene!
gene FCGR2B
we have a gene!
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
gene CDC73
gene PTPRC
running file  227183-WG01_walk_2_MYC_containing.fa
gene FKBP9
we have a gene!
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
running file  227183-WG01_walk_1_MYCN_containing.fa
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  227184-WG01_walk_2_MYCL_containing.fa
gene LCK
error!!!! in row index 0
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
we have a gene!
gene TAL1
we have a gene!
gene CDKN2C
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ATP1A1
gene PDE4DIP
we have a gene!
gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
gene TPM3
we have a gene!
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
we have a gene!
gene MUC1
gene SDHC
we have a gene!
gene SDHC
we have a gene!
gene ELF3

we have a gene!
gene CDC73
gene PTPRC
gene FCGR2B
we have a gene!
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
gene SDHC
we have a gene!
gene SDHC
we have a gene!
running file  227183-WG01_walk_2_MYCL_containing.fa
gene TP53
error!!!! in row index 0
gene PER1
error!!!! in row index 1
gene GAS7
gene MAP2K4
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
we have a gene!
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
we have a gene!
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene FUBP1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene ATP1A1
gene PDE4DIP
gene MUC1
gene SDHC
we have a gene!
gene FCGR2B
we have a gene!
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
running file  227184-WG01_walk_2_MYC_containing.fa
gene FKBP9
we have a gene!
gene FKBP9
we have a gene!
gene MYC
gene RECQL4
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B

In [42]:
final_walks_df

,patient,walk_file,walk_file_row_idx,chr,start,end,COSMIC_gene
0,1,226296-WG01_walk_5_MYCL_containing.fa,0,chr1,1,17349689,SDHB
1,1,226296-WG01_walk_5_MYCL_containing.fa,2,chr1,17351159,53225853,ARHGEF10L
2,1,226298-WG01_walk_1_MYC_containing.fa,0,chr8,1,42520419,IKBKB
3,1,226298-WG01_walk_1_MYC_containing.fa,1,chr8,42522790,145138636,HOOK3
4,1,226298-WG01_walk_1_MYCL_containing.fa,0,chr1,1,24037904,ID3
...,...,...,...,...,...,...,...
1314,24,227183-WG01_walk_2_MYCL_containing.fa,4,chr1,17351159,67596602,ARHGEF10L
1315,24,227183-WG01_walk_2_MYCL_containing.fa,8,chr1,161189008,161539861,SDHC
1316,24,227183-WG01_walk_2_MYCL_containing.fa,10,chr1,161540076,187750002,FCGR2B
1317,24,227184-WG01_walk_2_MYC_containing.fa,7,chr7,32853803,33062602,FKBP9
1318,24,227184-WG01_walk_2_MYC_containing.fa,7,chr7,32853803,33062602,FKBP9

In [41]:
final_walks_df.to_csv('/pollard/data/projects/shzhang/mdanderson/20241118_walks_genecentered_regions.csv')