In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import akita_utils_forplotting as utils
import numpy as np
import pandas as pd
import sys, os, psutil, time
import matplotlib.pyplot as plt
import pysam
    
from skimage.transform import resize


#from optparse import OptionParser


nt = ['A', 'T', 'C', 'G']

2024-11-20 13:10:52.022208: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pollard/home/shzhang/miniconda3/envs/dchic1/lib/R/library
2024-11-20 13:10:52.022240: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-11-20 13:10:54.969800: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pollard/home/shzhang/miniconda3/envs/dchic1/lib/R/library
2024-11-20 13:10:54.969832: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-11-20 13:10:54.969858: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bueno.gladstone.internal): /proc/driver/nvidia/version does not exist
2024-11-20 13:10:54.970078: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 sequence (InputLayer)          [(None, 1048576, 4)  0           []
                                ]

 stochastic_reverse_complement   ((None, 1048576, 4)  0          ['sequence[0][0]']
 (StochasticReverseComplement)  , ())

 stochastic_shift (StochasticSh  (None, 1048576, 4)  0           ['stochastic_reverse_complement[0
 ift)                                                            ][0]']

 re_lu (ReLU)                   (None, 1048576, 4)   0           ['stochastic_shift[0][0]']

 conv1d (Conv1D)                (None, 1048576, 96)  4224        ['re_lu[0][0]']

 batch_normalization (BatchNorm  (None, 1048576, 96)  384        ['conv1d[0][0]']
 alization)

 max_pooling1d (MaxPooling1D)   (None, 524288, 96)   0           ['batch_normalization[0][0]']

 re_lu_1 (ReLU)                 (None, 524288, 96)   0           ['max_pooling1d[0][0]']

 conv1d_1 (Conv1D)              (None, 524288, 96)   46080       ['re_lu_1[0][0]']

 batch_normalization_1 (BatchNo  (None, 524288, 96)  384         ['conv1d_1[0][0]']
 rmalization)

 max_pooling1d_1 (MaxPooling1D)  (None, 262144, 96)  0           ['batch_normalization_1[0][0]']

 re_lu_2 (ReLU)                 (None, 262144, 96)   0           ['max_pooling1d_1[0][0]']

 conv1d_2 (Conv1D)              (None, 262144, 96)   46080       ['re_lu_2[0][0]']

 batch_normalization_2 (BatchNo  (None, 262144, 96)  384         ['conv1d_2[0][0]']
 rmalization)

 max_pooling1d_2 (MaxPooling1D)  (None, 131072, 96)  0           ['batch_normalization_2[0][0]']

 re_lu_3 (ReLU)                 (None, 131072, 96)   0           ['max_pooling1d_2[0][0]']

 conv1d_3 (Conv1D)              (None, 131072, 96)   46080       ['re_lu_3[0][0]']

 batch_normalization_3 (BatchNo  (None, 131072, 96)  384         ['conv1d_3[0][0]']
 rmalization)

 max_pooling1d_3 (MaxPooling1D)  (None, 65536, 96)   0           ['batch_normalization_3[0][0]']

 re_lu_4 (ReLU)                 (None, 65536, 96)    0           ['max_pooling1d_3[0][0]']

 conv1d_4 (Conv1D)              (None, 65536, 96)    46080       ['re_lu_4[0][0]']

 batch_normalization_4 (BatchNo  (None, 65536, 96)   384         ['conv1d_4[0][0]']
 rmalization)

 max_pooling1d_4 (MaxPooling1D)  (None, 32768, 96)   0           ['batch_normalization_4[0][0]']

 re_lu_5 (ReLU)                 (None, 32768, 96)    0           ['max_pooling1d_4[0][0]']

 conv1d_5 (Conv1D)              (None, 32768, 96)    46080       ['re_lu_5[0][0]']

 batch_normalization_5 (BatchNo  (None, 32768, 96)   384         ['conv1d_5[0][0]']
 rmalization)

 max_pooling1d_5 (MaxPooling1D)  (None, 16384, 96)   0           ['batch_normalization_5[0][0]']

 re_lu_6 (ReLU)                 (None, 16384, 96)    0           ['max_pooling1d_5[0][0]']

 conv1d_6 (Conv1D)              (None, 16384, 96)    46080       ['re_lu_6[0][0]']

 batch_normalization_6 (BatchNo  (None, 16384, 96)   384         ['conv1d_6[0][0]']
 rmalization)

 max_pooling1d_6 (MaxPooling1D)  (None, 8192, 96)    0           ['batch_normalization_6[0][0]']

 re_lu_7 (ReLU)                 (None, 8192, 96)     0           ['max_pooling1d_6[0][0]']

 conv1d_7 (Conv1D)              (None, 8192, 96)     46080       ['re_lu_7[0][0]']

 batch_normalization_7 (BatchNo  (None, 8192, 96)    384         ['conv1d_7[0][0]']
 rmalization)

 max_pooling1d_7 (MaxPooling1D)  (None, 4096, 96)    0           ['batch_normalization_7[0][0]']

 re_lu_8 (ReLU)                 (None, 4096, 96)     0           ['max_pooling1d_7[0][0]']

 conv1d_8 (Conv1D)              (None, 4096, 96)     46080       ['re_lu_8[0][0]']

 batch_normalization_8 (BatchNo  (None, 4096, 96)    384         ['conv1d_8[0][0]']
 rmalization)

 max_pooling1d_8 (MaxPooling1D)  (None, 2048, 96)    0           ['batch_normalization_8[0][0]']

 re_lu_9 (ReLU)                 (None, 2048, 96)     0           ['max_pooling1d_8[0][0]']

 conv1d_9 (Conv1D)              (None, 2048, 96)     46080       ['re_lu_9[0][0]']

 batch_normalization_9 (BatchNo  (None, 2048, 96)    384         ['conv1d_9[0][0]']
 rmalization)

 max_pooling1d_9 (MaxPooling1D)  (None, 1024, 96)    0           ['batch_normalization_9[0][0]']

 re_lu_10 (ReLU)                (None, 1024, 96)     0           ['max_pooling1d_9[0][0]']

 conv1d_10 (Conv1D)             (None, 1024, 96)     46080       ['re_lu_10[0][0]']

 batch_normalization_10 (BatchN  (None, 1024, 96)    384         ['conv1d_10[0][0]']
 ormalization)

 max_pooling1d_10 (MaxPooling1D  (None, 512, 96)     0           ['batch_normalization_10[0][0]']
 )

 re_lu_11 (ReLU)                (None, 512, 96)      0           ['max_pooling1d_10[0][0]']

 conv1d_11 (Conv1D)             (None, 512, 48)      13824       ['re_lu_11[0][0]']

 batch_normalization_11 (BatchN  (None, 512, 48)     192         ['conv1d_11[0][0]']
 ormalization)

 re_lu_12 (ReLU)                (None, 512, 48)      0           ['batch_normalization_11[0][0]']

 conv1d_12 (Conv1D)             (None, 512, 96)      4608        ['re_lu_12[0][0]']

 batch_normalization_12 (BatchN  (None, 512, 96)     384         ['conv1d_12[0][0]']
 ormalization)

 dropout (Dropout)              (None, 512, 96)      0           ['batch_normalization_12[0][0]']

 add (Add)                      (None, 512, 96)      0           ['max_pooling1d_10[0][0]',
                                                                  'dropout[0][0]']

 re_lu_13 (ReLU)                (None, 512, 96)      0           ['add[0][0]']

 conv1d_13 (Conv1D)             (None, 512, 48)      13824       ['re_lu_13[0][0]']

 batch_normalization_13 (BatchN  (None, 512, 48)     192         ['conv1d_13[0][0]']
 ormalization)

 re_lu_14 (ReLU)                (None, 512, 48)      0           ['batch_normalization_13[0][0]']

 conv1d_14 (Conv1D)             (None, 512, 96)      4608        ['re_lu_14[0][0]']

 batch_normalization_14 (BatchN  (None, 512, 96)     384         ['conv1d_14[0][0]']
 ormalization)

 dropout_1 (Dropout)            (None, 512, 96)      0           ['batch_normalization_14[0][0]']

 add_1 (Add)                    (None, 512, 96)      0           ['add[0][0]',
                                                                  'dropout_1[0][0]']

 re_lu_15 (ReLU)                (None, 512, 96)      0           ['add_1[0][0]']

 conv1d_15 (Conv1D)             (None, 512, 48)      13824       ['re_lu_15[0][0]']

 batch_normalization_15 (BatchN  (None, 512, 48)     192         ['conv1d_15[0][0]']
 ormalization)

 re_lu_16 (ReLU)                (None, 512, 48)      0           ['batch_normalization_15[0][0]']

 conv1d_16 (Conv1D)             (None, 512, 96)      4608        ['re_lu_16[0][0]']

 batch_normalization_16 (BatchN  (None, 512, 96)     384         ['conv1d_16[0][0]']
 ormalization)

 dropout_2 (Dropout)            (None, 512, 96)      0           ['batch_normalization_16[0][0]']

 add_2 (Add)                    (None, 512, 96)      0           ['add_1[0][0]',
                                                                  'dropout_2[0][0]']

 re_lu_17 (ReLU)                (None, 512, 96)      0           ['add_2[0][0]']

 conv1d_17 (Conv1D)             (None, 512, 48)      13824       ['re_lu_17[0][0]']

 batch_normalization_17 (BatchN  (None, 512, 48)     192         ['conv1d_17[0][0]']
 ormalization)

 re_lu_18 (ReLU)                (None, 512, 48)      0           ['batch_normalization_17[0][0]']

 conv1d_18 (Conv1D)             (None, 512, 96)      4608        ['re_lu_18[0][0]']

 batch_normalization_18 (BatchN  (None, 512, 96)     384         ['conv1d_18[0][0]']
 ormalization)

 dropout_3 (Dropout)            (None, 512, 96)      0           ['batch_normalization_18[0][0]']

 add_3 (Add)                    (None, 512, 96)      0           ['add_2[0][0]',
                                                                  'dropout_3[0][0]']

 re_lu_19 (ReLU)                (None, 512, 96)      0           ['add_3[0][0]']

 conv1d_19 (Conv1D)             (None, 512, 48)      13824       ['re_lu_19[0][0]']

 batch_normalization_19 (BatchN  (None, 512, 48)     192         ['conv1d_19[0][0]']
 ormalization)

 re_lu_20 (ReLU)                (None, 512, 48)      0           ['batch_normalization_19[0][0]']

 conv1d_20 (Conv1D)             (None, 512, 96)      4608        ['re_lu_20[0][0]']

 batch_normalization_20 (BatchN  (None, 512, 96)     384         ['conv1d_20[0][0]']
 ormalization)

 dropout_4 (Dropout)            (None, 512, 96)      0           ['batch_normalization_20[0][0]']

 add_4 (Add)                    (None, 512, 96)      0           ['add_3[0][0]',
                                                                  'dropout_4[0][0]']

 re_lu_21 (ReLU)                (None, 512, 96)      0           ['add_4[0][0]']

 conv1d_21 (Conv1D)             (None, 512, 48)      13824       ['re_lu_21[0][0]']

 batch_normalization_21 (BatchN  (None, 512, 48)     192         ['conv1d_21[0][0]']
 ormalization)

 re_lu_22 (ReLU)                (None, 512, 48)      0           ['batch_normalization_21[0][0]']

 conv1d_22 (Conv1D)             (None, 512, 96)      4608        ['re_lu_22[0][0]']

 batch_normalization_22 (BatchN  (None, 512, 96)     384         ['conv1d_22[0][0]']
 ormalization)

 dropout_5 (Dropout)            (None, 512, 96)      0           ['batch_normalization_22[0][0]']

 add_5 (Add)                    (None, 512, 96)      0           ['add_4[0][0]',
                                                                  'dropout_5[0][0]']

 re_lu_23 (ReLU)                (None, 512, 96)      0           ['add_5[0][0]']

 conv1d_23 (Conv1D)             (None, 512, 48)      13824       ['re_lu_23[0][0]']

 batch_normalization_23 (BatchN  (None, 512, 48)     192         ['conv1d_23[0][0]']
 ormalization)

 re_lu_24 (ReLU)                (None, 512, 48)      0           ['batch_normalization_23[0][0]']

 conv1d_24 (Conv1D)             (None, 512, 96)      4608        ['re_lu_24[0][0]']

 batch_normalization_24 (BatchN  (None, 512, 96)     384         ['conv1d_24[0][0]']
 ormalization)

 dropout_6 (Dropout)            (None, 512, 96)      0           ['batch_normalization_24[0][0]']

 add_6 (Add)                    (None, 512, 96)      0           ['add_5[0][0]',
                                                                  'dropout_6[0][0]']

 re_lu_25 (ReLU)                (None, 512, 96)      0           ['add_6[0][0]']

 conv1d_25 (Conv1D)             (None, 512, 48)      13824       ['re_lu_25[0][0]']

 batch_normalization_25 (BatchN  (None, 512, 48)     192         ['conv1d_25[0][0]']
 ormalization)

 re_lu_26 (ReLU)                (None, 512, 48)      0           ['batch_normalization_25[0][0]']

 conv1d_26 (Conv1D)             (None, 512, 96)      4608        ['re_lu_26[0][0]']

 batch_normalization_26 (BatchN  (None, 512, 96)     384         ['conv1d_26[0][0]']
 ormalization)

 dropout_7 (Dropout)            (None, 512, 96)      0           ['batch_normalization_26[0][0]']

 add_7 (Add)                    (None, 512, 96)      0           ['add_6[0][0]',
                                                                  'dropout_7[0][0]']

 re_lu_27 (ReLU)                (None, 512, 96)      0           ['add_7[0][0]']

 conv1d_27 (Conv1D)             (None, 512, 64)      30720       ['re_lu_27[0][0]']

 batch_normalization_27 (BatchN  (None, 512, 64)     256         ['conv1d_27[0][0]']
 ormalization)

 re_lu_28 (ReLU)                (None, 512, 64)      0           ['batch_normalization_27[0][0]']

 one_to_two (OneToTwo)          (None, 512, 512, 64  0           ['re_lu_28[0][0]']
                                )

 concat_dist2d (ConcatDist2D)   (None, 512, 512, 65  0           ['one_to_two[0][0]']
                                )

 re_lu_29 (ReLU)                (None, 512, 512, 65  0           ['concat_dist2d[0][0]']
                                )

 conv2d (Conv2D)                (None, 512, 512, 48  28080       ['re_lu_29[0][0]']
                                )

 batch_normalization_28 (BatchN  (None, 512, 512, 48  192        ['conv2d[0][0]']
 ormalization)                  )

 symmetrize2d (Symmetrize2D)    (None, 512, 512, 48  0           ['batch_normalization_28[0][0]']
                                )

 re_lu_30 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d[0][0]']
                                )

 conv2d_1 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_30[0][0]']
                                )

 batch_normalization_29 (BatchN  (None, 512, 512, 24  96         ['conv2d_1[0][0]']
 ormalization)                  )

 re_lu_31 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_29[0][0]']
                                )

 conv2d_2 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_31[0][0]']
                                )

 batch_normalization_30 (BatchN  (None, 512, 512, 48  192        ['conv2d_2[0][0]']
 ormalization)                  )

 dropout_8 (Dropout)            (None, 512, 512, 48  0           ['batch_normalization_30[0][0]']
                                )

 add_8 (Add)                    (None, 512, 512, 48  0           ['symmetrize2d[0][0]',
                                )                                 'dropout_8[0][0]']

 symmetrize2d_1 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_8[0][0]']
                                )

 re_lu_32 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_1[0][0]']
                                )

 conv2d_3 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_32[0][0]']
                                )

 batch_normalization_31 (BatchN  (None, 512, 512, 24  96         ['conv2d_3[0][0]']
 ormalization)                  )

 re_lu_33 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_31[0][0]']
                                )

 conv2d_4 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_33[0][0]']
                                )

 batch_normalization_32 (BatchN  (None, 512, 512, 48  192        ['conv2d_4[0][0]']
 ormalization)                  )

 dropout_9 (Dropout)            (None, 512, 512, 48  0           ['batch_normalization_32[0][0]']
                                )

 add_9 (Add)                    (None, 512, 512, 48  0           ['symmetrize2d_1[0][0]',
                                )                                 'dropout_9[0][0]']

 symmetrize2d_2 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_9[0][0]']
                                )

 re_lu_34 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_2[0][0]']
                                )

 conv2d_5 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_34[0][0]']
                                )

 batch_normalization_33 (BatchN  (None, 512, 512, 24  96         ['conv2d_5[0][0]']
 ormalization)                  )

 re_lu_35 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_33[0][0]']
                                )

 conv2d_6 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_35[0][0]']
                                )

 batch_normalization_34 (BatchN  (None, 512, 512, 48  192        ['conv2d_6[0][0]']
 ormalization)                  )

 dropout_10 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_34[0][0]']
                                )

 add_10 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_2[0][0]',
                                )                                 'dropout_10[0][0]']

 symmetrize2d_3 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_10[0][0]']
                                )

 re_lu_36 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_3[0][0]']
                                )

 conv2d_7 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_36[0][0]']
                                )

 batch_normalization_35 (BatchN  (None, 512, 512, 24  96         ['conv2d_7[0][0]']
 ormalization)                  )

 re_lu_37 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_35[0][0]']
                                )

 conv2d_8 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_37[0][0]']
                                )

 batch_normalization_36 (BatchN  (None, 512, 512, 48  192        ['conv2d_8[0][0]']
 ormalization)                  )

 dropout_11 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_36[0][0]']
                                )

 add_11 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_3[0][0]',
                                )                                 'dropout_11[0][0]']

 symmetrize2d_4 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_11[0][0]']
                                )

 re_lu_38 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_4[0][0]']
                                )

 conv2d_9 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_38[0][0]']
                                )

 batch_normalization_37 (BatchN  (None, 512, 512, 24  96         ['conv2d_9[0][0]']
 ormalization)                  )

 re_lu_39 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_37[0][0]']
                                )

 conv2d_10 (Conv2D)             (None, 512, 512, 48  1152        ['re_lu_39[0][0]']
                                )

 batch_normalization_38 (BatchN  (None, 512, 512, 48  192        ['conv2d_10[0][0]']

 ormalization)                  )

 dropout_12 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_38[0][0]']
                                )

 add_12 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_4[0][0]',
                                )                                 'dropout_12[0][0]']

 symmetrize2d_5 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_12[0][0]']
                                )

 re_lu_40 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_5[0][0]']
                                )

 conv2d_11 (Conv2D)             (None, 512, 512, 24  10368       ['re_lu_40[0][0]']
                                )

 batch_normalization_39 (BatchN  (None, 512, 512, 24  96         ['conv2d_11[0][0]']
 ormalization)                  )

 re_lu_41 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_39[0][0]']
                                )

 conv2d_12 (Conv2D)             (None, 512, 512, 48  1152        ['re_lu_41[0][0]']
                                )

 batch_normalization_40 (BatchN  (None, 512, 512, 48  192        ['conv2d_12[0][0]']
 ormalization)                  )

 dropout_13 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_40[0][0]']
                                )

 add_13 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_5[0][0]',
                                )                                 'dropout_13[0][0]']

 symmetrize2d_6 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_13[0][0]']
                                )

 cropping2d (Cropping2D)        (None, 448, 448, 48  0           ['symmetrize2d_6[0][0]']
                                )

 upper_tri (UpperTri)           (None, 99681, 48)    0           ['cropping2d[0][0]']

 dense (Dense)                  (None, 99681, 5)     245         ['upper_tri[0][0]']

 switch_reverse_triu (SwitchRev  (None, 99681, 5)    0           ['dense[0][0]',
 erseTriu)                                                        'stochastic_reverse_complement[0
                                                                 ][1]']

==================================================================================================
Total params: 751,653
Trainable params: 746,149
Non-trainable params: 5,504
__________________________________________________________________________________________________
None
model_strides [2048]
target_lengths [99681]
target_crops [-49585]
model successfully loaded

In [3]:
import h5py
import pyBigWig
import intervaltree
import basenji
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages

# hic imports
import cooler
from cooltools.lib.numutils import observed_over_expected, adaptive_coarsegrain
from cooltools.lib.numutils import interpolate_bad_singletons, set_diag, interp_nan
from astropy.convolution import Gaussian2DKernel
from astropy.convolution import convolve

import collections

In [4]:
import cooltools.lib.plotting
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.ticker import EngFormatter
import seaborn as sns
from pybedtools import BedTool
import math

In [5]:
#REMEMBER!!!!!!! +1MB SEQUENCE GOES IN, BUT MAKES PREDICTION FOR 917504BP
#1MB CORRESPONDS TO 512, 2048 BP BINS THAT GETS CUT DOWN TO 448 BINS

In [6]:
def format_ticks(ax, x=True, y=True, rotate=True):
    if y:
        ax.yaxis.set_major_formatter(bp_formatter)
    if x:
        ax.xaxis.set_major_formatter(bp_formatter)
        ax.xaxis.tick_bottom()
    if rotate:
        ax.tick_params(axis='x',rotation=45)
        
def save_figures_to_pdf(output_pdf_path, figures):
    with PdfPages(output_pdf_path) as pdf:
        for fig in figures:
            pdf.savefig(fig)

In [7]:
def read_fasta(fa):
    #read in fasta and return sequence only 
    seq=''
    with open(fa, "r") as fa_file:
        for line in fa_file:
            if not (line.startswith('>')):
                seq += line.strip()
    fa_file.close()                
    return(seq)

In [8]:
#TOTAL AKITA INPUT LENGTH 

akita_seq_len=1048576


#HG38 REF FA
hg38_file = '/pollard/home/shzhang/akita/run_akita/refs/hg38.fa'
fasta_hg38 = pysam.Fastafile(hg38_file)

#GENCODE
gene_annot = pd.read_csv('/pollard/data/genetics/GENCODE/release32/gencode.v32.genes_only.bed', sep = '\t', names = ['CHROM', 'start_gene', 'end_gene', 'Gene'])
gene_annot[gene_annot.CHROM != 'chrM']

      CHROM  start_gene  end_gene         Gene
0      chr1       11869     14409      DDX11L1
1      chr1       14404     29570       WASH7P
2      chr1       17369     17436    MIR6859-1
3      chr1       29554     31109  MIR1302-2HG
4      chr1       30366     30503    MIR1302-2
...     ...         ...       ...          ...
60567  chrY    57184101  57197337         IL9R
60568  chrY    57190738  57208756   AJ271736.1
60569  chrY    57201143  57203357       WASIR1
60570  chrY    57207346  57212230       WASH6P
60571  chrY    57212184  57214397     DDX11L16

[60572 rows x 4 columns]

In [9]:
data_dir='/pollard/data/projects/shzhang/mdanderson/'
patient_data_dir=f'{data_dir}by_patient_20240529/'

In [10]:
meta=pd.read_csv(f'{data_dir}meta_sv2.csv')
meta['tumor_id']=meta['tumor'].str.split('-').str.get(0)
meta

,Patient,Tumor_Type,Timepoint,normal,tumor,gender,tumor_id
0,Patient1,DDLPS,baseline,226294-WG01,226295-WG01,XX,226295
1,Patient1,DDLPS,On_treatment,226294-WG01,226296-WG01,XX,226296
2,Patient1,DDLPS,Surgery,226294-WG01,226298-WG01,XX,226298
3,Patient1,DDLPS,Surgery,226294-WG01,226297-WG01,XX,226297
4,Patient2,DDLPS,baseline,226299-WG01,226300-WG01,XX,226300
...,...,...,...,...,...,...,...
67,Patient23,DDLPS,baseline,227190-WG01,227180-WG01,XX,227180
68,Patient23,DDLPS,On_treatment,227190-WG01,227181-WG01,XX,227181
69,Patient23,DDLPS,Surgery,227190-WG01,227182-WG01,XX,227182
70,Patient24,UPS,baseline,227191-WG01,227183-WG01,XX,227183
71,Patient24,UPS,On_treatment,227191-WG01,227184-WG01,XX,227184

In [32]:
meta[meta['Patient']=='Patient6']

,Patient,Tumor_Type,Timepoint,normal,tumor,gender,tumor_id
18,Patient6,DDLPS,On_treatment,226317-WG01,226318-WG01,XX,226318
19,Patient6,DDLPS,Surgery,226317-WG01,226319-WG01,XX,226319
20,Patient6,DDLPS,Relapse,226317-WG01,226320-WG01,XX,226320

In [11]:
#read in COSMIC gene information 
cosmic=pd.read_csv('/pollard/home/shzhang/data/COSMIC_census_2023.csv')
cosmic['chr'] = 'chr' + cosmic['Genome Location'].str.split(':').str[0]
cosmic['coords'] = cosmic['Genome Location'].str.split(':').str[1]
cosmic['start'] = cosmic['coords'].str.split('-').str[0]
cosmic['end'] = cosmic['coords'].str.split('-').str[1]
cosmic

,Gene Symbol,Name,Entrez GeneId,Genome Location,Tier,Hallmark,Chr Band,Somatic,Germline,Tumour Types(Somatic),...,Role in Cancer,Mutation Types,Translocation Partner,Other Germline Mut,Other Syndrome,Synonyms,chr,coords,start,end
0,A1CF,APOBEC1 complementation factor,29974.0,10:50799421-50885675,2,NaN,11.23,yes,NaN,melanoma,...,oncogene,Mis,NaN,NaN,NaN,"29974,A1CF,ACF,ACF64,ACF65,APOBEC1CF,ASP,ENSG0...",chr10,50799421-50885675,50799421,50885675
1,ABI1,abl-interactor 1,10006.0,10:26746593-26860935,1,Yes,12.10,yes,NaN,AML,...,"TSG, fusion",T,KMT2A,NaN,NaN,"10006,ABI-1,ABI1,E3B1,ENSG00000136754.17,Q8IZP...",chr10,26746593-26860935,26746593,26860935
2,ABL1,v-abl Abelson murine leukemia viral oncogene h...,25.0,9:130713946-130885683,1,Yes,34.12,yes,NaN,"CML, ALL, T-ALL",...,"oncogene, fusion","T, Mis","BCR, ETV6, NUP214",NaN,NaN,"25,ABL,ABL1,ENSG00000097007.17,JTK7,P00519,c-A...",chr9,130713946-130885683,130713946,130885683
3,ABL2,"c-abl oncogene 2, non-receptor tyrosine kinase",27.0,1:179099327-179229601,1,NaN,25.20,yes,NaN,AML,...,"oncogene, fusion",T,ETV6,NaN,NaN,"27,ABL2,ABLL,ARG,ENSG00000143322.19,P42684",chr1,179099327-179229601,179099327,179229601
4,ACKR3,atypical chemokine receptor 3,57007.0,2:236569641-236582358,1,Yes,37.30,yes,NaN,lipoma,...,"oncogene, fusion",T,HMGA2,NaN,NaN,"57007,ACKR3,CMKOR1,CXCR7,ENSG00000144476.5,GPR...",chr2,236569641-236582358,236569641,236582358
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,ZNF429,zinc finger protein 429,353088.0,19:21505564-21538078,2,NaN,12.00,yes,NaN,GBM,...,NaN,Mis,NaN,NaN,NaN,"353088,ENSG00000197013.9,Q86V71,ZNF429",chr19,21505564-21538078,21505564,21538078
732,ZNF479,zinc finger protein 479,90827.0,7:57119614-57139864,2,NaN,11.20,yes,NaN,"lung cancer, bladder carcinoma, prostate carci...",...,NaN,Mis,NaN,NaN,NaN,"90827,ENSG00000185177.12,KR19,Q96JC4,ZNF479",chr7,57119614-57139864,57119614,57139864
733,ZNF521,zinc finger protein 521,25925.0,18:25061926-25352152,1,NaN,11.20,yes,NaN,ALL,...,"oncogene, fusion",T,PAX5,NaN,NaN,"25925,EHZF,ENSG00000198795.10,Evi3,Q96K83,ZNF521",chr18,25061926-25352152,25061926,25352152
734,ZNRF3,zinc and ring finger 3,84133.0,22:28883592-29057487,2,NaN,12.10,yes,NaN,"colorectal cancer, adrenocortical carcinoma, g...",...,TSG,"N, F, Mis",NaN,NaN,NaN,"84133,BK747E2.3,ENSG00000183579.15,FLJ22057,KI...",chr22,28883592-29057487,28883592,29057487
735,ZRSR2,"zinc finger (CCCH type), RNA-binding motif and...",8233.0,X:15790472-15823260,1,Yes,22.20,yes,NaN,"MDS, CLL",...,TSG,"F, S, Mis",NaN,NaN,NaN,"8233,ENSG00000169249.12,Q15696,U2AF1-RS2,U2AF1...",chrX,15790472-15823260,15790472,15823260

In [12]:
#np.unique(cosmic['Gene Symbol'])

In [13]:
#drop rows without coords
cosmic_subset = cosmic[(cosmic['start'].notna()) & (cosmic['start'] != '') & 
                 (cosmic['end'].notna()) & (cosmic['end'] != '')]

single_cols = ['chr', 'start', 'end', 'Gene Symbol']
cosmic_subset = cosmic_subset[single_cols]

cosmic_BED=BedTool.from_dataframe(cosmic_subset.astype({'start': int, 'end': int}))
#cosmic_BED=BedTool.from_dataframe(cosmic_subset)

In [14]:
cosmic_subset[cosmic_subset['Gene Symbol']=='TNFRSF14']

      chr    start      end Gene Symbol
683  chr1  2556366  2563829    TNFRSF14

In [15]:
#ok, what we want to do is plot the changes at every breakpoint
#we also want to figure out which bin the gene is in, so we can make a note of that
#we also want to get the bin at which the boundaries change, so we can also make a note of that

In [29]:
#write separate plotting function so this isn't too messy
#for plotting post akita predictions 

def plot_complex_pred(mat_list, label_list, bkpt_bin_list, gene_start_bin_list, gene_end_bin_list, gene_name_start_list, gene_name_end_list, gene_len):

    #order of lists is REF_left, REF_right, ALT
     
    fig=plt.figure(figsize=(7.5,6))
    target_index = 0
    vmin=-2; vmax=2

    plt.subplot(121) 
    im = plt.matshow(mat_list[1], fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    
    for g in gene_start_bin_list:
        plt.axvline(x = g, color = 'limegreen', linestyle = '--', linewidth=1, label = 'gene start')
    for g in gene_end_bin_list:
        plt.axvline(x = g, color = 'forestgreen', linestyle = '--', linewidth=1, label = 'gene end')
    for g in bkpt_bin_list:
        plt.axvline(x = g, color = 'blue', linestyle = 'dotted', linewidth=1, label = 'other bkpts ')
        
    # Add gene name annotations
    for gene_name, start_bin in zip(gene_name_start_list, gene_start_bin_list):
        plt.text(
            x=start_bin, y=1.2 * mat_list[1].shape[0],  # Position annotation near the top of the matrix
            s=gene_name,
            color='limegreen', fontsize=10, rotation=45, ha='right'
        )
    for gene_name, end_bin in zip(gene_name_end_list, gene_end_bin_list):
        plt.text(
            x=end_bin, y=1.2 * mat_list[1].shape[0],  # Position annotation near the top of the matrix
            s=gene_name,
            color='forestgreen', fontsize=10, rotation=45, ha='right'
        )
    
    
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    plt.title(label_list[0], y=1.15)
    
    plt.subplot(122) 
    im = plt.matshow(mat_list[0], fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    gene_len_n_bin=math.floor(gene_len/2048)
    plt.axvline(x = 224-(gene_len_n_bin/2), color = 'limegreen', linestyle = '--', linewidth=1, label = 'gene start')
    plt.axvline(x = 224+(gene_len_n_bin/2), color = 'forestgreen', linestyle = '--', linewidth=1, label = 'gene end')


    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    plt.title(label_list[1], y=1.15)

    
    
    fig.suptitle(label_list[2], fontsize=16, y=0.90)

        
    plt.tight_layout()
    plt.subplots_adjust(top=0.75)
    return(fig)

In [30]:
#make akita predictions for each walk and plot 
def pred_akita_genecenter_COSMIC(fa_dir, fa_name, patient_num):
    bed_name=fa_name.replace('fa', 'bed')
    name_parts = bed_name.rsplit('_', 2)


    #read in corresponding fa sequence
    seq=read_fasta(f'{fa_dir}{fa_name}')
    
    try:

        #read in bed file and figure out where to center the file 
        bed=pd.read_csv(f'{patient_data_dir}walks_bed/' + bed_name, sep='\t', header=None)
        bed.columns = ['chr', 'start', 'end', 'strand', 'cn', '5']
        bed['chr'] = bed['chr'].astype('str') 
        bed['span']=abs(bed['end']-bed['start']) 
        bed['span_cumsum'] = bed['span'].cumsum().astype(int)
        bed['bed_idx']=bed.index
    
        print('bed file', bed)
        walks_BED=BedTool.from_dataframe(bed[['chr', 'start', 'end', 'strand', 'cn', 'span', 'span_cumsum', 'bed_idx']])

        
        #overlap walks bed with COSMIC gene list 
        genes_in_map_BED = walks_BED.intersect(cosmic_BED, wa = True, wb = True)


        
        if genes_in_map_BED == '':
            #only want to visualize if gene is in the fasta 
            pass

        else:
            genes_in_map = (genes_in_map_BED.to_dataframe()
                        .rename(columns = {'strand': 'span', 'itemRgb': 'gene_chrom', 'name': 'strand', 
                                           'score': 'cn', 'thickStart': 'span_cumsum', 'thickEnd': 'bed_idx',
                                           'blockCount':'gene_start', 'blockSizes': 'gene_end', 
                                           'blockStarts':'gene_name'}))
            genes_in_map=genes_in_map[['chrom', 'start', 'end', 'strand', 'cn', 'span', 'span_cumsum', 'bed_idx',
                                       'gene_chrom', 'gene_start', 'gene_end','gene_name']]
            
            #print(genes_in_map)
            
            
            
            figures=[]
            #loop through each gene, center it, plot 
            for gene in range(0, len(genes_in_map)):
            #for gene in range(0, 2):



                gene_intersect_row=genes_in_map.loc[gene]
                print('gene', gene_intersect_row.gene_name)
                #print('gene_row', gene_row)

 
                try:
        
        
                    #get row in original bed that corresponds to gene row
                    gene_row_idx=bed[((bed['chr']==gene_intersect_row['chrom']) 
                                      & (bed['start']==gene_intersect_row.start)
                                     & (bed['end']==gene_intersect_row['end']))].index.values[0] 
                
                    #get gene info 
                    gene_len=abs(gene_intersect_row.gene_end-gene_intersect_row.gene_start)
                    gene_mid_coord=np.floor(gene_intersect_row.gene_start + (gene_len/2))
                    
                   
                    
                    #get first, last rows, and subsets of bed before and after bkpt 
                    first_row=bed.iloc[0,:]
                    last_row=bed.iloc[(len(bed)-1), :]
                    gene_row=bed.iloc[gene_row_idx, :]
                    bed_to_gene=bed.iloc[0:(gene_row_idx),:]
                                      

                    #get relevant lengths
                    total_span=np.sum(bed['span'])
                    left_to_gene_mid_coord_span=gene_mid_coord-gene_row['start']
                    #gene_mid_coord_to_right=gene_row['end']-gene_mid_coord
                    left_to_gene_span=int(np.sum(bed_to_gene['span']) + left_to_gene_mid_coord_span)
                    gene_to_right_span=total_span-left_to_gene_span 

                    #print(left_to_gene_span)

                    # left sequence 
                    if left_to_gene_span>=utils.half_patch_size:
                        ALT_left=seq[(left_to_gene_span - utils.half_patch_size ):left_to_gene_span]
                        
                        #for gene annot
                        left_start=left_to_gene_span - utils.half_patch_size 

                    else:   
                        #need to pad left from reference 
                        diff_len=utils.half_patch_size-left_to_gene_span
                        #print('diff len', diff_len)

                        first_row_idx=first_row.start
                        ALT_fromref_left=fasta_hg38.fetch(first_row.chr, first_row_idx-diff_len, first_row_idx).upper()

                        ALT_left=ALT_fromref_left + seq[0:len_left_to_bkpt]
                        
                        #for gene annot
                        left_start=-diff_len


                    # right sequence 
                    if gene_to_right_span>utils.half_patch_size:
                        ALT_right=seq[left_to_gene_span: (left_to_gene_span + utils.half_patch_size)]

                    else:
                        #need to pad right from reference        
                        diff_len=utils.half_patch_size-gene_to_right_span

                        last_row_idx=last_row.end
                        ALT_fromref_right=fasta_hg38.fetch(last_row.chr, last_row_idx, last_row_idx + diff_len).upper()

                        ALT_right=seq[left_to_gene_span:total_span] + ALT_fromref_right


                    ALT_seq = ALT_left + ALT_right
                    
                    #print('left start', left_start)
                    
                    #########################
                    #finally, get the REF -- center at the gene 
                    left_ref_coords=[gene_intersect_row.gene_chrom, gene_mid_coord-utils.half_patch_size, 
                                                  gene_mid_coord+utils.half_patch_size]


                    REF_seq_gene=fasta_hg38.fetch(left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]).upper()


                    ####################
                    
                    if REF_seq_gene==ALT_seq:
                        #want where breakpoints and genes differ 
                        pass
                    


                    else:
                        
                        #check sequence lengths, and then run akita 
                        assert len(REF_seq_gene) == utils.seq_length, 'REF_seq_left is not right length'
                        assert len(ALT_seq) == utils.seq_length, 'ALT_seq is not right length'



                        #this is where akita is actually run, output vector size is (99681,)
                        REF_gene_vec,  ALT_vec = utils.vector_from_seq(REF_seq_gene),  utils.vector_from_seq(ALT_seq)
                        REF_gene_mat,  ALT_mat = utils.mat_from_vector(REF_gene_vec), utils.mat_from_vector(ALT_vec)


                        #order is REF_left, REF_right, ALT
                        mat_list=[REF_gene_mat, ALT_mat]

                        
                        
                        #######################

                        #we want to get indices of the breakpoints, if others are in the window 


                        span_cumsum_list=np.array(bed['span_cumsum'].tolist())
                        bkpt_pos_from_left_all= span_cumsum_list-left_start


                        #subset to those less than akita window size
                        bkpt_pos_from_left=bkpt_pos_from_left_all[(bkpt_pos_from_left_all>0) & (bkpt_pos_from_left_all<utils.MB)]
                        #print(bkpt_pos_from_left)

                        #get the bin index
                        bkpt_pos_from_left=bkpt_pos_from_left.tolist()
                        bkpt_bin_list_all=[utils.get_bin(bkpt) for bkpt in bkpt_pos_from_left]
                        bkpt_bin_list = [bkpt for bkpt in bkpt_bin_list_all if 0 < bkpt <= 448]



                        ########################
                        #finally, get the positions of the gene(s)

                        gene_start_bin_list=[]
                        gene_end_bin_list=[]
                        gene_name_start_list=[]
                        gene_name_end_list=[]


                        #check the start of the gene 
                        for g in range(0, len(genes_in_map)):
                            gene_annot_row=genes_in_map.loc[g]
                            bed_g_idx=gene_annot_row['bed_idx']
                            bed_g_row=bed.iloc[bed_g_idx, :]
                            bed_to_gene=bed.iloc[0:(bed_g_idx),:]


                            #check that start coord is in the bed
                            if (gene_annot_row['gene_start']>bed_g_row.start & gene_annot_row['gene_start']<bed_g_row.end):
                                len_to_gene_start_row=gene_annot_row['gene_start'] - (bed_g_row.start) 
                                left_to_gene_start=np.sum(bed_to_gene['span']) + len_to_gene_start_row
                                gene_start_pos_window=utils.get_bin(left_to_gene_start - left_start)
                                if (gene_start_pos_window>0) & (gene_start_pos_window<448):
                                    gene_start_bin_list.append(gene_start_pos_window)
                                    gene_name_start_list.append(gene_annot_row['gene_name'])


                            #check that end coord is in bed
                            if (gene_annot_row['gene_end']>bed_g_row.start & gene_annot_row['gene_end']<bed_g_row.end):
                                len_to_gene_end_row=gene_annot_row['gene_end'] - (bed_g_row.start) 
                                left_to_gene_end=np.sum(bed_to_gene['span']) + len_to_gene_end_row
                                gene_end_pos_window=utils.get_bin(left_to_gene_end - left_start)
                            if (gene_end_pos_window>0) & (gene_end_pos_window<448):
                                gene_end_bin_list.append(gene_end_pos_window)
                                gene_name_end_list.append(gene_annot_row['gene_name'])


                        ####################

                        #get label list 
                        label_list=[f'Row {gene_row_idx}, centered at {gene_intersect_row.gene_name}', 
                                    'REF at {} \n {}:{}-{}'.format(gene_intersect_row.gene_name, left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]), 
                                    f'{fa_name[:-3]}']

                        #print(label_list)

                        # plot!
                        fig=plot_complex_pred(mat_list, label_list, bkpt_bin_list, gene_start_bin_list, gene_end_bin_list, gene_name_start_list, gene_name_end_list, gene_len)
                        figures.append(fig)

                except:
                    print('error!!!! in row index', gene)
                    
                    
            if len(figures)>0:                    
                print(f'saving to {fig_dir}patient_{patient_num}/{bed_name[:-4]}_breakpoints.pdf')
                save_figures_to_pdf(f'{fig_dir}patient_{patient_num}/{bed_name[:-4]}_plot.pdf', figures)
            plt.close('all')

                            
    except:
        print('error in file', fa_name)

In [31]:
fig_dir='/pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/'

#run for all patients
for patient_num in range(1,25):
#for patient_num in range(1,2):
    print('running patient ', patient_num)
    dir_patient=f'{patient_data_dir}patient_{patient_num}/walks_fasta/'
    dir_files=os.listdir(dir_patient)
    
    #run for all walks in patient 
    for f in range (0, len(dir_files)):
    #for f in range (0,5):

        print('running file ', dir_files[f])
        pred_akita_genecenter_COSMIC(fa_dir=dir_patient, fa_name=dir_files[f], patient_num=patient_num)

running patient  1
running file  226296-WG01_walk_5_MYCL_containing.fa
bed file     chr     start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr1         1   17349689      +   4     1  17349688     17349688        0
1  chr1  17349690   17351158      +   4     2      1468     17351156        1
2  chr1  17351159   53225853      +   5     3  35874694     53225850        2
3  chr3  98322576   99224962      +   5  2220    902386     54128236        3
4  chr3  99224963   99230671      +   4  2221      5708     54133944        4
5  chr3  99230672  109150007      +   5  2222   9919335     64053279        5
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene EPS15
gene TFG
gene CBLB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226296-WG01_walk_5_MYCL_containing_breakpoints.pdf
running file  226298-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8         1   42520419      +   2  919   42520418     42520418        0
1  chr8  42522790  145138636      +   2  921  102615846    145136264        1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226298-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226297-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1   35320943      +   2  32  35320942     35320942        0
1  chr12  36636646   43583657      +   2  36   6947011     42267953        1
2  chr12  43585747  133275309      +   2  38  89689562    131957515        2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226298-WG01_walk_1_MYCL_containing.fa
bed file       chr      start        end strand  cn     5       span  span_cumsum  \
0    chr1          1   24037904      +   2     1   24037903     24037903
1    chr1   24037905   29552242      +   3     2    5514337     29552240
2    chr1   29552243  109563774      +   2     3   80011531    109563771
3    chr1  109563775  109564001      +   3     4        226    109563997
4    chr1  109564002  122503003      +   2     5   12939001    122502998
5    chr1  122503004  150227602      +   3     6   27724598    150227596
6    chr1  150227603  150806402      +   4     7     578799    150806395
7    chr1  150806403  152560265      +   3     8    1753862    152560257
8   chr12   56929770   57034372      +   6   183     104602    152664859
9   chr12   95660441   95741519      +   7   487      81078    152745937
10  chr12   95741520   95741890      +   8   488        370    152746307
11  chr12   95741891   95794372      +  11   489      52481    152798788
12  chr12   68690867   68715553      +  14   296      24686    152823474
13  chr12   96116086   96251602      +   9   498     135516    152958990
14  chr12   96251603   96278748      +  11   499      27145    152986135
15  chr12   96278749   96390413      +  13   500     111664    153097799
16  chr12   96390414   96393453      +  11   501       3039    153100838
17  chr12   96393454   96410219      +  12   502      16765    153117603
18  chr12   96410220   96441448      +  11   503      31228    153148831
19  chr12  127855974  127876592      -  12  -774      20618    153169449
20  chr12  127855357  127855973      -  11  -773        616    153170065
21  chr12   37734942   37749359      +   7    82      14417    153184482
22  chr12   54275179   54304648      +   6   176      29469    153213951
23  chr12   54304649   54487424      +   4   177     182775    153396726
24  chr12  115619961  115645718      +   6   684      25757    153422483
25  chr12  115645719  115703002      +   7   685      57283    153479766
26  chr12  115703003  115703285      +   8   686        282    153480048
27  chr12   76707168   76722588      -   7  -383      15420    153495468
28  chr12  125195491  125197040      -   8  -750       1549    153497017
29  chr12  125944788  126023651      -   4  -762      78863    153575880
30  chr12  116484669  116541125      -   5  -693      56456    153632336
31  chr12  130659963  130730372      +   4   792      70409    153702745
32  chr12   67270171   67387480      -   5  -290     117309    153820054
33  chr12   67208726   67270170      -   6  -289      61444    153881498
34  chr12  127644412  127664612      +   5   767      20200    153901698
35  chr12  127664613  127722222      +   8   768      57609    153959307
36  chr12   66462528   66471326      +  15   277       8798    153968105
37  chr12   66471327   66484693      +  11   278      13366    153981471
38  chr12  115719773  115720047      +   5   688        274    153981745
39  chr12  115720048  115973196      +   4   689     253148    154234893
40  chr12   68783017   68808126      +  17   301      25109    154260002
41   chrX  152888058  152923433      -   2 -1097      35375    154295377
42   chrX    5139459  152888057      -   1 -1096  147748598    302043975
43   chrX          1    5137306      -   1 -1094    5137305    307181280

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
gene ARID1A
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene SETDB1
gene MLLT11
gene ARNT
gene SSX4
gene WAS
gene SSX2
gene FOXO4
gene IRS4
gene DCAF12L2
gene ZRSR2
gene EIF1AX
gene FAM47C
gene BCOR
gene DDX3X
gene ARAF
gene SSX1
gene GATA1
gene TFE3
gene SMC1A

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene AMER1
gene MSN
gene MED12
gene NONO
gene ZMYM3
gene BTK
gene ELF4
gene PHF6
gene TMSB4X
gene USP9X
gene KDM5C
gene AR
gene SEPT6
gene STAG2
gene GPC3
gene KDM6A
gene RBM10
gene ATRX
gene BCORL1
gene CRLF2
gene P2RY8
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226298-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226296-WG01_walk_4_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  150228403  150481802      -  12 -8    253399       253399        0
1  chr1  124686403  150228402      -   7 -7  25541999     25795398        1
2  chr1   94954905  124686402      -   4 -6  29731497     55526895        2
3  chr1   94947817   94954904      -   3 -5      7087     55533982        3
4  chr1   53225854   94947816      -   4 -4  41721962     97255944        4
5  chr1   17351159   53225853      -   5 -3  35874694    133130638        5
6  chr1   17349690   17351158      -   4 -2      1468    133132106        6
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226296-WG01_walk_4_MYCL_containing_breakpoints.pdf
running file  226296-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr6  160621003  170805979      -   4 -2381  10184976     10184976        0
1  chr6  129283798  160621002      -   5 -2380  31337204     41522180        1
2  chr2   18726391   77975705      -   5 -2064  59249314    100771494        2
3  chr2          1   18726390      -   4 -2063  18726389    119497883        3
gene FGFR1OP
gene AFDN
gene QKI
gene MYB
gene BCLAF1
gene TNFAIP3
gene EZR
gene ECT2L
gene LATS1
gene ARID1B
gene ESR1
gene SGK1
gene PCBP1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226296-WG01_walk_2_MYCN_containing.fa
bed file       chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0    chr2         1  18726390      +   4  2063  18726389     18726389        0
1    chr2  18726391  77975705      +   5  2064  59249314     77975703        1
2    chr2  77975706  98730467      +   4  2065  20754761     98730464        2
3    chr2  98730468  98730810      +  13  2066       342     98730806        3
4   chr12  97092635  97093123      -  12 -1269       488     98731294        4
5   chr12  97026468  97092634      -   5 -1268     66166     98797460        5
6   chr12  97025490  97026467      -   8 -1267       977     98798437        6
7   chr12  96996379  97025489      -  28 -1266     29110     98827547        7
8   chr12  96963121  96996378      -  32 -1265     33257     98860804        8
9   chr12  96963034  96963120      -  37 -1264        86     98860890        9
10  chr12  96948229  96963033      -  44 -1263     14804     98875694       10
11  chr12  96947947  96948228      -  36 -1262       281     98875975       11
12  chr12  96923915  96947946      -  43 -1261     24031     98900006       12
13  chr12  96923875  96923914      -  59 -1260        39     98900045       13
14  chr12  96923688  96923874      -  61 -1259       186     98900231       14
15  chr12  96913257  96923687      -  45 -1258     10430     98910661       15
16  chr12  34087088  34111313      +  45   180     24225     98934886       16
17  chr12  50777867  50806602      +  46   391     28735     98963621       17
gene MYCN
gene PCBP1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene TMEM127
gene CTNNA2
gene ATF1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226296-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226297-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1   35320943      +   2  32  35320942     35320942        0
1  chr12  36636646   43583657      +   2  36   6947011     42267953        1
2  chr12  43585747  133275309      +   2  38  89689562    131957515        2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226296-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1          1   17349689      +   4   1  17349688     17349688        0
1  chr1   17349690   17351158      +   4   2      1468     17351156        1
2  chr1   17351159   53225853      +   5   3  35874694     53225850        2
3  chr1   53225854   94947816      +   4   4  41721962     94947812        3
4  chr1   94954905  124686402      +   4   6  29731497    124679309        4
5  chr1  124686403  150228402      +   7   7  25541999    150221308        5
6  chr1  150228403  150481802      +  12   8    253399    150474707        6
7  chr1  150481803  151984580      +  10   9   1502777    151977484        7
8  chr1  151984581  152166202      +  14  10    181621    152159105        8
9  chr1  152166203  152548002      +   9  11    381799    152540904        9
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene SETDB1
gene MLLT11
gene ARNT
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226296-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226295-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12   95660441   95727668      -  23 -730     67227        67227        0
1  chr12   56991907   57034372      -  20 -261     42465       109692        1
2  chr12   56929770   56991906      -  22 -260     62136       171828        2
3   chr1  152166203  152560265      -   5   -8    394062       565890        3
4   chr1  151989603  152166202      -   8   -7    176599       742489        4
5   chr1  150481803  151989602      -   5   -6   1507799      2250288        5
6   chr1  150228403  150481802      -   6   -5    253399      2503687        6
7   chr1  124932203  150228402      -   3   -4  25296199     27799886        7
8   chr1   94954905  124932202      -   2   -3  29977297     57777183        8
9   chr1          1   94947816      -   2   -1  94947815    152724998        9
gene SETDB1
gene MLLT11
gene ARNT
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226295-WG01_walk_1_MYCL_containing_breakpoints.pdf

running file  226298-WG01_walk_1_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2         1  42119119      +   2  831  42119118     42119118        0
1  chr2  42119120  44249371      +   3  832   2130251     44249369        1
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene EML4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226298-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226295-WG01_walk_1_MYCN_containing.fa
bed file     chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0  chr2         1  87433202      +   2  1241  87433201     87433201        0
1  chr2  87433203  88729728      +   3  1242   1296525     88729726        1
2  chr2  88732766  90381211      +   3  1244   1648445     90378171        2
3  chr2  90381212  90393319      +   2  1245     12107     90390278        3
4  chr2  90393320  98730467      +   3  1246   8337147     98727425        4
5  chr2  98730468  99110138      +   5  1247    379670     99107095        5
6  chr2  99110139  99185806      +   9  1248     75667     99182762        6
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene TMEM127
running file  226298-WG01_walk_2_MYCL_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr1          1   24037904      +   2    1  24037903     24037903
1    chr1   24037905   29552242      +   3    2   5514337     29552240
2    chr1   29552243  109563774      +   2    3  80011531    109563771
3    chr1  109563775  109564001      +   3    4       226    109563997
4    chr1  109564002  122503003      +   2    5  12939001    122502998
5    chr1  122503004  150227602      +   3    6  27724598    150227596
6    chr1  150227603  150806402      +   4    7    578799    150806395
7    chr1  150806403  152560265      +   3    8   1753862    152560257
8    chr1  152560266  153166143      +   2    9    605877    153166134
9    chr1  153166144  153726002      +   3   10    559858    153725992
10   chr1  153726003  154663202      +   4   11    937199    154663191
11   chr1  154663203  155194202      +   3   12    530999    155194190
12   chr1  155194203  156346602      +   4   13   1152399    156346589
13   chr1  156346603  156490802      +   3   14    144199    156490788
14   chr1  156490803  157300202      +   4   15    809399    157300187
15   chr1  157300203  159239066      +   3   16   1938863    159239050
16   chr1  159239067  159632428      +   2   17    393361    159632411
17   chr1  159632429  159715946      +   4   18     83517    159715928
18   chr2  212661782  212667851      +   4  864      6069    159721997
19  chr12   48464461   48540295      +   6  150     75834    159797831

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
gene ARID1A
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
gene TPM3
gene MUC1
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226298-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226297-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2          1  193824778      +   2  61  193824777    193824777        0
1  chr2  193834042  242193529      +   2  63   48359487    242184264        1
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene ACKR3
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene SF3B1
gene CUL3
gene ERBB4
gene PAX3
running file  226296-WG01_walk_3_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  150228403  150481802      -  12 -8    253399       253399        0
1  chr1  124686403  150228402      -   7 -7  25541999     25795398        1
2  chr1   94954905  124686402      -   4 -6  29731497     55526895        2
3  chr1   94947817   94954904      -   3 -5      7087     55533982        3
4  chr1   53225854   94947816      -   4 -4  41721962     97255944        4
5  chr1   17351159   53225853      -   5 -3  35874694    133130638        5
6  chr1          1   17349689      -   4 -1  17349688    150480326        6
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene EPS15
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226296-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226296-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  151984581  152166202      -  14 -10    181621       181621        0
1  chr1  150481803  151984580      -  10  -9   1502777      1684398        1
2  chr1  150228403  150481802      -  12  -8    253399      1937797        2
3  chr1  124686403  150228402      -   7  -7  25541999     27479796        3
4  chr1   94954905  124686402      -   4  -6  29731497     57211293        4
5  chr1   94947817   94954904      -   3  -5      7087     57218380        5
6  chr1   53225854   94947816      -   4  -4  41721962     98940342        6
7  chr1   17351159   53225853      -   5  -3  35874694    134815036        7
8  chr1   17349690   17351158      -   4  -2      1468    134816504        8
9  chr1          1   17349689      -   4  -1  17349688    152166192        9
gene SETDB1
gene MLLT11
gene ARNT
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene EPS15
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226296-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226295-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn     5       span  span_cumsum  bed_idx
0  chr8         1   41923202      +   2  1347   41923201     41923201        0
1  chr8  41923203   43501202      +   3  1348    1577999     43501200        1
2  chr8  43501203  145138636      +   2  1349  101637433    145138633        2
gene LEPROTL1
gene FGFR1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene IKBKB
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1

gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226295-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226297-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8          1   42520419      +   2  112  42520418     42520418        0
1  chr8   42522790  131265479      +   2  114  88742689    131263107        1
2  chr8  131268277  145138636      +   2  116  13870359    145133466        2
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226297-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226297-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1          1   24832212      +   2   1  24832211     24832211        0
1  chr1   24835019   84052256      +   2   3  59217237     84049448        1
2  chr1   84058947  100351876      +   2   5  16292929    100342377        2
3  chr1  100351877  100352152      +   3   6       275    100342652        3
4  chr1  100352153  197531390      +   2   7  97179237    197521889        4
5  chr1  197534142  245662258      +   2   9  48128116    245650005        5
6  chr1  245662259  245662594      +   4  10       335    245650340        6
7  chr1  245662595  248956422      +   2  11   3293827    248944167        7
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
gene MYCL
gene JUN
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene ARID1A
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene PTPRC
gene AKT3
gene RGS7
running file  226296-WG01_walk_2_MYC_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr8          1   14453491      +   4  2414  14453490     14453490        0
1  chr8   14453492   43982602      +   5  2415  29529110     43982600        1
2  chr8   43982603   52597982      +   4  2416   8615379     52597979        2
3  chr8   52597983   60710548      +   3  2417   8112565     60710544        3
4  chr8   60710549  101421297      +   4  2418  40710748    101421292        4
5  chr8  101421298  103881458      +   5  2419   2460160    103881452        5
6  chr8  103881459  130804104      +   4  2420  26922645    130804097        6
gene ARHGEF10
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene NCOA2
gene PREX2
gene CNBD1
gene UBR5
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
running file  226295-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0  chr2  99110139  99185806      -   9 -1248     75667        75667        0
1  chr2  98730468  99110138      -   5 -1247    379670       455337        1
2  chr2  90393320  98730467      -   3 -1246   8337147      8792484        2
3  chr2  88732766  90381211      -   3 -1244   1648445     10440929        3
4  chr2  87433203  88729728      -   3 -1242   1296525     11737454        4
5  chr2         1  87433202      -   2 -1241  87433201     99170655        5
gene TMEM127
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226295-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  151989603  152166202      -   8 -7    176599       176599        0
1  chr1  150481803  151989602      -   5 -6   1507799      1684398        1
2  chr1  150228403  150481802      -   6 -5    253399      1937797        2
3  chr1  124932203  150228402      -   3 -4  25296199     27233996        3
4  chr1   94954905  124932202      -   2 -3  29977297     57211293        4
5  chr1   94947817   94954904      -   1 -2      7087     57218380        5
6  chr1          1   94947816      -   2 -1  94947815    152166195        6
gene SETDB1
gene MLLT11
gene ARNT
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_1/226295-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226296-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr5  137688198  144132923      -   5 -2352   6444725      6444725        0
1  chr5  137686890  137688197      -   4 -2351      1307      6446032        1
2  chr5  122245114  137686889      -   5 -2350  15441775     21887807        2
3  chr5   85464947  122240436      -   4 -2348  36775489     58663296        3
4  chr5   52899492   85464946      -   5 -2347  32565454     91228750        4
5  chr8   14453492   43982602      +   5  2415  29529110    120757860        5
6  chr8   43982603   52597982      +   4  2416   8615379    129373239        6
7  chr8  101421298  103881458      +   5  2419   2460160    131833399        7
8  chr8  103881459  130804104      +   4  2420  26922645    158756044        8
gene CTNNA1
gene ARHGAP26
gene ACSL6
gene AFF4
gene APC
gene RAD17
gene IL6ST
gene MAP3K1
gene PIK3R1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene UBR5
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
running patient  2
running file  226301-WG01_walk_4_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr8   6585424   6636002      -  25 -524     50578        50578        0
1   chr12  71796794  73055205      -  15 -270   1258411      1308989        1
2   chr12  71158403  71795379      -  15 -268    636976      1945965        2
3   chr12  70204203  71158402      -  16 -267    954199      2900164        3
4   chr12  68633403  70204202      -  17 -266   1570799      4470963        4
5   chr12  67382403  68633402      -  14 -265   1250999      5721962        5
6   chr12  65774368  67382402      -  15 -264   1608034      7329996        6
7   chr12  64437803  65774367      -  20 -263   1336564      8666560        7
8   chr12  63926483  64437802      -  22 -262    511319      9177879        8
9   chr12  61394003  63926482      -   6 -261   2532479     11710358        9
10  chr12  61209803  61394002      -   8 -260    184199     11894557       10
11  chr12  55732603  61209802      -   6 -259   5477199     17371756       11
12  chr12  55359603  55732602      -   8 -258    372999     17744755       12
13  chr12  55278869  55359602      -  13 -257     80733     17825488       13
14  chr12  55278603  55278868      -  10 -256       265     17825753       14
15  chr12  52825603  55278602      -   5 -255   2452999     20278752       15
16  chr12  52778838  52825602      -  13 -254     46764     20325516       16
17  chr12  52778709  52778837      -   9 -253       128     20325644       17
18  chr12  52328603  52778708      -   5 -252    450105     20775749       18
19  chr12  47936868  52328602      -   6 -251   4391734     25167483       19
20  chr12  47269996  47936867      -  20 -250    666871     25834354       20
21   chr8  53553470  53628130      -  20 -577     74660     25909014       21
22   chr8  53029100  53553469      -   6 -576    524369     26433383       22
23  chr19  32659775  46323823      -   7 -349  13664048     40097431       23
24  chr19  31312080  32659774      -  10 -348   1347694     41445125       24
25  chr19  30044981  31312079      -   9 -347   1267098     42712223       25
26  chr19  24897453  30044980      -   9 -346   5147527     47859750       26
27  chr19  22115841  24897452      -   7 -345   2781611     50641361       27
28  chr19  21017550  22115840      -  10 -344   1098290     51739651       28
29  chr19  20572852  21017549      -  11 -343    444697     52184348       29
30  chr19  13518578  20572851      -   9 -342   7054273     59238621       30
31  chr19   9508751  13518577      -   8 -341   4009826     63248447       31
32  chr19         1   9508750      -   8 -340   9508749     72757196       32
gene PTPRB

gene MDM2
gene HMGA2
gene WIF1
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene CEBPA
gene BCL3
gene CD79A
gene CIC
gene CBLC
gene CEP89
gene LSM14A
gene AKT2
gene ERCC2
gene CCNE1
gene ZNF429
gene PRKACA
gene DNAJB1
gene BRD4
gene TPM4
gene CRTC1
gene ELL
gene JAK3
gene LYL1
gene KEAP1
gene CALR
gene DNM2
gene SMARCA4
gene FSTL3
gene CD209
gene STK11
gene TCF3
gene GNA11
gene MAP2K2
gene SH3GL1
gene MLLT1
gene VAV1
gene MUC16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_4_MDM2_containing_breakpoints.pdf
running file  226300-WG01_walk_3_MYCL_containing.fa
bed file      chr      start        end strand  cn    5       span  span_cumsum  \
0   chr5   28645683   28678602      -  13 -688      32919        32919
1   chr5  126492335  126505740      -  18 -726      13405        46324
2   chr5  126492005  126492334      -  16 -725        329        46653
3   chr5  126491061  126492004      -  25 -724        943        47596
4   chr5  126491008  126491060      -  17 -723         52        47648
5   chr5  126428003  126491007      -  29 -722      63004       110652
6   chr5  126245978  126428002      -  26 -721     182024       292676
7   chr5  126082603  126245977      -  23 -720     163374       456050
8   chr5  126082514  126082602      -  19 -719         88       456138
9   chr1  194356388  194484802      +   9  100     128414       584552
10  chr1  194484803  195184042      +  10  101     699239      1283791
11  chr1  195184043  195218841      +  16  102      34798      1318589
12  chr1  145462190  145771331      -  29   -4     309141      1627730
13  chr1  144426382  145462189      -  21   -3    1035807      2663537
14  chr1  125178603  144426381      -  17   -2   19247778     21911315
15  chr1          1  125178602      -   4   -1  125178601    147089916

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226301-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  22028160  54802346      -   5 -352  32774186     32774186        0
1  chr2         1  22028159      -   4 -351  22028158     54802344        1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226301-WG01_walk_3_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  137011228  145138636      -   5 -591   8127408      8127408        0
1   chr8  108005603  137011227      -   6 -590  29005624     37133032        1
2   chr8  106663403  108005602      -  15 -589   1342199     38475231        2
3   chr8  103513803  106663402      -  14 -588   3149599     41624830        3
4   chr8  103050403  103513802      -  19 -587    463399     42088229        4
5   chr8   77266124  103050402      -   6 -586  25784278     67872507        5
6   chr8   67575640   77266123      -   7 -585   9690483     77562990        6
7   chr4  165074087  167199589      +   7  443   2125502     79688492        7
8  chr19   24897453   30044980      -   9 -346   5147527     84836019        8
gene RECQL4
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene RSPO2
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene UBR5
gene CNBD1
gene NCOA2
gene PREX2
gene CCNE1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226301-WG01_walk_2_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  111637203  112622002      -   8 -280    984799       984799
1   chr12  111348003  111637202      -   7 -279    289199      1273998
2   chr12   93504603  111348002      -   6 -278  17843399     19117397
3   chr12   93028803   93504602      -   7 -277    475799     19593196
4   chr12   92995803   93028802      -  13 -276     32999     19626195
5   chr12   92866603   92995802      -  19 -275    129199     19755394
6   chr12   92205603   92866602      -  12 -274    660999     20416393
7   chr12   91841803   92205602      -  11 -273    363799     20780192
8   chr12   73152203   91841802      -   7 -272  18689599     39469791
9   chr12   73055206   73152202      -  11 -271     96996     39566787
10  chr12   71796794   73055205      -  15 -270   1258411     40825198
11  chr12   71158403   71795379      -  15 -268    636976     41462174
12  chr12   70204203   71158402      -  16 -267    954199     42416373
13  chr12   68633403   70204202      -  17 -266   1570799     43987172
14  chr12   67382403   68633402      -  14 -265   1250999     45238171
15  chr12   65774368   67382402      -  15 -264   1608034     46846205
16  chr12   64437803   65774367      -  20 -263   1336564     48182769
17  chr12   63926483   64437802      -  22 -262    511319     48694088
18  chr20   62231912   62234307      -  29 -400      2395     48696483
19  chr12   47269996   47936867      -  20 -250    666871     49363354
20   chr8   53553470   53628130      -  20 -577     74660     49438014
21   chr8   53029100   53553469      -   6 -576    524369     49962383
22   chr8   26844207   53029099      -   4 -575  26184892     76147275
23   chr8   26713603   26844206      -   9 -574    130603     76277878
24   chr8   26688841   26713602      -   3 -573     24761     76302639
25   chr8   26528003   26688840      -   8 -572    160837     76463476

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
gene ALDH2
error!!!! in row index 0
gene PTPN11
gene SH2B3
gene USP44
gene CHST11
gene BTG1
gene PTPRB
gene MDM2
gene HMGA2
gene WIF1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226301-WG01_walk_3_MYCL_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr1          1  125093802      +   4    1  125093801    125093801        0
1  chr1  125093803  145780186      +  19    2   20686383    145780184        1
2  chr1  188198469  188200188      +  11   87       1719    145781903        2
3  chr5  126621074  126631162      +  11  483      10088    145791991        3
4  chr1  189980753  193123477      +   5   90    3142724    148934715        4
5  chr1  159497161  159551719      +   8   34      54558    148989273        5
6  chr1  159551720  159610170      +  12   35      58450    149047723        6
7  chr1  169062482  169068475      +  12   66       5993    149053716        7
8  chr1  169068476  169124542      +   8   67      56066    149109782        8
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR

gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene CDC73
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226300-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr8  126114603  145138636      -   5  -929  19024033     19024033
1   chr8  125363003  126114602      -   6  -928    751599     19775632
2   chr8  112877203  125363002      -   5  -927  12485799     32261431
3   chr8  110821803  112877202      -   6  -926   2055399     34316830
4   chr8  109125305  110821802      -   5  -925   1696497     36013327
5   chr8  109097903  109125304      -  12  -924     27401     36040728
6   chr4   88182210   88200832      +  11   651     18622     36059350
7   chr4  121831260  122072215      +  10   663    240955     36300305
8   chrX   48185924   48212258      +  13  1115     26334     36326639
9   chrX   48212259   57788602      +   5  1116   9576343     45902982
10  chrX   57788603   62489002      +   3  1117   4700399     50603381
11  chrX   62489003   70202202      +   2  1118   7713199     58316580
12  chrX   70202203  135882602      +   1  1119  65680399    123996979
13  chrX  135882603  153119602      +   2  1120  17236999    141233978
14  chrX  153119603  154648402      +   3  1121   1528799    142762777
15  chrX  154648403  156040895      +   2  1122   1392492    144155269

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene RAD21
gene EXT1
gene CSMD3
gene CSMD3
gene SSX4
gene WAS
gene SSX2
gene SSX1
gene GATA1
gene TFE3
gene SMC1A
gene KDM5C
gene AMER1
gene MSN
gene AR
gene FOXO4
gene IRS4
gene DCAF12L2
gene MED12
gene NONO
gene ZMYM3
gene BTK
gene ELF4

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene PHF6
gene SEPT6
gene STAG2
gene GPC3
gene ATRX
gene BCORL1
gene RPL10
gene ATP2B3
gene FLNA
gene MTCP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226300-WG01_walk_3_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  67908403  68615602      +  18  295    707199       707199        0
1   chr12  68615603  68783349      +  20  296    167746       874945        1
2   chr12  68783350  68991602      +  22  297    208252      1083197        2
3   chr12  68991603  69102585      +  19  298    110982      1194179        3
4   chr12  69102586  69443494      +  21  299    340908      1535087        4
5   chr12  69443495  70027891      +  24  300    584396      2119483        5
6   chr12  70027892  70227988      +  25  301    200096      2319579        6
7   chr12  70227989  70720202      +  21  302    492213      2811792        7
8   chr12  70720203  70993402      +  18  303    273199      3084991        8
9   chr12  70993403  71534945      +  20  304    541542      3626533        9
10  chr12  71534946  71795379      +  13  305    260433      3886966       10
11  chr12  71796794  72011665      +  13  307    214871      4101837       11
12   chr8  15668760  15696938      +   5  850     28178      4130015       12
13   chr8  15696939  15733480      +   2  851     36541      4166556       13
14   chr8  15733481  15769257      +   7  852     35776      4202332       14
15   chr8  25215560  25414305      -   9 -878    198745      4401077       15
16   chr8  24163797  24174249      -   8 -874     10452      4411529       16
17   chr8  24122678  24163796      -   3 -873     41118      4452647       17
18   chr8  23763417  24122677      -   5 -872    359260      4811907       18
19   chr8  23745995  23763416      -   4 -871     17421      4829328       19
20   chr8  21331995  23745994      -   5 -870   2413999      7243327       20
21   chr8  21272359  21331994      -  36 -869     59635      7302962       21
22  chr16  50267576  51390895      -   7 -449   1123319      8426281       22
23  chr16  50025063  50267575      -   7 -448    242512      8668793       23
24  chr16  48878316  50025062      -   5 -447   1146746      9815539       24
25  chr16  48290745  48878315      -   1 -446    587570     10403109       25
26  chr16  36102080  48290744      -   3 -445  12188664     22591773       26
27  chr16  34520803  36102079      -   2 -444   1581276     24173049       27
28  chr16  24412387  34520802      -   3 -443  10108415     34281464       28
29  chr16  16687003  24412386      -   4 -442   7725383     42006847       29
30  chr16  14693203  16687002      -   5 -441   1993799     44000646       30
gene MDM2
gene PTPRB
gene CYLD
gene FUS
gene IL21R
gene PALB2
gene PRKCB
gene MYH11
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_3_MDM2_containing_breakpoints.pdf
running file  226302-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1   47269995      +   2  16  47269994     47269994        0
1  chr12  47269996   47936867      +   4  17    666871     47936865        1
2  chr20  62231912   62234307      +   4  47      2395     47939260        2
3  chr12  63926483   65907802      +   4  19   1981319     49920579        3
4  chr12  65907803   68594202      +   3  20   2686399     52606978        4
5  chr12  68594203   71909002      +   4  21   3314799     55921777        5
6  chr12  71909003   73144802      +   3  22   1235799     57157576        6
7  chr12  73144803  133275309      +   2  23  60130506    117288082        7
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene ERC1
gene WIF1
gene HMGA2
gene HMGA2
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226302-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226301-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1  37238002      +   5  247  37238001     37238001        0
1  chr12  37238003  43439960      +   6  248   6201957     43439958        1
2  chr12  43439961  47269995      +   6  249   3830034     47269992        2
3  chr12  47269996  47936867      +  20  250    666871     47936863        3
4  chr20  62231912  62234307      +  29  400      2395     47939258        4
5  chr20  62234308  62235802      +  13  401      1494     47940752        5
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene ARID2
running file  226300-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  99336803  114560011      -   5 -527  15223208     15223208        0
1  chr2  94090204   99336802      -   3 -526   5246598     20469806        1
2  chr2  76223942   94090203      -   4 -525  17866261     38336067        2
3  chr2  32870557   75256720      -   4 -523  42386163     80722230        3
4  chr2  23728218   32866671      -   5 -521   9138453     89860683        4
5  chr2         1   23728217      -   4 -520  23728216    113588899        5
gene RANBP2
gene RGPD3
gene AFF3
error!!!! in row index 2
gene PAX8
gene TMEM127
gene CTNNA2
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226302-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr5  131047203  181538259      -   2 -61  50491056     50491056        0
1  chr15   61674325   64869464      -   3 -31   3195139     53686195        1
2   chr1  171609696  173659340      -   3  -9   2049644     55735839        2
3   chr1  165974203  171609695      -   2  -8   5635492     61371331        3
4   chr1  164917448  165974202      -   3  -7   1056754     62428085        4
5   chr1  161902689  164917447      -   2  -6   3014758     65442843        5
6   chr1  121605203  161688004      -   3  -4  40082801    105525644        6
7   chr1   28769003  121605202      -   2  -3  92836199    198361843        7
8   chr1   26422403   28769002      -   3  -2   2346599    200708442        8
9   chr1          1   26422402      -   2  -1  26422401    227130843        9
gene PDGFRB
gene CD74
gene ITK
gene PWWP2A
gene NPM1
gene FGFR4
gene ACSL6
gene AFF4
gene CTNNA1
gene ARHGAP26
gene CSF1R
gene EBF1
gene TLX3
gene FLT4
gene NSD1
gene PRRX1
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene BCL9
gene ARNT
gene SDHC
gene PDE4DIP
gene MUC1
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene EPS15
gene ATP1A1
gene ARID1A
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226302-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226300-WG01_walk_3_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  32866672  32870556      -   1 -522      3884         3884        0
1  chr2  23728218  32866671      -   5 -521   9138453      9142337        1
2  chr2         1  23728217      -   4 -520  23728216     32870553        2

gene WDCP
error!!!! in row index 0
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226302-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1   47269995      +   2  16  47269994     47269994        0
1  chr12  47269996   47936867      +   4  17    666871     47936865        1
2  chr20  62231912   62234307      +   4  47      2395     47939260        2
3  chr12  63926483   65907802      +   4  19   1981319     49920579        3
4  chr12  65907803   68594202      +   3  20   2686399     52606978        4
5  chr12  68594203   71909002      +   4  21   3314799     55921777        5
6  chr12  71909003   73144802      +   3  22   1235799     57157576        6
7  chr12  73144803  133275309      +   2  23  60130506    117288082        7
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene ERC1
gene WIF1
gene HMGA2
gene HMGA2
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226302-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226301-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5       span  span_cumsum  bed_idx
0   chr1  152766288  153282202      -  17 -13     515914       515914        0
1   chr1  152583203  152766287      -  13 -12     183084       698998        1
2   chr1  152157056  152583202      -   9 -11     426146      1125144        2
3   chr1  151553803  152157055      -  13 -10     603252      1728396        3
4   chr1  151467203  151553802      -  16  -9      86599      1814995        4
5   chr1  150600797  151467202      -  22  -8     866405      2681400        5
6   chr1  150313277  150600796      -  24  -7     287519      2968919        6
7   chr1  149806603  150313276      -  12  -6     506673      3475592        7
8   chr1  148242035  149806602      -  18  -5    1564567      5040159        8
9   chr1  147095019  148242034      -  21  -4    1147015      6187174        9
10  chr1  145780187  147095018      -  14  -3    1314831      7502005       10
11  chr1  125093803  145780186      -  19  -2   20686383     28188388       11
12  chr1          1  125093802      -   4  -1  125093801    153282189       12
gene SETDB1
gene MLLT11
gene ARNT
gene PDE4DIP
gene BCL9
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226300-WG01_walk_4_MDM2_containing.fa
bed file      chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  68783350   68991602      -  22 -297    208252       208252        0
1  chr13  72789680   73857181      +   2  339   1067501      1275753        1
2  chr13  73857182   82763202      +   3  340   8906020     10181773        2
3  chr13  82763203  114364328      +   2  341  31601125     41782898        3
gene MDM2
error!!!! in row index 0
gene SOX21
gene ERCC5
gene GPC5
running file  226301-WG01_walk_3_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr8  26713603  26844206      +   9  574    130603       130603        0
1    chr8  26844207  53029099      +   4  575  26184892     26315495        1
2    chr8  53029100  53553469      +   6  576    524369     26839864        2
3    chr8  53553470  53628130      +  20  577     74660     26914524        3
4   chr12  47269996  47936867      +  20  250    666871     27581395        4
5   chr12  47936868  52328602      +   6  251   4391734     31973129        5
6   chr12  52328603  52778708      +   5  252    450105     32423234        6
7   chr12  52778709  52778837      +   9  253       128     32423362        7
8   chr12  52778838  52825602      +  13  254     46764     32470126        8
9   chr12  52825603  55278602      +   5  255   2452999     34923125        9
10  chr12  55278603  55278868      +  10  256       265     34923390       10
11  chr12  55278869  55359602      +  13  257     80733     35004123       11
12  chr12  55359603  55732602      +   8  258    372999     35377122       12
13  chr12  55732603  61209802      +   6  259   5477199     40854321       13
14  chr12  61209803  61394002      +   8  260    184199     41038520       14
15  chr12  61394003  63926482      +   6  261   2532479     43570999       15
16  chr12  63926483  64437802      +  22  262    511319     44082318       16
17  chr12  64437803  65774367      +  20  263   1336564     45418882       17
18  chr12  65774368  67382402      +  15  264   1608034     47026916       18
19  chr12  67382403  68633402      +  14  265   1250999     48277915       19
20  chr12  68633403  70204202      +  17  266   1570799     49848714       20
21  chr12  70204203  71158402      +  16  267    954199     50802913       21
22  chr12  71158403  71795379      +  15  268    636976     51439889       22
23  chr12  71796794  73055205      +  15  270   1258411     52698300       23
24  chr12  73055206  73152202      +  11  271     96996     52795296       24
25  chr12  73152203  91841802      +   7  272  18689599     71484895       25
26  chr12  91841803  92205602      +  11  273    363799     71848694       26
27  chr12  92205603  92866602      +  12  274    660999     72509693       27
28  chr12  92866603  92995802      +  19  275    129199     72638892       28
29  chr12  92995803  93028802      +  13  276     32999     72671891       29
30  chr12  93028803  93504602      +   7  277    475799     73147690       30
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_3_MDM2_containing_breakpoints.pdf
running file  226300-WG01_walk_4_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr16  86645403  87034002      -   7 -456    388599       388599        0
1  chr16  85147803  86645402      -   5 -455   1497599      1886198        1
2  chr16  84511455  85147802      -   6 -454    636347      2522545        2
3  chr12  47269996  47310195      -  38 -275     40199      2562744        3
4  chr12  34859203  47269995      -   6 -274  12410792     14973536        4
5  chr12  16305599  34859202      -   5 -273  18553603     33527139        5
6  chr12         1  16305598      -   6 -272  16305597     49832736        6
gene ARID2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 6
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226300-WG01_walk_2_MYCL_containing.fa
bed file       chr      start        end strand  cn    5       span  span_cumsum  \
0   chr10  120089603  120160302      +  13  161      70699        70699
1   chr10  120160303  120180884      +  11  162      20581        91280
2   chr10  120180885  120193790      +  13  163      12905       104185
3   chr10  120193791  120510037      +   9  164     316246       420431
4    chr1  163046848  163063870      +  12   47      17022       437453
5    chr1  193044092  193123477      +   8   97      79385       516838
6    chr1  193123478  193149057      +   5   98      25579       542417
7    chr1  193149058  194356387      +   4   99    1207329      1749746
8    chr1  194356388  194484802      +   9  100     128414      1878160
9    chr1  194484803  195184042      +  10  101     699239      2577399
10   chr1  195184043  195218841      +  16  102      34798      2612197
11   chr1  145462190  145771331      -  29   -4     309141      2921338
12   chr1  144426382  145462189      -  21   -3    1035807      3957145
13   chr1  125178603  144426381      -  17   -2   19247778     23204923
14   chr1          1  125178602      -   4   -1  125178601    148383524

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
gene CDC73

gene CDC73
gene CDC73
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226300-WG01_walk_2_MDM2_containing.fa
bed file       chr     start       end strand  cn    5    span  span_cumsum  bed_idx
0    chr8  18599003  19237763      +  11  856  638760       638760        0
1    chr8  19237764  19480422      +  15  857  242658       881418        1
2    chr8  19480423  19511846      +  26  858   31423       912841        2
3    chr8  19511847  19752838      +  22  859  240991      1153832        3
4    chr8  19752839  19807460      +  21  860   54621      1208453        4
..    ...       ...       ...    ...  ..  ...     ...          ...      ...
183  chr8  19752839  19807460      -  21 -860   54621     74197177      183
184  chr8  19511847  19752838      -  22 -859  240991     74438168      184
185  chr8  19480423  19511846      -  26 -858   31423     74469591      185
186  chr8  19237764  19480422      -  15 -857  242658     74712249      186
187  chr8  18599003  19237763      -  11 -856  638760     75351009      187

[188 rows x 9 columns]
gene WIF1
gene WIF1
gene HMGA2
gene HMGA2
gene MDM2
gene PTPRB
gene CREB3L1
gene CREB3L1
gene DDB2
gene CLP1
gene CTNND1
gene SDHAF2
gene FEN1
gene MEN1
gene MALAT1
gene CCND1
gene FADD
gene NUMA1
gene NUMA1
gene FADD
gene CCND1
gene MEN1
gene MALAT1
gene FEN1

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene SDHAF2
gene CLP1
gene CTNND1
gene DDB2
gene CREB3L1
gene CREB3L1
gene PTPRB
gene MDM2
gene HMGA2
gene HMGA2
gene WIF1
gene WIF1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226300-WG01_walk_3_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  126114603  145138636      -   5 -929  19024033     19024033        0
1   chr8  125363003  126114602      -   6 -928    751599     19775632        1
2   chr8  112877203  125363002      -   5 -927  12485799     32261431        2
3   chr8  110821803  112877202      -   6 -926   2055399     34316830        3
4   chr8  109125305  110821802      -   5 -925   1696497     36013327        4
5   chr8  109097903  109125304      -  12 -924     27401     36040728        5
6   chr4   88182210   88200832      +  11  651     18622     36059350        6
7   chr4  121831260  122072215      +  10  663    240955     36300305        7
8   chr4  122072216  128363667      +   3  664   6291451     42591756        8
9   chr4  128363668  129748015      +   4  665   1384347     43976103        9
10  chr4   88231561   88534469      +   6  653    302908     44279011       10
11  chr4   88534470   88539629      +  12  654      5159     44284170       11
12  chr4   88539630   89445249      +   5  655    905619     45189789       12
13  chr4   89445250   91379147      +   3  656   1933897     47123686       13
14  chr4   91379148   91672158      +   4  657    293010     47416696       14
15  chr4   91672159   93610002      +   3  658   1937843     49354539       15
16  chr4   93610003   97279602      +   4  659   3669599     53024138       16
17  chr4   97279603  104109755      +   3  660   6830152     59854290       17
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene RAD21
gene EXT1
gene CSMD3
gene CSMD3
gene IL2
gene FAT4
gene RAP1GDS1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226300-WG01_walk_1_MYCL_containing.fa
bed file       chr      start        end strand  cn    5       span  span_cumsum  \
0    chr5  126082603  126245977      +  23  720     163374       163374
1    chr5  126245978  126428002      +  26  721     182024       345398
2    chr5  126428003  126491007      +  29  722      63004       408402
3   chr15   54234478   54342802      +  17  381     108324       516726
4   chr15   54342803   54482884      +  19  382     140081       656807
..    ...        ...        ...    ...  ..  ...        ...          ...
87   chr1  145771332  145780186      -  20   -5       8854     29859714
88   chr1  145462190  145771331      -  29   -4     309141     30168855
89   chr1  144426382  145462189      -  21   -3    1035807     31204662
90   chr1  125178603  144426381      -  17   -2   19247778     50452440
91   chr1          1  125178602      -   4   -1  125178601    175631041

    bed_idx
0         0
1         1
2         2
3         3
4         4
..      ...
87       87
88       88
89       89
90       90
91       91

[92 rows x 9 columns]
gene C15orf65
gene MYO5A
gene MYO5A
gene SETDB1
gene MLLT11
gene ARNT
gene PBX1
gene DDR2
gene FCGR2B
gene SDHC
gene FCRL4
gene NTRK1
gene PRCC
gene LMNA
gene MUC1
gene TPM3
gene S100A7
gene SETDB1
gene MLLT11
gene ARNT
gene PDE4DIP
gene PDE4DIP

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene BCL9
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226302-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8  18312203   18822802      +   3  78     510599       510599        0
1  chr8  18822803   20675402      +   4  79    1852599      2363198        1
2  chr8  20675403   20956202      +   2  80     280799      2643997        2
3  chr8  20956203   21332002      +   4  81     375799      3019796        3
4  chr8  21332003  145138636      +   2  82  123806633    126826429        4
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226301-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  92866603  92995802      -  19 -275    129199       129199        0
1   chr12  92205603  92866602      -  12 -274    660999       790198        1
2   chr12  91841803  92205602      -  11 -273    363799      1153997        2
3   chr12  73152203  91841802      -   7 -272  18689599     19843596        3
4   chr12  73055206  73152202      -  11 -271     96996     19940592        4
..    ...       ...       ...    ...  ..  ...       ...          ...      ...
58  chr12  73055206  73152202      +  11  271     96996     87327534       58
59  chr12  73152203  91841802      +   7  272  18689599    106017133       59
60  chr12  91841803  92205602      +  11  273    363799    106380932       60
61  chr12  92205603  92866602      +  12  274    660999    107041931       61
62  chr12  92866603  92995802      +  19  275    129199    107171130       62

[63 rows x 9 columns]
gene BTG1
gene PTPRB
gene MDM2
gene HMGA2
gene WIF1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226303-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  32  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226300-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2         1  23728217      +   4  520  23728216     23728216        0
1  chr2  23728218  32866671      +   5  521   9138453     32866669        1
2  chr2  32870557  75256720      +   4  523  42386163     75252832        2
3  chr2  75256721  76223941      +   2  524    967220     76220052        3
4  chr2  76223942  94090203      +   4  525  17866261     94086313        4
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226300-WG01_walk_4_MYCL_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr1          1  125178602      +   4    1  125178601    125178601        0
1  chr1  125178603  144426381      +  17    2   19247778    144426379        1
2  chr1  144426382  145462189      +  21    3    1035807    145462186        2
3  chr1  145462190  145771331      +  29    4     309141    145771327        3
4  chr1  195184043  195218841      -  16 -102      34798    145806125        4
5  chr5  127521803  127549559      -  14 -734      27756    145833881        5
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running file  226300-WG01_walk_2_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr8  53553403  53553469      +   8  884        66           66        0
1    chr8  53553470  53628130      +  37  885     74660        74726        1
2   chr12  47269996  47310195      +  38  275     40199       114925        2
3   chr12  47310196  47435802      +  35  276    125606       240531        3
4   chr12  47435803  47659594      +  39  277    223791       464322        4
5   chr12  47659595  47807802      +  45  278    148207       612529        5
6   chr12  47807803  47891048      +  43  279     83245       695774        6
7   chr12  47891049  47936867      +  44  280     45818       741592        7
8   chr20  62231912  62234307      +  44  574      2395       743987        8
9   chr12  63926483  64307664      +  46  283    381181      1125168        9
10  chr12  64307665  64395546      +  48  284     87881      1213049       10
11  chr12  64395547  64397728      +  44  285      2181      1215230       11
12  chr12  64397729  65067825      +  40  286    670096      1885326       12
13  chr12  65067826  65308600      +  41  287    240774      2126100       13
14  chr12  65308601  65774367      +  42  288    465766      2591866       14
15   chr8  20073888  20157659      +  43  864     83771      2675637       15
16   chr8  20157660  20260453      +  41  865    102793      2778430       16
17   chr8  20260454  20675246      +  37  866    414792      3193222       17
18   chr8  21272359  21331994      -  36 -869     59635      3252857       18
19   chr8  20956090  21272358      -  33 -868    316268      3569125       19
20   chr8  20675247  20956089      -   4 -867    280842      3849967       20
21   chr8  20260454  20675246      -  37 -866    414792      4264759       21
22   chr8  20157660  20260453      -  41 -865    102793      4367552       22
23   chr8  20073888  20157659      -  43 -864     83771      4451323       23
24  chr12  65308601  65774367      -  42 -288    465766      4917089       24
25  chr12  65067826  65308600      -  41 -287    240774      5157863       25
26  chr12  64397729  65067825      -  40 -286    670096      5827959       26
27  chr12  64395547  64397728      -  44 -285      2181      5830140       27
28  chr12  64307665  64395546      -  48 -284     87881      5918021       28
29  chr12  63926483  64307664      -  46 -283    381181      6299202       29
30  chr20  62231912  62234307      -  44 -574      2395      6301597       30
31  chr12  47891049  47936867      -  44 -280     45818      6347415       31
32  chr12  47807803  47891048      -  43 -279     83245      6430660       32
33  chr12  47659595  47807802      -  45 -278    148207      6578867       33
34  chr12  47435803  47659594      -  39 -277    223791      6802658       34
35  chr12  47310196  47435802      -  35 -276    125606      6928264       35
36  chr12  47269996  47310195      -  38 -275     40199      6968463       36
37  chr12  34859203  47269995      -   6 -274  12410792     19379255       37
38  chr12  16305599  34859202      -   5 -273  18553603     37932858       38
39  chr12         1  16305598      -   6 -272  16305597     54238455       39
gene WIF1

gene WIF1
gene WIF1
gene WIF1
gene ARID2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 10
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226302-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  173659341  188545459      -   2 -10  14886118     14886118        0
1  chr1  171609696  173659340      -   3  -9   2049644     16935762        1
2  chr1  165974203  171609695      -   2  -8   5635492     22571254        2
3  chr1  164917448  165974202      -   3  -7   1056754     23628008        3
4  chr1  161902689  164917447      -   2  -6   3014758     26642766        4
5  chr1  161688005  161902688      -   2  -5    214683     26857449        5
6  chr1  121605203  161688004      -   3  -4  40082801     66940250        6
7  chr1   28769003  121605202      -   2  -3  92836199    159776449        7
8  chr1   26422403   28769002      -   3  -2   2346599    162123048        8
9  chr1          1   26422402      -   2  -1  26422401    188545449        9
gene TPR
gene ABL2
gene PRRX1
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene BCL9
gene ARNT
gene SDHC
gene PDE4DIP
gene MUC1
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene EPS15
gene ATP1A1
gene ARID1A
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226302-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226303-WG01_walk_1_KRAS_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  4  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226300-WG01_walk_6_MDM2_containing.fa
bed file       chr     start       end strand  cn    5     span  span_cumsum  bed_idx
0   chr20  34652603  35388602      +  13  557   735999       735999        0
1   chr20  35388603  36073202      +  11  558   684599      1420598        1
2   chr20  36073203  38983002      +  10  559  2909799      4330397        2
3   chr20  38983003  39872602      +   9  560   889599      5219996        3
4   chr20  39872603  42104575      +  10  561  2231972      7451968        4
5   chr20  42104576  42107265      +   5  562     2689      7454657        5
6   chr20  42107266  42124415      +  10  563    17149      7471806        6
7   chr20  42124416  42214202      +   5  564    89786      7561592        7
8   chr20  42214203  42644802      +   8  565   430599      7992191        8
9   chr20  42644803  43828248      +   6  566  1183445      9175636        9
10  chr20  43828249  43834352      +   9  567     6103      9181739       10
11  chr20  43834353  43846447      +  10  568    12094      9193833       11
12  chr20  43846448  50729567      +   6  569  6883119     16076952       12
13  chr20  50729568  50840833      +   8  570   111265     16188217       13
14  chr20  50840834  51288074      +  11  571   447240     16635457       14
15  chr20  51288075  58348986      +   7  572  7060911     23696368       15
16  chr20  58348987  62231911      +   6  573  3882924     27579292       16
17  chr20  62231912  62234307      +  44  574     2395     27581687       17
18  chr12  63926483  64307664      +  46  283   381181     27962868       18
19  chr12  64307665  64395546      +  48  284    87881     28050749       19
20  chr12  64395547  64397728      +  44  285     2181     28052930       20
21  chr12  64397729  65067825      +  40  286   670096     28723026       21
22  chr12  65067826  65308600      +  41  287   240774     28963800       22
23  chr12  65308601  65774367      +  42  288   465766     29429566       23
24  chr12  65774368  65907345      +  24  289   132977     29562543       24
25  chr12  65974377  66465130      +  24  291   490753     30053296       25
26  chr12  66465131  66627236      +  25  292   162105     30215401       26
27  chr12  66627237  67655402      +  19  293  1028165     31243566       27
28  chr12  67655403  67908402      +  17  294   252999     31496565       28
29  chr12  67908403  68615602      +  18  295   707199     32203764       29
30  chr12  68615603  68783349      +  20  296   167746     32371510       30
31  chr12  68783350  68991602      +  22  297   208252     32579762       31
32  chr12  68991603  69102585      +  19  298   110982     32690744       32
33  chr12  69102586  69443494      +  21  299   340908     33031652       33
34  chr12  69443495  70027891      +  24  300   584396     33616048       34
35  chr12  70027892  70227988      +  25  301   200096     33816144       35
36  chr12  70227989  70720202      +  21  302   492213     34308357       36
gene SRC
gene MAFB
gene TOP1
gene PLCG1
gene PTPRT
gene PTPRT
gene PTPRT
gene PTPRT
gene PTPRT
gene PTPRT
gene SDC4
gene SALL4
gene NFATC2
gene GNAS
gene SS18L1
gene WIF1
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_6_MDM2_containing_breakpoints.pdf
running file  226301-WG01_walk_5_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12   37238003   43439960      +   6  248   6201957      6201957        0
1   chr8  108005603  137011227      -   6 -590  29005624     35207581        1
2   chr8  106663403  108005602      -  15 -589   1342199     36549780        2
3   chr8  103513803  106663402      -  14 -588   3149599     39699379        3
4   chr8  103050403  103513802      -  19 -587    463399     40162778        4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene RSPO2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_5_MYC_containing_breakpoints.pdf
running file  226300-WG01_walk_2_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  126114603  145138636      -   5 -929  19024033     19024033        0
1   chr8  125363003  126114602      -   6 -928    751599     19775632        1
2   chr8  112877203  125363002      -   5 -927  12485799     32261431        2
3   chr8  110821803  112877202      -   6 -926   2055399     34316830        3
4   chr8  109125305  110821802      -   5 -925   1696497     36013327        4
5   chr8  109097903  109125304      -  12 -924     27401     36040728        5
6   chr4   88182210   88200832      +  11  651     18622     36059350        6
7   chr4   88200833   88231560      +   4  652     30727     36090077        7
8   chr4   88231561   88534469      +   6  653    302908     36392985        8
9   chr4   88534470   88539629      +  12  654      5159     36398144        9
10  chr4   88539630   89445249      +   5  655    905619     37303763       10
11  chr4   84297244   84522895      +   5  649    225651     37529414       11
12  chr4  105094621  121831259      +   3  662  16736638     54266052       12
13  chr4  121831260  122072215      +  10  663    240955     54507007       13
14  chr4  122072216  128363667      +   3  664   6291451     60798458       14
15  chr4  128363668  129748015      +   4  665   1384347     62182805       15
16  chr4  129748016  136260600      +   2  666   6512584     68695389       16
17  chr4  136260601  137501482      +   4  667   1240881     69936270       17
18  chr4  158815385  172512402      +   3  671  13697017     83633287       18
19  chr4  172512403  174113402      +   4  672   1600999     85234286       19
20  chr4  174113403  176689602      +   3  673   2576199     87810485       20
21  chr4  176689603  177883602      +   2  674   1193999     89004484       21
22  chr4  177883603  180511602      +   3  675   2627999     91632483       22
23  chr4  180511603  182478402      +   4  676   1966799     93599282       23
24  chr4  182478403  182498945      +   5  677     20542     93619824       24
25  chr4  184341080  186056802      +   4  682   1715722     95335546       25
gene MYC
gene RECQL4
gene NDRG1

gene FAM135B
gene RAD21
gene EXT1
gene CSMD3
gene CSMD3
gene TET2
gene LEF1
gene IL2
gene FAT4
gene CASP3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226300-WG01_walk_5_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  68615603  68783349      +  20  296    167746       167746        0
1   chr12  68783350  68991602      +  22  297    208252       375998        1
2   chr12  68991603  69102585      +  19  298    110982       486980        2
3   chr12  69102586  69443494      +  21  299    340908       827888        3
4   chr12  69443495  70027891      +  24  300    584396      1412284        4
5   chr12  70027892  70227988      +  25  301    200096      1612380        5
6   chr16  48878316  50025062      +   5  447   1146746      2759126        6
7   chr16  50025063  50267575      +   7  448    242512      3001638        7
8   chr16  50267576  51390895      +   7  449   1123319      4124957        8
9   chr16  51390896  78607602      +   4  450  27216706     31341663        9
10  chr16  78607603  80453403      +   5  451   1845800     33187463       10
11  chr16  80453404  81772435      +   4  452   1319031     34506494       11
12  chr16  81772436  84511454      +   3  453   2739018     37245512       12
13  chr16  84511455  85147802      +   6  454    636347     37881859       13
14  chr16  85147803  86645402      +   5  455   1497599     39379458       14
15  chr16  86645403  87034002      +   7  456    388599     39768057       15
16  chr16  87034003  87515402      +   6  457    481399     40249456       16
17  chr16  87515403  87942764      +   4  458    427361     40676817       17
18  chr16  87942765  88608802      +   6  459    666037     41342854       18
19  chr16  88608803  88844602      +   8  460    235799     41578653       19
gene MDM2
error!!!! in row index 0
gene CYLD
gene HERPUD1
gene CBFB
gene RFWD3
gene CTCF
gene CDH1
gene CDH11
gene ZFHX3
gene MAF
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_5_MDM2_containing_breakpoints.pdf
running file  226302-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8  21332003  145138636      -   2 -82  123806633    123806633        0
1  chr8  20956203   21332002      -   4 -81     375799    124182432        1
2  chr8  20675403   20956202      -   2 -80     280799    124463231        2
3  chr8  18822803   20675402      -   4 -79    1852599    126315830        3
4  chr8  18312203   18822802      -   3 -78     510599    126826429        4
5  chr8   7183603   18312202      -   2 -77   11128599    137955028        5
6  chr8   7001603    7183602      -   3 -76     181999    138137027        6
7  chr8   1393603    7001602      -   4 -75    5607999    143745026        7
8  chr8    364776    1393602      -   3 -74    1028826    144773852        8
9  chr8         1     336623      -   3 -72     336622    145110474        9
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene PCM1
gene ARHGEF10
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226302-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226301-WG01_walk_2_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  137011228  145138636      -   5 -591   8127408      8127408        0
1  chr8  108005603  137011227      -   6 -590  29005624     37133032        1
2  chr8  106663403  108005602      -  15 -589   1342199     38475231        2
3  chr8  103513803  106663402      -  14 -588   3149599     41624830        3
4  chr8  103050403  103513802      -  19 -587    463399     42088229        4
5  chr8   77266124  103050402      -   6 -586  25784278     67872507        5
6  chr8   67575640   77266123      -   7 -585   9690483     77562990        6
7  chr4  165074087  167199589      +   7  443   2125502     79688492        7
8  chr4  167199590  172509002      +   4  444   5309412     84997904        8
gene RECQL4
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene RSPO2
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene UBR5
gene CNBD1
gene NCOA2
gene PREX2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226300-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12         1  16305598      +   6  272  16305597     16305597        0
1   chr12  16305599  34859202      +   5  273  18553603     34859200        1
2   chr12  34859203  47269995      +   6  274  12410792     47269992        2
3   chr12  47269996  47310195      +  38  275     40199     47310191        3
4   chr12  47310196  47435802      +  35  276    125606     47435797        4
5   chr12  47435803  47659594      +  39  277    223791     47659588        5
6   chr12  47659595  47807802      +  45  278    148207     47807795        6
7   chr12  47807803  47891048      +  43  279     83245     47891040        7
8   chr12  47891049  47936867      +  44  280     45818     47936858        8
9   chr20  62231912  62234307      +  44  574      2395     47939253        9
10  chr12  63926483  64307664      +  46  283    381181     48320434       10
11  chr12  64307665  64395546      +  48  284     87881     48408315       11
12  chr12  64395547  64397728      +  44  285      2181     48410496       12
13  chr12  64397729  65067825      +  40  286    670096     49080592       13
14  chr12  65067826  65308600      +  41  287    240774     49321366       14
15  chr12  65308601  65774367      +  42  288    465766     49787132       15
16   chr8  20073888  20157659      +  43  864     83771     49870903       16
17   chr8  20157660  20260453      +  41  865    102793     49973696       17
18   chr8  20260454  20675246      +  37  866    414792     50388488       18
19   chr8  20675247  20956089      +   4  867    280842     50669330       19
20   chr8  20956090  21272358      +  33  868    316268     50985598       20
21   chr8  21272359  21331994      +  36  869     59635     51045233       21
22   chr8  20260454  20675246      -  37 -866    414792     51460025       22
23   chr8  20157660  20260453      -  41 -865    102793     51562818       23
24   chr8  20073888  20157659      -  43 -864     83771     51646589       24
25  chr12  65308601  65774367      -  42 -288    465766     52112355       25
26  chr12  65067826  65308600      -  41 -287    240774     52353129       26
27  chr12  64397729  65067825      -  40 -286    670096     53023225       27
28  chr12  64395547  64397728      -  44 -285      2181     53025406       28
29  chr12  64307665  64395546      -  48 -284     87881     53113287       29
30  chr12  63926483  64307664      -  46 -283    381181     53494468       30
31  chr20  62231912  62234307      -  44 -574      2395     53496863       31
32  chr12  47891049  47936867      -  44 -280     45818     53542681       32
33  chr12  47807803  47891048      -  43 -279     83245     53625926       33
34  chr12  47659595  47807802      -  45 -278    148207     53774133       34
35  chr12  47435803  47659594      -  39 -277    223791     53997924       35
36  chr12  47310196  47435802      -  35 -276    125606     54123530       36
37  chr12  47269996  47310195      -  38 -275     40199     54163729       37
38  chr12  34859203  47269995      -   6 -274  12410792     66574521       38
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
gene KRAS
gene ETNK1
gene PPFIBP1
gene ARID2
gene WIF1

gene WIF1
gene WIF1
gene WIF1
gene ARID2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226302-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2          1  125687802      +   2  41  125687801    125687801        0
1  chr2  125687803  130512403      +   3  42    4824600    130512401        1
2  chr2  130512404  131247802      +   2  43     735398    131247799        2
3  chr2  131247803  136149255      +   3  44    4901452    136149251        3
4  chr2  136149256  242193529      +   2  45  106044273    242193524        4
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene ERCC3
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226302-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226301-WG01_walk_5_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  123802003  133275309      -   6 -285   9473306      9473306
1   chr12  119792003  123802002      -   7 -284   4009999     13483305
2   chr12  114671603  119792002      -   6 -283   5120399     18603704
3   chr12  113568803  114671602      -   8 -282   1102799     19706503
4   chr12  112622003  113568802      -   6 -281    946799     20653302
5   chr12  111637203  112622002      -   8 -280    984799     21638101
6   chr12  111348003  111637202      -   7 -279    289199     21927300
7   chr12   93504603  111348002      -   6 -278  17843399     39770699
8   chr12   93028803   93504602      -   7 -277    475799     40246498
9   chr12   92995803   93028802      -  13 -276     32999     40279497
10  chr12   92866603   92995802      -  19 -275    129199     40408696
11  chr12   92205603   92866602      -  12 -274    660999     41069695
12  chr12   91841803   92205602      -  11 -273    363799     41433494
13  chr12   73152203   91841802      -   7 -272  18689599     60123093
14  chr12   73055206   73152202      -  11 -271     96996     60220089
15  chr12   71796794   73055205      -  15 -270   1258411     61478500
16  chr12   71158403   71795379      -  15 -268    636976     62115476
17  chr12   70204203   71158402      -  16 -267    954199     63069675
18  chr12   68633403   70204202      -  17 -266   1570799     64640474
19  chr12   67382403   68633402      -  14 -265   1250999     65891473
20  chr12   65774368   67382402      -  15 -264   1608034     67499507
21  chr12   64437803   65774367      -  20 -263   1336564     68836071
22  chr12   63926483   64437802      -  22 -262    511319     69347390
23  chr20   62231912   62234307      -  29 -400      2395     69349785
24  chr20   62231651   62231911      -  15 -399       260     69350045
25  chr11   69402307   70006602      +  14  225    604295     69954340

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
gene NCOR2
gene POLE
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene TBX3
gene TBX3
gene ALDH2
gene PTPN11
gene SH2B3
gene USP44
gene CHST11
gene BTG1
gene PTPRB
gene MDM2
gene HMGA2
gene WIF1
gene CCND1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_5_MDM2_containing_breakpoints.pdf
running file  226301-WG01_walk_4_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  137011228  145138636      -   5 -591   8127408      8127408        0
1  chr8  108005603  137011227      -   6 -590  29005624     37133032        1
2  chr8  106663403  108005602      -  15 -589   1342199     38475231        2
3  chr8  103513803  106663402      -  14 -588   3149599     41624830        3
4  chr8  103050403  103513802      -  19 -587    463399     42088229        4
gene RECQL4
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene RSPO2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_4_MYC_containing_breakpoints.pdf
running file  226300-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  92867403  93028802      -  19 -315    161399       161399        0
1   chr12  92328603  92867402      -  16 -314    538799       700198        1
2   chr12  91841803  92328602      -  15 -313    486799      1186997        2
3   chr12  73471203  91841802      -   7 -312  18370599     19557596        3
4   chr12  73152203  73471202      -   6 -311    318999     19876595        4
..    ...       ...       ...    ...  ..  ...       ...          ...      ...
66   chr3   2589603   2809002      -  10 -607    219399    102477410       66
67   chr3   2164635   2589602      -   8 -606    424967    102902377       67
68   chr8   6438424   6552602      +  26  833    114178    103016555       68
69   chr8   6552603   6585423      +  21  834     32820    103049375       69
70   chr8   6585424   6925602      +  22  835    340178    103389553       70

[71 rows x 9 columns]
gene BTG1
gene PTPRB
gene MDM2
gene HMGA2
gene HMGA2
gene WIF1
gene WIF1
gene BAP1
gene MLH1
gene CTNNB1
gene NCKIPSD
gene RHOA
gene MYD88
gene SETD2
gene PBRM1
gene CACNA1D
gene MITF
gene FHIT
gene FOXP1
gene CCR4
gene TGFBR2
gene XPC
gene FBLN2
gene RAF1
gene FBLN2
gene PPARG
gene VHL
gene FANCD2
gene SRGAP3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226301-WG01_walk_6_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  92866603  92995802      -  19 -275    129199       129199        0
1   chr12  92205603  92866602      -  12 -274    660999       790198        1
2   chr12  91841803  92205602      -  11 -273    363799      1153997        2
3   chr12  73152203  91841802      -   7 -272  18689599     19843596        3
4   chr12  73055206  73152202      -  11 -271     96996     19940592        4
5   chr12  71796794  73055205      -  15 -270   1258411     21199003        5
6   chr12  71795380  71796793      -   4 -269      1413     21200416        6
7   chr12  71158403  71795379      -  15 -268    636976     21837392        7
8   chr12  70204203  71158402      -  16 -267    954199     22791591        8
9   chr12  68633403  70204202      -  17 -266   1570799     24362390        9
10  chr12  67382403  68633402      -  14 -265   1250999     25613389       10
11  chr12  65774368  67382402      -  15 -264   1608034     27221423       11
12  chr12  64437803  65774367      -  20 -263   1336564     28557987       12
13  chr12  63926483  64437802      -  22 -262    511319     29069306       13
14  chr20  62231912  62234307      -  29 -400      2395     29071701       14
15  chr20  62231651  62231911      -  15 -399       260     29071961       15
16  chr20  54907603  62231650      -   6 -398   7324047     36396008       16
17  chr20  51288075  54907602      -   7 -397   3619527     40015535       17
18  chr20  50792803  51288074      -  15 -396    495271     40510806       18
19  chr20  47420403  50792802      -   7 -395   3372399     43883205       19
20  chr20  47257603  47420402      -  10 -394    162799     44046004       20
21  chr20  46118803  47257602      -   6 -393   1138799     45184803       21
22  chr20  43846448  46118802      -   7 -392   2272354     47457157       22
23  chr20  43828249  43846447      -  15 -391     18198     47475355       23
24  chr11  56025148  56142402      +  25  204    117254     47592609       24
25  chr11  56142403  56268402      +  16  205    125999     47718608       25
26  chr11  56268403  56477802      +  22  206    209399     47928007       26
27  chr11  56477803  56674402      +  31  207    196599     48124606       27
28  chr11  56674403  56722626      +  23  208     48223     48172829       28
29  chr11  56722627  57109802      +   5  209    387175     48560004       29
gene BTG1

gene PTPRB
gene MDM2
gene HMGA2
gene WIF1
gene GNAS
gene SS18L1
gene SALL4
gene NFATC2
gene SDC4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_6_MDM2_containing_breakpoints.pdf
running file  226301-WG01_walk_7_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr11  44775803  45842002      +  13  190   1066199      1066199        0
1   chr11  45842003  46085602      +   9  191    243599      1309798        1
2   chr11  46085603  46085999      +  13  192       396      1310194        2
3   chr11  46086000  46161680      +  17  193     75680      1385874        3
4   chr12  55278869  55359602      +  13  257     80733      1466607        4
5   chr12  55359603  55732602      +   8  258    372999      1839606        5
6   chr12  55732603  61209802      +   6  259   5477199      7316805        6
7   chr12  61209803  61394002      +   8  260    184199      7501004        7
8   chr12  61394003  63926482      +   6  261   2532479     10033483        8
9   chr12  63926483  64437802      +  22  262    511319     10544802        9
10  chr12  64437803  65774367      +  20  263   1336564     11881366       10
11  chr12  65774368  67382402      +  15  264   1608034     13489400       11
12  chr12  67382403  68633402      +  14  265   1250999     14740399       12
13  chr12  68633403  70204202      +  17  266   1570799     16311198       13
14  chr12  70204203  71158402      +  16  267    954199     17265397       14
15  chr12  71158403  71795379      +  15  268    636976     17902373       15
16  chr12  71795380  71796793      +   4  269      1413     17903786       16
17  chr12  71796794  73055205      +  15  270   1258411     19162197       17
18  chr12  73055206  73152202      +  11  271     96996     19259193       18
19  chr12  73152203  91841802      +   7  272  18689599     37948792       19
20  chr12  91841803  92205602      +  11  273    363799     38312591       20
21  chr12  92205603  92866602      +  12  274    660999     38973590       21
22  chr12  92866603  92995802      +  19  275    129199     39102789       22
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene ERBB3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_7_MDM2_containing_breakpoints.pdf
running file  226300-WG01_walk_4_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  110821803  112877202      +   6  926   2055399      2055399        0
1  chr8  112877203  125363002      +   5  927  12485799     14541198        1
2  chr8  125363003  126114602      +   6  928    751599     15292797        2
3  chr8  126114603  145138636      +   5  929  19024033     34316830        3
gene CSMD3
gene RAD21
gene EXT1
gene CSMD3
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_4_MYC_containing_breakpoints.pdf
running file  226303-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   91629002      +   2  15   91629001     91629001        0
1  chr2  91629003   92085802      +   3  16     456799     92085800        1
2  chr2  92085803  242193529      +   2  17  150107726    242193526        2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226301-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  63926483  64437802      -  22 -262    511319       511319        0
1  chr20  62231912  62234307      -  29 -400      2395       513714        1
2  chr12  47269996  47936867      -  20 -250    666871      1180585        2
3  chr12  43439961  47269995      -   6 -249   3830034      5010619        3
4  chr12  37238003  43439960      -   6 -248   6201957     11212576        4
5  chr12         1  37238002      -   5 -247  37238001     48450577        5
gene ARID2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 3
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226301-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  127158735  130525002      -  18 -361   3366267      3366267        0
1   chr2  126373033  127158734      -  22 -360    785701      4151968        1
2   chr2  122799397  126373032      -  12 -359   3573635      7725603        2
3   chr2  119628803  122799396      -  10 -358   3170593     10896196        3
4   chr2  114509438  119628802      -   4 -357   5119364     16015560        4
5   chr2  109917603  114509437      -   5 -356   4591834     20607394        5
6   chr2   93150426  109917602      -   4 -355  16767176     37374570        6
7   chr2   83062078   93150425      -   5 -354  10088347     47462917        7
8   chr2   54802347   83062077      -   4 -353  28259730     75722647        8
9   chr2   22028160   54802346      -   5 -352  32774186    108496833        9
10  chr2          1   22028159      -   4 -351  22028158    130524991       10
gene ERCC3
error!!!! in row index 0
gene PAX8
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
running file  226300-WG01_walk_3_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  73055206  73152202      -  14 -310     96996        96996        0
1   chr12  72298036  73055205      -  15 -309    757169       854165        1
2   chr12  72011666  72298035      -  11 -308    286369      1140534        2
3   chr12  71796794  72011665      -  13 -307    214871      1355405        3
4   chr12  71795380  71796793      -   7 -306      1413      1356818        4
5   chr12  71534946  71795379      -  13 -305    260433      1617251        5
6   chr12  70993403  71534945      -  20 -304    541542      2158793        6
7   chr12  70720203  70993402      -  18 -303    273199      2431992        7
8   chr12  70227989  70720202      -  21 -302    492213      2924205        8
9   chr12  70027892  70227988      -  25 -301    200096      3124301        9
10  chr12  69443495  70027891      -  24 -300    584396      3708697       10
11  chr12  69102586  69443494      -  21 -299    340908      4049605       11
12   chr8  20073888  20157659      -  43 -864     83771      4133376       12
13  chr12  65308601  65774367      -  42 -288    465766      4599142       13
14  chr12  65067826  65308600      -  41 -287    240774      4839916       14
15  chr12  64397729  65067825      -  40 -286    670096      5510012       15
16  chr12  64395547  64397728      -  44 -285      2181      5512193       16
17  chr12  64307665  64395546      -  48 -284     87881      5600074       17
18  chr12  63926483  64307664      -  46 -283    381181      5981255       18
19  chr20  62231912  62234307      -  44 -574      2395      5983650       19
20  chr12  47891049  47936867      -  44 -280     45818      6029468       20
21  chr12  47807803  47891048      -  43 -279     83245      6112713       21
22  chr12  47659595  47807802      -  45 -278    148207      6260920       22
23  chr12  47435803  47659594      -  39 -277    223791      6484711       23
24  chr12  47310196  47435802      -  35 -276    125606      6610317       24
25  chr12  47269996  47310195      -  38 -275     40199      6650516       25
26  chr12  34859203  47269995      -   6 -274  12410792     19061308       26
27  chr12  16305599  34859202      -   5 -273  18553603     37614911       27
28  chr12         1  16305598      -   6 -272  16305597     53920508       28
gene PTPRB

gene WIF1
gene WIF1
gene ARID2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 9
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226300-WG01_walk_3_KRAS_containing_breakpoints.pdf
running file  226303-WG01_walk_1_MDM2_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  4  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226301-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr22   49453130   50818468      -   6 -419   1365338      1365338
1   chr16   72064138   78961513      -   5 -330   6897375      8262713
2   chr16   60032345   72064137      -   4 -329  12031792     20294505
3   chr16   48990731   60032344      -   4 -328  11041613     31336118
4    chr8   58471538   58787179      +   6  581    315641     31651759
5    chr8   58787180   63053948      +   9  582   4266768     35918527
6    chr8   63053949   65955846      +   8  583   2901897     38820424
7    chr8   65955847   67575639      +   6  584   1619792     40440216
8    chr8   67575640   77266123      +   7  585   9690483     50130699
9    chr8   77266124  103050402      +   6  586  25784278     75914977
10   chr8  103050403  103513802      +  19  587    463399     76378376
11   chr8  103513803  106663402      +  14  588   3149599     79527975
12   chr8  106663403  108005602      +  15  589   1342199     80870174
13   chr8  108005603  137011227      +   6  590  29005624    109875798
14   chr8  137011228  145138636      +   5  591   8127408    118003206

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
gene RFWD3
gene ZFHX3
gene CBFB
gene CTCF
gene CDH1
gene CDH11
gene CYLD
gene HERPUD1
gene NCOA2
gene PREX2
gene HEY1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene RUNX1T1
gene UBR5
gene CNBD1
gene RSPO2
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226303-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226301-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  125093802      +   4  1  125093801    125093801        0
1  chr1  125093803  145780186      +  19  2   20686383    145780184        1
2  chr1  145780187  147095018      +  14  3    1314831    147095015        2
3  chr1  147095019  148242034      +  21  4    1147015    148242030        3
4  chr1  148242035  149806602      +  18  5    1564567    149806597        4
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene BCL9
gene PDE4DIP
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_2/226301-WG01_walk_2_MYCL_containing_breakpoints.pdf
running patient  3
running file  226305-WG01_walk_2_MDM2_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  131652003  133275309      -   2 -103   1623306      1623306        0
1  chr12   31959390  131652002      -   4 -102  99692612    101315918        1
2  chr12   28604795   31959389      -   5 -101   3354594    104670512        2
3  chr12   18969760   28604794      -   4 -100   9635034    114305546        3
4  chr12   18890411   18969759      -  11  -99     79348    114384894        4
5  chr12          1   18890410      -   4  -98  18890409    133275303        5
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226306-WG01_walk_4_MDM2_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12   38183203  119537214      +   4  106  81354011     81354011        0
1  chr12  119537215  133275309      +   3  107  13738094     95092105        1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226305-WG01_walk_2_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  74842803  75640802      -   7 -13    797999       797999        0
1   chr1  71151603  74842802      -   8 -12   3691199      4489198        1
2   chr1  70459403  71151602      -   7 -11    692199      5181397        2
3   chr1  70229803  70459402      -   6 -10    229599      5410996        3
4   chr1  69926203  70229802      -   7  -9    303599      5714595        4
5   chr1  68854003  69926202      -   8  -8   1072199      6786794        5
6   chr1  62292404  68854002      -   5  -7   6561598     13348392        6
7   chr1  62284037  62292403      -   6  -6      8366     13356758        7
8   chr1  42165170  62284036      -   5  -5  20118866     33475624        8
9   chr1  42164968  42165169      -   6  -4       201     33475825        9
10  chr1  17953403  42164967      -   4  -3  24211564     57687389       10
11  chr1   2843785  17953402      -   3  -2  15109617     72797006       11
12  chr1         1   2843784      -   4  -1   2843783     75640789       12
gene JAK1
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene RPL22
gene CASP9

gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene CAMTA1
gene PRDM16
gene TNFRSF14
gene SKI
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226306-WG01_walk_4_MYCN_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr17  83044153  83257441      -   5 -202    213288       213288        0
1   chr17  83034839  83044152      -   4 -201      9313       222601        1
2   chr17  82980427  83034838      -   6 -200     54411       277012        2
3   chr17  82335236  82980426      -   3 -199    645190       922202        3
4   chr17  82323468  82335235      -   6 -198     11767       933969        4
5   chr17  80640094  82323467      -   5 -197   1683373      2617342        5
6   chr17  80630099  80640093      -   6 -196      9994      2627336        6
7   chr17  80401994  80630098      -   5 -195    228104      2855440        7
8   chr17  80245945  80401993      -   3 -194    156048      3011488        8
9   chr17  80185759  80245944      -   5 -193     60185      3071673        9
10  chr17  76964383  80185758      -   3 -192   3221375      6293048       10
11  chr17  75297586  76964382      -   5 -191   1666796      7959844       11
12  chr17  74065242  75297585      -   3 -190   1232343      9192187       12
13  chr17  73479764  74065241      -   6 -189    585477      9777664       13
14  chr17  73447944  73479763      -   3 -188     31819      9809483       14
15  chr17  73402953  73447943      -   5 -187     44990      9854473       15
16  chr17  45585791  73402952      -   4 -186  27817161     37671634       16
17  chr17  45510603  45585790      -   1 -185     75187     37746821       17
18  chr17  39741709  45510602      -   2 -184   5768893     43515714       18
19   chr2  16371803  23809681      -   5 -238   7437878     50953592       19
20   chr2  13499003  16371802      -   4 -237   2872799     53826391       20
21   chr2  12483003  13499002      -   5 -236   1015999     54842390       21
22   chr2   8700003  12483002      -   4 -235   3782999     58625389       22
23   chr2   6377603   8700002      -   5 -234   2322399     60947788       23
24   chr2    163003   6377602      -   4 -233   6214599     67162387       24
25   chr2         1    163002      -   5 -232    163001     67325388       25
gene ASPSCR1
gene RNF213
gene CANT1
gene SEPT9
gene H3F3B
gene SRSF2
gene RNF43
gene PPM1D
gene CD79B
gene DDX5
gene PRKAR1A
gene COL1A1
gene KAT7
gene SPOP
gene HLF
gene CLTC
gene BRIP1
gene AXIN2
gene MSI2
gene CCR7
gene RARA
gene ETV4
gene SMARCE1
gene STAT3
gene STAT5B
gene BRCA1
gene IKZF3
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_4_MYCN_containing_breakpoints.pdf
running file  226305-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr9  119068086  138394717      -   4 -445  19326631     19326631        0
1   chr9  105792403  119068085      -   5 -444  13275682     32602313        1
2   chr9  104534203  105792402      -   4 -443   1258199     33860512        2
3   chr9  100795403  104534202      -   5 -442   3738799     37599311        3
4   chr9  100086003  100795402      -   4 -441    709399     38308710        4
5   chr9  100077969  100086002      -   5 -440      8033     38316743        5
6   chr9  100006680  100077968      -   6 -439     71288     38388031        6
7   chr9   98303203  100006679      -   5 -438   1703476     40091507        7
8   chr9   97819203   98303202      -   4 -437    483999     40575506        8
9   chr9   97290603   97819202      -   5 -436    528599     41104105        9
10  chr9   96252203   97290602      -   4 -435   1038399     42142504       10
11  chr9   94773203   96252202      -   5 -434   1478999     43621503       11
12  chr9   93980203   94773202      -   4 -433    792999     44414502       12
13  chr9   93449203   93980202      -   5 -432    530999     44945501       13
14  chr9   91498803   93449202      -   4 -431   1950399     46895900       14
15  chr9   88720403   91498802      -   5 -430   2778399     49674299       15
16  chr9   87939803   88720402      -   4 -429    780599     50454898       16
17  chr9   45509203   87939802      -   5 -428  42430599     92885497       17
18  chr9   42684803   45509202      -   4 -427   2824399     95709896       18
19  chr9   39824604   42684802      -   5 -426   2860198     98570094       19
20  chr9   25543425   39824603      -   6 -425  14281178    112851272       20
21  chr2  113374495  134477351      -   5 -213  21102856    133954128       21
22  chr2  110321403  113374494      -   6 -212   3053091    137007219       22
23  chr2   48624203  110321402      -   5 -211  61697199    198704418       23
24  chr2   37663926   48624202      -   4 -210  10960276    209664694       24
25  chr2    1107003   37663925      -   5 -209  36556922    246221616       25
26  chr2     162003    1107002      -   4 -208    944999    247166615       26
27  chr2          1     162002      -   5 -207    162001    247328616       27
gene SET
gene RALGDS
gene BRD3
gene NOTCH1
gene CNTRL
gene PPP6C
gene ABL1
gene NUP214
gene TSC1
gene FNBP1
gene KLF4
gene TNC
gene TAL2
gene NR4A3
gene XPA
gene PTCH1
gene FANCC
gene OMD
gene WNK2
gene SYK
gene GNAQ
gene FANCG
gene PAX5
gene ERCC3
gene PAX8
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226307-WG01_walk_2_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  79963973  86909402      -   7 -166   6945429      6945429        0
1   chr2  79231340  79963972      -   6 -165    732632      7678061        1
2   chr2  77810818  79231339      -   7 -164   1420521      9098582        2
3   chr2  74966058  77810817      -   6 -163   2844759     11943341        3
4   chr2  64429807  74966057      -   7 -162  10536250     22479591        4
5   chr2  62651347  64429806      -   8 -161   1778459     24258050        5
6   chr2  61692870  62651346      -   8 -160    958476     25216526        6
7   chr2  61692478  61692869      -   9 -159       391     25216917        7
8   chr2  61374044  61692477      -  10 -158    318433     25535350        8
9   chr2  48592875  61374043      -   7 -157  12781168     38316518        9
10  chr2  45129718  48592874      -   7 -156   3463156     41779674       10
11  chr2  42446588  45129717      -   8 -155   2683129     44462803       11
12  chr2  27074998  42446587      -   7 -154  15371589     59834392       12
13  chr2  24746895  27074997      -   8 -153   2328102     62162494       13
14  chr2  23736941  24746894      -   9 -152   1009953     63172447       14
15  chr2  23630497  23736940      -   6 -151    106443     63278890       15
16  chr2  11862888  23630496      -   6 -150  11767608     75046498       16
17  chr2   7005124  11862887      -   7 -149   4857763     79904261       17
18  chr2   5390639   7005123      -   6 -148   1614484     81518745       18
19  chr2   3531403   5390638      -   6 -147   1859235     83377980       19
20  chr2         1   3531402      -   5 -146   3531401     86909381       20
gene CTNNA2
error!!!! in row index 0
gene CTNNA2
gene PCBP1
gene DCTN1
gene XPO1
gene BCL11A
gene REL
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene ASXL2
gene NCOA1
gene DNMT3A
gene WDCP
gene NCOA1
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226307-WG01_walk_4_MYCL_containing.fa
bed file      chr     start       end strand  cn    5     span  span_cumsum  bed_idx
0   chr1  31505603  37341310      +   7   12  5835707      5835707        0
1   chr1  37341311  40889248      +   8   13  3547937      9383644        1
2   chr1  40889249  44748962      +   7   14  3859713     13243357        2
3   chr1  44748963  53773043      +   8   15  9024080     22267437        3
4   chr1  53773044  61337067      +   7   16  7564023     29831460        4
5   chr4  32659466  32712316      -   8 -283    52850     29884310        5
6   chr4  26597555  32659465      -   7 -282  6061910     35946220        6
7   chr4  25690706  26597554      -   8 -281   906848     36853068        7
8   chr1  40889249  44748962      -   7  -14  3859713     40712781        8
9   chr1  37341311  40889248      -   8  -13  3547937     44260718        9
10  chr1  31505603  37341310      -   7  -12  5835707     50096425       10
gene LCK

gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene MPL
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
running file  226308-WG01_walk_3_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  94947846  94948398      -   9 -37       552          552        0
1   chr1  93145769  94947845      -   5 -36   1802076      1802628        1
2   chr1  93145122  93145768      -   6 -35       646      1803274        2
3   chr1  92297137  93145121      -   7 -34    847984      2651258        3
4   chr1  90318677  92297136      -   5 -33   1978459      4629717        4
5   chr1  88419270  90318676      -   6 -32   1899406      6529123        5
6   chr1  86886555  88419269      -   5 -31   1532714      8061837        6
7   chr1  86508503  86886554      -   6 -30    378051      8439888        7
8   chr1  70491339  86508502      -   5 -29  16017163     24457051        8
9   chr1  60382930  70491338      -   5 -28  10108408     34565459        9
10  chr1  54825057  60382929      -   4 -27   5557872     40123331       10
11  chr1  52578778  54825056      -   4 -26   2246278     42369609       11
12  chr1  50618395  52578777      -   6 -25   1960382     44329991       12
13  chr1  46318883  50618394      -   4 -24   4299511     48629502       13
14  chr1  44214995  46318882      -   6 -23   2103887     50733389       14
15  chr1  40727723  44214994      -   4 -22   3487271     54220660       15
16  chr1  40326922  40727722      -   6 -21    400800     54621460       16
17  chr1  36109616  40326921      -   4 -20   4217305     58838765       17
18  chr1  35054028  36109615      -   6 -19   1055587     59894352       18
19  chr1  32610429  35054027      -   4 -18   2443598     62337950       19
20  chr1  32459739  32610428      -   6 -17    150689     62488639       20
21  chr1  31504403  32459738      -   5 -16    955335     63443974       21
gene RPL5
gene BCL10
gene FUBP1
gene JAK1
gene JUN
gene CDKN2C
gene EPS15
gene STIL
gene TAL1
gene MUTYH
gene MPL
gene MYCL
gene THRAP3
gene CSF3R
gene SFPQ
gene LCK
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226308-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226305-WG01_walk_3_MYCN_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12          1   18890410      +   4   98  18890409     18890409
1   chr12   18890411   18969759      +  11   99     79348     18969757
2    chr2  137791847  137792983      -  10 -217      1136     18970893
3    chr2  137649003  137791846      -   3 -216    142843     19113736
4    chr2  135588799  137649002      -   6 -215   2060203     21173939
5    chr2  134477352  135588798      -   2 -214   1111446     22285385
6    chr2  113374495  134477351      -   5 -213  21102856     43388241
7    chr2  110321403  113374494      -   6 -212   3053091     46441332
8    chr2   48624203  110321402      -   5 -211  61697199    108138531
9    chr2   37663926   48624202      -   4 -210  10960276    119098807
10   chr2    1107003   37663925      -   5 -209  36556922    155655729
11   chr2     162003    1107002      -   4 -208    944999    156600728
12   chr2          1     162002      -   5 -207    162001    156762729

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
gene CXCR4
gene ERCC3
gene PAX8
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226307-WG01_walk_3_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr1  146957203  148527802      +   7   52   1570599      1570599        0
1   chr1  148527803  149131202      +   5   53    603399      2173998        1
2   chr1  149131203  149152402      +   2   54     21199      2195197        2
3   chr1  149152403  149876402      +   6   55    723999      2919196        3
4   chr1  149876403  151748768      +  10   56   1872365      4791561        4
5   chr1  151748769  153701009      +   7   57   1952240      6743801        5
6   chr1  153701010  154357149      +  10   58    656139      7399940        6
7   chr1  154357150  155122252      +   8   59    765102      8165042        7
8   chr2   61374044   61692477      +  10  158    318433      8483475        8
9   chr2   61692478   61692869      -   9 -159       391      8483866        9
10  chr2   61374044   61692477      -  10 -158    318433      8802299       10
11  chr2   48592875   61374043      -   7 -157  12781168     21583467       11
12  chr2   45129718   48592874      -   7 -156   3463156     25046623       12
13  chr2   42446588   45129717      -   8 -155   2683129     27729752       13
14  chr2   27074998   42446587      -   7 -154  15371589     43101341       14
15  chr2   24746895   27074997      -   8 -153   2328102     45429443       15
16  chr2   23736941   24746894      -   9 -152   1009953     46439396       16
17  chr2   23630497   23736940      -   6 -151    106443     46545839       17
18  chr2   11862888   23630496      -   6 -150  11767608     58313447       18
19  chr2    7005124   11862887      -   7 -149   4857763     63171210       19
20  chr2    5390639    7005123      -   6 -148   1614484     64785694       20
21  chr2    3531403    5390638      -   6 -147   1859235     66644929       21
gene BCL9
gene PDE4DIP
gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
gene TPM3
gene XPO1
gene XPO1
gene BCL11A
gene REL
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene ASXL2
gene NCOA1
gene DNMT3A
gene WDCP
gene NCOA1
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226305-WG01_walk_1_KRAS_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  131652003  133275309      -   2 -103   1623306      1623306        0
1  chr12   31959390  131652002      -   4 -102  99692612    101315918        1
2  chr12   28604795   31959389      -   5 -101   3354594    104670512        2
3  chr12   18969760   28604794      -   4 -100   9635034    114305546        3
4  chr12   18890411   18969759      -  11  -99     79348    114384894        4
5  chr12          1   18890410      -   4  -98  18890409    133275303        5
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226305-WG01_walk_4_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  17953403  42164967      +   4  3  24211564     24211564        0
1  chr1  42164968  42165169      +   6  4       201     24211765        1
2  chr1  42165170  62284036      +   5  5  20118866     44330631        2
3  chr1  62284037  62292403      +   6  6      8366     44338997        3
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
running file  226306-WG01_walk_1_MYC_containing.fa

bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  144896003  145138636      -   6 -465    242633       242633        0
1   chr8  142832603  144896002      -   7 -464   2063399      2306032        1
2   chr8  140122003  142832602      -   6 -463   2710599      5016631        2
3   chr8  137805403  140122002      -   5 -462   2316599      7333230        3
4   chr8  136077003  137805402      -   6 -461   1728399      9061629        4
5   chr8  134814803  136077002      -   4 -460   1262199     10323828        5
6   chr8  130363725  134814802      -   5 -459   4451077     14774905        6
7   chr8  130221003  130308350      -   5 -457     87347     14862252        7
8   chr8   45941403  130221002      -   4 -456  84279599     99141851        8
9   chr8   42172618   45941402      -   3 -455   3768784    102910635        9
10  chr8   34829684   42172617      -   4 -454   7342933    110253568       10
11  chr8   34826522   34829683      -   6 -453      3161    110256729       11
12  chr8   34815228   34826521      -   5 -452     11293    110268022       12
13  chr8   34486604   34815227      -   6 -451    328623    110596645       13
14  chr8   34380430   34486603      -   4 -450    106173    110702818       14
15  chr8   34357451   34380429      -   5 -449     22978    110725796       15
16  chr8   29890112   34357450      -   4 -448   4467338    115193134       16
17  chr8   29887545   29890111      -   5 -447      2566    115195700       17
18  chr8   27067177   27411608      -   5 -444    344431    115540131       18
19  chr8   26787859   27067176      -   6 -443    279317    115819448       19
20  chr8   26754952   26787858      -   5 -442     32906    115852354       20
21  chr8   21514753   26754951      -   4 -441   5240198    121092552       21
22  chr8   21510555   21514752      -   6 -440      4197    121096749       22
23  chr8   21505349   21510554      +   4  439      5205    121101954       23
24  chr8   21510555   21514752      +   6  440      4197    121106151       24
25  chr8   21514753   26754951      +   4  441   5240198    126346349       25
26  chr8   26754952   26787858      +   5  442     32906    126379255       26
27  chr8   26787859   27067176      +   6  443    279317    126658572       27
28  chr8   27067177   27411608      +   5  444    344431    127003003       28
29  chr8   27411609   28998015      +   4  445   1586406    128589409       29
gene RECQL4
gene FAM135B
gene NDRG1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene IKBKB
gene HOOK3
gene FGFR1
gene NSD3
gene ANK1
gene KAT6A
gene LEPROTL1
gene WRN
gene NRG1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226305-WG01_walk_2_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8   33790203   34243602      +   4  413    453399       453399        0
1  chr8   34243603   34486603      +   5  414    243000       696399        1
2  chr8   34486604   34829683      +   6  415    343079      1039478        2
3  chr8   34829684   37878202      +   4  416   3048518      4087996        3
4  chr8   37878203   38267202      +   3  417    388999      4476995        4
5  chr8   38267203   43969802      +   4  418   5702599     10179594        5
6  chr8   43969803  130308350      +   5  419  86338547     96518141        6
7  chr8  130363725  145138636      +   5  421  14774911    111293052        7
gene FGFR1
gene IKBKB
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226306-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  31959390  34783002      -   4 -104   2823612      2823612        0
1  chr12  31896839  31959389      -   2 -103     62550      2886162        1
2  chr12  29091075  31896838      -   4 -102   2805763      5691925        2
3  chr12  28604795  29091074      -   5 -101    486279      6178204        3
4  chr12  18969760  28604794      -   3 -100   9635034     15813238        4
5  chr12  18890411  18969759      -  10  -99     79348     15892586        5
6  chr12  18888730  18890410      -   3  -98      1680     15894266        6
7  chr12  18688754  18888729      -   5  -97    199975     16094241        7
8  chr12     60764  18688753      -   3  -96  18627989     34722230        8
9  chr12         1     60763      -   4  -95     60762     34782992        9
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 5
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226305-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  130363725  145138636      -   5 -421  14774911     14774911        0
1   chr8   43969803  130308350      -   5 -419  86338547    101113458        1
2   chr8   38267203   43969802      -   4 -418   5702599    106816057        2
3   chr8   37878203   38267202      -   3 -417    388999    107205056        3
4   chr8   34829684   37878202      -   4 -416   3048518    110253574        4
5   chr8   34486604   34829683      -   6 -415    343079    110596653        5
6   chr8   34243603   34486603      -   5 -414    243000    110839653        6
7   chr8   33790203   34243602      -   4 -413    453399    111293052        7
8   chr8   33357403   33790202      -   3 -412    432799    111725851        8
9   chr8   31100203   33357402      -   4 -411   2257199    113983050        9
10  chr8   30048803   31100202      -   3 -410   1051399    115034449       10
11  chr8   29173803   30048802      -   4 -409    874999    115909448       11
12  chr8   29076556   29173802      -   6 -408     97246    116006694       12
13  chr8   28744603   29076555      -   4 -407    331952    116338646       13
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FGFR1
gene IKBKB
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene WRN
gene NRG1
gene LEPROTL1
gene WRN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226306-WG01_walk_2_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  103469197  107539316      -   5 -36   4070119      4070119        0
1   chr1   96038036  103469196      -   4 -35   7431160     11501279        1
2   chr1   95990882   96038035      -   6 -34     47153     11548432        2
3   chr1   94786711   95990881      -   4 -33   1204170     12752602        3
4   chr1   94262871   94786710      -   5 -32    523839     13276441        4
5   chr1   90765003   94262870      -   6 -31   3497867     16774308        5
6   chr1   88983203   90765002      -   7 -30   1781799     18556107        6
7   chr1   88492803   88983202      -   6 -29    490399     19046506        7
8   chr1   87049603   88492802      -   7 -28   1443199     20489705        8
9   chr1   84465203   87049602      -   6 -27   2584399     23074104        9
10  chr1   81999003   84465202      -   7 -26   2466199     25540303       10
11  chr1   81175803   81999002      -   6 -25    823199     26363502       11
12  chr1   78097803   81175802      -   7 -24   3077999     29441501       12
13  chr1   77205603   78097802      -   6 -23    892199     30333700       13
14  chr1   76130203   77205602      -   7 -22   1075399     31409099       14
15  chr1   75387603   76130202      -   6 -21    742599     32151698       15
16  chr1   71015403   75387602      -   7 -20   4372199     36523897       16
17  chr1   68854041   71015402      -   6 -19   2161361     38685258       17
18  chr1   62325932   68854040      -   4 -18   6528108     45213366       18
19  chr1   62312930   62325931      -   6 -17     13001     45226367       19
20  chr1   45319593   45325496      +   6   4      5903     45232270       20
21  chr1   45325497   45426514      +   6   5    101017     45333287       21
22  chr1   45426515   45637202      +   4   6    210687     45543974       22
23  chr1   45637203   47120202      +   6   7   1482999     47026973       23
24  chr1   47120203   47359037      +   4   8    238834     47265807       24
25  chr1   47359038   47362503      +   6   9      3465     47269272       25
26  chr1   47362504   55573314      +   4  10   8210810     55480082       26
27  chr1   55573315   55738738      +   5  11    165423     55645505       27
28  chr1   55738739   58707802      +   4  12   2969063     58614568       28
29  chr1   58707803   60795068      +   5  13   2087265     60701833       29
30  chr1   60795069   61659802      +   4  14    864733     61566566       30
31  chr1   61659803   62284036      +   3  15    624233     62190799       31
32  chr1   62284037   62312929      +   4  16     28892     62219691       32
33  chr1   62312930   62325931      +   6  17     13001     62232692       33
34  chr1   45325497   45426514      -   6  -5    101017     62333709       34
35  chr1   45319593   45325496      -   6  -4      5903     62339612       35
36  chr1   17956803   45319592      -   4  -3  27362789     89702401       36
gene RPL5
gene BCL10

gene FUBP1
gene JAK1
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene MUTYH
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MDS2
gene ARID1A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226306-WG01_walk_3_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr2  143404140  143408402      -   5 -257      4262         4262
1    chr2  142490521  142525702      +   4  253     35181        39443
2    chr9   23404481   24564407      +   4  473   1159926      1199369
3    chr2  137648603  137649000      -   4 -245       397      1199766
4    chr2  135588799  137648602      -   5 -244   2059803      3259569
5    chr2  134751478  135588798      -   2 -243    837320      4096889
6   chr12   38183203  119537214      -   4 -106  81354011     85450900
7   chr12   34783003   38183202      -   3 -105   3400199     88851099
8   chr12   31959390   34783002      -   4 -104   2823612     91674711
9   chr12   28604795   29091074      +   5  101    486279     92160990
10  chr12   29091075   31896838      +   4  102   2805763     94966753
11  chr12   18688754   18888729      -   5  -97    199975     95166728

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
gene CXCR4
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
running file  226306-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  119537215  133275309      -   3 -107  13738094     13738094
1   chr12   38183203  119537214      -   4 -106  81354011     95092105
2   chr12   34783003   38183202      -   3 -105   3400199     98492304
3   chr12   31959390   34783002      -   4 -104   2823612    101315916
4   chr12   31896839   31959389      -   2 -103     62550    101378466
5   chr12   29091075   31896838      -   4 -102   2805763    104184229
6   chr12   28604795   29091074      -   5 -101    486279    104670508
7   chr12   18969760   28604794      -   3 -100   9635034    114305542
8   chr12   18890411   18969759      -  10  -99     79348    114384890
9    chr2  142156278  142438896      +   9  251    282618    114667508
10   chr9   25070702   25493404      -   9 -475    422702    115090210
11   chr2  143763362  143827638      +  10  259     64276    115154486
12   chr2  143076825  143149030      +   9  255     72205    115226691
13   chr2  144016087  144225002      +   9  261    208915    115435606
14   chr2  144225003  146116603      +   3  262   1891600    117327206

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226306-WG01_walk_4_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  136077003  137805402      -   6 -461   1728399      1728399        0
1  chr8  134814803  136077002      -   4 -460   1262199      2990598        1
2  chr8  130363725  134814802      -   5 -459   4451077      7441675        2
3  chr8  130221003  130308350      -   5 -457     87347      7529022        3
4  chr8   45941403  130221002      -   4 -456  84279599     91808621        4
gene NDRG1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
running file  226307-WG01_walk_2_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr1   8253578  12755602      -   7  -5   4502024      4502024        0
1   chr1  84058947  84509620      -   9 -25    450673      4952697        1
2   chr1  70432459  84058946      -   8 -24  13626487     18579184        2
3   chr1  69297423  70432458      -   9 -23   1135035     19714219        3
4   chr1  69143313  69297422      -   7 -22    154109     19868328        4
5   chr1  69000283  69143312      -   8 -21    143029     20011357        5
6   chr1  67422523  69000282      -   7 -20   1577759     21589116        6
7   chr1  64603212  67422522      -   8 -19   2819310     24408426        7
8   chr1  62833866  64603211      -   7 -18   1769345     26177771        8
9   chr1  61337068  62833865      -   8 -17   1496797     27674568        9
10  chr1  53773044  61337067      -   7 -16   7564023     35238591       10
11  chr1  44748963  53773043      -   8 -15   9024080     44262671       11
12  chr1  40889249  44748962      -   7 -14   3859713     48122384       12
13  chr1  37341311  40889248      -   8 -13   3547937     51670321       13
14  chr1  31505603  37341310      -   7 -12   5835707     57506028       14
gene MTOR
gene FUBP1
gene JAK1
gene JUN
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene MPL
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226307-WG01_walk_3_MYCL_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr1  37341311  40889248      +   8   13   3547937      3547937        0
1   chr1  40889249  44748962      +   7   14   3859713      7407650        1
2   chr1  44748963  53773043      +   8   15   9024080     16431730        2
3   chr1  53773044  61337067      +   7   16   7564023     23995753        3
4   chr1  61337068  62833865      +   8   17   1496797     25492550        4
5   chr1  62833866  64603211      +   7   18   1769345     27261895        5
6   chr1  64603212  67422522      +   8   19   2819310     30081205        6
7   chr1  67422523  69000282      +   7   20   1577759     31658964        7
8   chr1  69000283  69143312      +   8   21    143029     31801993        8
9   chr1  69143313  69297422      +   7   22    154109     31956102        9
10  chr1  69297423  70432458      +   9   23   1135035     33091137       10
11  chr2  42446588  45129717      +   8  155   2683129     35774266       11
12  chr2  45129718  48592874      +   7  156   3463156     39237422       12
13  chr2  48592875  61374043      +   7  157  12781168     52018590       13
14  chr2  61374044  61692477      +  10  158    318433     52337023       14
15  chr2  61692478  61692869      +   9  159       391     52337414       15
16  chr2  61692870  62651346      +   8  160    958476     53295890       16
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
gene SIX2
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene BCL11A
gene REL
gene XPO1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226306-WG01_walk_3_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1     60763      +   4   95     60762        60762        0
1  chr12     60764  18688753      +   3   96  18627989     18688751        1
2  chr12  18688754  18888729      +   5   97    199975     18888726        2
3  chr12  29091075  31896838      -   4 -102   2805763     21694489        3
4  chr12  28604795  29091074      -   5 -101    486279     22180768        4
5  chr12  18969760  28604794      -   3 -100   9635034     31815802        5
6  chr12  18890411  18969759      -  10  -99     79348     31895150        6
7  chr12  18888730  18890410      -   3  -98      1680     31896830        7
8  chr12  18688754  18888729      -   5  -97    199975     32096805        8
gene PTPN6
gene CDKN1B
gene KDM5A

error!!!! in row index 2
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226306-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1   17956803   45319592      +   4   3  27362789     27362789        0
1   chr1   45319593   45325496      +   6   4      5903     27368692        1
2   chr1   45325497   45426514      +   6   5    101017     27469709        2
3   chr1   62312930   62325931      -   6 -17     13001     27482710        3
4   chr1   62284037   62312929      -   4 -16     28892     27511602        4
5   chr1   94262871   94786710      -   5 -32    523839     28035441        5
6   chr1   90765003   94262870      -   6 -31   3497867     31533308        6
7   chr1   88983203   90765002      -   7 -30   1781799     33315107        7
8   chr1   88492803   88983202      -   6 -29    490399     33805506        8
9   chr1   87049603   88492802      -   7 -28   1443199     35248705        9
10  chr1   84465203   87049602      -   6 -27   2584399     37833104       10
11  chr1   81999003   84465202      -   7 -26   2466199     40299303       11
12  chr1   81175803   81999002      -   6 -25    823199     41122502       12
13  chr1   78097803   81175802      -   7 -24   3077999     44200501       13
14  chr1   77205603   78097802      -   6 -23    892199     45092700       14
15  chr1   76130203   77205602      -   7 -22   1075399     46168099       15
16  chr1   75387603   76130202      -   6 -21    742599     46910698       16
17  chr1   71015403   75387602      -   7 -20   4372199     51282897       17
18  chr1   68854041   71015402      -   6 -19   2161361     53444258       18
19  chr1   47359038   47362503      -   6  -9      3465     53447723       19
20  chr1   95990882   96038035      +   6  34     47153     53494876       20
21  chr1   96038036  103469196      +   4  35   7431160     60926036       21
22  chr1  103469197  107539316      +   5  36   4070119     64996155       22
23  chr1  107539317  180483402      +   4  37  72944085    137940240       23
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MDS2
gene ARID1A
gene MUTYH
gene RPL5
gene BCL10
gene FUBP1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226305-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1   2843784      +   4  1   2843783      2843783        0
1  chr1   2843785  17953402      +   3  2  15109617     17953400        1
2  chr1  17953403  42164967      +   4  3  24211564     42164964        2
3  chr1  42164968  42165169      +   6  4       201     42165165        3
4  chr1  42165170  62284036      +   5  5  20118866     62284031        4
5  chr1  62284037  62292403      +   6  6      8366     62292397        5
6  chr1  62292404  68854002      +   5  7   6561598     68853995        6
7  chr1  68854003  69926202      +   8  8   1072199     69926194        7
8  chr1  69926203  70229802      +   7  9    303599     70229793        8
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JAK1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226305-WG01_walk_5_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  130363725  145138636      -   5 -421  14774911     14774911        0
1  chr8  130308351  130363724      -   2 -420     55373     14830284        1
2  chr8   43969803  130308350      -   5 -419  86338547    101168831        2
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
running file  226306-WG01_walk_3_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2          1     163002      +   5  232    163001       163001        0
1  chr2     163003    6377602      +   4  233   6214599      6377600        1
2  chr2    6377603    8700002      +   5  234   2322399      8699999        2
3  chr2    8700003   12483002      +   4  235   3782999     12482998        3
4  chr2   12483003   13499002      +   5  236   1015999     13498997        4
5  chr2   13499003   16371802      +   4  237   2872799     16371796        5
6  chr2   16371803   23809681      +   5  238   7437878     23809674        6
7  chr2   23809682   53398634      +   4  239  29588952     53398626        7
8  chr2   53400862  134477351      +   4  241  81076489    134475115        8
9  chr2  134477352  134751477      +   2  242    274125    134749240        9
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226306-WG01_walk_2_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  119537215  133275309      -   3 -107  13738094     13738094
1   chr12   38183203  119537214      -   4 -106  81354011     95092105
2   chr12   34783003   38183202      -   3 -105   3400199     98492304
3   chr12   31959390   34783002      -   4 -104   2823612    101315916
4   chr12   31896839   31959389      -   2 -103     62550    101378466
5   chr12   29091075   31896838      -   4 -102   2805763    104184229
6   chr12   28604795   29091074      -   5 -101    486279    104670508
7   chr12   18969760   28604794      -   3 -100   9635034    114305542
8   chr12   18890411   18969759      -  10  -99     79348    114384890
9    chr2  142156278  142438896      +   9  251    282618    114667508
10   chr9   25070702   25493404      -   9 -475    422702    115090210
11   chr2  143763362  143827638      +  10  259     64276    115154486
12   chr2  143076825  143149030      +   9  255     72205    115226691
13   chr2  144016087  144225002      +   9  261    208915    115435606
14   chr2  144225003  146116603      +   3  262   1891600    117327206

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226307-WG01_walk_5_MYCL_containing.fa
bed file      chr      start        end strand  cn    5     span  span_cumsum  bed_idx
0   chr1  122462773  122503003      -  43  -44    40230        40230        0
1   chr1  121742333  122462772      -  26  -43   720439       760669        1
2   chr1  121387803  121742332      -   9  -42   354529      1115198        2
3   chr1  120172403  121387802      -   5  -41  1215399      2330597        3
4   chr1  114051302  120172402      -   7  -40  6121100      8451697        4
5   chr1  113492829  114051301      -   9  -39   558472      9010169        5
6   chr1  111934671  113492828      -   8  -38  1558157     10568326        6
7   chr1  109445213  111934670      -   7  -37  2489457     13057783        7
8   chr1  108258203  109445212      -   8  -36  1187009     14244792        8
9   chr1  105915464  108258202      -   7  -35  2342738     16587530        9
10  chr1  103394930  105915463      -   7  -34  2520533     19108063       10
11  chr1   31064410   31500002      +   9   10   435592     19543655       11
12  chr1   31500003   31505602      +   1   11     5599     19549254       12
13  chr1   31505603   37341310      +   7   12  5835707     25384961       13
14  chr1   37341311   40889248      +   8   13  3547937     28932898       14
15  chr4   32659466   32712316      +   8  283    52850     28985748       15
16  chr4   32712317   38650602      +   7  284  5938285     34924033       16
17  chr4   38650603   39113880      +   9  285   463277     35387310       17
18  chr4   39113881   40817602      +  10  286  1703721     37091031       18
19  chr4   40817603   44891614      +   7  287  4074011     41165042       19
gene NRAS
gene TENT5C
gene TRIM33

gene NOTCH2
gene ATP1A1
gene RBM15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene N4BP2
gene RHOH
gene PHOX2B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_5_MYCL_containing_breakpoints.pdf
running file  226307-WG01_walk_1_MYCL_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  31505603   37341310      +   7  12   5835707      5835707        0
1   chr1  37341311   40889248      +   8  13   3547937      9383644        1
2   chr1  40889249   44748962      +   7  14   3859713     13243357        2
3   chr1  44748963   53773043      +   8  15   9024080     22267437        3
4   chr1  53773044   61337067      +   7  16   7564023     29831460        4
5   chr1  61337068   62833865      +   8  17   1496797     31328257        5
6   chr1  62833866   64603211      +   7  18   1769345     33097602        6
7   chr1  64603212   67422522      +   8  19   2819310     35916912        7
8   chr1  67422523   69000282      +   7  20   1577759     37494671        8
9   chr1  69000283   69143312      +   8  21    143029     37637700        9
10  chr1  69143313   69297422      +   7  22    154109     37791809       10
11  chr1  69297423   70432458      +   9  23   1135035     38926844       11
12  chr1  70432459   84058946      +   8  24  13626487     52553331       12
13  chr1  84058947   84509620      +   9  25    450673     53004004       13
14  chr1  84509621   84973287      +   8  26    463666     53467670       14
15  chr1  84973288   86199486      +   9  27   1226198     54693868       15
16  chr1  86199487   91427651      +   8  28   5228164     59922032       16
17  chr1  91427652   91793306      +   9  29    365654     60287686       17
18  chr1  91793307   93250563      +  10  30   1457256     61744942       18
19  chr1  93250564  103327802      +   7  31  10077238     71822180       19
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
gene FUBP1
gene BCL10
gene RPL5
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226305-WG01_walk_5_MYCN_containing.fa
bed file     chr    start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  1107003  37663925      -   5 -209  36556922     36556922        0
1  chr2   162003   1107002      -   4 -208    944999     37501921        1
2  chr2        1    162002      -   5 -207    162001     37663922        2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
running file  226306-WG01_walk_3_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  144896003  145138636      -   6 -465    242633       242633        0
1   chr8  142832603  144896002      -   7 -464   2063399      2306032        1
2   chr8  140122003  142832602      -   6 -463   2710599      5016631        2
3   chr8  137805403  140122002      -   5 -462   2316599      7333230        3
4   chr8  136077003  137805402      -   6 -461   1728399      9061629        4
5   chr8  134814803  136077002      -   4 -460   1262199     10323828        5
6   chr8  130363725  134814802      -   5 -459   4451077     14774905        6
7   chr8  130221003  130308350      -   5 -457     87347     14862252        7
8   chr8   45941403  130221002      -   4 -456  84279599     99141851        8
9   chr8   42172618   45941402      -   3 -455   3768784    102910635        9
10  chr8   34829684   42172617      -   4 -454   7342933    110253568       10
11  chr8   34826522   34829683      -   6 -453      3161    110256729       11
12  chr8   34815228   34826521      -   5 -452     11293    110268022       12
13  chr8   34486604   34815227      -   6 -451    328623    110596645       13
14  chr8   20078254   20148600      -   6 -434     70346    110666991       14
15  chr8   20068136   20078253      -   5 -433     10117    110677108       15
16  chr8   17907633   20068135      -   6 -432   2160502    112837610       16
17  chr8   17887606   17907632      -   8 -431     20026    112857636       17
gene RECQL4
gene FAM135B
gene NDRG1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene IKBKB
gene HOOK3
gene FGFR1
gene NSD3
gene ANK1
gene KAT6A
gene PCM1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226305-WG01_walk_4_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8   38267203   43969802      +   4  418   5702599      5702599        0
1  chr8   43969803  130308350      +   5  419  86338547     92041146        1
2  chr8  130363725  145138636      +   5  421  14774911    106816057        2
gene FGFR1
error!!!! in row index 0
gene IKBKB
gene NSD3
error!!!! in row index 2
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
running file  226308-WG01_walk_1_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  54791754  55551569      -   5 -139    759815       759815        0
1   chr2  48624203  54791753      -   4 -138   6167550      6927365        1
2   chr2  42119120  48624202      -   5 -137   6505082     13432447        2
3   chr2  40046323  42119119      -   4 -136   2072796     15505243        3
4   chr2  39040232  40046322      -   5 -135   1006090     16511333        4
5   chr2  38516847  39040231      -   6 -134    523384     17034717        5
6   chr2  36693768  38516846      -   5 -133   1823078     18857795        6
7   chr2  33305151  36693767      -   4 -132   3388616     22246411        7
8   chr2  32496089  33305150      -   5 -131    809061     23055472        8
9   chr2  31899027  32496088      -   6 -130    597061     23652533        9
10  chr2  28860042  31899026      -   4 -129   3038984     26691517       10
11  chr2  23783519  28860041      -   5 -128   5076522     31768039       11
12  chr2  23234707  23783518      -   3 -127    548811     32316850       12
13  chr2  10664708  23234706      -   4 -126  12569998     44886848       13
14  chr2   4197405  10664707      -   4 -125   6467302     51354150       14
15  chr2   2135280   4197404      -   3 -124   2062124     53416274       15
16  chr2         1   2135279      -   3 -123   2135278     55551552       16
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene STRN
gene BIRC6
gene BIRC6
gene ALK
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226308-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226306-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1   2843784      +   3  1   2843783      2843783        0
1  chr1   2843785  17956802      +   2  2  15113017     17956800        1
2  chr1  17956803  45319592      +   4  3  27362789     45319589        2
3  chr1  45319593  45325496      +   6  4      5903     45325492        3
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MDS2
gene ARID1A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226306-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2    6377603    8700002      +   5  234   2322399      2322399        0
1   chr2    8700003   12483002      +   4  235   3782999      6105398        1
2   chr2   12483003   13499002      +   5  236   1015999      7121397        2
3   chr2   13499003   16371802      +   4  237   2872799      9994196        3
4   chr2   16371803   23809681      +   5  238   7437878     17432074        4
5   chr2   23809682   53398634      +   4  239  29588952     47021026        5
6   chr2   53400862  134477351      +   4  241  81076489    128097515        6
7   chr2  134477352  134751477      +   2  242    274125    128371640        7
8   chr2  134751478  135588798      +   2  243    837320    129208960        8
9   chr2  135588799  137648602      +   5  244   2059803    131268763        9
10  chr2  137648603  137649000      +   4  245       397    131269160       10
11  chr9   23404481   24564407      -   4 -473   1159926    132429086       11
12  chr9   23377803   23404480      -   2 -472     26677    132455763       12
13  chr9   23054235   23377802      -   4 -471    323567    132779330       13
14  chr9   21052003   23054234      -   2 -470   2002231    134781561       14
15  chr9   21020803   21052002      -   8 -469     31199    134812760       15
16  chr9   16286409   21020802      -   2 -468   4734393    139547153       16
17  chr9   16176933   16286408      -   4 -467    109475    139656628       17
18  chr9          1   16176932      -   2 -466  16176931    155833559       18
gene MYCN

gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
gene CXCR4
gene CDKN2A
gene MLLT3
gene CD274
gene PDCD1LG2
gene JAK2
gene NFIB
gene PSIP1
gene PTPRD
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226306-WG01_walk_2_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8   17887606   17907632      +   8  431     20026        20026        0
1   chr8   17907633   20068135      +   6  432   2160502      2180528        1
2   chr8   20068136   20078253      +   5  433     10117      2190645        2
3   chr8   20078254   20148600      +   6  434     70346      2260991        3
4   chr8   20148601   20171555      +   4  435     22954      2283945        4
5   chr8   20171556   21475725      +   6  436   1304169      3588114        5
6   chr8   21475726   21504765      +   4  437     29039      3617153        6
7   chr8   21504766   21505348      +   2  438       582      3617735        7
8   chr8   21505349   21510554      +   4  439      5205      3622940        8
9   chr8   21510555   21514752      +   6  440      4197      3627137        9
10  chr8   21514753   26754951      +   4  441   5240198      8867335       10
11  chr8   26754952   26787858      +   5  442     32906      8900241       11
12  chr8   26787859   27067176      +   6  443    279317      9179558       12
13  chr8   27067177   27411608      +   5  444    344431      9523989       13
14  chr8   27411609   28998015      +   4  445   1586406     11110395       14
15  chr8   28998016   29887544      +   4  446    889528     11999923       15
16  chr8   29887545   29890111      +   5  447      2566     12002489       16
17  chr8   29890112   34357450      +   4  448   4467338     16469827       17
18  chr8   34357451   34380429      +   5  449     22978     16492805       18
19  chr8   34380430   34486603      +   4  450    106173     16598978       19
20  chr8   34486604   34815227      +   6  451    328623     16927601       20
21  chr8   34815228   34826521      +   5  452     11293     16938894       21
22  chr8   34826522   34829683      +   6  453      3161     16942055       22
23  chr8   34829684   42172617      +   4  454   7342933     24284988       23
24  chr8   42172618   45941402      +   3  455   3768784     28053772       24
25  chr8   45941403  130221002      +   4  456  84279599    112333371       25
26  chr8  130221003  130308350      +   5  457     87347    112420718       26
27  chr8  130308351  130363724      +   1  458     55373    112476091       27
28  chr8  130363725  134814802      +   5  459   4451077    116927168       28
29  chr8  134814803  136077002      +   4  460   1262199    118189367       29
30  chr8  136077003  137805402      +   6  461   1728399    119917766       30
31  chr8  137805403  140122002      +   5  462   2316599    122234365       31
32  chr8  140122003  142832602      +   6  463   2710599    124944964       32
33  chr8  142832603  144896002      +   7  464   2063399    127008363       33
34  chr8  144896003  145138636      +   6  465    242633    127250996       34
gene PCM1
error!!!! in row index 0
gene LEPROTL1
gene WRN
gene NRG1
gene FGFR1
gene NSD3
gene ANK1
gene KAT6A
gene IKBKB
gene HOOK3
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene NDRG1
gene FAM135B
gene RECQL4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226305-WG01_walk_3_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  130363725  145138636      -   5 -421  14774911     14774911        0
1  chr8  130308351  130363724      -   2 -420     55373     14830284        1
2  chr8   43969803  130308350      -   5 -419  86338547    101168831        2
3  chr8   38267203   43969802      -   4 -418   5702599    106871430        3
4  chr8   37878203   38267202      -   3 -417    388999    107260429        4
5  chr8   34829684   37878202      -   4 -416   3048518    110308947        5
6  chr8   34486604   34829683      -   6 -415    343079    110652026        6
7  chr8   34243603   34486603      -   5 -414    243000    110895026        7
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FGFR1
gene IKBKB
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226306-WG01_walk_2_MYCN_containing.fa
bed file      chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr9  34396403   36154202      -   6 -481   1757799      1757799        0
1   chr9  33829403   34396402      -   5 -480    566999      2324798        1
2   chr9  32400403   33829402      -   6 -479   1428999      3753797        2
3   chr9  30540803   32400402      -   7 -478   1859599      5613396        3
4   chr9  25543425   30540802      -   4 -477   4997377     10610773        4
5   chr2  53400862  134477351      -   4 -241  81076489     91687262        5
6   chr2  23809682   53398634      -   4 -239  29588952    121276214        6
7   chr2  16371803   23809681      -   5 -238   7437878    128714092        7
8   chr2  13499003   16371802      -   4 -237   2872799    131586891        8
9   chr2  12483003   13499002      -   5 -236   1015999    132602890        9
10  chr2   8700003   12483002      -   4 -235   3782999    136385889       10
11  chr2   6377603    8700002      -   5 -234   2322399    138708288       11
12  chr2    163003    6377602      -   4 -233   6214599    144922887       12
13  chr2         1     163002      -   5 -232    163001    145085888       13
gene FANCG
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226306-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226305-WG01_walk_2_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   31959390  131652002      -   4 -102  99692612     99692612
1   chr12   28604795   31959389      -   5 -101   3354594    103047206
2   chr12   18969760   28604794      -   4 -100   9635034    112682240
3   chr12   18890411   18969759      -  11  -99     79348    112761588
4    chr2  142156278  142438802      +  10  221    282524    113044112
5    chr2  142438803  143076824      +   3  222    638021    113682133
6    chr2  143076825  143149030      +  10  223     72205    113754338
7    chr2  143149031  143763361      +   3  224    614330    114368668
8    chr2  143763362  143763402      +   7  225        40    114368708
9    chr2  143763403  143827638      +  10  226     64235    114432943
10   chr2  143827639  144016086      +   3  227    188447    114621390
11   chr2  144016087  144224802      +  10  228    208715    114830105

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8

gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226305-WG01_walk_1_MDM2_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12   31959390  131652002      -   4 -102  99692612     99692612        0
1  chr12   28604795   31959389      +   5  101   3354594    103047206        1
2  chr12   31959390  131652002      +   4  102  99692612    202739818        2
3  chr12  131652003  133275309      +   2  103   1623306    204363124        3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226308-WG01_walk_1_MYCL_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr1  94947846  94948398      -   9  -37       552          552        0
1   chr1  93145769  94947845      -   5  -36   1802076      1802628        1
2   chr1  93145122  93145768      -   6  -35       646      1803274        2
3   chr1  92297137  93145121      -   7  -34    847984      2651258        3
4   chr1  90318677  92297136      -   5  -33   1978459      4629717        4
5   chr1  88419270  90318676      -   6  -32   1899406      6529123        5
6   chr1  86886555  88419269      -   5  -31   1532714      8061837        6
7   chr1  86508503  86886554      -   6  -30    378051      8439888        7
8   chr1  70491339  86508502      -   5  -29  16017163     24457051        8
9   chr1  60382930  70491338      -   5  -28  10108408     34565459        9
10  chr1  54825057  60382929      -   4  -27   5557872     40123331       10
11  chr1  52578778  54825056      -   4  -26   2246278     42369609       11
12  chr1  50618395  52578777      -   6  -25   1960382     44329991       12
13  chr1  46318883  50618394      -   4  -24   4299511     48629502       13
14  chr1  44214995  46318882      -   6  -23   2103887     50733389       14
15  chr1  40727723  44214994      -   4  -22   3487271     54220660       15
16  chr1  40326922  40727722      -   6  -21    400800     54621460       16
17  chr1  36109616  40326921      -   4  -20   4217305     58838765       17
18  chr1  35054028  36109615      -   6  -19   1055587     59894352       18
19  chr1  32610429  35054027      -   4  -18   2443598     62337950       19
20  chr1  32459739  32610428      -   6  -17    150689     62488639       20
21  chr1  31504403  32459738      -   5  -16    955335     63443974       21
22  chr1  29179357  31504402      -   4  -15   2325045     65769019       22
23  chr1  26435752  29179356      -   6  -14   2743604     68512623       23
24  chr1  24638628  26435751      -   5  -13   1797123     70309746       24
25  chr1  23895154  24638627      -   4  -12    743473     71053219       25
26  chr1  18896603  23895153      -   5  -11   4998550     76051769       26
27  chr1  17505638  18896602      -   3  -10   1390964     77442733       27
28  chr1  17365607  17505637      -   4   -9    140030     77582763       28
29  chr1  16635170  17365606      -   3   -8    730436     78313199       29
30  chr6  30507390  30918312      +   6  373    410922     78724121       30
31  chr6  30918313  31791882      +   5  374    873569     79597690       31
32  chr6  31791883  33617402      +   4  375   1825519     81423209       32
33  chr6  33617403  34289310      +   3  376    671907     82095116       33
34  chr6  34289311  34410303      +   6  377    120992     82216108       34
35  chr6  34410304  35875270      +   4  378   1464966     83681074       35
36  chr6  35875271  36616282      +   5  379    741011     84422085       36
37  chr6  36616283  38969602      +   4  380   2353319     86775404       37
38  chr6  38969603  41703202      +   3  381   2733599     89509003       38
39  chr6  41703203  42910200      +   5  382   1206997     90716000       39
40  chr6  42910201  42911019      +   7  383       818     90716818       40
gene RPL5
gene BCL10
gene FUBP1
gene JAK1
gene JUN
gene CDKN2C
gene EPS15
gene STIL
gene TAL1
gene MUTYH
gene MPL
gene MYCL
gene THRAP3
gene CSF3R
gene SFPQ
gene LCK
gene ARID1A
gene ID3
gene MDS2
gene PAX7
gene ARHGEF10L
gene SDHB
gene POU5F1
gene DAXX
gene HMGA1
gene FANCE
gene SRSF3
gene CDKN1A
gene PIM1
gene TFEB
gene CCND3

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene TFEB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226308-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226306-WG01_walk_1_MDM2_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  119537215  133275309      -   3 -107  13738094     13738094        0
1  chr12   38183203  119537214      -   4 -106  81354011     95092105        1
2  chr12   34783003   38183202      -   3 -105   3400199     98492304        2
3  chr12   31959390   34783002      -   4 -104   2823612    101315916        3
4  chr12   28604795   29091074      +   5  101    486279    101802195        4
5   chr1  221524256  248956422      +   2   39  27432166    129234361        5
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene H3F3A
gene FH
gene AKT3
gene RGS7
running file  226305-WG01_walk_3_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   31959390  131652002      -   4 -102  99692612     99692612
1   chr12   28604795   31959389      -   5 -101   3354594    103047206
2   chr12   18969760   28604794      -   4 -100   9635034    112682240
3   chr12   18890411   18969759      -  11  -99     79348    112761588
4    chr2  142156278  142438802      +  10  221    282524    113044112
5    chr2  142438803  143076824      +   3  222    638021    113682133
6    chr2  143076825  143149030      +  10  223     72205    113754338
7    chr2  143149031  143763361      +   3  224    614330    114368668
8    chr2  143763362  143763402      +   7  225        40    114368708
9    chr2  143763403  143827638      +  10  226     64235    114432943
10   chr2  143827639  144016086      +   3  227    188447    114621390
11   chr2  144016087  144224802      +  10  228    208715    114830105

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene KRAS
gene ETNK1
gene PPFIBP1
running file  226307-WG01_walk_1_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  92599614  92795750      -  19 -172    196136       196136        0
1   chr2  92275246  92599613      -  20 -171    324367       520503        1
2   chr2  89838611  92275245      -   7 -170   2436634      2957137        2
3   chr2  88373604  89838610      -   6 -169   1465006      4422143        3
4   chr2  87988403  88373603      -   7 -168    385200      4807343        4
5   chr2  86909403  87988402      -   5 -167   1078999      5886342        5
6   chr2  79963973  86909402      -   7 -166   6945429     12831771        6
7   chr2  79231340  79963972      -   6 -165    732632     13564403        7
8   chr2  77810818  79231339      -   7 -164   1420521     14984924        8
9   chr2  74966058  77810817      -   6 -163   2844759     17829683        9
10  chr2  64429807  74966057      -   7 -162  10536250     28365933       10
11  chr2  62651347  64429806      -   8 -161   1778459     30144392       11
12  chr2  61692870  62651346      -   8 -160    958476     31102868       12
13  chr2  61692478  61692869      -   9 -159       391     31103259       13
14  chr2  61374044  61692477      -  10 -158    318433     31421692       14
15  chr2  48592875  61374043      -   7 -157  12781168     44202860       15
16  chr2  45129718  48592874      -   7 -156   3463156     47666016       16
17  chr2  42446588  45129717      -   8 -155   2683129     50349145       17
18  chr2  27074998  42446587      -   7 -154  15371589     65720734       18
19  chr2  24746895  27074997      -   8 -153   2328102     68048836       19
20  chr2  23736941  24746894      -   9 -152   1009953     69058789       20
21  chr2  23630497  23736940      -   6 -151    106443     69165232       21
22  chr2  11862888  23630496      -   6 -150  11767608     80932840       22
23  chr2   7005124  11862887      -   7 -149   4857763     85790603       23
24  chr2   5390639   7005123      -   6 -148   1614484     87405087       24
25  chr2   3531403   5390638      -   6 -147   1859235     89264322       25
26  chr2         1   3531402      -   5 -146   3531401     92795723       26
gene CTNNA2
gene CTNNA2
gene PCBP1
gene DCTN1
gene XPO1
gene BCL11A
gene REL
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene ASXL2
gene NCOA1
gene DNMT3A
gene WDCP
gene NCOA1
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226307-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226305-WG01_walk_2_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr1   85906403   86590002      +   8   23    683599       683599        0
1   chr1   86590003   87098802      +   7   24    508799      1192398        1
2   chr1   87098803   88483202      +   8   25   1384399      2576797        2
3   chr1   88483203   88982202      +   7   26    498999      3075796        3
4   chr1   88982203   89764802      +   8   27    782599      3858395        4
5   chr1   89764803   90173402      +   7   28    408599      4266994        5
6   chr1   90173403   90594002      +   8   29    420599      4687593        6
7   chr1   90594003   91816802      +   7   30   1222799      5910392        7
8   chr1   91816803   93158602      +   6   31   1341799      7252191        8
9   chr1   93158603   94262402      +   7   32   1103799      8355990        9
10  chr1   94262403   94611002      +   6   33    348599      8704589       10
11  chr1   94611003   94786710      +   7   34    175707      8880296       11
12  chr1   94786711  104826465      +   6   35  10039754     18920050       12
13  chr1  104826466  180483602      +   5   36  75657136     94577186       13
14  chr1  180483603  209912602      +   3   37  29428999    124006185       14
15  chr1  209912603  213843010      +   2   38   3930407    127936592       15
16  chr2  110321403  113374494      -   6 -212   3053091    130989683       16
17  chr2   48624203  110321402      -   5 -211  61697199    192686882       17
18  chr2   37663926   48624202      -   4 -210  10960276    203647158       18
19  chr2    1107003   37663925      -   5 -209  36556922    240204080       19
20  chr2     162003    1107002      -   4 -208    944999    241149079       20
21  chr2          1     162002      -   5 -207    162001    241311080       21
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene CDC73
gene PTPRC
gene PAX8
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226308-WG01_walk_2_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  17365607  17505637      +   4   9    140030       140030        0
1   chr1  17505638  18896602      +   3  10   1390964      1530994        1
2   chr1  18896603  23895153      +   5  11   4998550      6529544        2
3   chr1  23895154  24638627      +   4  12    743473      7273017        3
4   chr1  24638628  26435751      +   5  13   1797123      9070140        4
5   chr1  26435752  29179356      +   6  14   2743604     11813744        5
6   chr1  29179357  31504402      +   4  15   2325045     14138789        6
7   chr1  31504403  32459738      +   5  16    955335     15094124        7
8   chr1  32459739  32610428      +   6  17    150689     15244813        8
9   chr1  32610429  35054027      +   4  18   2443598     17688411        9
10  chr1  35054028  36109615      +   6  19   1055587     18743998       10
11  chr1  36109616  40326921      +   4  20   4217305     22961303       11
12  chr1  40326922  40727722      +   6  21    400800     23362103       12
13  chr1  40727723  44214994      +   4  22   3487271     26849374       13
14  chr1  44214995  46318882      +   6  23   2103887     28953261       14
15  chr1  46318883  50618394      +   4  24   4299511     33252772       15
16  chr1  50618395  52578777      +   6  25   1960382     35213154       16
17  chr1  52578778  54825056      +   4  26   2246278     37459432       17
18  chr1  54825057  60382929      +   4  27   5557872     43017304       18
19  chr1  60382930  70491338      +   5  28  10108408     53125712       19
20  chr1  70491339  86508502      +   5  29  16017163     69142875       20
21  chr1  86508503  86886554      +   6  30    378051     69520926       21
22  chr1  86886555  88419269      +   5  31   1532714     71053640       22
23  chr1  88419270  90318676      +   6  32   1899406     72953046       23
24  chr1  90318677  92297136      +   5  33   1978459     74931505       24
25  chr1  92297137  93145121      +   7  34    847984     75779489       25
26  chr1  93145122  93145768      +   6  35       646     75780135       26
27  chr1  93145769  94947845      +   5  36   1802076     77582211       27
28  chr1  94947846  94948398      +   9  37       552     77582763       28
gene PAX7

gene ARHGEF10L
error!!!! in row index 1
gene ID3
gene MDS2
gene ARID1A
gene LCK
gene SFPQ
gene MYCL
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
gene BCL10
gene FUBP1
gene RPL5
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226308-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226305-WG01_walk_4_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2    1107003   37663925      +   5  209  36556922     36556922        0
1  chr2   37663926   48624202      +   4  210  10960276     47517198        1
2  chr2   48624203  110321402      +   5  211  61697199    109214397        2
3  chr2  110321403  113374494      +   6  212   3053091    112267488        3
4  chr2  113374495  134477351      +   5  213  21102856    133370344        4
5  chr9   25543425   39824603      +   6  425  14281178    147651522        5
6  chr9   39824604   42684802      +   5  426   2860198    150511720        6
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene SIX2
gene EPAS1
gene MSH6
gene EML4
gene FBXO11
gene MSH2
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene CTNNA2
gene AFF3
gene PAX8
gene ERCC3
gene FANCG
gene PAX5
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_4_MYCN_containing_breakpoints.pdf
running file  226305-WG01_walk_1_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr1         1   2843784      +   4   1   2843783      2843783        0
1   chr1   2843785  17953402      +   3   2  15109617     17953400        1
2   chr1  17953403  42164967      +   4   3  24211564     42164964        2
3   chr1  42164968  42165169      +   6   4       201     42165165        3
4   chr1  42165170  62284036      +   5   5  20118866     62284031        4
5   chr1  62284037  62292403      +   6   6      8366     62292397        5
6   chr1  62292404  68854002      +   5   7   6561598     68853995        6
7   chr1  68854003  69926202      +   8   8   1072199     69926194        7
8   chr1  69926203  70229802      +   7   9    303599     70229793        8
9   chr1  70229803  70459402      +   6  10    229599     70459392        9
10  chr1  70459403  71151602      +   7  11    692199     71151591       10
11  chr1  71151603  74842802      +   8  12   3691199     74842790       11
12  chr1  74842803  75640802      +   7  13    797999     75640789       12
13  chr1  75640803  75962402      +   6  14    321599     75962388       13
14  chr1  75962403  76177602      +   7  15    215199     76177587       14
15  chr1  76177603  77098802      +   8  16    921199     77098786       15
16  chr1  77098803  77561002      +   7  17    462199     77560985       16
17  chr1  77561003  78071602      +   6  18    510599     78071584       17
18  chr1  78071603  81185602      +   8  19   3113999     81185583       18
19  chr1  81185603  81921202      +   7  20    735599     81921182       19
20  chr1  81921203  84466202      +   8  21   2544999     84466181       20
21  chr1  84466203  85906402      +   7  22   1440199     85906380       21
22  chr1  85906403  86590002      +   8  23    683599     86589979       22
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JAK1
gene FUBP1
gene BCL10
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_3/226305-WG01_walk_1_MYCL_containing_breakpoints.pdf
running patient  4
running file  226315-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   32866671      +   2  19   32866670     32866670        0
1  chr2  32870557   86732202      +   2  21   53861645     86728315        1
2  chr2  86732203   92102402      +   3  22    5370199     92098514        2
3  chr2  92102403   94074602      +   4  23    1972199     94070713        3
4  chr2  94074603  242193529      +   2  24  148118926    242189639        4
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_4/226315-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226314-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1  50242696      +   2  151  50242695     50242695        0
1  chr12  50242697  50251611      +  17  152      8914     50251609        1
2  chr12  71649550  72072602      +   4  403    423052     50674661        2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_4/226314-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226315-WG01_walk_1_KRAS_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  8  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226315-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8          1  134070686      +   2  40  134070685    134070685        0
1  chr8  134076773  145138636      +   2  42   11061863    145132548        1
gene HEY1
gene MYC
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene KAT6A
gene RECQL4
gene FAM135B
running file  226315-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  120674602      +   2  1  120674601    120674601        0
1  chr1  120674603  150113843      +   3  2   29439240    150113841        1
2  chr1  150113844  192121766      +   2  3   42007922    192121763        2
3  chr1  192121767  192122895      +   1  4       1128    192122891        3
4  chr1  192122896  248956422      +   2  5   56833526    248956417        4
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene BCL9
gene PDE4DIP
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR

gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene MUC1
gene PBX1
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
running file  226314-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  730  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226314-WG01_walk_1_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2         1  89002507      +   2  686  89002506     89002506        0
1  chr2  89002508  90228516      +   2  687   1226008     90228514        1
2  chr2         1  89002507      -   2 -686  89002506    179231020        2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226315-WG01_walk_1_MDM2_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  8  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226315-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  192122896  248956422      -   2 -5   56833526     56833526        0
1  chr1  150113844  192121766      -   2 -3   42007922     98841448        1
2  chr1  120674603  150113843      -   3 -2   29439240    128280688        2
3  chr1          1  120674602      -   2 -1  120674601    248955289        3
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene MUC1
gene PBX1
gene BCL9
gene PDE4DIP
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
running patient  5
running file  226311-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr1         1  59760940      +   3    1  59760939     59760939        0
1  chr8  45946203  47959765      -   2 -164   2013562     61774501        1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226309-WG01_walk_2_MYCL_containing.fa
bed file     chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  91806603  109061095      -   2 -4  17254492     17254492        0
1  chr1  76225403   91806602      -   3 -3  15581199     32835691        1
2  chr1  67373495   76225402      -   2 -2   8851907     41687598        2
3  chr1         1   67373494      -   3 -1  67373493    109061091        3
gene RPL5
gene BCL10
gene FUBP1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226312-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   25843602      +   2  17   25843601     25843601        0
1  chr2  25843603   26090402      +   3  18     246799     26090400        1
2  chr2  26090403   92097203      +   2  19   66006800     92097200        2
3  chr2  92097204   94151602      +   3  20    2054398     94151598        3
4  chr2  94151603  242193529      +   2  21  148041926    242193524        4
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_5/226312-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226312-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr12         1   37240603      +   2  6  37240602     37240602        0
1  chr12  37240604   37419802      +   3  7    179198     37419800        1
2  chr12  37419803  133275309      +   2  8  95855506    133275306        2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226311-WG01_walk_2_MYCN_containing.fa
bed file     chr   start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr3       1    175802      +   4  87    175801       175801        0
1  chr3  175803  57044488      +   2  88  56868685     57044486        1
2  chr2       1  20473000      -   2 -67  20472999     77517485        2
gene CCR4
gene BAP1
gene VHL
gene PPARG
gene RAF1
gene MLH1
gene CTNNB1
gene NCKIPSD
gene RHOA
gene SRGAP3
gene FANCD2
gene XPC
gene TGFBR2
gene MYD88
gene SETD2
gene PBRM1
gene CACNA1D
gene FBLN2
gene MYCN
running file  226309-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  84039803  133275309      -   2 -34  49235506     49235506        0
1  chr12  34837203   84039802      -   1 -33  49202599     98438105        1
2  chr12         1   34837202      -   2 -32  34837201    133275306        2
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB

gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226309-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  135877203  145138636      -   2 -166   9261433      9261433        0
1   chr8  133889203  135877202      -   3 -165   1987999     11249432        1
2   chr8  133260403  133889202      -   2 -164    628799     11878231        2
3   chr8  130575803  133260402      -   3 -163   2684599     14562830        3
4   chr8  129769803  130575802      -   2 -162    805999     15368829        4
5   chr8  128003603  129769802      -   3 -161   1766199     17135028        5
6   chr8  127560003  128003602      -   2 -160    443599     17578627        6
7   chr8  126801403  127560002      -   3 -159    758599     18337226        7
8   chr8  126268203  126801402      -   2 -158    533199     18870425        8
9   chr8  125657603  126268202      -   3 -157    610599     19481024        9
10  chr8  124166203  125657602      -   2 -156   1491399     20972423       10
11  chr8  123553803  124166202      -   3 -155    612399     21584822       11
12  chr8  122741603  123553802      -   2 -154    812199     22397021       12
13  chr8  122086203  122741602      -   3 -153    655399     23052420       13
14  chr8  121453603  122086202      -   2 -152    632599     23685019       14
15  chr8  120322403  121453602      -   3 -151   1131199     24816218       15
16  chr8  119584203  120322402      -   2 -150    738199     25554417       16
17  chr8  103108403  119584202      -   3 -149  16475799     42030216       17
18  chr8  102205403  103108402      -   2 -148    902999     42933215       18
19  chr8  101726803  102205402      -   3 -147    478599     43411814       19
20  chr8   97399603  101726802      -   2 -146   4327199     47739013       20
21  chr8   95328003   97399602      -   3 -145   2071599     49810612       21
22  chr8   93557003   95328002      -   2 -144   1770999     51581611       22
23  chr8   86590403   93557002      -   3 -143   6966599     58548210       23
24  chr8   86023003   86590402      -   2 -142    567399     59115609       24
25  chr8          1   86023002      -   1 -141  86023001    145138610       25
gene RECQL4
gene FAM135B
gene NDRG1
gene NDRG1
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene UBR5
gene COX6C
gene PABPC1
gene CDH17
gene NBN
gene RUNX1T1
gene CNBD1
gene HEY1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene NCOA2
gene PREX2
gene KAT6A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_5/226309-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226311-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  71162659  133275309      -   2 -31  62112650     62112650        0
1  chr12  34812203   71162658      -   1 -30  36350455     98463105        1
2  chr12         1   34812202      -   2 -29  34812201    133275306        2
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226311-WG01_walk_2_KRAS_containing.fa
bed file      chr  start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12      1  34812202      +   2  29  34812201     34812201        0
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226311-WG01_walk_2_MYCL_containing.fa
bed file     chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1   59760940      +   3  1  59760939     59760939        0
1  chr1  59760941   76227402      +   2  2  16466461     76227400        1
2  chr1  76227403   91833202      +   3  3  15605799     91833199        2
3  chr1  91833203  108450602      +   2  4  16617399    108450598        3
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JAK1
gene BCL10
gene FUBP1
gene RPL5
running file  226309-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  84039803  133275309      -   2 -34  49235506     49235506        0
1  chr12  34837203   84039802      -   1 -33  49202599     98438105        1
2  chr12         1   34837202      -   2 -32  34837201    133275306        2
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226309-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1          1   67373494      +   3  1  67373493     67373493        0
1  chr1   67373495   76225402      +   2  2   8851907     76225400        1
2  chr1   76225403   91806602      +   3  3  15581199     91806599        2
3  chr1   91806603  109061095      +   2  4  17254492    109061091        3
4  chr1  109061096  109694803      +   1  5    633707    109694798        4
5  chr1  109694804  171344202      +   2  6  61649398    171344196        5
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene FUBP1
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226309-WG01_walk_3_MYCL_containing.fa
bed file     chr  start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1      1  67373494      -   3 -1  67373493     67373493        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226311-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  144930256  145138636      -   4 -169    208380       208380        0
1  chr8  135876403  144930255      -   2 -168   9053852      9262232        1
2  chr8  112035922  135876402      -   3 -167  23840480     33102712        2
3  chr8   86022803  112035921      -   3 -166  26013118     59115830        3
gene RECQL4
gene FAM135B
gene MYC
gene RAD21
gene NDRG1
gene EXT1
gene CSMD3
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RUNX1T1
gene UBR5
gene CNBD1
gene RSPO2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_5/226311-WG01_walk_1_MYC_containing_breakpoints.pdf

running file  226311-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr1          1   59760940      +   3    1  59760939     59760939        0
1  chr1   59760941   76227402      +   2    2  16466461     76227400        1
2  chr1   76227403   91833202      +   3    3  15605799     91833199        2
3  chr1   91833203  108450602      +   2    4  16617399    108450598        3
4  chr1  108450603  109694803      +   1    5   1244200    109694798        4
5  chr1  109694804  121612402      +   2    6  11917598    121612396        5
6  chr1  121612403  143496602      +   1    7  21884199    143496595        6
7  chr1  143496603  177305328      +   2    8  33808725    177305320        7
8  chr6  159497654  170805979      +   3  149  11308325    188613645        8
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JAK1
gene BCL10
gene FUBP1
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene PDE4DIP
gene MUC1
gene PBX1
gene FGFR1OP
gene AFDN
gene QKI
running file  226311-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr2          1   20473000      +   2  67  20472999     20472999        0
1  chr2   20473001   36182202      +   1  68  15709201     36182200        1
2  chr2   36182203   85040790      +   2  69  48858587     85040787        2
3  chr2   85040791  138804889      +   1  70  53764098    138804885        3
4  chr2  138804890  159089817      +   2  71  20284927    159089812        4
5  chr2  159089818  171379654      +   1  72  12289836    171379648        5
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene CXCR4
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene AFF3
gene PAX8
gene ACVR1
gene LRP1B
gene ACVR2A
running file  226311-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  71162659  133275309      -   2 -31  62112650     62112650        0
1  chr12  34812203   71162658      -   1 -30  36350455     98463105        1
2  chr12         1   34812202      -   2 -29  34812201    133275306        2
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226309-WG01_walk_2_KRAS_containing.fa
bed file      chr  start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12      1  34837202      +   2  32  34837201     34837201        0
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226312-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226312-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  43  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226312-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr12         1   37240603      +   2  6  37240602     37240602        0
1  chr12  37240604   37419802      +   3  7    179198     37419800        1
2  chr12  37419803  133275309      +   2  8  95855506    133275306        2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226309-WG01_walk_1_MYCN_containing.fa
bed file     chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr2   5199516   6610289      +   2  80   1410773      1410773        0
1  chr2   6610290  74090722      +   1  81  67480432     68891205        1
2  chr2  74090723  82251664      +   2  82   8160941     77052146        2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene DCTN1
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_5/226309-WG01_walk_1_MYCN_containing_breakpoints.pdf
running patient  6
running file  226319-WG01_walk_1_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr14         1  48260892      +   2  535  48260891     48260891        0
1  chr14  48260893  48261376      +  16  536       483     48261374        1
2   chr2   3800523   3801183      +  15  600       660     48262034        2
3   chr2   3801184  33669513      +   2  601  29868329     78130363        3
4   chr2  33669514  33696765      +   3  602     27251     78157614        4
5  chr12  90988382  91014066      +  51  433     25684     78183298        5
6  chr12  91014067  91015887      +  61  434      1820     78185118        6
7   chr2   1190645   1314765      +  42  596    124120     78309238        7
8   chr2   1314766   1361190      +  34  597     46424     78355662        8
9  chr12  89447803  89463025      -  40 -382     15222     78370884        9
gene FOXA1
gene NKX2-1
gene CCNB1IP1
gene PRKD1
gene ARHGAP5
gene BAZ1A
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
running file  226319-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12          1   44666396      +   2   24  44666395     44666395
1   chr12   44666397   44844756      +   8   25    178359     44844754
2   chr12   91402603   92556355      -   8 -447   1153752     45998506
3   chr12   91401092   91402602      -  21 -446      1510     46000016
4   chr12   91338556   91401091      -   8 -445     62535     46062551
5   chr12   91277118   91338555      -  14 -444     61437     46123988
6   chr12   91177632   91277117      -  16 -443     99485     46223473
7   chr12   91177481   91177631      -  17 -442       150     46223623
8   chr12   91177351   91177480      -  14 -441       129     46223752
9   chr12   91130612   91177350      -  11 -440     46738     46270490
10  chr12   91122345   91130611      -  19 -439      8266     46278756
11  chr12   91101644   91122344      -  20 -438     20700     46299456
12  chr12   78584552   78715719      -  15 -282    131167     46430623
13  chr12   78573528   78584551      -  20 -281     11023     46441646
14  chr12   78217434   78573527      -  22 -280    356093     46797739
15  chr12   78202603   78217433      -  42 -279     14830     46812569
16  chr12   78146499   78202602      -  57 -278     56103     46868672
17  chr12   78057549   78146498      -  54 -277     88949     46957621
18  chr12   78038453   78057548      -  64 -276     19095     46976716
19  chr12   78018198   78038452      -  67 -275     20254     46996970
20  chr12   78004470   78018197      -  72 -274     13727     47010697
21  chr12   76406516   76422361      +  16  247     15845     47026542
22  chr12   76422362   76432886      +  10  248     10524     47037066
23  chr12   76432887   76433226      +  12  249       339     47037405
24  chr12  103791496  103794506      +  41  479      3010     47040415
25  chr12  103810781  103826338      +  35  482     15557     47055972
26  chr12  104304505  104333431      -  37 -492     28926     47084898
27  chr12  104149733  104304504      -  38 -491    154771     47239669
28  chr12   75554879   75590559      +  42  219     35680     47275349
29  chr12   75590560   75595891      +  48  220      5331     47280680
30  chr12   75595892   75710074      +  55  221    114182     47394862
31  chr12   52006217   52028394      +  55   36     22177     47417039

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
gene PTPN6

gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene BTG1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_6/226319-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226318-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12          1   34773602      +   2   23  34773601     34773601
1   chr12   34773603   37616402      +   1   24   2842799     37616400
2   chr12   37616403   50409906      +   2   25  12793503     50409903
3   chr12   50409907   50448065      +  10   26     38158     50448061
4   chr12   50572540   50597436      +   9   30     24896     50472957
5   chr12   82174422   82293903      +   8  373    119481     50592438
6   chr12   82293904   82306519      +  38  374     12615     50605053
7   chr12   87957293   87981722      -  32 -409     24429     50629482
8   chr12   87933080   87957292      -  68 -408     24212     50653694
9   chr12   87929886   87933079      -  71 -407      3193     50656887
10  chr12   76819231   76848477      +  14  299     29246     50686133
11  chr12   96286672   96300939      +  40  545     14267     50700400
12  chr12   74156948   74178324      -  36 -204     21376     50721776
13   chr4  100347492  100367421      +  32  869     19929     50741705
14   chr4  100367422  100460222      +  34  870     92800     50834505
15   chr4  100460223  100520160      +  26  871     59937     50894442
16  chr12   89407970   89416834      +  47  438      8864     50903306
17  chr12   89416835   89421105      +  31  439      4270     50907576
18  chr12   89421106   89425099      +  59  440      3993     50911569
19  chr12   74885234   74961971      -  82 -225     76737     50988306
20  chr12   74883411   74885233      -  71 -224      1822     50990128
21  chr12   74879803   74883410      -  87 -223      3607     50993735

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ARID2
gene KMT2D
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_6/226318-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226318-WG01_walk_2_KRAS_containing.fa
bed file      chr  start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12      1  34773602      +   2  23  34773601     34773601        0
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226318-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8  43967403  145138636      -   3 -899  101171233    101171233        0
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226319-WG01_walk_2_MYCN_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  89161057  89170739      -  49 -370      9682         9682        0
1   chr12  89127191  89161056      -  53 -369     33865        43547        1
2   chr12  89125459  89127190      -  18 -368      1731        45278        2
3   chr12  89117234  89125458      -  30 -367      8224        53502        3
4    chr2  60843060  60927589      +  23  610     84529       138031        4
5    chr2  60927590  60953439      +  21  611     25849       163880        5
6    chr2  64268372  64458080      +  21  613    189708       353588        6
7    chr2  64458081  64458692      +  24  614       611       354199        7
8    chr2  64458693  64470382      +  23  615     11689       365888        8
9    chr2  59777776  59964102      +  23  604    186326       552214        9
10   chr2  59964103  59976881      +  10  605     12778       564992       10
11   chr2  59976882  60078619      +  16  606    101737       666729       11
12   chr2  60078620  60079145      +  16  607       525       667254       12
13   chr2  59976882  60078619      -  16 -606    101737       768991       13
14   chr2  59964103  59976881      -  10 -605     12778       781769       14
15   chr2  59777776  59964102      -  23 -604    186326       968095       15
16   chr2  33696766  59777775      -   2 -603  26081009     27049104       16
17   chr2  33669514  33696765      -   3 -602     27251     27076355       17
18   chr2   3801184  33669513      -   2 -601  29868329     56944684       18
19   chr2   3800523   3801183      -  15 -600       660     56945344       19
20  chr14  48260893  48261376      -  16 -536       483     56945827       20
21  chr12  51882438  51926779      +  46   32     44341     56990168       21
22  chr12  51926780  51958821      +  53   33     32041     57022209       22
23  chr12  51958822  51990569      +  51   34     31747     57053956       23
24  chr12  51990570  52006216      +  45   35     15646     57069602       24
25  chr12  52006217  52028394      +  55   36     22177     57091779       25
26  chr12  52028395  52040927      +  44   37     12532     57104311       26
27  chr12  52040928  52148602      +  35   38    107674     57211985       27
28  chr12  57781735  57924232      -  35  -49    142497     57354482       28
29  chr12  57780302  57781734      -  31  -48      1432     57355914       29
30  chr12  57772411  57780301      -  43  -47      7890     57363804       30
31  chr12  57762814  57772410      -  44  -46      9596     57373400       31
32  chr12  57729194  57762813      -  43  -45     33619     57407019       32
33  chr12  79758762  79759533      +  41  311       771     57407790       33
34  chr12  79759534  79760602      +  46  312      1068     57408858       34
gene REL
error!!!! in row index 0
gene REL
error!!!! in row index 1
gene SIX2
gene EPAS1
gene MSH6
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene ACVR1B
gene ACVR1B
gene ACVR1B
gene CDK4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_6/226319-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226318-WG01_walk_1_MYCL_containing.fa
bed file     chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  81637007  105882210      -   2 -3  24245203     24245203        0
1  chr1  81636874   81637006      -  19 -2       132     24245335        1
2  chr1         1   81636873      -   2 -1  81636872    105882207        2
gene BCL10
gene RPL5
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226318-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn    5     span  span_cumsum  bed_idx
0   chr22  31899002  41613647      -   1 -805  9714645      9714645        0
1   chr22  31895595  31899001      -   6 -804     3406      9718051        1
2   chr22  31873990  31895594      -   7 -803    21604      9739655        2
3   chr22  31856824  31873989      -   3 -802    17165      9756820        3
4   chr12  97905538  98774181      -   3 -548   868643     10625463        4
..    ...       ...       ...    ...  ..  ...      ...          ...      ...
59  chr12  68874142  68904229      +  96  115    30087     78443739       59
60  chr12  68904230  68954222      +  97  116    49992     78493731       60
61  chr12  68954223  68986252      +  93  117    32029     78525760       61
62   chr4  32888463  33011196      -  14 -833   122733     78648493       62
63   chr2  60551953  60716780      -  14 -698   164827     78813320       63

[64 rows x 9 columns]
gene APOBEC3B

gene ISX
gene PDGFB
gene MYH9
gene MRTFA
gene EP300
gene LRIG3
gene ACVR1B
gene ACVR1B
gene ACVR1B
gene ACVR1B
gene MDM2
gene MDM2
gene IL2
gene FAT4
gene FBXW7
gene BCL11A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_6/226318-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226319-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  175896059  199673594      -   2 -7  23777535     23777535        0
1  chr1  153981928  175896058      -   1 -6  21914130     45691665        1
2  chr1  152611604  153981927      -   2 -5   1370323     47061988        2
3  chr1  121874403  152611603      -   1 -4  30737200     77799188        3
4  chr1   81637007  121874402      -   2 -3  40237395    118036583        4
5  chr1   81636876   81637006      -  18 -2       130    118036713        5
6  chr1          1   81636875      -   2 -1  81636874    199673587        6
gene TPR
gene ABL2
gene CDC73
gene PTPRC
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene SDHC
gene DDR2
gene MUC1
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene BCL9
gene ARNT
gene PDE4DIP
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_6/226319-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226318-WG01_walk_2_MYCL_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr1          1   81636873      +   2    1  81636872     81636872        0
1   chr1   81636874   81637006      +  19    2       132     81637004        1
2   chr4  100565565  100566544      -  20 -878       979     81637983        2
3   chr4  100561776  100565564      -  39 -877      3788     81641771        3
4   chr4  100546795  100561775      -  38 -876     14980     81656751        4
5  chr12   90418047   90419129      -  81 -474      1082     81657833        5
6  chr12   83126888   83134158      +  52  391      7270     81665103        6
7  chr12   89530275   89530981      +  42  447       706     81665809        7
8  chr12   89530982   89531702      +  48  448       720     81666529        8
9  chr12   76532472   76589802      +  19  297     57330     81723859        9
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226318-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8         1   12057802      +   2  896   12057801     12057801        0
1  chr8  12057803   25131803      +   3  897   13074000     25131801        1
2  chr8  25131804   43967402      +   2  898   18835598     43967399        2
3  chr8  43967403  145138636      +   3  899  101171233    145138632        3
gene ARHGEF10
gene PCM1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226319-WG01_walk_2_MYCL_containing.fa
bed file     chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  81637007  121874402      -   2 -3  40237395     40237395        0
1  chr1  81636876   81637006      -  18 -2       130     40237525        1
2  chr1         1   81636875      -   2 -1  81636874    121874399        2
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226319-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  776  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running patient  7
running file  226324-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226322-WG01_walk_3_MDM2_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  13394003  37238202      +   4  117  23844199     23844199        0
1  chr12  37238203  72093202      +   3  118  34854999     58699198        1
2  chr12  72093203  73156602      +   5  119   1063399     59762597        2
3  chr12  73156603  73412402      +   6  120    255799     60018396        3
4  chr12  73412403  74039802      +   4  121    627399     60645795        4
5  chr12  74039803  74716002      +   6  122    676199     61321994        5
6  chr12  74716003  75379602      +   7  123    663599     61985593        6
7  chr12  75379603  75732802      +   6  124    353199     62338792        7
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226322-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  137834345  145138636      -   3 -501   7304291      7304291        0
1  chr8   43966003  137834344      -   4 -500  93868341    101172632        1
2  chr8    8476603   43966002      -   2 -499  35489399    136662031        2
3  chr8    8208803    8476602      -   1 -498    267799    136929830        3
4  chr8    7532603    8208802      -   2 -497    676199    137606029        4
5  chr8    1394203    7532602      -   5 -496   6138399    143744428        5
6  chr8          1    1394202      -   4 -495   1394201    145138629        6
gene RECQL4
gene FAM135B
error!!!! in row index 1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene ARHGEF10

saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226322-WG01_walk_3_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  46750403  47110202      -   3 -214    359799       359799        0
1  chr2  45063203  46750402      -   4 -213   1687199      2046998        1
2  chr2         1  45063202      -   3 -212  45063201     47110199        2
gene EPAS1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226323-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  124933002      +   2  1  124933001    124933001        0
1  chr1  124933003  149246802      +   3  2   24313799    149246800        1
2  chr1  149246803  248956422      +   2  3   99709619    248956419        2
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene BCL9
gene PDE4DIP
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene MUC1
gene PBX1
gene RGS7
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226323-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226325-WG01_walk_1_MDM2_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  4  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226322-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  108674603  133275309      -   4 -136  24600706     24600706
1   chr12   96664689  108674602      -   5 -135  12009913     36610619
2   chr12   82957403   96664688      -   6 -134  13707285     50317904
3   chr12   82653603   82957402      -   5 -133    303799     50621703
4   chr12   82070403   82653602      -   6 -132    583199     51204902
5   chr12   80370803   82070402      -   7 -131   1699599     52904501
6   chr12   80072403   80370802      -   6 -130    298399     53202900
7   chr12   79396003   80072402      -   5 -129    676399     53879299
8   chr12   79153203   79396002      -   6 -128    242799     54122098
9   chr12   78024003   79153202      -   7 -127   1129199     55251297
10  chr12   77040203   78024002      -   6 -126    983799     56235096
11  chr12   75732803   77040202      -   5 -125   1307399     57542495
12  chr12   75379603   75732802      -   6 -124    353199     57895694
13  chr12   74716003   75379602      -   7 -123    663599     58559293
14  chr12   74039803   74716002      -   6 -122    676199     59235492
15  chr12   73412403   74039802      -   4 -121    627399     59862891
16  chr12   73156603   73412402      -   6 -120    255799     60118690
17  chr12   72093203   73156602      -   5 -119   1063399     61182089
18  chr12   37238203   72093202      -   3 -118  34854999     96037088
19  chr12   13394003   37238202      -   4 -117  23844199    119881287
20  chr12    8021403   13394002      -   3 -116   5372599    125253886
21  chr12    7609403    8021402      -   1 -115    411999    125665885
22  chr12    5883003    7609402      -   3 -114   1726399    127392284
23  chr12    4478203    5883002      -   4 -113   1404799    128797083
24  chr12    3910603    4478202      -   3 -112    567599    129364682
25  chr12    3198003    3910602      -   4 -111    712599    130077281
26  chr12    2728203    3198002      -   2 -110    469799    130547080
27  chr12    1742803    2728202      -   4 -109    985399    131532479
28  chr12    1145003    1742802      -   3 -108    597799    132130278
29  chr12     341403    1145002      -   2 -107    803599    132933877
30  chr12     139003     341402      -   4 -106    202399    133136276
31  chr12          1     139002      -   6 -105    139001    133275277

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CHST11
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene KRAS
gene ETNK1
gene PPFIBP1
gene CDKN1B
gene ETV6
gene PTPN6
gene CHD4
gene ZNF384
gene CCND2
gene ERC1
gene KDM5A
error!!!! in row index 45
gene ERC1
gene KDM5A
error!!!! in row index 47
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226325-WG01_walk_1_KRAS_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  4  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226323-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  73  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226322-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2         1  45063202      +   3  212  45063201     45063201        0
1  chr2  45063203  46750402      +   4  213   1687199     46750400        1
2  chr2  46750403  47110202      +   3  214    359799     47110199        2
3  chr2  47110203  47968402      +   2  215    858199     47968398        3
4  chr2  47968403  48483202      +   3  216    514799     48483197        4
gene MYCN

gene WDCP
gene ASXL2
gene SIX2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226322-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  108674603  133275309      -   4 -136  24600706     24600706
1   chr12   96664689  108674602      -   5 -135  12009913     36610619
2   chr12   82957403   96664688      -   6 -134  13707285     50317904
3   chr12   82653603   82957402      -   5 -133    303799     50621703
4   chr12   82070403   82653602      -   6 -132    583199     51204902
5   chr12   80370803   82070402      -   7 -131   1699599     52904501
6   chr12   80072403   80370802      -   6 -130    298399     53202900
7   chr12   79396003   80072402      -   5 -129    676399     53879299
8   chr12   79153203   79396002      -   6 -128    242799     54122098
9   chr12   78024003   79153202      -   7 -127   1129199     55251297
10  chr12   77040203   78024002      -   6 -126    983799     56235096
11  chr12   75732803   77040202      -   5 -125   1307399     57542495
12  chr12   75379603   75732802      -   6 -124    353199     57895694
13  chr12   74716003   75379602      -   7 -123    663599     58559293
14  chr12   74039803   74716002      -   6 -122    676199     59235492
15  chr12   73412403   74039802      -   4 -121    627399     59862891
16  chr12   73156603   73412402      -   6 -120    255799     60118690
17  chr12   72093203   73156602      -   5 -119   1063399     61182089
18  chr12   37238203   72093202      -   3 -118  34854999     96037088
19  chr12   13394003   37238202      -   4 -117  23844199    119881287
20  chr12    8021403   13394002      -   3 -116   5372599    125253886
21  chr12    7609403    8021402      -   1 -115    411999    125665885
22  chr12    5883003    7609402      -   3 -114   1726399    127392284
23  chr12    4478203    5883002      -   4 -113   1404799    128797083
24  chr12    3910603    4478202      -   3 -112    567599    129364682
25  chr12    3198003    3910602      -   4 -111    712599    130077281
26  chr12    2728203    3198002      -   2 -110    469799    130547080
27  chr12    1742803    2728202      -   4 -109    985399    131532479
28  chr12    1145003    1742802      -   3 -108    597799    132130278
29  chr12     341403    1145002      -   2 -107    803599    132933877
30  chr12     139003     341402      -   4 -106    202399    133136276
31  chr12          1     139002      -   6 -105    139001    133275277

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CHST11
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene KRAS
gene ETNK1
gene PPFIBP1
gene CDKN1B
gene ETV6
gene PTPN6
gene CHD4
gene ZNF384
gene CCND2
gene ERC1
gene KDM5A
error!!!! in row index 45
gene ERC1
gene KDM5A
error!!!! in row index 47
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226325-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   32866671      +   2  12   32866670     32866670        0
1  chr2  32870557   90338202      +   2  14   57467645     90334315        1
2  chr2  90338203   94031602      +   3  15    3693399     94027714        2
3  chr2  94031603  242193529      +   2  16  148161926    242189640        3
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226325-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226325-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  29  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226322-WG01_walk_2_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  120359803  120574402      -   4  -5    214599       214599        0
1   chr1  105480803  120359802      -   3  -4  14878999     15093598        1
2   chr1   54883403  105480802      -   4  -3  50597399     65690997        2
3   chr1   14638454   54883402      -   2  -2  40244948    105935945        3
4  chr11    2813243    3308402      +   4  45    495159    106431104        4
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene EPS15
gene CARS
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226323-WG01_walk_1_KRAS_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12          1     219602      +   3   7    219601       219601        0
1  chr12     219603    4907802      +   2   8   4688199      4907800        1
2  chr12    4907803    5878402      +   3   9    970599      5878399        2
3  chr12    5878403   72051402      +   2  10  66172999     72051398        3
4  chr12   72051403  108637802      +   3  11  36586399    108637797        4
5  chr12  108637803  133275309      +   2  12  24637506    133275303        5
gene KDM5A
error!!!! in row index 0
gene CCND2
gene ERC1
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226322-WG01_walk_3_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  13394003  37238202      +   4  117  23844199     23844199        0
1  chr12  37238203  72093202      +   3  118  34854999     58699198        1
2  chr12  72093203  73156602      +   5  119   1063399     59762597        2
3  chr12  73156603  73412402      +   6  120    255799     60018396        3
4  chr12  73412403  74039802      +   4  121    627399     60645795        4
5  chr12  74039803  74716002      +   6  122    676199     61321994        5
6  chr12  74716003  75379602      +   7  123    663599     61985593        6
7  chr12  75379603  75732802      +   6  124    353199     62338792        7
gene KRAS

gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226322-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8   8476603   43966002      +   2  499  35489399     35489399        0
1  chr8  43966003  137834344      +   4  500  93868341    129357740        1
2  chr4  46150003   46936727      -   9 -382    786724    130144464        2
3  chr4  42588803   46150002      -   7 -381   3561199    133705663        3
4  chr4  42419603   42588802      -   6 -380    169199    133874862        4
5  chr4  42078203   42419602      -   4 -379    341399    134216261        5
6  chr4  41883603   42078202      -   5 -378    194599    134410860        6
7  chr4  41463203   41883602      -   6 -377    420399    134831259        7
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene PHOX2B
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226322-WG01_walk_3_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8   43966003  137834344      +   4  500  93868341     93868341        0
1  chr8  137834345  145138636      +   3  501   7304291    101172632        1
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_7/226322-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226325-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226322-WG01_walk_2_MDM2_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12   8021403  13394002      +   3  116   5372599      5372599        0
1  chr12  13394003  37238202      +   4  117  23844199     29216798        1
2  chr12  37238203  72093202      +   3  118  34854999     64071797        2
3  chr12  72093203  73156602      +   5  119   1063399     65135196        3
4  chr12  73156603  73412402      +   6  120    255799     65390995        4
5  chr12  73412403  74039802      +   4  121    627399     66018394        5
6  chr12  74039803  74716002      +   6  122    676199     66694593        6
7  chr12  74716003  75379602      +   7  123    663599     67358192        7
gene CDKN1B
gene ETV6
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226322-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12   8021403  13394002      +   3  116   5372599      5372599        0
1  chr12  13394003  37238202      +   4  117  23844199     29216798        1
2  chr12  37238203  72093202      +   3  118  34854999     64071797        2
3  chr12  72093203  73156602      +   5  119   1063399     65135196        3
4  chr12  73156603  73412402      +   6  120    255799     65390995        4
5  chr12  73412403  74039802      +   4  121    627399     66018394        5
6  chr12  74039803  74716002      +   6  122    676199     66694593        6
7  chr12  74716003  75379602      +   7  123    663599     67358192        7
gene CDKN1B
gene ETV6
gene KRAS
gene ETNK1
gene PPFIBP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  226323-WG01_walk_1_MYCN_containing.fa
bed file     chr   start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2       1     164002      +   3  35     164001       164001        0
1  chr2  164003  242193529      +   2  36  242029526    242193527        1
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226324-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  23  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226324-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr12         1   93810975      +   2  4  93810974     93810974        0
1  chr12  93810976   93811194      +   3  5       218     93811192        1
2  chr12  93811195  133275309      +   2  6  39464114    133275306        2
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene ERC1
gene TBX3
gene SETD1B
gene ZCCHC8
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running patient  8
running file  226327-WG01_walk_4_MYC_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr8  142935399  145138636      -   3 -1312   2203237      2203237        0
1  chr8  102662258  142935398      -   4 -1311  40273140     42476377        1
2  chr8  102655221  102662257      -   2 -1310      7036     42483413        2
3  chr8   45850203  102655220      -   4 -1309  56805017     99288430        3
gene RECQL4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1

gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene NCOA2
gene PREX2
gene CNBD1
running file  226328-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  72344803      +   5  1  72344802     72344802        0
1  chr1  72344804  75614002      +   6  2   3269198     75614000        1
2  chr1  75614003  75997602      +   5  3    383599     75997599        2
3  chr1  75997603  77173802      +   6  4   1176199     77173798        3
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226328-WG01_walk_2_MYCN_containing.fa
bed file       chr      start        end strand  cn    5       span  span_cumsum  \
0   chr12   57301266   57347808      +  24   95      46542        46542
1   chr12   57347809   57352973      +  33   96       5164        51706
2   chr12   57352974   57360610      +  13   97       7636        59342
3   chr12   57360611   57372082      +  21   98      11471        70813
4   chr12   77819464   77835217      -  19 -390      15753        86566
5   chr18   46610425   46647540      -  15 -505      37115       123681
6   chr18   46609884   46610424      -  23 -504        540       124221
7   chr18   46604424   46609883      -  21 -503       5459       129680
8   chr18   46478540   46604423      -  14 -502     125883       255563
9   chr18   46455892   46478539      -   7 -501      22647       278210
10  chr12   67704667   67831381      +   9  307     126714       404924
11   chr2  124188104  124199097      -  30 -643      10993       415917
12   chr2  124146825  124188103      -  27 -642      41278       457195
13   chr2  123776803  124146824      -  24 -641     370021       827216
14   chr2  123538917  123776802      -  27 -640     237885      1065101
15   chr2  123357803  123538916      -  23 -639     181113      1246214
16   chr2  123093720  123357802      -  28 -638     264082      1510296
17   chr2  122809203  123093719      -  24 -637     284516      1794812
18   chr2  122627283  122809202      -  19 -636     181919      1976731
19   chr2  121825403  122627282      -   3 -635     801879      2778610
20   chr2  121621403  121825402      -   2 -634     203999      2982609
21   chr2  121360603  121621402      -   3 -633     260799      3243408
22   chr2  120919613  121360602      -   2 -632     440989      3684397
23   chr2  120223810  120919612      -  14 -631     695802      4380199
24   chr2  120109170  120223809      -  19 -630     114639      4494838
25   chr2  119964603  120109169      -  14 -629     144566      4639404
26   chr2  119545203  119964602      -  16 -628     419399      5058803
27   chr2  119384803  119545202      -  13 -627     160399      5219202
28   chr2  119254203  119384802      -  19 -626     130599      5349801
29   chr2  119103203  119254202      -  14 -625     150999      5500800
30   chr2  118901203  119103202      -  16 -624     201999      5702799
31   chr2  118118662  118901202      -  17 -623     782540      6485339
32   chr2  117906693  118118661      -  20 -622     211968      6697307
33   chr2  115165385  115269514      -  22 -616     104129      6801436
34   chr2  114722003  115165384      -  13 -615     443381      7244817
35   chr2          1  114722002      -   3 -614  114722001    121966818

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  226327-WG01_walk_2_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  76194603  77174202      -   7 -9    979599       979599        0
1  chr1  75863203  76194602      -   6 -8    331399      1310998        1
2  chr1  75613803  75863202      -   5 -7    249399      1560397        2
3  chr1  74840403  75613802      -   6 -6    773399      2333796        3
4  chr1  72346003  74840402      -   7 -5   2494399      4828195        4
5  chr1  47361700  72346002      -   6 -4  24984302     29812497        5
6  chr1  38196324  47361699      -   5 -3   9165375     38977872        6
7  chr1  38195902  38196323      -   6 -2       421     38978293        7
8  chr1         1  38195901      -   5 -1  38195900     77174193        8
gene JUN
gene CDKN2C
gene JAK1
gene EPS15
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226329-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   4  784  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226328-WG01_walk_3_MYCN_containing.fa
bed file       chr      start        end strand  cn    5       span  span_cumsum  \
0    chr2          1  114722002      +   3  614  114722001    114722001
1    chr2  114722003  115165384      +  13  615     443381    115165382
2    chr2  115165385  115269514      +  22  616     104129    115269511
3    chr2  117906693  118118661      +  20  622     211968    115481479
4    chr2  118118662  118901202      +  17  623     782540    116264019
5    chr2  118901203  119103202      +  16  624     201999    116466018
6    chr2  119103203  119254202      +  14  625     150999    116617017
7    chr2  119254203  119384802      +  19  626     130599    116747616
8    chr2  119384803  119545202      +  13  627     160399    116908015
9    chr2  119545203  119964602      +  16  628     419399    117327414
10   chr2  119964603  120109169      +  14  629     144566    117471980
11   chr2  120109170  120223809      +  19  630     114639    117586619
12  chr12   67841359   68019499      +   6  310     178140    117764759
13  chr12   68019500   68040396      +  25  311      20896    117785655
14  chr12   68040397   68048275      +  32  312       7878    117793533
15  chr12   68048276   68109393      +  24  313      61117    117854650
16  chr12   69738010   69852459      -  28 -335     114449    117969099
17  chr18   43896960   43926919      +  27  487      29959    117999058
18  chr18   43926920   43931256      +  29  488       4336    118003394
19  chr18   43931257   43989686      +  28  489      58429    118061823
20  chr12   58881417   58882970      -  59 -162       1553    118063376
21  chr12   58866954   58881416      -  73 -161      14462    118077838
22  chr12   61017942   61025389      +  73  207       7447    118085285
23  chr19    5874376    6010194      +  14  601     135818    118221103
24  chr19    5868781    5874371      +  16  599       5590    118226693
25   chr2  155562268  155573316      +  15  678      11048    118237741
26  chr18   52211146   52211256      +  61  533        110    118237851
27  chr12   66429223   66431788      -  60 -297       2565    118240416
28  chr18   60683821   60697622      +  62  574      13801    118254217
29  chr18   60697623   60698175      +  81  575        552    118254769
30  chr12   58820698   58826650      -  74 -158       5952    118260721
31  chr12   58804263   58820697      -  57 -157      16434    118277155
32  chr12   58782346   58804262      -  54 -156      21916    118299071
33  chr12   58771622   58782345      -  63 -155      10723    118309794
34  chr12   63110347   63111991      +  43  245       1644    118311438
35  chr12   63111992   63181437      +  39  246      69445    118380883
36  chr12   63181438   63185505      +  45  247       4067    118384950
37  chr12   63185506   63215900      +  47  248      30394    118415344
38  chr12   63215901   63216770      +  53  249        869    118416213
39  chr12   60472122   60473035      +  36  182        913    118417126
40  chr12   60473036   60506047      +  27  183      33011    118450137
41  chr18   55724979   55784982      +  64  563      60003    118510140
42  chr18   55784983   55822983      +  61  564      38000    118548140
43  chr18   55822984   55956398      +  57  565     133414    118681554
44  chr18   55956399   55959952      +  49  566       3553    118685107
45  chr12   78031978   78088202      +  40  396      56224    118741331

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45

gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRIG3
gene LRIG3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226328-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226328-WG01_walk_1_MYCN_containing.fa
bed file        chr      start        end strand  cn    5       span  span_cumsum  \
0    chr12   61238358   61327802      -  14 -217      89444        89444
1    chr12   61208003   61238357      -  23 -216      30354       119798
2    chr12   61155357   61208002      -  25 -215      52645       172443
3    chr19    1143940    1153427      +  11  582       9487       181930
4    chr19    1153428    1163055      +  14  583       9627       191557
..     ...        ...        ...    ...  ..  ...        ...          ...
115   chr2  115871803  116067867      -  13 -618     196064      7367457
116   chr2  115269515  115871802      -  15 -617     602287      7969744
117   chr2  115165385  115269514      -  22 -616     104129      8073873
118   chr2  114722003  115165384      -  13 -615     443381      8517254
119   chr2          1  114722002      -   3 -614  114722001    123239255

     bed_idx
0          0
1          1
2          2
3          3
4          4
..       ...
115      115
116      116
117      117
118      118
119      119

[120 rows x 9 columns]
gene SETBP1
gene SETBP1
gene SETBP1
gene LRIG3
gene LRIG3
gene LRIG3
gene LRIG3
gene SMAD2
gene SMAD2
gene HMGA2
gene HMGA2
gene HMGA2
gene HMGA2
gene SMAD2
gene SMAD2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226328-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226328-WG01_walk_1_MYCL_containing.fa
bed file      chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0   chr1         1   72344803      +   5  1  72344802     72344802        0
1   chr1  72344804   75614002      +   6  2   3269198     75614000        1
2   chr1  75614003   75997602      +   5  3    383599     75997599        2
3   chr1  75997603   77173802      +   6  4   1176199     77173798        3
4   chr1  77173803   77174280      +   3  5       477     77174275        4
5   chr1  77174281  119259783      +   2  6  42085502    119259777        5
6   chr1  77173803   77174280      -   3 -5       477    119260254        6
7   chr1  75997603   77173802      -   6 -4   1176199    120436453        7
8   chr1  75614003   75997602      -   5 -3    383599    120820052        8
9   chr1  72344804   75614002      -   6 -2   3269198    124089250        9
10  chr1         1   72344803      -   5 -1  72344802    196434052       10
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226329-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  119255096  119384002      -  23 -626    128906       128906        0
1  chr2  118121203  119255095      -  18 -625   1133892      1262798        1
2  chr2  117906693  118121202      -  23 -624    214509      1477307        2
3  chr2  115165385  115269514      -  25 -617    104129      1581436        3
4  chr2  114871203  115165384      -  16 -616    294181      1875617        4
5  chr2  114721945  114871202      -  15 -615    149257      2024874        5
6  chr2   92088803  114721944      -   3 -614  22633141     24658015        6
7  chr2          1   92088802      -   2 -613  92088801    116746816        7
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226328-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12   8027403  33931600      +   2  54  25904197     25904197        0
1  chr12  33931601  37235402      +   1  55   3303801     29207998        1
2  chr12  37235403  40899428      +   2  56   3664025     32872023        2
3  chr12  40899429  40940602      +   8  57     41173     32913196        3
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
running file  226327-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn   5     span  span_cumsum  bed_idx
0   chr12  38202003  38898802      -   3 -90   696799       696799        0
1   chr12  38011203  38202002      -   2 -89   190799       887598        1
2   chr12  36940940  38011202      -   1 -88  1070262      1957860        2
3   chr12  34192203  35816874      -   1 -86  1624671      3582531        3
4   chr12  33004403  34192202      -   2 -85  1187799      4770330        4
5   chr12  31217603  33004402      -   1 -84  1786799      6557129        5
6   chr12  25438403  31217602      -   2 -83  5779199     12336328        6
7   chr12  24889203  25438402      -   1 -82   549199     12885527        7
8   chr12  19666203  24889202      -   2 -81  5222999     18108526        8
9   chr12  19245003  19666202      -   1 -80   421199     18529725        9
10  chr12  14364003  19245002      -   2 -79  4880999     23410724       10
11  chr12  14116803  14364002      -   1 -78   247199     23657923       11
12  chr12  13049403  14116802      -   2 -77  1067399     24725322       12
13  chr12  11863403  13049402      -   1 -76  1185999     25911321       13
14  chr12   9065403  11863402      -   2 -75  2797999     28709320       14
15  chr12         1   9065402      -   1 -74  9065401     37774721       15
gene PPFIBP1
gene KRAS
gene ETNK1
gene CDKN1B
gene ETV6
gene ETV6
gene PTPN6
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene ZNF384
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226328-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1          1   72344803      +   5  1  72344802     72344802        0
1  chr1   72344804   75614002      +   6  2   3269198     75614000        1
2  chr1   75614003   75997602      +   5  3    383599     75997599        2
3  chr1   75997603   77173802      +   6  4   1176199     77173798        3
4  chr1   77173803   77174280      +   3  5       477     77174275        4
5  chr1   77174281  119259783      +   2  6  42085502    119259777        5
6  chr1  119259784  120216002      +   5  7    956218    120215995        6
7  chr1  120216003  124623203      +   3  8   4407200    124623195        7
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene ATP1A1
gene NOTCH2

saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226328-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226327-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr8  142935399  145138636      -   3 -1312   2203237      2203237
1   chr8  102662258  142935398      -   4 -1311  40273140     42476377
2   chr8  102655221  102662257      -   2 -1310      7036     42483413
3   chr8   45850203  102655220      -   4 -1309  56805017     99288430
4   chr8   40917203   45850202      -   3 -1308   4932999    104221429
5   chr8   30740441   40917202      -   4 -1307  10176761    114398190
6   chr8   21223491   30740440      -   3 -1306   9516949    123915139
7   chr8   12072603   21223490      -   4 -1305   9150887    133066026
8   chr8   10323603   12072602      -   3 -1304   1748999    134815025
9   chr8    9992603   10323602      -   4 -1303    330999    135146024
10  chr8    7676804    9992602      -   3 -1302   2315798    137461822
11  chr8    1970485    7676803      -   4 -1301   5706318    143168140
12  chr8    1393203    1970484      -   3 -1300    577281    143745421
13  chr8          1    1393202      -   4 -1299   1393201    145138622

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
gene RECQL4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene WRN
gene NRG1
gene NSD3
gene LEPROTL1
gene PCM1
gene ARHGEF10
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226327-WG01_walk_2_MYC_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr8  102662258  142935398      -   4 -1311  40273140     40273140
1   chr8   45850203  102655220      -   4 -1309  56805017     97078157
2   chr8   40917203   45850202      -   3 -1308   4932999    102011156
3   chr8   30740441   40917202      -   4 -1307  10176761    112187917
4   chr8   21223491   30740440      -   3 -1306   9516949    121704866
5   chr8   12072603   21223490      -   4 -1305   9150887    130855753
6   chr8   10323603   12072602      -   3 -1304   1748999    132604752
7   chr8    9992603   10323602      -   4 -1303    330999    132935751
8   chr8    7676804    9992602      -   3 -1302   2315798    135251549
9   chr8    1970485    7676803      -   4 -1301   5706318    140957867
10  chr8    1393203    1970484      -   3 -1300    577281    141535148
11  chr8          1    1393202      -   4 -1299   1393201    142928349

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene WRN
gene NRG1
gene NSD3
gene LEPROTL1
gene PCM1
gene ARHGEF10
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226329-WG01_walk_2_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  76337403  77174202      -   7 -6    836799       836799        0
1  chr1  75124203  76337402      -   6 -5   1213199      2049998        1
2  chr1  32438671  75124202      -   7 -4  42685531     44735529        2
3  chr1  32438644  32438670      -   6 -3        26     44735555        3
4  chr1  32438433  32438643      -   7 -2       210     44735765        4
5  chr1         1  32438432      -   6 -1  32438431     77174196        5
gene MYCL
gene JUN
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  226329-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  41009182  41043802      -  11 -40     34620        34620        0
1  chr12  40939003  41009181      -   4 -39     70178       104798        1
2  chr12  40899403  40939002      -  10 -38     39599       144397        2
3  chr12         1  40899402      -   2 -37  40899401     41043798        3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226327-WG01_walk_3_MYC_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr8  142935399  145138636      -   3 -1312   2203237      2203237        0
1  chr8  102662258  142935398      -   4 -1311  40273140     42476377        1
2  chr8   45850203  102655220      -   4 -1309  56805017     99281394        2
3  chr8   40917203   45850202      -   3 -1308   4932999    104214393        3
4  chr8   30740441   40917202      -   4 -1307  10176761    114391154        4
5  chr1   47361700   72346002      +   6     4  24984302    139375456        5
6  chr1   72346003   74840402      +   7     5   2494399    141869855        6
7  chr1   74840403   75613802      +   6     6    773399    142643254        7
gene RECQL4
gene MYC
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene WRN
gene NRG1
gene NSD3
gene JUN
gene CDKN2C
gene JAK1
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226327-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  117906803  118122602      -  22 -931    215799       215799        0
1   chr2  117906693  117906802      -  19 -930       109       215908        1
2   chr2  115165385  115269514      -  23 -920    104129       320037        2
3   chr2  114721945  115165384      -  15 -919    443439       763476        3
4   chr2   99806083  114721944      -   3 -918  14915861     15679337        4
5   chr2   99201236   99806082      -   2 -917    604846     16284183        5
6   chr2   94186805   99201235      -   3 -916   5014430     21298613        6
7   chr2   94185414   94186804      -   4 -915      1390     21300003        7
8   chr2   94183782   94185413      -   3 -914      1631     21301634        8
9   chr2   94181273   94183781      -   4 -913      2508     21304142        9
10  chr2   94090003   94181272      -   3 -912     91269     21395411       10
11  chr2   89773347   94090002      -   2 -911   4316655     25712066       11
12  chr2   77465887   89773346      -   3 -910  12307459     38019525       12
13  chr2   77459844   77465886      -   4 -909      6042     38025567       13
14  chr2   34074003   77459843      -   3 -908  43385840     81411407       14
15  chr2   32374803   34074002      -   2 -907   1699199     83110606       15
16  chr2   32013203   32374802      -   1 -906    361599     83472205       16
17  chr2   31691003   32013202      -   2 -905    322199     83794404       17
18  chr2   30447803   31691002      -   3 -904   1243199     85037603       18
19  chr2   30067003   30447802      -   2 -903    380799     85418402       19
20  chr2   29427203   30067002      -   3 -902    639799     86058201       20
21  chr2   28127603   29427202      -   2 -901   1299599     87357800       21
22  chr2   27880803   28127602      -   3 -900    246799     87604599       22
23  chr2   26197003   27880802      -   2 -899   1683799     89288398       23
24  chr2   25855203   26197002      -   1 -898    341799     89630197       24
25  chr2   25380603   25855202      -   2 -897    474599     90104796       25
26  chr2   24964203   25380602      -   1 -896    416399     90521195       26
27  chr2   23443803   24964202      -   2 -895   1520399     92041594       27
28  chr2    1704203   23443802      -   3 -894  21739599    113781193       28
29  chr2    1344803    1704202      -   2 -893    359399    114140592       29
30  chr2     188203    1344802      -   3 -892   1156599    115297191       30
31  chr2          1     188202      -   4 -891    188201    115485392       31

gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene AFF3
gene TMEM127
gene CTNNA2
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene BIRC6
gene BIRC6
gene ALK
gene ALK
gene ASXL2
gene DNMT3A
gene WDCP
gene NCOA1
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226329-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  32438671  75124202      +   7  4  42685531     42685531        0
gene MYCL
gene JUN
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
running file  226329-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  119202898  120700202      -   4 -10   1497304      1497304        0
1  chr1   95026070  119202897      -   2  -9  24176827     25674131        1
2  chr1   94937609   95026069      -   7  -8     88460     25762591        2
3  chr1   77174203   94937608      -   2  -7  17763405     43525996        3
4  chr1   76337403   77174202      -   7  -6    836799     44362795        4
5  chr1   75124203   76337402      -   6  -5   1213199     45575994        5
6  chr1   32438671   75124202      -   7  -4  42685531     88261525        6
7  chr1   32438644   32438670      -   6  -3        26     88261551        7
8  chr1   32438433   32438643      -   7  -2       210     88261761        8
9  chr1          1   32438432      -   6  -1  32438431    120700192        9
gene NOTCH2
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene MYCL
gene JUN
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  226328-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  45927403  145138636      -   4 -854  99211233     99211233        0
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226327-WG01_walk_1_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr1         1  38195901      +   5    1  38195900     38195900        0
1    chr1  38195902  38196323      +   6    2       421     38196321        1
2    chr1  38196324  47361699      +   5    3   9165375     47361696        2
3    chr1  47361700  72346002      +   6    4  24984302     72345998        3
4    chr1  72346003  74840402      +   7    5   2494399     74840397        4
5    chr1  74840403  75613802      +   6    6    773399     75613796        5
6    chr1  75613803  75863202      +   5    7    249399     75863195        6
7    chr1  75863203  76194602      +   6    8    331399     76194594        7
8    chr1  76194603  77174202      +   7    9    979599     77174193        8
9    chr1  77174203  94937608      +   2   10  17763405     94937598        9
10   chr1  94937609  95026069      +   5   11     88460     95026058       10
11  chr12  43832678  43850868      +  10  127     18190     95044248       11
12  chr12  43850869  43898852      +   6  128     47983     95092231       12
13  chr12  78174100  78210559      +  33  563     36459     95128690       13
14  chr12  78210560  78254445      +  35  564     43885     95172575       14
15  chr12  65324187  65345866      +  39  383     21679     95194254       15
16  chr12  65345867  65346343      +  27  384       476     95194730       16
17  chr12  65346344  65358332      +  50  385     11988     95206718       17
18  chr12  65358333  65360804      +  42  386      2471     95209189       18
19  chr12  65360805  65430102      +  54  387     69297     95278486       19
20  chr12  79898355  79917286      -  30 -588     18931     95297417       20
21  chr12  77049234  77050027      -  41 -514       793     95298210       21
22  chr12  79884832  79894144      -  29 -586      9312     95307522       22
23  chr12  79849035  79884831      -  28 -585     35796     95343318       23
24  chr12  79848637  79849034      -  32 -584       397     95343715       24
25  chr12  79772203  79848636      -  31 -583     76433     95420148       25
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene MYCL
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene JUN
gene CDKN2C
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene FUBP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_8/226327-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226328-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  45927403  145138636      -   4 -854  99211233     99211233        0
1  chr8  40922203   45927402      -   3 -853   5005199    104216432        1
2  chr8  14101565   40922202      -   4 -852  26820637    131037069        2
3  chr8  14101377   14101564      -   7 -851       187    131037256        3
4  chr8  11979203   14101376      -   4 -850   2122173    133159429        4
5  chr8  10314403   11979202      -   3 -849   1664799    134824228        5
6  chr8   9993603   10314402      -   4 -848    320799    135145027        6
7  chr8         1    9993602      -   3 -847   9993601    145138628        7
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene LEPROTL1
gene FGFR1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ARHGEF10
running patient  9
running file  226336-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  159458939  160071228      +   7  13    612289       612289        0
1  chr1  144979203  150837558      -   7  -4   5858355      6470644        1
2  chr1  112155203  144979202      -   4  -3  32823999     39294643        2
3  chr1   71895550  112155202      -   5  -2  40259652     79554295        3
4  chr1          1   71895549      -   4  -1  71895548    151449843        4
gene BCL9
gene ARNT
gene PDE4DIP
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226337-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  72415177  145138636      -   4 -328  72723459     72723459        0
1  chr8  72140906   72415176      -   2 -327    274270     72997729        1
2  chr8  51402282   72140905      -   4 -326  20738623     93736352        2
3  chr8  51320838   51402281      -   6 -325     81443     93817795        3
4  chr8  12083204   51320837      -   4 -324  39237633    133055428        4
5  chr8   7984203   12083203      -   3 -323   4099000    137154428        5
6  chr8         1    7984202      -   4 -322   7984201    145138629        6
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B

gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene ARHGEF10
running file  226336-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  72045403  133275309      -   4  -59  61229906     61229906        0
1  chr12  56186203   72045402      -   2  -58  15859199     77089105        1
2  chr12  47562603   56186202      -   4  -57   8623599     85712704        2
3  chr12  39531203   47562602      -   2  -56   8031399     93744103        3
4  chr12  34780403   39531202      -   6  -55   4750799     98494902        4
5  chr12  34307232   34780402      -   4  -54    473170     98968072        5
6  chr18  66018803   69001420      -   4 -120   2982617    101950689        6
7  chr18  20856804   66018802      -   2 -119  45161998    147112687        7
8  chr18  15477003   20856803      -   3 -118   5379800    152492487        8
9  chr18         1   15477002      -   5 -117  15477001    167969488        9
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene ERBB3
gene ARID2
gene SMAD4
gene KDSR
gene SS18
gene SETBP1
gene SMAD2
gene BCL2
gene DCC
gene MALT1
gene ZNF521
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226338-WG01_walk_2_KRAS_containing.fa
bed file      chr    start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  6353603  133275309      -   2 -23  126921706    126921706        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226336-WG01_walk_3_MYCL_containing.fa
bed file     chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  71895550  112155202      -   5 -2  40259652     40259652        0
1  chr1         1   71895549      -   4 -1  71895548    112155200        1
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  226338-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   17090754      +   2  58   17090753     17090753        0
1  chr2  17090755   92245002      +   3  59   75154247     92245000        1
2  chr2  92245003  242193529      +   2  60  149948526    242193526        2
gene MYCN
gene PCBP1
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226336-WG01_walk_3_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  87530603  92134802      -   4 -138   4604199      4604199        0
1  chr2  52558003  87530602      -   5 -137  34972599     39576798        1
2  chr2  13967233  52558002      -   4 -136  38590769     78167567        2
3  chr2   7377157  13967232      -   2 -135   6590075     84757642        3
4  chr2         1   7377156      -   4 -134   7377155     92134797        4
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226336-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  34780403  39531202      -   6 -55   4750799      4750799        0
1  chr12  34307232  34780402      -   4 -54    473170      5223969        1
2  chr12  34307203  34307231      -   3 -53        28      5223997        2
3  chr12  34223603  34307202      -   2 -52     83599      5307596        3
4  chr12  32785803  34223602      -   4 -51   1437799      6745395        4
5  chr12  32722203  32785802      -   2 -50     63599      6808994        5
6  chr12  29443003  32722202      -   4 -49   3279199     10088193        6
7  chr12  28024603  29443002      -   5 -48   1418399     11506592        7
8  chr12  26956403  28024602      -   4 -47   1068199     12574791        8
9  chr12   1085603  26956402      -   3 -46  25870799     38445590        9
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226337-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  156846987  157002072      -   4 -18    155085       155085        0
1   chr1  156679025  156846986      -   5 -17    167961       323046        1
2   chr1  155011038  156679024      -   5 -16   1667986      1991032        2
3   chr1  153105106  155011037      -   3 -15   1905931      3896963        3
4   chr1  152268334  153105105      -   4 -14    836771      4733734        4
5   chr1  202828406  202835615      -   4 -41      7209      4740943        5
6   chr1  202178145  202828405      -   5 -40    650260      5391203        6
7   chr1  151779344  152146331      -   5 -12    366987      5758190        7
8   chr1  151731131  151779343      -   6 -11     48212      5806402        8
9   chr1  150321400  151731130      -   4 -10   1409730      7216132        9
10  chr1  150105057  150321399      -   3  -9    216342      7432474       10
11  chr1  144950603  150105056      -   5  -8   5154453     12586927       11
12  chr1  119077706  144950602      -   4  -7  25872896     38459823       12
13  chr1  118918236  119077705      -   2  -6    159469     38619292       13
14  chr1   46430003  118918235      -   4  -5  72488232    111107524       14
15  chr1   44514603   46430002      -   3  -4   1915399    113022923       15
16  chr1   40367603   44514602      -   4  -3   4146999    117169922       16
17  chr1    9907624   40367602      -   3  -2  30459978    147629900       17
18  chr1          1    9907623      -   4  -1   9907622    157537522       18
gene NTRK1
error!!!! in row index 0
gene PRCC
error!!!! in row index 1
gene LMNA
gene MUC1
error!!!! in row index 3
gene S100A7
gene TPM3
gene SETDB1
gene MLLT11
gene ARNT
gene BCL9
gene PDE4DIP
gene NOTCH2
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene EPS15
gene ATP1A1
gene MUTYH
gene MPL
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_1_MYCL_containing_breakpoints.pdf

running file  226338-WG01_walk_1_MDM2_containing.fa
bed file      chr    start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  6353603  133275309      -   2 -23  126921706    126921706        0
1  chr12  2050203    6353602      -   1 -22    4303399    131225105        1
2  chr12        1    2050202      -   2 -21    2050201    133275306        2
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CCND2
gene KDM5A
error!!!! in row index 44
gene ERC1
running file  226336-WG01_walk_2_MDM2_containing.fa
bed file       chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr12  26956403   28024602      +   4  47   1068199      1068199        0
1   chr12  28024603   29443002      +   5  48   1418399      2486598        1
2   chr12  29443003   32722202      +   4  49   3279199      5765797        2
3   chr12  32722203   32785802      +   2  50     63599      5829396        3
4   chr12  32785803   34223602      +   4  51   1437799      7267195        4
5   chr12  34223603   34307202      +   2  52     83599      7350794        5
6   chr12  34307203   34307231      +   3  53        28      7350822        6
7   chr12  34307232   34780402      +   4  54    473170      7823992        7
8   chr12  34780403   39531202      +   6  55   4750799     12574791        8
9   chr12  39531203   47562602      +   2  56   8031399     20606190        9
10  chr12  47562603   56186202      +   4  57   8623599     29229789       10
11  chr12  56186203   72045402      +   2  58  15859199     45088988       11
12  chr12  72045403  133275309      +   4  59  61229906    106318894       12
gene PPFIBP1
gene ARID2
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene ERBB3
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226338-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  149880117  157002072      -   3 -10   7121955      7121955        0
1  chr1  144779003  149880116      -   4  -9   5101113     12223068        1
2  chr1  106229003  144779002      -   3  -8  38549999     50773067        2
3  chr1  104845403  106229002      -   2  -7   1383599     52156666        3
4  chr1   82930803  104845402      -   3  -6  21914599     74071265        4
5  chr1   80168603   82930802      -   2  -5   2762199     76833464        5
6  chr1   76331203   80168602      -   3  -4   3837399     80670863        6
7  chr1   24835019   76331202      -   2  -3  51496183    132167046        7
8  chr1          1   24832212      -   2  -1  24832211    156999257        8
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene ARNT
gene MUC1
gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene MYCL
gene JUN
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARID1A
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226338-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226337-WG01_walk_3_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  44970203  46676402      -   5 -221   1706199      1706199        0
1   chr2  41974003  44970202      -   4 -220   2996199      4702398        1
2   chr2  39979003  41974002      -   5 -219   1994999      6697397        2
3   chr2  23289603  39979002      -   4 -218  16689399     23386796        3
4   chr2  17223975  23289602      -   5 -217   6065627     29452423        4
5   chr2  17090755  17223974      -   7 -216    133219     29585642        5
6   chr2  16315803  17090754      -   5 -215    774951     30360593        6
7   chr2  15372803  16315802      -   4 -214    942999     31303592        7
8   chr2  13967233  15372802      -   5 -213   1405569     32709161        8
9   chr2   5683803   7377156      -   5 -211   1693353     34402514        9
10  chr2         1   5683802      -   4 -210   5683801     40086315       10
gene SIX2
error!!!! in row index 0
gene EPAS1
gene EML4
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226338-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  91  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226338-WG01_walk_2_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  76331203  80168602      -   3 -4   3837399      3837399        0
1  chr1  24835019  76331202      -   2 -3  51496183     55333582        1
2  chr1         1  24832212      -   2 -1  24832211     80165793        2
gene FUBP1
gene MYCL
gene JUN
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARID1A
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  226338-WG01_walk_2_MDM2_containing.fa
bed file      chr    start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  6353603  133275309      -   2 -23  126921706    126921706        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  226336-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5       span  span_cumsum  \
0   chr2          1    7377156      +   4  134    7377155      7377155
1   chr2   13967233   52558002      +   4  136   38590769     45967924
2   chr2   52558003   87530602      +   5  137   34972599     80940523
3   chr2   87530603   92134802      +   4  138    4604199     85544722
4   chr2   92134803   94162402      +   3  139    2027599     87572321
5   chr2   94162403  210557802      +   4  140  116395399    203967720
6   chr2  210557803  220534202      +   2  141    9976399    213944119
7   chr2  220534203  223674202      +   4  142    3139999    217084118
8   chr2  223674203  223702002      +   2  143      27799    217111917
9   chr2  223702003  224391402      +   6  144     689399    217801316
10  chr2  224391403  242193529      +   2  145   17802126    235603442

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10

gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene BARD1
gene ATIC
gene ERBB4
gene ACSL3
gene PAX3
gene ACKR3
gene CUL3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226337-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  72415177  145138636      -   4 -328  72723459     72723459        0
1  chr8  72140906   72415176      -   2 -327    274270     72997729        1
2  chr8  51402282   72140905      -   4 -326  20738623     93736352        2
3  chr8  51320838   51402281      -   6 -325     81443     93817795        3
4  chr8  12083204   51320837      -   4 -324  39237633    133055428        4
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene LEPROTL1
gene FGFR1
gene IKBKB
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
running file  226336-WG01_walk_2_MYCN_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2  94162403  210557802      -   4 -140  116395399    116395399        0
1  chr2  92134803   94162402      -   3 -139    2027599    118422998        1
2  chr2  87530603   92134802      -   4 -138    4604199    123027197        2
3  chr2  52558003   87530602      -   5 -137   34972599    157999796        3
4  chr2  13967233   52558002      -   4 -136   38590769    196590565        4
5  chr2   7377157   13967232      -   2 -135    6590075    203180640        5
6  chr2         1    7377156      -   4 -134    7377155    210557795        6
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226336-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   4  214  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226336-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  157929364  159149308      +   4  11   1219944      1219944        0
1  chr1  159149309  159458938      +   5  12    309629      1529573        1
2  chr1  159458939  160071228      +   7  13    612289      2141862        2
3  chr1  144979203  150837558      -   7  -4   5858355      8000217        3
4  chr1  112155203  144979202      -   4  -3  32823999     40824216        4
5  chr1   71895550  112155202      -   5  -2  40259652     81083868        5
6  chr1          1   71895549      -   4  -1  71895548    152979416        6
gene BCL9
gene ARNT
gene PDE4DIP
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226337-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2          1    5683802      +   4  210   5683801      5683801        0
1   chr2    5683803    7377156      +   5  211   1693353      7377154        1
2   chr2   13967233   15372802      +   5  213   1405569      8782723        2
3   chr2   15372803   16315802      +   4  214    942999      9725722        3
4   chr2   16315803   17090754      +   5  215    774951     10500673        4
5   chr2   17090755   17223974      +   7  216    133219     10633892        5
6   chr2   17223975   23289602      +   5  217   6065627     16699519        6
7   chr2   23289603   39979002      +   4  218  16689399     33388918        7
8   chr2   39979003   41974002      +   5  219   1994999     35383917        8
9   chr2   41974003   44970202      +   4  220   2996199     38380116        9
10  chr2   44970203   46676402      +   5  221   1706199     40086315       10
11  chr2   46676403   48787802      +   4  222   2111399     42197714       11
12  chr2   48787803   52555003      +   5  223   3767200     45964914       12
13  chr2   52555004   92132403      +   4  224  39577399     85542313       13
14  chr2   92132404   94078402      +   3  225   1945998     87488311       14
15  chr2   94078403  164466798      +   4  226  70388395    157876706       15
16  chr2  164466799  175481954      +   3  227  11015155    168891861       16
17  chr2  175481955  175487993      +   3  228      6038    168897899       17
18  chr2  175487994  210557202      +   4  229  35069208    203967107       18
19  chr2  210557203  220534204      +   1  230   9977001    213944108       19
20  chr2  220534205  223674802      +   4  231   3140597    217084705       20
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene EML4
gene SIX2
gene EPAS1
gene MSH6
gene FBXO11
gene MSH2
gene PCBP1
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene CTNNA2
gene CXCR4
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene ACVR1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene HOXD11
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene COL3A1
gene SF3B1
gene ITGAV
gene PMS1
gene FEV
gene BARD1
gene ATIC
gene ERBB4
gene ACSL3
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226338-WG01_walk_1_KRAS_containing.fa
bed file      chr    start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  6353603  133275309      -   2 -23  126921706    126921706        0
1  chr12  2050203    6353602      -   1 -22    4303399    131225105        1
2  chr12        1    2050202      -   2 -21    2050201    133275306        2
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene CHD4
error!!!! in row index 8
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
error!!!! in row index 23
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene CCND2
gene KDM5A
error!!!! in row index 44
gene ERC1
running file  226336-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  29443003  32722202      -   4 -49   3279199      3279199        0
1  chr12  28024603  29443002      -   5 -48   1418399      4697598        1
2  chr12  26956403  28024602      -   4 -47   1068199      5765797        2
3  chr12   1085603  26956402      -   3 -46  25870799     31636596        3
4  chr12    172403   1085602      -   2 -45    913199     32549795        4
5  chr12         1    172402      -   3 -44    172401     32722196        5

gene PPFIBP1
gene PTPN6
gene CDKN1B
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene ERC1
gene KDM5A
error!!!! in row index 10
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226336-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226337-WG01_walk_3_MYC_containing.fa
bed file       chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0    chr8  72415177  145138636      -   4 -328  72723459     72723459        0
1    chr2  17090755   17223974      -   7 -216    133219     72856678        1
2   chr20  59803603   60503188      -   7 -248    699585     73556263        2
3   chr20  57148403   59803602      -   6 -247   2655199     76211462        3
4   chr20  56226603   57148402      -   5 -246    921799     77133261        4
5   chr20  52127803   56226602      -   6 -245   4098799     81232060        5
6   chr20  51672603   52127802      -   5 -244    455199     81687259        6
7   chr20  44825724   51672602      -   6 -243   6846878     88534137        7
8   chr20  41404066   41404754      -   6 -241       688     88534825        8
9   chr17  50993969   51095089      +   4  165    101120     88635945        9
10  chr20  63256164   64444167      +   4  257   1188003     89823948       10
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene GNAS
gene SALL4
gene SDC4
gene NFATC2
gene PTK6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226337-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  144950603  150105056      -   5 -8   5154453      5154453        0
1  chr1  119077706  144950602      -   4 -7  25872896     31027349        1
2  chr1   46430003  118918235      -   4 -5  72488232    103515581        2
3  chr1   44514603   46430002      -   3 -4   1915399    105430980        3
4  chr1   40367603   44514602      -   4 -3   4146999    109577979        4
5  chr1    9907624   40367602      -   3 -2  30459978    140037957        5
6  chr1          1    9907623      -   4 -1   9907622    149945579        6
gene BCL9
gene PDE4DIP
gene NOTCH2
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene EPS15
gene ATP1A1
gene MUTYH
gene MPL
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226337-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  75525615  133275309      -   4 -77  57749694     57749694        0
1  chr12  72047203   75525614      -   3 -76   3478411     61228105        1
2  chr12  56186177   72047202      -   2 -75  15861025     77089130        2
3  chr12  47563403   56186176      -   4 -74   8622773     85711903        3
4  chr12  39531089   47563402      -   2 -73   8032313     93744216        4
5  chr12  38105803   39531088      -   6 -72   1425285     95169501        5
6  chr12  36570430   38105802      -   5 -71   1535372     96704873        6
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene KMT2D
gene ERBB3
gene ARID2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226337-WG01_walk_2_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  48787803  52555003      -   5 -223   3767200      3767200        0
1   chr2  46676403  48787802      -   4 -222   2111399      5878599        1
2   chr2  44970203  46676402      -   5 -221   1706199      7584798        2
3   chr2  41974003  44970202      -   4 -220   2996199     10580997        3
4   chr2  39979003  41974002      -   5 -219   1994999     12575996        4
5   chr2  23289603  39979002      -   4 -218  16689399     29265395        5
6   chr2  17223975  23289602      -   5 -217   6065627     35331022        6
7   chr2  17090755  17223974      -   7 -216    133219     35464241        7
8   chr2  16315803  17090754      -   5 -215    774951     36239192        8
9   chr2  15372803  16315802      -   4 -214    942999     37182191        9
10  chr2  13967233  15372802      -   5 -213   1405569     38587760       10
11  chr2   5683803   7377156      -   5 -211   1693353     40281113       11
12  chr2         1   5683802      -   4 -210   5683801     45964914       12
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
gene EPAS1
gene EML4
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_9/226337-WG01_walk_2_MYCN_containing_breakpoints.pdf
running patient  10
running file  226330-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr2  234150403  242193529      -   2 -36   8043126      8043126        0
1  chr2  233557203  234150402      -   3 -35    593199      8636325        1
2  chr2  226710603  233557202      -   2 -34   6846599     15482924        2
3  chr2  224923003  226710602      -   3 -33   1787599     17270523        3
4  chr2  137421192  224923002      -   2 -32  87501810    104772333        4
5  chr2  137420947  137421191      -   3 -31       244    104772577        5
6  chr2   94086403  137420946      -   2 -30  43334543    148107120        6
7  chr2   90166204   94086402      -   1 -29   3920198    152027318        7
8  chr2          1   90166203      -   2 -28  90166202    242193520        8
gene ACKR3
gene HOXD11
gene FEV
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene CXCR4
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene AFF3
gene PAX8
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226330-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226330-WG01_walk_1_KRAS_containing.fa
bed file      chr   start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12       1     201802      +   3  10     201801       201801        0
1  chr12  201803  133275309      +   2  11  133073506    133275307        1
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226330-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr8  96509688  145138636      -   2 -73  48628948     48628948        0
1  chr8  96508480   96509687      -   2 -72      1207     48630155        1
2  chr8  43966003   96508479      -   3 -71  52542476    101172631        2
3  chr8  38593803   43966002      -   2 -70   5372199    106544830        3
4  chr8  37422603   38593802      -   3 -69   1171199    107716029        4
5  chr8  36502603   37422602      -   4 -68    919999    108636028        5
6  chr8  32140929   36502602      -   3 -67   4361673    112997701        6
7  chr8  32132613   32140928      -   4 -66      8315    113006016        7
8  chr8  31076603   32132612      -   3 -65   1056009    114062025        8
9  chr8         1   31076602      -   2 -64  31076601    145138626        9

gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene TCEA1
gene LYN
gene RUNX1T1
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene NSD3
gene NRG1
gene WRN
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226330-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226334-WG01_walk_2_MDM2_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  125126730  125127001      -   3 -81       271          271        0
1  chr12  110504463  125126729      -   2 -80  14622266     14622537        1
2  chr12  109959224  110504462      -   3 -79    545238     15167775        2
3  chr12  101970822  109959223      -   2 -78   7988401     23156176        3
4  chr12  101787889  101970821      -   3 -77    182932     23339108        4
5  chr12   56693268  101787888      -   2 -76  45094620     68433728        5
6  chr12   55621095   56693267      -   3 -75   1072172     69505900        6
7  chr12   14658406   55621094      -   2 -74  40962688    110468588        7
8  chr12   14243903   14658405      -   3 -73    414502    110883090        8
9  chr12          1   14243902      -   2 -72  14243901    125126991        9
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene CHST11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene ERBB3
gene HOXC13
gene HOXC11
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 39
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226333-WG01_walk_3_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  100530027  100530594      -   9 -26       567          567        0
1  chr1  100243623  100530026      -   7 -25    286403       286970        1
2  chr1  100242988  100243622      -  10 -24       634       287604        2
3  chr1   37773223  100242987      -   6 -23  62469764     62757368        3
4  chr1   37772740   37773222      -   7 -22       482     62757850        4
5  chr1   34707310   37772739      -   5 -21   3065429     65823279        5
6  chr1   33335020   34707309      -   4 -20   1372289     67195568        6
7  chr1   33334697   33335019      +   9  19       322     67195890        7
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene SFPQ
gene THRAP3
gene CSF3R
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226333-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226334-WG01_walk_2_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2   62736386   65363120      -   3 -157   2626734      2626734        0
1   chr2   62148557   62736385      -   2 -156    587828      3214562        1
2   chr2   54511715   62148556      -   2 -155   7636841     10851403        2
3   chr2   46911381   54511714      -   2 -154   7600333     18451736        3
4   chr8   70136123   70693115      +   3  310    556992     19008728        4
5   chr8   70693116   73751625      +   2  311   3058509     22067237        5
6   chr8   73751626   73852218      +   3  312    100592     22167829        6
7   chr8   73852219   98061985      +   2  313  24209766     46377595        7
8   chr8   98061986  100553487      +   3  314   2491501     48869096        8
9   chr8  100553488  124108187      +   2  315  23554699     72423795        9
10  chr8  124108188  125374088      +   3  316   1265900     73689695       10
11  chr8  125374089  139047008      +   2  317  13672919     87362614       11
12  chr8  139047009  139773755      +   1  318    726746     88089360       12
13  chr8  139773756  145138636      +   2  319   5364880     93454240       13
gene BCL11A
gene REL
gene XPO1
gene MSH6
gene FBXO11
gene MSH2
gene NCOA2
gene HEY1
gene NBN
gene CDH17
gene RUNX1T1
gene CNBD1
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene MYC
gene NDRG1
gene FAM135B
gene RECQL4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226332-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  18752403  34302602      -   2 -12  15550199     15550199        0
1  chr12  16176403  18752402      -   3 -11   2575999     18126198        1
2  chr12         1  16176402      -   2 -10  16176401     34302599        2
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 5
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226334-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chrX  130401002  151519954      -   1 -518  21118952     21118952
1    chr9  124794911  125414971      -   3 -340    620060     21739012
2    chr9  112530087  124794910      -   2 -339  12264823     34003835
3    chr9  111184333  112530086      -   3 -338   1345753     35349588
4   chr14   84320895  103812176      +   2  103  19491281     54840869
5   chr12  109959224  110504462      -   3  -79    545238     55386107
6   chr12  101970822  109959223      -   2  -78   7988401     63374508
7   chr12  101787889  101970821      -   3  -77    182932     63557440
8   chr12   56693268  101787888      -   2  -76  45094620    108652060
9   chr12   55621095   56693267      -   3  -75   1072172    109724232
10  chr12   14658406   55621094      -   2  -74  40962688    150686920
11  chr12   14243903   14658405      -   3  -73    414502    151101422
12  chr12          1   14243902      -   2  -72  14243901    165345323

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
gene PHF6
gene GPC3
gene PPP6C
gene TNC
gene CNTRL
gene TCL1A
gene DICER1
gene TRIP11
gene GOLGA5
gene BCL11B
gene HSP90AA1
gene CHST11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene ERBB3
gene HOXC13
gene HOXC11
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226332-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr12   74210603   75338402      -   3 -16   1127799      1127799        0
1   chr12   37924724   74210602      -   2 -15  36285878     37413677        1
2   chr12   37924184   37924723      +   2  14       539     37414216        2
3   chr12   37924724   74210602      +   2  15  36285878     73700094        3
4   chr12   74210603   75338402      +   3  16   1127799     74827893        4
5   chr12   75338403   77317202      +   2  17   1978799     76806692        5
6   chr12   77317203   79107202      +   3  18   1789999     78596691        6
7   chr12   79107203   81255002      +   2  19   2147799     80744490        7
8   chr12   81255003   82519202      +   3  20   1264199     82008689        8
9   chr12   82519203   83883602      +   2  21   1364399     83373088        9
10  chr12   83883603   88585602      +   3  22   4701999     88075087       10
11  chr12   88585603   89765202      +   2  23   1179599     89254686       11
12  chr12   89765203   91962402      +   3  24   2197199     91451885       12
13  chr12   91962403  133159002      +   2  25  41196599    132648484       13
14  chr12  133159003  133275309      +   3  26    116306    132764790       14
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226332-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226333-WG01_walk_1_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  65399033  65399675      +  12  105       642          642        0
1   chr2  63518163  65399032      -   7 -104   1880869      1881511        1
2   chr2  44824767  63518162      -   6 -103  18693395     20574906        2
3   chr2  35093701  44824766      -   6 -102   9731065     30305971        3
4   chr2  33057104  35093700      -   5 -101   2036596     32342567        4
5   chr2  26230076  33057103      -   6 -100   6827027     39169594        5
6   chr2  26161763  26230075      -   5  -99     68312     39237906        6
7   chr2  26161172  26161762      -   6  -98       590     39238496        7
8   chr2  23722803  26161171      -   7  -97   2438368     41676864        8
9   chr2   4978603  23722802      -   5  -96  18744199     60421063        9
10  chr2   1492145   4978602      -   4  -95   3486457     63907520       10
11  chr2    809403   1492144      -   4  -94    682741     64590261       11
12  chr2         1    809402      -   5  -93    809401     65399662       12
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene FBXO11
gene MSH2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226333-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226334-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr8   12608403   66621493      +   2  307  54013090     54013090
1    chr8   66621494   66783655      +   3  308    162161     54175251
2    chr8   66783656   70136122      +   2  309   3352466     57527717
3    chr8   70136123   70693115      +   3  310    556992     58084709
4    chr8   70693116   73751625      +   2  311   3058509     61143218
5    chr8   73751626   73852218      +   3  312    100592     61243810
6    chr8   73852219   98061985      +   2  313  24209766     85453576
7    chr8   98061986  100553487      +   3  314   2491501     87945077
8    chr8  100553488  124108187      +   2  315  23554699    111499776
9    chr8  124108188  125374088      +   3  316   1265900    112765676
10   chr8  125374089  139047008      +   2  317  13672919    126438595
11  chr18   54985462   80373285      +   2  144  25387823    151826418

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene KAT6A
gene NCOA2
gene PREX2
gene NCOA2
gene HEY1
gene NBN
gene CDH17
gene RUNX1T1
gene CNBD1
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene MYC
gene NDRG1
gene FAM135B
gene KDSR
gene BCL2
gene MALT1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226330-WG01_walk_2_MYCN_containing.fa
bed file     chr  start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr2      1  90166203      +   2  28  90166202     90166202        0
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226330-WG01_walk_2_MYCL_containing.fa
bed file     chr     start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1         1   54626601      +   2  1   54626600     54626600        0
1  chr1  54630294  248956422      +   2  3  194326128    248952728        1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226330-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr8  96509688  145138636      -   2 -73  48628948     48628948        0
1  chr8  43966003   96508479      -   3 -71  52542476    101171424        1
2  chr8  38593803   43966002      -   2 -70   5372199    106543623        2
3  chr8  37422603   38593802      -   3 -69   1171199    107714822        3
4  chr8  36502603   37422602      -   4 -68    919999    108634821        4
5  chr8  32140929   36502602      -   3 -67   4361673    112996494        5
6  chr8  32132613   32140928      -   4 -66      8315    113004809        6
7  chr8  31076603   32132612      -   3 -65   1056009    114060818        7
8  chr8         1   31076602      -   2 -64  31076601    145137419        8
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN

gene CDH17
gene TCEA1
gene LYN
gene RUNX1T1
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene FGFR1
gene NSD3
gene NRG1
gene WRN
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226330-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226330-WG01_walk_1_MDM2_containing.fa
bed file      chr   start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12       1     201802      +   3  10     201801       201801        0
1  chr12  201803  133275309      +   2  11  133073506    133275307        1
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226332-WG01_walk_2_MYCN_containing.fa
bed file     chr   start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr2  708203  90166203      -   2 -49  89458000     89458000        0
1  chr2       1    708202      -   3 -48    708201     90166201        1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226333-WG01_walk_4_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1   37772740   37773222      +   7  22       482          482        0
1  chr1   37773223  100242987      +   6  23  62469764     62470246        1
2  chr1  100242988  100243622      -  10 -24       634     62470880        2
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
running file  226332-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  85  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226332-WG01_walk_2_MYCL_containing.fa
bed file     chr     start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1   54626601      +   2  1  54626600     54626600        0
1  chr1  54626602   54630293      +   1  2      3691     54630291        1
2  chr1  54630294  121617002      +   2  3  66986708    121616999        2
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene ATP1A1
running file  226332-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  37924184  37924723      -   2 -14       539          539        0
1  chr12  34302603  37924183      -   1 -13   3621580      3622119        1
2  chr12  18752403  34302602      -   2 -12  15550199     19172318        2
3  chr12  16176403  18752402      -   3 -11   2575999     21748317        3
4  chr12         1  16176402      -   2 -10  16176401     37924718        4
gene KRAS
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 5
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  226332-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2  94161403  242193529      -   2 -51  148032126    148032126        0
1  chr2  90166204   94161402      -   1 -50    3995198    152027324        1
2  chr2    708203   90166203      -   2 -49   89458000    241485324        2
3  chr2         1     708202      -   3 -48     708201    242193525        3
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226334-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chrX  130401002  151519954      -   1 -518  21118952     21118952
1    chr9  124794911  125414971      -   3 -340    620060     21739012
2    chr9  112530087  124794910      -   2 -339  12264823     34003835
3    chr9  111184333  112530086      -   3 -338   1345753     35349588
4   chr14   84320895  103812176      +   2  103  19491281     54840869
5   chr12  109959224  110504462      -   3  -79    545238     55386107
6   chr12  101970822  109959223      -   2  -78   7988401     63374508
7   chr12  101787889  101970821      -   3  -77    182932     63557440
8   chr12   56693268  101787888      -   2  -76  45094620    108652060
9   chr12   55621095   56693267      -   3  -75   1072172    109724232
10  chr12   14658406   55621094      -   2  -74  40962688    150686920
11  chr12   14243903   14658405      -   3  -73    414502    151101422
12  chr12          1   14243902      -   2  -72  14243901    165345323

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
gene PHF6
error!!!! in row index 0
gene GPC3
error!!!! in row index 1
gene PPP6C
error!!!! in row index 2
gene TNC
error!!!! in row index 3
gene CNTRL
error!!!! in row index 4
gene TCL1A
error!!!! in row index 5
gene DICER1
error!!!! in row index 6
gene TRIP11
error!!!! in row index 7
gene GOLGA5
error!!!! in row index 8
gene BCL11B
error!!!! in row index 9
gene HSP90AA1
error!!!! in row index 10
gene CHST11
error!!!! in row index 11
gene NAB2
error!!!! in row index 12
gene GLI1
error!!!! in row index 13
gene DDIT3
error!!!! in row index 14
gene CDK4
error!!!! in row index 15
gene NACA
error!!!! in row index 16
gene STAT6
error!!!! in row index 17
gene LRIG3
error!!!! in row index 18
gene WIF1
error!!!! in row index 19
gene HMGA2
error!!!! in row index 20
gene MDM2
error!!!! in row index 21
gene PTPRB
error!!!! in row index 22
gene BTG1
error!!!! in row index 23
gene USP44
error!!!! in row index 24
gene ERBB3
error!!!! in row index 25
gene HOXC13
error!!!! in row index 26
gene HOXC11
error!!!! in row index 27
gene KRAS
error!!!! in row index 28
gene COL2A1
error!!!! in row index 29
gene PRPF40B
error!!!! in row index 30
gene SMARCD1
error!!!! in row index 31
gene ATF1
error!!!! in row index 32
gene ACVR1B
error!!!! in row index 33
gene ETNK1
error!!!! in row index 34
gene PPFIBP1
error!!!! in row index 35
gene ARID2
error!!!! in row index 36
gene KMT2D
error!!!! in row index 37
gene PTPN6
error!!!! in row index 38
gene CDKN1B
error!!!! in row index 39
gene KDM5A
error!!!! in row index 40
gene CCND2
error!!!! in row index 41
gene CHD4
error!!!! in row index 42
gene ZNF384
error!!!! in row index 43
gene ETV6
error!!!! in row index 44
gene ERC1
error!!!! in row index 45
running file  226333-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr1  100242988  100243622      +  10   24       634          634        0
1  chr1   37773223  100242987      -   6  -23  62469764     62470398        1
2  chr1   37772740   37773222      -   7  -22       482     62470880        2
3  chr1   34707310   37772739      -   5  -21   3065429     65536309        3
4  chr2   44824767   63518162      +   6  103  18693395     84229704        4
5  chr2   63518163   65399032      +   7  104   1880869     86110573        5
6  chr2   65399033   65399675      -  12 -105       642     86111215        6

gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene SFPQ
gene THRAP3
gene CSF3R
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene FBXO11
gene MSH2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226333-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226333-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  100530027  100530594      -   9 -26       567          567        0
1  chr1  100243623  100530026      -   7 -25    286403       286970        1
2  chr1  100242988  100243622      -  10 -24       634       287604        2
3  chr1   37773223  100242987      -   6 -23  62469764     62757368        3
4  chr1   37772740   37773222      -   7 -22       482     62757850        4
5  chr1   34707310   37772739      -   5 -21   3065429     65823279        5
6  chr1   33335020   34707309      -   4 -20   1372289     67195568        6
7  chr1   33334697   33335019      -   9 -19       322     67195890        7
8  chr1   31505603   33334696      -   6 -18   1829093     69024983        8
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene JAK1
gene EPS15
gene SFPQ
gene THRAP3
gene CSF3R
gene LCK
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226333-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226334-WG01_walk_1_MYCN_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr10  69026216  69026530      +   4   46       314          314        0
1  chr10  68458361  69026215      -   3  -45    567854       568168        1
2   chr2  46911381  54511714      -   2 -154   7600333      8168501        2
3   chr2  46523593  46911380      -   3 -153    387787      8556288        3
4   chr2  43606853  46523592      -   2 -152   2916739     11473027        4
5   chr2  43099138  43606852      -   3 -151    507714     11980741        5
6   chr2         1  43099137      -   2 -150  43099136     55079877        6
gene TET1
error!!!! in row index 0
gene MSH6
gene FBXO11
gene MSH2
gene SIX2
gene EPAS1
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226334-WG01_walk_2_KRAS_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  125126730  125127001      -   3 -81       271          271        0
1  chr12  110504463  125126729      -   2 -80  14622266     14622537        1
2  chr12  109959224  110504462      -   3 -79    545238     15167775        2
3  chr12  101970822  109959223      -   2 -78   7988401     23156176        3
4  chr12  101787889  101970821      -   3 -77    182932     23339108        4
5  chr12   56693268  101787888      -   2 -76  45094620     68433728        5
6  chr12   55621095   56693267      -   3 -75   1072172     69505900        6
7  chr12   14658406   55621094      -   2 -74  40962688    110468588        7
8  chr12   14243903   14658405      -   3 -73    414502    110883090        8
9  chr12          1   14243902      -   2 -72  14243901    125126991        9
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene CHST11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene ERBB3
gene HOXC13
gene HOXC11
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 39
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226330-WG01_walk_1_MYCL_containing.fa
bed file     chr     start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1         1   54626601      +   2  1   54626600     54626600        0
1  chr1  54626602   54630293      +   1  2       3691     54630291        1
2  chr1  54630294  248956422      +   2  3  194326128    248956419        2
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226332-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  143433003  248956422      -   2 -5  105523419    105523419        0
1  chr1  121617003  143433002      -   1 -4   21815999    127339418        1
2  chr1   54630294  121617002      -   2 -3   66986708    194326126        2
3  chr1          1   54626601      -   2 -1   54626600    248952726        3
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene ATP1A1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226333-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  65399033  65399675      +  12  105       642          642        0
1  chr2  63518163  65399032      -   7 -104   1880869      1881511        1
2  chr2  44824767  63518162      -   6 -103  18693395     20574906        2
3  chr2  35093701  44824766      -   6 -102   9731065     30305971        3
4  chr2  33057104  35093700      -   5 -101   2036596     32342567        4
5  chr2  26230076  33057103      -   6 -100   6827027     39169594        5
6  chr2  26161763  26230075      -   5  -99     68312     39237906        6
7  chr2  26161172  26161762      -   6  -98       590     39238496        7
8  chr2  23722803  26161171      -   7  -97   2438368     41676864        8
9  chr2   4978603  23722802      -   5  -96  18744199     60421063        9
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene FBXO11
gene MSH2
gene STRN
gene EML4
gene ALK
gene BIRC6
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226333-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226334-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  46523593  46911380      -   3 -153    387787       387787        0
1  chr2  43606853  46523592      -   2 -152   2916739      3304526        1
2  chr2  43099138  43606852      -   3 -151    507714      3812240        2
3  chr2         1  43099137      -   2 -150  43099136     46911376        3
gene SIX2
gene EPAS1
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_10/226334-WG01_walk_2_MYCN_containing_breakpoints.pdf

running patient  11
running file  226346-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  180511665  229313602      -   4 -6  48801937     48801937        0
1  chr1  178782779  180511664      -   3 -5   1728885     50530822        1
2  chr1  108243803  178782778      -   4 -4  70538975    121069797        2
3  chr1   55020403  108243802      -   5 -3  53223399    174293196        3
4  chr1    1712403   55020402      -   3 -2  53307999    227601195        4
5  chr1          1    1712402      -   4 -1   1712401    229313596        5
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene CDC73
gene PTPRC
gene ABL2
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226345-WG01_walk_3_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  124585800  145138636      -   3 -582  20552836     20552836        0
1  chr8  124558963  124585799      -   2 -581     26836     20579672        1
2  chr8   46522603  124558962      -   3 -580  78036359     98616031        2
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
running file  226346-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand   cn    5      span  span_cumsum  \
0   chr12   72007803   72774602      -   29 -172    766799       766799
1   chr12   71850673   72007802      -   25 -171    157129       923928
2   chr12   68802928   68824882      +  113  138     21954       945882
3   chr12   68824883   68826010      +  123  139      1127       947009
4   chr12   68826011   68851967      +  132  140     25956       972965
5   chr12   68851968   68852067      +  110  141        99       973064
6   chr12   68852068   68852070      +  122  142         2       973066
7   chr12   68852071   68858417      +  112  143      6346       979412
8   chr12   68858418   68892747      +  101  144     34329      1013741
9   chr12   68892748   69163279      +  112  145    270531      1284272
10  chr12   69163280   69163588      +  133  146       308      1284580
11  chr12   69163589   69224002      +  112  147     60413      1344993
12  chr12   69224003   69361621      +   83  148    137618      1482611
13   chr2  221901026  222460504      +   29  536    559478      2042089
14   chr2  232319226  232420623      +   14  564    101397      2143486
15  chr12   69755385   69764698      +   67  153      9313      2152799
16  chr12   94890000   94915867      +   23  260     25867      2178666
17  chr12   94915868   94932757      +   20  261     16889      2195555
18  chr12   94932758   94959292      +   36  262     26534      2222089
19  chr12   98326656   98326996      -   38 -296       340      2222429
20  chr12  100330481  100397857      -  142 -319     67376      2289805
21  chr12  100313003  100330480      -  143 -318     17477      2307282
22  chr12  100294898  100313002      -   73 -317     18104      2325386
23  chr12  100281134  100294897      -   43 -316     13763      2339149
24  chr12  100219486  100281133      -   29 -315     61647      2400796
25   chr2  194225203  194306424      -   14 -464     81221      2482017
26   chr2  193827603  194225202      -    8 -463    397599      2879616
27   chr2  130510603  193827602      -    5 -462  63316999     66196615

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
gene MDM2
gene MDM2
gene MDM2
gene PAX3
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ACVR1
gene COL3A1
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226346-WG01_walk_3_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  46355203  46595202      -  22 -46    239999       239999        0
1  chr12  46134403  46355202      -  20 -45    220799       460798        1
2  chr12  46005955  46134402      -  16 -44    128447       589245        2
3  chr12  28940711  46005954      -   4 -43  17065243     17654488        3
4  chr12   9033003  28940710      -   5 -42  19907707     37562195        4
gene ARID2
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_3_KRAS_containing_breakpoints.pdf
running file  226346-WG01_walk_2_KRAS_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr5  180949603  181538259      -   4 -848    588656       588656        0
1   chr5  177910603  180949602      -   3 -847   3038999      3627655        1
2   chr5  150842491  177910602      -   5 -846  27068111     30695766        2
3  chr12    9033003   28940710      -   5  -42  19907707     50603473        3
gene FLT4
gene ITK
gene PWWP2A
gene NPM1
gene FGFR4
gene EBF1
gene TLX3
gene NSD1
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226345-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr12         1  46005954      +   2  4  46005953     46005953        0
1  chr12  46005955  46115002      +   8  5    109047     46115000        1
2  chr12  46115003  46595402      +   9  6    480399     46595399        2
3  chr12  46595403  47053402      +   7  7    457999     47053398        3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226345-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226346-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  247894203  248956422      -   5 -18   1062219      1062219        0
1   chr1  241661803  247894202      -   3 -17   6232399      7294618        1
2   chr1  241263803  241661802      -   4 -16    397999      7692617        2
3   chr1  240026203  241263802      -   3 -15   1237599      8930216        3
4   chr1  237280403  240026202      -   4 -14   2745799     11676015        4
5   chr1  236519203  237280402      -   3 -13    761199     12437214        5
6   chr1  236295203  236519202      -   2 -12    223999     12661213        6
7   chr1  235002003  236295202      -   3 -11   1293199     13954412        7
8   chr1  232657203  235002002      -   4 -10   2344799     16299211        8
9   chr1  232160603  232657202      -   5  -9    496599     16795810        9
10  chr1  229605603  232160602      -   4  -8   2554999     19350809       10
11  chr1  229313603  229605602      -   3  -7    291999     19642808       11
12  chr1  180511665  229313602      -   4  -6  48801937     68444745       12
13  chr1  178782779  180511664      -   3  -5   1728885     70173630       13
14  chr1  108243803  178782778      -   4  -4  70538975    140712605       14
15  chr1   55020403  108243802      -   5  -3  53223399    193936004       15
16  chr1    1712403   55020402      -   3  -2  53307999    247244003       16
17  chr1          1    1712402      -   4  -1   1712401    248956404       17

gene AKT3
gene FH
gene RGS7
gene RGS7
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene CDC73
gene PTPRC
gene ABL2
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226346-WG01_walk_2_MDM2_containing.fa
bed file       chr     start       end strand  cn    5    span  span_cumsum  bed_idx
0   chr12  99420070  99492402      -  27 -302   72332        72332        0
1   chr12  99408140  99420069      -  21 -301   11929        84261        1
2   chr12  99182887  99408139      -  20 -300  225252       309513        2
3   chr12  99137764  99182886      -  21 -299   45122       354635        3
4   chr12  90660960  90699804      -  23 -239   38844       393479        4
..    ...       ...       ...    ...  ..  ...     ...          ...      ...
83  chr12  98098855  98125161      +  75  287   26306     53656220       83
84  chr12  98125162  98144856      +  76  288   19694     53675914       84
85  chr12  98144857  98161611      +  67  289   16754     53692668       85
86  chr12  98161612  98191224      +  66  290   29612     53722280       86
87  chr12  98191225  98194402      +  88  291    3177     53725457       87

[88 rows x 9 columns]
gene TERT
gene TERT
gene FEV
gene TFG
gene CBLB
gene GATA2
gene RPN1
gene CNBP
gene POLQ
gene STAG1
gene FOXL2
gene PIK3CB
gene ATR
gene PAX3
gene MDM2
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226346-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8         1   43966602      +   6  866   43966601     43966601        0
1  chr8  43966603  145138636      +   7  867  101172033    145138634        1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226346-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8  43966603  145138636      -   7 -867  101172033    101172033        0
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226345-WG01_walk_2_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2          1  193834002      +   2  327  193834001    193834001        0
1  chr2  193834003  194306424      +   4  328     472421    194306422        1
2  chr2  194306425  196899649      +   2  329    2593224    196899646        2
3  chr2  196899650  197209463      +   3  330     309813    197209459        3
4  chr2  197209464  197211229      +   2  331       1765    197211224        4
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  226346-WG01_walk_3_MYCL_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr20    1464820   28525402      -   7 -592  27060582     27060582        0
1   chr1  108243803  178782778      -   4   -4  70538975     97599557        1
2   chr1   55020403  108243802      -   5   -3  53223399    150822956        2
3   chr1    1712403   55020402      -   3   -2  53307999    204130955        3
4   chr1          1    1712402      -   4   -1   1712401    205843356        4
gene SIRPA
error!!!! in row index 0
gene CRNKL1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226345-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226345-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2  197675480  198419760      -  13 -333     744280       744280        0
1  chr2  197211230  197675479      -   2 -332     464249      1208529        1
2  chr2  196899650  197209463      -   3 -330     309813      1518342        2
3  chr2  194306425  196899649      -   2 -329    2593224      4111566        3
4  chr2  193834003  194306424      -   4 -328     472421      4583987        4
5  chr2          1  193834002      -   2 -327  193834001    198417988        5
gene SF3B1
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226345-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226345-WG01_walk_2_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  124585800  145138636      -   3 -582  20552836     20552836        0
1  chr8   46522603  124558962      -   3 -580  78036359     98589195        1
2  chr8   45954003   46522602      -   2 -579    568599     99157794        2
3  chr8          1   45954002      -   3 -578  45954001    145111795        3
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A

running file  226346-WG01_walk_1_MYCN_containing.fa
bed file       chr      start        end strand   cn    5       span  span_cumsum  \
0   chr12   86956403   87339611      +   67  229     383208       383208
1   chr12   87339612   87351602      +   68  230      11990       395198
2   chr12   87351603   87516240      +   63  231     164637       559835
3   chr12   87516241   87642202      +   59  232     125961       685796
4   chr12   87642203   87713281      +   78  233      71078       756874
5   chr12   87713282   88778407      +   10  234    1065125      1821999
6   chr12   88778408   88820308      +   26  235      41900      1863899
7    chr2  237498910  237514798      +   17  579      15888      1879787
8   chr12   77894469   77922506      +   60  190      28037      1907824
9   chr12   77922507   77931824      +   70  191       9317      1917141
10  chr12   77931825   77945295      +   86  192      13470      1930611
11   chr3  118362729  118362886      +   26  652        157      1930768
12  chr12   77743488   77746284      -  101 -186       2796      1933564
13  chr12   77951555   78091094      +   87  194     139539      2073103
14   chr2  220861953  221901025      +   18  535    1039072      3112175
15   chr2  221901026  222460504      +   29  536     559478      3671653
16   chr2  232319226  232420623      +   14  564     101397      3773050
17  chr12   69755385   69764698      +   67  153       9313      3782363
18  chr12   94890000   94915867      +   23  260      25867      3808230
19  chr12   94915868   94932757      +   20  261      16889      3825119
20  chr12   94932758   94959292      +   36  262      26534      3851653
21  chr12   98326656   98326996      -   38 -296        340      3851993
22  chr12  100330481  100397857      -  142 -319      67376      3919369
23  chr12  100313003  100330480      -  143 -318      17477      3936846
24  chr12  100294898  100313002      -   73 -317      18104      3954950
25  chr12  100281134  100294897      -   43 -316      13763      3968713
26  chr12  100219486  100281133      -   29 -315      61647      4030360
27   chr2  194225203  194306424      -   14 -464      81221      4111581
28   chr2  193827603  194225202      -    8 -463     397599      4509180
29   chr2  130510603  193827602      -    5 -462   63316999     67826179
30   chr2    8649403  130510602      -    4 -461  121861199    189687378
31   chr2    5738603    8649402      -    5 -460    2910799    192598177
32   chr2    5358803    5738602      -    4 -459     379799    192977976
33   chr2    3966403    5358802      -    5 -458    1392399    194370375
34   chr2     848203    3966402      -    4 -457    3118199    197488574
35   chr2     155403     848202      -    5 -456     692799    198181373
36   chr2          1     155402      -    7 -455     155401    198336774

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
gene PAX3
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ACVR1
gene COL3A1
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226345-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  124585800  145138636      -   3 -582  20552836     20552836        0
1  chr8  124558963  124585799      -   2 -581     26836     20579672        1
2  chr8   46522603  124558962      -   3 -580  78036359     98616031        2
3  chr8   45954003   46522602      -   2 -579    568599     99184630        3
4  chr8          1   45954002      -   3 -578  45954001    145138631        4
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
running file  226346-WG01_walk_2_MYCN_containing.fa
bed file       chr      start        end strand   cn    5       span  span_cumsum  \
0    chr2          1     155402      +    7  455     155401       155401
1    chr2     155403     848202      +    5  456     692799       848200
2    chr2     848203    3966402      +    4  457    3118199      3966399
3    chr2    3966403    5358802      +    5  458    1392399      5358798
4    chr2    5358803    5738602      +    4  459     379799      5738597
5    chr2    5738603    8649402      +    5  460    2910799      8649396
6    chr2    8649403  130510602      +    4  461  121861199    130510595
7    chr2  130510603  193827602      +    5  462   63316999    193827594
8    chr2  193827603  194225202      +    8  463     397599    194225193
9    chr2  194225203  194306424      +   14  464      81221    194306414
10  chr12  100219486  100281133      +   29  315      61647    194368061
11  chr12  100281134  100294897      +   43  316      13763    194381824
12  chr12  100294898  100313002      +   73  317      18104    194399928
13  chr12  100313003  100330480      +  143  318      17477    194417405
14  chr12  100330481  100397857      +  142  319      67376    194484781
15  chr12  100397858  100404989      +  127  320       7131    194491912
16  chr12  100404990  100446205      +  129  321      41215    194533127
17  chr12  100446206  100544498      +  127  322      98292    194631419
18  chr12  100544499  100638469      +  125  323      93970    194725389
19  chr12   90955982   90982112      -  114 -241      26130    194751519
20  chr12   68720052   68761100      +  109  134      41048    194792567
21  chr12   68761101   68781687      +  113  135      20586    194813153
22  chr12   68781688   68789709      +  108  136       8021    194821174
23  chr12   77851181   77894468      +   45  189      43287    194864461
24  chr12   77894469   77922506      +   60  190      28037    194892498
25  chr12   77922507   77931824      +   70  191       9317    194901815
26  chr12   77931825   77945295      +   86  192      13470    194915285
27   chr3  118362729  118362886      +   26  652        157    194915442
28  chr12   77743488   77746284      -  101 -186       2796    194918238
29  chr12   77951555   78091094      +   87  194     139539    195057777
30  chr12   78091095   78110308      +   78  195      19213    195076990
31  chr12   78110309   78118895      +   85  196       8586    195085576
32  chr12   78118896   78120241      +  100  197       1345    195086921
33  chr12   78120242   78215502      +  106  198      95260    195182181
34  chr12  123781825  123821013      +   49  360      39188    195221369
35  chr12  123821014  123821612      +   40  361        598    195221967
36  chr12  123821613  123943449      +   31  362     121836    195343803
37  chr12  123943450  123974814      +   38  363      31364    195375167
38  chr12  123974815  124022797      +   35  364      47982    195423149
39  chr12  124022798  124022802      +   30  365          4    195423153

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39

gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ACVR1
gene COL3A1
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  226346-WG01_walk_1_KRAS_containing.fa
bed file       chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0    chr3  91545403   99333552      +   5  645   7788149      7788149        0
1    chr3  99333553   99486550      +  17  646    152997      7941146        1
2    chr3  99490523   99563602      +  17  648     73079      8014225        2
3    chr3  99563603   99930002      +  20  649    366399      8380624        3
4    chr3  99930003  100290643      +  18  650    360640      8741264        4
5   chr12  77474774   77480403      +  69  180      5629      8746893        5
6   chr12  46595203   47053326      -  18  -47    458123      9205016        6
7   chr12  46355203   46595202      -  22  -46    239999      9445015        7
8   chr12  46134403   46355202      -  20  -45    220799      9665814        8
9   chr12  46005955   46134402      -  16  -44    128447      9794261        9
10  chr12  28940711   46005954      -   4  -43  17065243     26859504       10
11  chr12   9033003   28940710      -   5  -42  19907707     46767211       11
12  chr12   8558803    9033002      -   3  -41    474199     47241410       12
13  chr12         1    8558802      -   4  -40   8558801     55800211       13
gene ARID2
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene ZNF384
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_11/226346-WG01_walk_1_KRAS_containing_breakpoints.pdf
running patient  12
running file  226342-WG01_walk_1_MYCL_containing.fa
bed file     chr     start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1         1   79756097      +   2  1   79756096     79756096        0
1  chr1  79757344  248956422      +   2  3  169199078    248955174        1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226342-WG01_walk_1_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2         1  91423469      +   2  521  91423468     91423468        0
1  chr4  40811003  48082390      -   2 -570   7271387     98694855        1
2  chr4  38737603  40811002      -   3 -569   2073399    100768254        2
3  chr4    609803  38737602      -   2 -568  38127799    138896053        3
4  chr4         1    609802      -   3 -567    609801    139505854        4
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene PHOX2B
gene N4BP2
gene RHOH
gene FGFR3
gene SLC34A2
gene NSD2
running file  226342-WG01_walk_1_KRAS_containing.fa
bed file        chr      start        end strand  cn    5      span  span_cumsum  \
0    chr12   94116268   94117757      -  48 -407      1489         1489
1    chr12   94088970   94116267      -  44 -406     27297        28786
2    chr12   49264603   49268567      +  44   39      3964        32750
3    chr12  114132075  114133782      -  44 -504      1707        34457
4    chr12  101622690  101642437      -  44 -456     19747        54204
..     ...        ...        ...    ...  ..  ...       ...          ...
105  chr12   43819659   43854969      -  22  -25     35310     12736859
106  chr12   43600027   43819658      -  14  -24    219631     12956490
107  chr12   43578091   43600026      -  18  -23     21935     12978425
108  chr12   43511004   43578090      -  14  -22     67086     13045511
109  chr12          1   43511003      -   2  -21  43511002     56556513

     bed_idx
0          0
1          1
2          2
3          3
4          4
..       ...
105      105
106      106
107      107
108      108
109      109

[110 rows x 9 columns]
gene LRIG3
gene LATS1
gene CDK4
gene CDK4
gene NACA
gene NACA
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226342-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226342-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12  114133783  133275309      -   2 -505  19141526     19141526
1   chr12  114132075  114133782      -  44 -504      1707     19143233
2   chr12  101622690  101642437      -  44 -456     19747     19162980
3   chr12  111965968  111988675      -  44 -500     22707     19185687
4   chr12   69638615   69681949      +  26  179     43334     19229021
..    ...        ...        ...    ...  ..  ...       ...          ...
56  chr12   69638615   69681949      -  26 -179     43334     27477893
57  chr12  111965968  111988675      +  44  500     22707     27500600
58  chr12  101622690  101642437      +  44  456     19747     27520347
59  chr12  114132075  114133782      +  44  504      1707     27522054
60  chr12  114133783  133275309      +   2  505  19141526     46663580

    bed_idx
0         0
1         1
2         2
3         3
4         4
..      ...
56       56
57       57
58       58
59       59
60       60

[61 rows x 9 columns]
gene TBX3
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene LRIG3
gene CHST11
gene PTPRB
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene TBX3
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226342-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226340-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226341-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR

gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226340-WG01_walk_2_MYC_containing.fa
bed file      chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  95283396  145138636      -   2 -725  49855240     49855240        0
1   chr8  95283054   95283395      -   3 -724       341     49855581        1
2  chr12  67749534   67754892      +  66  150      5358     49860939        2
3  chr12  67754893   67765402      +  68  151     10509     49871448        3
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226341-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  487  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226341-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1  43530728      +   2   25  43530727     43530727        0
1  chr12  43530729  43578090      +   4   26     47361     43578088        1
2  chr12  43578091  43578228      +  11   27       137     43578225        2
3  chr12  43578229  43580275      +  15   28      2046     43580271        3
4  chr12  43580276  43600026      +   8   29     19750     43600021        4
5  chr12  67734251  67749533      +  55  133     15282     43615303        5
6  chr12  67749534  67765402      +  57  134     15868     43631171        6
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226342-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8         1   31846458      +   2  652  31846457     31846457        0
1  chr8  31846459   31918728      +   9  653     72269     31918726        1
2  chr8  31918729   94309402      +   2  654  62390673     94309399        2
3  chr8  94309403   95051202      +   3  655    741799     95051198        3
4  chr8  95051203  145138636      +   2  656  50087433    145138631        4
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
gene HEY1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene KAT6A
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226342-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226340-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  519  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226340-WG01_walk_2_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   62508420   62556396      -  24  -98     47976        47976
1   chr12   74094889   74095325      -   3 -190       436        48412
2   chr12   70888721   74094888      -   2 -189   3206167      3254579
3   chr12   70872189   70888720      -   7 -188     16531      3271110
4   chr12  100905802  100906388      -  23 -465       586      3271696
5   chr10   19519494   19544431      +   7   20     24937      3296633
6    chr6  146686884  147124535      -   7 -690    437651      3734284
7   chr12   75269890   75289189      -  16 -214     19299      3753583
8    chr6  133066610  133201792      -   7 -667    135182      3888765
9    chr6  132701636  133066609      -   2 -666    364973      4253738
10   chr6  132685805  132701635      -  10 -665     15830      4269568
11   chr6  132490032  132571765      -  10 -663     81733      4351301
12   chr6  132364820  132490031      -  13 -662    125211      4476512
13   chr6  132346111  132364819      -   8 -661     18708      4495220
14   chr6  132345959  132346110      -  10 -660       151      4495371
15   chr6  115709228  116165002      +  15  627    455774      4951145
16   chr6  116165003  116177519      +  19  628     12516      4963661
17   chr6  116177520  116240568      +  17  629     63048      5026709
18   chr6  116240569  116659086      +  13  630    418517      5445226
19   chr6  116659087  116673394      +  23  631     14307      5459533
20   chr6  116673395  116742813      +  14  632     69418      5528951
21   chr6  116742814  116743174      +  15  633       360      5529311
22   chr6  116743175  116754015      +  14  634     10840      5540151
23   chr6  108249266  108409879      -  14 -612    160613      5700764
24  chr10   20767093   20772217      +  13   22      5124      5705888
25  chr12   77705736   77707141      +  13  254      1405      5707293
26  chr12   43530729   43540089      +  12   26      9360      5716653
27  chr12   43540090   43550986      -   7  -27     10896      5727549
28  chr12   43530729   43540089      -  12  -26      9360      5736909
29  chr12          1   43530728      -   2  -25  43530727     49267636

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226342-WG01_walk_2_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12         1  43511003      +   2   21  43511002     43511002        0
1   chr12  43511004  43578090      +  14   22     67086     43578088        1
2   chr12  43578091  43600026      +  18   23     21935     43600023        2
3   chr12  67734251  67765378      +  43  144     31127     43631150        3
4   chr12  69346810  69361123      +  43  169     14313     43645463        4
5   chr12  69361124  69411155      +  54  170     50031     43695494        5
6   chr12  69411156  69483587      +  55  171     72431     43767925        6
7   chr12  69483588  69511421      +  45  172     27833     43795758        7
8   chr12  69511422  69519527      +  69  173      8105     43803863        8
9   chr12  69519528  69522082      +  44  174      2554     43806417        9
10  chr12  69522083  69522083      +  51  175         0     43806417       10
11  chr12  69522084  69522637      +  64  176       553     43806970       11
12  chr12  69522638  69603402      +  40  177     80764     43887734       12

gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226343-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226343-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8  31873091  145138636      -   2 -653  113265545    113265545        0
1  chr8  31869808   31873090      -   7 -652       3282    113268827        1
2  chr8  31846459   31869807      -  14 -651      23348    113292175        2
3  chr8  13241085   31846458      -   2 -650   18605373    131897548        3
gene HEY1
gene MYC
gene RECQL4
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene LEPROTL1
gene PCM1
gene WRN
running file  226343-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1  43530728      +   2  23  43530727     43530727        0
1  chr12  43530729  43578090      +   4  24     47361     43578088        1
2  chr12  43578091  43578228      +   9  25       137     43578225        2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226343-WG01_walk_2_MYC_containing.fa
bed file       chr      start        end strand  cn    5       span  span_cumsum  \
0    chr8   31873091  145138636      -   2 -653  113265545    113265545
1    chr8   31869808   31873090      -   7 -652       3282    113268827
2    chr8   31846459   31869807      -  14 -651      23348    113292175
3   chr12   79106015   79106309      +  14  255        294    113292469
4   chr12  100189616  100272377      +  14  438      82761    113375230
5   chr12   88157348   88171734      -  15 -318      14386    113389616
6   chr12   87909072   87910817      +  14  310       1745    113391361
7   chr12   70064774   70153701      +  13  179      88927    113480288
8   chr12   90750490   90763291      -  34 -360      12801    113493089
9   chr12   90716678   90750489      -  26 -359      33811    113526900
10   chr6   91392964   91407402      +   5  538      14438    113541338
11   chr6   91407403   91420587      +   7  539      13184    113554522
12   chr6   91420588   91530924      +   4  540     110336    113664858
13   chr6   91530925   91551165      +  12  541      20240    113685098
14   chr6   91825231   91851992      +  12  543      26761    113711859
15  chr12  100950110  100988835      +  17  449      38725    113750584
16  chr12   85877261   85881714      +  18  300       4453    113755037
17  chr12   63246142   63284060      -  18  -94      37918    113792955
18  chr12   94067569   94083331      -  18 -403      15762    113808717
19  chr12   93431096   94067568      -   2 -402     636472    114445189
20  chr12   93385752   93431095      -  10 -401      45343    114490532
21  chr12   93376847   93385751      -  13 -400       8904    114499436
22  chr12   75169277   75174887      +  13  201       5610    114505046
23  chr12   75174888   75196389      +  16  202      21501    114526547
24  chr12   57372158   57385016      +  16   66      12858    114539405
25  chr12   57385017   57402765      +  21   67      17748    114557153
26  chr12   57402766   57445884      +  15   68      43118    114600271
27  chr12   56704517   56713324      +  15   64       8807    114609078
28  chr12   94088970   94231011      -  18 -405     142041    114751119
29  chr12   49264603   49268567      +  18   35       3964    114755083
30  chr12  114132075  114133782      -  18 -488       1707    114756790
31  chr12  101622690  101642437      -  18 -451      19747    114776537
32  chr12  111966003  111988675      -  18 -486      22672    114799209

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
gene HEY1
gene MYC
gene RECQL4
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene NACA
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226343-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226340-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   67533572   67552602      -  46 -142     19030        19030
1   chr12   67470677   67533571      -  45 -141     62894        81924
2   chr12   67461332   67470676      -  56 -140      9344        91268
3   chr12   67383926   67461331      -   9 -139     77405       168673
4   chr12   97934476   97996256      +   9  433     61780       230453
5   chr12   92225617   92326152      +   9  410    100535       330988
6   chr12   50670438   50744879      +  10   51     74441       405429
7   chr12   90575920   90583491      +  31  367      7571       413000
8   chr12   54366984   54433936      -  22  -55     66952       479952
9   chr12   56333576   56350699      +  22   66     17123       497075
10  chr12   92468391   92473423      +  22  412      5032       502107
11  chr12   92473424   92479744      +   7  413      6320       508427
12  chr12   76384188   76384338      +  29  229       150       508577
13  chr12   76179979   76262320      -  25 -226     82341       590918
14  chr12   75616396   75706857      -   3 -219     90461       681379
15   chr6  131926675  131985951      -   3 -655     59276       740655
16  chr12   91445916   91464959      -  35 -401     19043       759698
17  chr12   64248585   64355301      -  19 -107    106716       866414
18  chr12   64192403   64248584      -   7 -106     56181       922595
19  chr12   64192345   64192402      -   6 -105        57       922652
20  chr12   66622384   66849401      +   6  130    227017      1149669
21  chr12   58541926   58639216      -   6  -80     97290      1246959
22   chr6  129307681  129426483      -  20 -648    118802      1365761
23   chr6  128963882  129307680      -  17 -647    343798      1709559
24  chr12  100499865  100506142      -  41 -461      6277      1715836
25  chr12  100480654  100499864      -  46 -460     19210      1735046
26  chr12  100475755  100480653      -  37 -459      4898      1739944
27  chr12  100470767  100475754      -  16 -458      4987      1744931
28  chr12  100272419  100470766      -   2 -457    198347      1943278
29  chr12  100189617  100272418      -  17 -456     82801      2026079
30  chr12  100189616  100189616      -   8 -455         0      2026079
31  chr12   79106015   79106308      -   8 -266       293      2026372
32   chr8   31846459   31873090      +  17  720     26631      2053003
33   chr8   31873091   32460225      +   2  721    587134      2640137
34   chr8   32460226   32460376      +  15  722       150      2640287
35   chr8   32460377   95283053      +   2  723  62822676     65462963
36   chr8   95283054   95283395      +   3  724       341     65463304
37   chr8   95283396  145138636      +   2  725  49855240    115318544

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37

gene HEY1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene KAT6A
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226340-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226340-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr6  135462003  137051437      +   6  676   1589434      1589434
1    chr6  137051438  137427002      +   8  677    375564      1964998
2    chr6  137427003  138984602      +   9  678   1557599      3522597
3    chr6  138984603  138984704      +   8  679       101      3522698
4    chr6   95818018   95841887      +   8  588     23869      3546567
5    chr6   95841888   95842390      +   2  589       502      3547069
6    chr6   95842391   95843740      +   6  590      1349      3548418
7    chr6  105591420  105625253      +   6  592     33833      3582251
8    chr6  105634454  105760602      +   6  594    126148      3708399
9    chr6  105760603  106022307      +   7  595    261704      3970103
10   chr6  106022308  106263876      +  16  596    241568      4211671
11   chr6  106897809  107120795      +  18  599    222986      4434657
12   chr6  107120796  107122175      +  26  600      1379      4436036
13   chr6  110390373  110390791      -   9 -614       418      4436454
14   chr6  108409880  110390372      -   2 -613   1980492      6416946
15   chr6  108249266  108409879      -  14 -612    160613      6577559
16  chr10   20767093   20772217      +  13   22      5124      6582683
17  chr12   77705736   77707141      +  13  254      1405      6584088
18  chr12   43530729   43540089      +  12   26      9360      6593448
19  chr12   43540090   43550986      -   7  -27     10896      6604344
20  chr12   43530729   43540089      -  12  -26      9360      6613704
21  chr12          1   43530728      -   2  -25  43530727     50144431

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
gene BCLAF1
gene TNFAIP3
gene ECT2L
gene PRDM1
gene FOXO3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226340-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226343-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  501  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226341-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr8   95283396  145138636      -   2 -639  49855240     49855240
1    chr8   95283054   95283395      -   4 -638       341     49855581
2    chr8   31873091   95283053      -   2 -637  63409962    113265543
3    chr8   31846459   31873090      -  14 -636     26631    113292174
4   chr12   79106015   79106234      +  14  244       219    113292393
5   chr12  100189617  100272439      +  14  420     82822    113375215
6   chr12   88157348   88171748      -  15 -303     14400    113389615
7   chr12   87909072   87910817      +  13  295      1745    113391360
8   chr12   70064774   70153772      +  13  169     88998    113480358
9   chr12   90750490   90763326      -  39 -341     12836    113493194
10  chr12   90716678   90750489      -  31 -340     33811    113527005
11  chr12   90695060   90716677      -  27 -339     21617    113548622
12  chr12   90690068   90695059      -  35 -338      4991    113553613
13  chr12   90585715   90690067      -  33 -337    104352    113657965
14  chr12   80747524   80767529      +  27  251     20005    113677970
15  chr12   69638615   69681949      -  27 -167     43334    113721304
16  chr12  111965968  111988675      +  15  472     22707    113744011
17  chr12  101622690  101642437      +  15  434     19747    113763758
18  chr12  114132075  114133782      +  15  474      1707    113765465
19  chr12   49264603   49268567      -  15  -37      3964    113769429
20  chr12   94088970   94231011      +  15  386    142041    113911470
21  chr12   94231012   94247866      +   7  387     16854    113928324
22  chr12   90086960   90151160      +  26  319     64200    113992524
23  chr12   90151161   90178935      +  33  320     27774    114020298
24  chr12   43578229   43580275      +  15   28      2046    114022344
25  chr12   75155327   75157444      +   9  190      2117    114024461
26  chr12   75146956   75148636      +   9  188      1680    114026141
27   chr6  107122176  107147380      -  16 -541     25204    114051345
28   chr6  107120796  107122175      -  21 -540      1379    114052724
29   chr6  106897809  107120795      -  14 -539    222986    114275710
30   chr6  106022308  106263876      -  14 -537    241568    114517278
31   chr6  105760003  106022307      -   7 -536    262304    114779582
32   chr6  105634454  105760002      -   6 -535    125548    114905130
33   chr6  105591420  105625253      -   6 -533     33833    114938963
34   chr6   95841888   95843740      -   6 -531      1852    114940815
35   chr6   95818018   95841887      -   9 -530     23869    114964684
36   chr6  137395984  138984704      -   9 -600   1588720    116553404
37   chr6  137395784  137395983      -  13 -599       199    116553603
38   chr6  137052003  137395783      -   9 -598    343780    116897383

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
gene MYC
gene RECQL4
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene KAT6A
gene PRDM1
gene TNFAIP3
gene ECT2L
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_12/226341-WG01_walk_1_MYC_containing_breakpoints.pdf
running patient  13
running file  226350-WG01_walk_1_MDM2_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  4  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B

gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226350-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  29  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226350-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226350-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   89562002      +   2  14   89562001     89562001        0
1  chr2  89562003   94089602      +   3  15    4527599     94089600        1
2  chr2  94089603  242193529      +   2  16  148103926    242193526        2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226351-WG01_walk_1_MDM2_containing.fa
bed file      chr      start        end strand  cn    5       span  span_cumsum  \
0   chr6          1  148616452      +   2  161  148616451    148616451
1   chr6  148616453  149245146      +   7  162     628693    149245144
2   chr6  149245147  149438893      +   8  163     193746    149438890
3  chr12   78208005   78208400      +   8   93        395    149439285
4  chr12   77619280   77740905      +   8   90     121625    149560910
5  chr12   61195642   61293809      -   9  -63      98167    149659077
6  chr12   68920719   68974950      -  11  -73      54231    149713308
7  chr12   68803403   68920718      -  13  -72     117315    149830623
8  chr12   68799673   68803402      -  17  -71       3729    149834352
9  chr12   68689203   68799672      -  16  -70     110469    149944821

   bed_idx
0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7
8        8
9        9
gene HIST1H3B
gene HIST1H4I
gene HLA-A
gene POU5F1
gene DAXX
gene CCND3
gene NFKBIE
gene DEK
gene TRIM27
gene HMGA1
gene FANCE
gene CDKN1A
gene SRSF3
gene PIM1
gene TFEB
gene HSP90AB1
gene CCNC
gene PRDM1
gene MYB
gene BCLAF1
gene TNFAIP3
gene IRF4
error!!!! in row index 21
gene BMP5
gene FOXO3
gene ROS1
gene GOPC
gene RSPO3
gene PTPRK
gene ECT2L
gene EPHA7
gene SGK1
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226351-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226349-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  276  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226349-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1  57645247      +   2   95  57645246     57645246        0
1  chr12  57645248  57743402      +  10   96     98154     57743400        1
2  chr12  57743403  57757556      +  17   97     14153     57757553        2
3  chr12  57757557  57757581      +  13   98        24     57757577        3
4  chr12  57757582  57789223      +   6   99     31641     57789218        4
5  chr12  57789224  57825203      +  12  100     35979     57825197        5
6  chr12  57825204  57830802      +  10  101      5598     57830795        6
7  chr12  57830803  57906402      +  15  102     75599     57906394        7
8  chr12  57906403  58009024      +  10  103    102621     58009015        8
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226349-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226348-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  418  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226351-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  169  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226351-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1  57645247      +   2  57  57645246     57645246        0
1  chr12  57645248  58104429      +   8  58    459181     58104427        1
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226351-WG01_walk_1_KRAS_containing_breakpoints.pdf

running file  226350-WG01_walk_1_KRAS_containing.fa
bed file      chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr12      1  133275309      +   2  4  133275308    133275308        0
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene ERC1
running file  226351-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2         1   32866671      +   2  146   32866670     32866670        0
1  chr2  32870557  242193529      +   2  148  209322972    242189642        1
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226351-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226348-WG01_walk_1_MYCN_containing.fa
bed file      chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0   chr2  23225003  242193529      -   2 -368  218968526    218968526        0
1   chr2  20991003   23225002      -   3 -367    2233999    221202525        1
2   chr2  19592403   20991002      -   2 -366    1398599    222601124        2
3   chr2  18104003   19592402      -   3 -365    1488399    224089523        3
4   chr2  17568003   18104002      -   2 -364     535999    224625522        4
5   chr2  16520603   17568002      -   3 -363    1047399    225672921        5
6   chr2  13363203   16520602      -   2 -362    3157399    228830320        6
7   chr2  12253803   13363202      -   3 -361    1109399    229939719        7
8   chr2   8559603   12253802      -   2 -360    3694199    233633918        8
9   chr2   6482603    8559602      -   3 -359    2076999    235710917        9
10  chr2    199203    6482602      -   2 -358    6283399    241994316       10
11  chr2         1     199202      -   3 -357     199201    242193517       11
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene MYCN
running file  226351-WG01_walk_1_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  55341787      +   2  1  55341786     55341786        0
1  chr1  55341788  56728838      +   4  2   1387050     56728836        1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226349-WG01_walk_1_MYCL_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr1          1   52557504      +   2    1  52557503     52557503
1    chr1   52557505   52621828      +   3    2     64323     52621826
2    chr1   52621829   55341802      +   2    3   2719973     55341799
3    chr1   55341803   56221802      +   8    4    879999     56221798
4    chr1   56221803   56576402      +   7    5    354599     56576397
5    chr1   56576403   56695437      +   8    6    119034     56695431
6   chr12   77438238   77581752      -   8 -161    143514     56838945
7   chr12   81736487   81739120      +   8  188      2633     56841578
8    chr1  147293127  147293642      -   8  -16       515     56842093
9   chr12   85433539   85440842      -   8 -192      7303     56849396
10   chr1  185950317  185957592      -  21  -88      7275     56856671
11  chr12   77717157   77740931      +  24  165     23774     56880445
12  chr12   77740932   77768668      +  12  166     27736     56908181
13  chr12   58104430   58106073      +   5  106      1643     56909824
14  chr12   74888689   74923520      +   5  154     34831     56944655
15  chr12   68870310   68873717      +  29  124      3407     56948062
16  chr12   68873718   68879516      +  32  125      5798     56953860
17  chr12   68879517   68920718      +  31  126     41201     56995061
18  chr12   77115142   77130118      +   5  158     14976     57010037
19  chr12   77799405   77802903      +  12  168      3498     57013535
20  chr12   77802904   77910202      +   9  169    107298     57120833
21  chr12   77910203   77954202      +  14  170     43999     57164832
22  chr12   77954203   78206703      +   8  171    252500     57417332
23   chr1   63299940   63349667      -   8  -10     49727     57467059
24   chr1   56928308   63299939      -   2   -9   6371631     63838690
25   chr1   56701113   56928307      -   9   -8    227194     64065884
26   chr1  172782805  172790452      -  11  -72      7647     64073531
27   chr1  172776138  172782804      -  22  -71      6666     64080197
28  chr12   69229492   69236075      +  21  134      6583     64086780
29  chr12   57789224   57825203      +  12  100     35979     64122759
30  chr12   57825204   57830802      +  10  101      5598     64128357
31  chr12   57830803   57906402      +  15  102     75599     64203956
32  chr12   57906403   58009024      +  10  103    102621     64306577

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
gene JUN
running file  226348-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr1   56071603   56695437      +  20    8    623834       623834
1   chr12   77438238   77581752      -  21 -214    143514       767348
2   chr12   81736487   81739120      +  21  258      2633       769981
3    chr1  147293126  147293642      -  20  -23       516       770497
4   chr12   85433539   85440927      -  22 -265      7388       777885
5    chr1  185950317  185957592      -  45 -118      7275       785160
6   chr12   77717157   77740927      +  52  217     23770       808930
7   chr12   61195642   61293899      -  27 -146     98257       907187
8   chr12   61092770   61195641      -   3 -145    102871      1010058
9   chr12   61084384   61092769      -  11 -144      8385      1018443
10  chr12   57757557   57757581      -  28 -133        24      1018467
11  chr12   57679156   57757556      -  29 -132     78400      1096867
12  chr12   57645203   57679155      -  17 -131     33952      1130819
13  chr12          1   57645202      -   2 -130  57645201     58776020

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13

gene CDK4
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226348-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226348-WG01_walk_1_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  49839136      +   2  1  49839135     49839135        0
1  chr1  49839137  51500500      +   3  2   1661363     51500498        1
2  chr1  51500501  51506972      +   6  3      6471     51506969        2
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene CDKN2C
gene EPS15
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226348-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226349-WG01_walk_2_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  52557505  52621828      -   3 -2     64323        64323        0
1  chr1         1  52557504      -   2 -1  52557503     52621826        1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  226349-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  323  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226349-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   57743403   57757556      +  17   97     14153        14153
1    chr1  172765834  172766047      +  27   69       213        14366
2    chr1  172766048  172776137      +  20   70     10089        24455
3    chr1  172776138  172782804      +  22   71      6666        31121
4    chr1  171111761  171146402      +  20   42     34641        65762
5    chr1  171146403  171196315      +  18   43     49912       115674
6    chr1   63357363   63677260      -   9  -12    319897       435571
7    chr1   63349668   63357362      -   2  -11      7694       443265
8    chr1   63299940   63349667      -   8  -10     49727       492992
9    chr1  185957593  185962817      -  15  -89      5224       498216
10   chr1  185950317  185957592      -  21  -88      7275       505491
11  chr12   77717157   77740931      +  24  165     23774       529265
12  chr12   61195642   61293865      -  14 -110     98223       627488
13  chr12   68920719   68974950      -  28 -127     54231       681719
14  chr12   68879517   68920718      -  31 -126     41201       722920
15  chr12   68873718   68879516      -  32 -125      5798       728718
16  chr12   68870310   68873717      -  29 -124      3407       732125
17  chr12   68779100   68870309      -  24 -123     91209       823334
18  chr12   68778948   68779099      -  27 -122       151       823485
19  chr12   68725972   68778947      -  26 -121     52975       876460
20  chr12   68725966   68725971      -  28 -120         5       876465
21  chr12   68725743   68725965      -  21 -119       222       876687
22  chr12   68674099   68725742      -  19 -118     51643       928330
23  chr12   68639314   68674098      -  18 -117     34784       963114
24  chr12   70080219   70105909      -  18 -147     25690       988804
25  chr12   70075606   70080218      -  23 -146      4612       993416
26  chr12   70075478   70075605      -  20 -145       127       993543
27   chr1   63357363   63677260      +   9   12    319897      1313440
28   chr1   63677261  122500602      +   2   13  58823341     60136781
29   chr1  122500603  143312802      +   3   14  20812199     80948980
30   chr1  143312803  147293126      +   2   15   3980323     84929303
31   chr1  147293127  147293642      +   8   16       515     84929818
32   chr1  147293643  147690149      +   2   17    396506     85326324
33   chr1  147690150  148332766      +   5   18    642616     85968940
34  chr12   70075606   70080218      +  23  146      4612     85973552
35  chr12   70080219   70105909      +  18  147     25690     85999242
36  chr12   68639314   68674098      +  18  117     34784     86034026
37  chr12   68674099   68725742      +  19  118     51643     86085669
38  chr12   68725743   68725965      +  21  119       222     86085891
39  chr12   68725966   68725971      +  28  120         5     86085896
40  chr12   68725972   68778947      +  26  121     52975     86138871
41  chr12   68778948   68779099      +  27  122       151     86139022
42  chr12   68779100   68870309      +  24  123     91209     86230231
43  chr12   68870310   68873717      +  29  124      3407     86233638
44  chr12   68873718   68879516      +  32  125      5798     86239436
45  chr12   68879517   68920718      +  31  126     41201     86280637
46  chr12   68920719   68974950      +  28  127     54231     86334868
47  chr12   61195642   61293865      +  14  110     98223     86433091
48  chr12   77717157   77740931      -  24 -165     23774     86456865
49   chr1  185950317  185957592      +  21   88      7275     86464140
50   chr1  185957593  185962817      +  15   89      5224     86469364
51   chr1  185962818  186209811      +   9   90    246993     86716357
52   chr1  186209812  186238802      +   8   91     28990     86745347

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48
49       49
50       50
51       51
52       52
gene CDK4
error!!!! in row index 0
gene MDM2
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_13/226349-WG01_walk_1_MDM2_containing_breakpoints.pdf
running patient  14
running file  226355-WG01_walk_2_MYCN_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0   chr19   24897100   24908203      -  11 -1082     11103        11103
1    chr5  169228698  169229189      -  19 -1540       491        11594
2    chr5  169051916  169228697      -  12 -1539    176781       188375
3   chr12   92719179   92730508      -  50  -781     11329       199704
4    chr6   80412729   80630872      +  11  1616    218143       417847
5    chr6   81910728   81957658      +  16  1628     46930       464777
6    chr5   29786203   29863433      -  13 -1452     77230       542007
7    chr5   29758277   29786202      -  21 -1451     27925       569932
8    chr5   29700788   29758276      -  13 -1450     57488       627420
9    chr5   29664203   29700787      -  22 -1449     36584       664004
10   chr5   29593920   29664202      -  13 -1448     70282       734286
11  chr12   88834349   88877908      -  12  -657     43559       777845
12  chr12   91820679   91837246      -  56  -696     16567       794412
13  chr12   91819942   91820678      -  59  -695       736       795148
14  chr12   91705771   91819941      -  37  -694    114170       909318
15   chr2   53648318   53697490      -   9 -1112     49172       958490
16   chr2   49712660   53648317      -   5 -1111   3935657      4894147
17   chr2   49351627   49712659      -   8 -1110    361032      5255179
18   chr2   49226694   49351626      -   9 -1109    124932      5380111
19   chr2          1   49226693      -   5 -1108  49226692     54606803

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19

gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226355-WG01_walk_3_MYC_containing.fa
bed file       chr     start        end strand  cn     5       span  span_cumsum  \
0    chr8   8420293  145138636      -   4 -1769  136718343    136718343
1    chr8   8413139    8420292      -  19 -1768       7153    136725496
2    chr8   8397243    8401521      -  19 -1766       4278    136729774
3    chr8   2960584    8397242      -   4 -1765    5436658    142166432
4    chr8   2955330    2960583      -  14 -1764       5253    142171685
5   chr12  91968518   91969016      +  81   711        498    142172183
6   chr12  80873281   80927091      +  21   612      53810    142225993
7   chr12  93968879   93973468      -  39  -805       4589    142230582
8   chr12  93883522   93968878      -  48  -804      85356    142315938
9   chr12  93881827   93883521      -  69  -803       1694    142317632
10  chr12  93881449   93881826      -  77  -802        377    142318009
11  chr12  84053740   84070765      -  29  -629      17025    142335034
12   chr5  29664203   29700787      -  22 -1449      36584    142371618

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226356-WG01_walk_1_MYC_containing.fa
bed file      chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr12  68317603   68464402      +   7   29     146799       146799        0
1  chr12  68464403   68464412      +   4   30          9       146808        1
2   chr8    947436    8397242      +   2   95    7449806      7596614        2
3   chr8   8397243    8608873      +   3   96     211630      7808244        3
4   chr8   8608874   17734932      +   2   97    9126058     16934302        4
5   chr8  17734933   20498880      +   3   98    2763947     19698249        5
6   chr8  21786697  145138636      +   2  100  123351939    143050188        6
gene ARHGEF10
gene PCM1
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226356-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226355-WG01_walk_1_MDM2_containing.fa
bed file        chr     start       end strand  cn    5   span  span_cumsum  bed_idx
0    chr12  69042111  69044402      -  59 -535   2291         2291        0
1    chr12  69035326  69042110      -  79 -534   6784         9075        1
2    chr12  69029763  69035325      -  74 -533   5562        14637        2
3    chr12  69015877  69029762      -  81 -532  13885        28522        3
4    chr12  69015396  69015876      -  83 -531    480        29002        4
..     ...       ...       ...    ...  ..  ...    ...          ...      ...
217  chr12  93881449  93881826      +  77  802    377     48050073      217
218  chr12  93881827  93883521      +  69  803   1694     48051767      218
219  chr12  93883522  93968878      +  48  804  85356     48137123      219
220  chr12  93968879  93973468      +  39  805   4589     48141712      220
221  chr12  93973469  94017402      +  20  806  43933     48185645      221

[222 rows x 9 columns]
gene MDM2
error!!!! in row index 0
gene MDM2
error!!!! in row index 1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene CDC73
gene PTPRC
gene CDK4
gene CDK4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226355-WG01_walk_2_MYC_containing.fa
bed file       chr      start        end strand  cn     5       span  span_cumsum  \
0   chr11   30183397   30529402      -  11  -333     346005       346005
1   chr11   29807841   30183396      -  13  -332     375555       721560
2   chr11   29807599   29807840      -  11  -331        241       721801
3   chr11   29361312   29807598      -  12  -330     446286      1168087
4   chr12  106629267  106678633      +  24   989      49366      1217453
5   chr12  106678634  106695704      +  27   990      17070      1234523
6   chr12  106695705  106753719      +  14   991      58014      1292537
7   chr12  106753720  106757436      +  17   992       3716      1296253
8   chr12   81079885   81105617      -  15  -614      25732      1321985
9   chr12   80927092   81079884      -   2  -613     152792      1474777
10  chr12   80873281   80927091      -  21  -612      53810      1528587
11  chr12   91968518   91969016      -  81  -711        498      1529085
12   chr8    2955330    2960583      +  14  1764       5253      1534338
13   chr8    2960584    8397242      +   4  1765    5436658      6970996
14   chr8    8397243    8401521      +  19  1766       4278      6975274
15   chr8    8413139    8420292      +  19  1768       7153      6982427
16   chr8    8420293  145138636      +   4  1769  136718343    143700770

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226356-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr12  67457745  67545602      -   3 -27     87857        87857        0
1   chr12  67455803  67457744      -   8 -26      1941        89798        1
2   chr12  66918403  67455802      -   2 -25    537399       627197        2
3   chr12  66670003  66918402      -   3 -24    248399       875596        3
4   chr12  66531013  66670002      -   5 -23    138989      1014585        4
5   chr12  66454803  66531012      -   3 -22     76209      1090794        5
6   chr12  66370803  66454802      -   7 -21     83999      1174793        6
7   chr12  66370496  66370802      -   3 -20       306      1175099        7
8   chr12  66107003  66370495      -   2 -19    263492      1438591        8
9   chr12  65766403  66107002      -   5 -18    340599      1779190        9
10  chr12  60316803  65766402      -   2 -17   5449599      7228789       10
11  chr12  60059803  60316802      -   4 -16    256999      7485788       11
12  chr12  58684603  60059802      -   2 -15   1375199      8860987       12
13  chr12  58642191  58684602      -   3 -14     42411      8903398       13
14  chr12  58326803  58642190      -   2 -13    315387      9218785       14
15  chr12  58190003  58326802      -   4 -12    136799      9355584       15
16  chr12  57985003  58190002      -   2 -11    204999      9560583       16
17  chr12  57676457  57985002      -   5 -10    308545      9869128       17
18  chr12         1  57676456      -   2  -9  57676455     67545583       18
gene HMGA2
gene WIF1
gene LRIG3
gene CDK4
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 11
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA

gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226356-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226356-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  170611299      +   2  1  170611298    170611298        0
1  chr1  170611300  172489906      +   4  2    1878606    172489904        1
2  chr1  172489907  229065117      +   2  3   56575210    229065114        2
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ABL2
gene CDC73
gene PTPRC
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226356-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226354-WG01_walk_1_KRAS_containing.fa
bed file        chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr12         1  34893402      +   4  382  34893401     34893401        0
1    chr12  34893403  54086003      +   3  383  19192600     54086001        1
2    chr12  54086004  57676456      +   4  384   3590452     57676453        2
3    chr12  57676457  57714090      +  56  385     37633     57714086        3
4    chr12  57714091  57723571      +  79  386      9480     57723566        4
..     ...       ...       ...    ...  ..  ...       ...          ...      ...
243  chr12  57714091  57723571      -  79 -386      9480     60470242      243
244  chr12  57676457  57714090      -  56 -385     37633     60507875      244
245  chr12  54086004  57676456      -   4 -384   3590452     64098327      245
246  chr12  34893403  54086003      -   3 -383  19192600     83290927      246
247  chr12         1  34893402      -   4 -382  34893401    118184328      247

[248 rows x 9 columns]
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene CDK4
gene CDK4
gene BTG1
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene BTG1
gene CDK4
gene CDK4
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 53
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226356-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  58642191  58684602      -   3 -14     42411        42411        0
1  chr12  58326803  58642190      -   2 -13    315387       357798        1
2  chr12  58190003  58326802      -   4 -12    136799       494597        2
3  chr12  57985003  58190002      -   2 -11    204999       699596        3
4  chr12  57676457  57985002      -   5 -10    308545      1008141        4
5  chr12         1  57676456      -   2  -9  57676455     58684596        5
gene CDK4
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226356-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226354-WG01_walk_3_KRAS_containing.fa
bed file      chr  start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12      1  34893402      +   4  382  34893401     34893401        0
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226354-WG01_walk_4_MYCN_containing.fa
bed file       chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0    chr2         1  53648317      +   5  1068  53648316     53648316        0
1    chr2  53648318  53697490      +   9  1069     49172     53697488        1
2   chr12  91705771  91819941      +  37   678    114170     53811658        2
3   chr12  91819942  91820678      +  56   679       736     53812394        3
4   chr11  63019663  63321485      +   4   367    301822     54114216        4
5   chr11  63321486  63336371      +   6   368     14885     54129101        5
6   chr11  63336372  63359837      +  15   369     23465     54152566        6
7   chr12  88682901  88694759      -  19  -638     11858     54164424        7
8   chr12  96423597  96429944      -  43  -878      6347     54170771        8
9   chr12  96423341  96423596      -  89  -877       255     54171026        9
10  chr12  97529068  97543609      +  55   899     14541     54185567       10
11  chr12  68641558  68644085      +  55   497      2527     54188094       11
12  chr12  68644086  68691082      +  83   498     46996     54235090       12
13  chr12  68691083  68694453      +  76   499      3370     54238460       13
14  chr12  68694454  68727733      +  75   500     33279     54271739       14
15  chr12  68727734  68729596      +  76   501      1862     54273601       15
16  chr12  91920221  91923569      -  83  -687      3348     54276949       16
17  chr12  91906458  91920220      -  78  -686     13762     54290711       17
18  chr12  91901328  91906457      -  77  -685      5129     54295840       18
19   chr6  99786973  99802489      -  22 -1589     15516     54311356       19
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226355-WG01_walk_2_MYCL_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0    chr5   29758277   29786202      -   21 -1451     27925        27925
1    chr1   14052595   14117662      +   13     3     65067        92992
2    chr1   14117663   23301082      +    4     4   9183419      9276411
3    chr1   23301083   40252697      +    3     5  16951614     26228025
4    chr1   40252698   45441688      +    4     6   5188990     31417015
5    chr1   45441689   50082031      +    3     7   4640342     36057357
6    chr1   50082032   51467341      +    4     8   1385309     37442666
7    chr1   51467342   57713803      +    3     9   6246461     43689127
8    chr1   57713804   60931683      +    4    10   3217879     46907006
9    chr1   60931684   61184851      +    3    11    253167     47160173
10   chr1   61184852   62541380      +    3    12   1356528     48516701
11   chr1   62541381   62548210      +    7    13      6829     48523530
12   chr1   62548211   64728729      +    4    14   2180518     50704048
13   chr1   64728730   64749675      +    5    15     20945     50724993
14   chr1   64749676   64862175      +   12    16    112499     50837492
15  chr12   91557790   91571340      +   43   685     13550     50851042
16  chr12   91571341   91609306      +   57   686     37965     50889007
17  chr12   91609307   91617487      +   53   687      8180     50897187
18  chr12   91617488   91628264      +   55   688     10776     50907963
19  chr12   91628265   91640538      +   48   689     12273     50920236
20  chr12   91640539   91664320      +   45   690     23781     50944017
21   chr2  183922295  183945294      +   10  1172     22999     50967016
22   chr2  183945295  183964426      +    4  1173     19131     50986147
23   chr2  183964427  184084468      +    6  1174    120041     51106188
24   chr2  184084469  185657068      +    4  1175   1572599     52678787
25   chr2  185657069  185789243      +    5  1176    132174     52810961
26   chr2  185789244  186376992      +    6  1177    587748     53398709
27   chr2  186376993  186748200      +    5  1178    371207     53769916
28   chr2  186748201  187593840      +    4  1179    845639     54615555
29   chr2  187593841  189775074      +    5  1180   2181233     56796788
30   chr2  189775075  192087250      +    6  1181   2312175     59108963
31   chr2  192087251  192384526      +    7  1182    297275     59406238
32   chr2  192384527  192505353      +   18  1183    120826     59527064
33  chr12   92303740   92310735      +  146   754      6995     59534059
34  chr12   92310736   92321392      +  139   755     10656     59544715
35   chr4   15757908   15773013      -   20 -1286     15105     59559820
36   chr4   15749362   15757907      -   19 -1285      8545     59568365
37  chr12   68328945   68335257      -   55  -488      6312     59574677
38  chr12   68325088   68328944      -   63  -487      3856     59578533
39  chr12   68317499   68325087      -   45  -486      7588     59586121
40  chr12   65401389   65401798      +   45   435       409     59586530
41  chr12   75830413   75851580      -   47  -585     21167     59607697
42  chr12   75818981   75830412      -   44  -584     11431     59619128
43  chr12   75535280   75605465      -   35  -581     70185     59689313
44  chr12   67456182   67457744      -   46  -474      1562     59690875
45  chr12   67492255   67496351      +   43   477      4096     59694971
46  chr12   57897896   57985095      -   33  -399     87199     59782170
47  chr12   57892726   57897895      -   36  -398      5169     59787339
48  chr12   57892648   57892725      -   49  -397        77     59787416
49  chr12   57891208   57892647      -   54  -396      1439     59788855
50  chr12   57880971   57891207      -   51  -395     10236     59799091
51  chr12   92167952   92174055      -  152  -736      6103     59805194
52  chr12   92165025   92167951      -  165  -735      2926     59808120
53  chr12   92164365   92165024      -  152  -734       659     59808779
54   chr6  129475401  129494762      +   23  1697     19361     59828140
55  chr12   92224179   92231737      +  128   744      7558     59835698
56  chr12   92231738   92232369      +  153   745       631     59836329

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48
49       49
50       50
51       51
52       52
53       53
54       54
55       55
56       56

gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene ID3
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene EPS15
gene JUN
gene JAK1
gene ITGAV
gene COL3A1
gene PMS1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226355-WG01_walk_3_MYCN_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0    chr2          1   49226693      +   5  1108  49226692     49226692
1    chr2   49226694   49351626      +   9  1109    124932     49351624
2    chr2   49351627   49712659      +   8  1110    361032     49712656
3    chr2   49712660   53648317      +   5  1111   3935657     53648313
4    chr2   53648318   53697490      +   9  1112     49172     53697485
5   chr12   91705771   91819941      +  37   694    114170     53811655
6   chr12   91819942   91820678      +  59   695       736     53812391
7   chr11   63019663   63057532      +   7   362     37869     53850260
8   chr12   69600603   69641649      -  44  -567     41046     53891306
9   chr12   69591582   69600602      -  55  -566      9020     53900326
10  chr12   95560875   95593598      -  41  -884     32723     53933049
11  chr12   95548947   95560874      -  47  -883     11927     53944976
12   chr6   73862688   74087395      -  11 -1609    224707     54169683
13   chr1  225440009  225468402      +  18    99     28393     54198076

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene USP44
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226354-WG01_walk_1_MYC_containing.fa
bed file     chr    start        end strand  cn     5       span  span_cumsum  bed_idx
0  chr8  2956593    2960583      +  14  1727       3990         3990        0
1  chr8  2960584    8397241      +   4  1728    5436657      5440647        1
2  chr8  8397242    8401521      +  18  1729       4279      5444926        2
3  chr8  8413139    8420292      +  18  1731       7153      5452079        3
4  chr8  8420293  145138636      +   4  1732  136718343    142170422        4
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226355-WG01_walk_4_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1  34508125      +   4  377  34508124     34508124        0
1  chr12  34508126  37183002      +   4  378   2674876     37183000        1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226355-WG01_walk_3_KRAS_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0   chr12  104229403  104230309      +   55   969       906          906
1   chr12  104230310  104251073      +   57   970     20763        21669
2   chr12  104251074  104259781      +   55   971      8707        30376
3   chr12  104259782  104267829      +   54   972      8047        38423
4   chr12  104267830  104271774      +   52   973      3944        42367
5    chr8    8397243    8401521      +   19  1766      4278        46645
6    chr8    8401522    8413138      +   14  1767     11616        58261
7    chr8    8413139    8420292      +   19  1768      7153        65414
8   chr12   66472304   66473163      +   27   454       859        66273
9   chr12   66473164   66512227      +   11   455     39063       105336
10  chr12   66512228   66531012      +   15   456     18784       124120
11  chr12   66531013   66611090      +   17   457     80077       204197
12  chr12   66611091   66635002      +   23   458     23911       228108
13  chr12   66635003   66635701      +   16   459       698       228806
14  chr12   66635702   66644119      +   15   460      8417       237223
15  chr12   66644120   66653142      +   33   461      9022       246245
16  chr12   92503939   92519873      +   28   770     15934       262179
17  chr12   92519874   92557991      +   30   771     38117       300296
18  chr12   92557992   92572239      +   32   772     14247       314543
19  chr12   92572240   92596593      +   39   773     24353       338896
20  chr12   92596594   92618008      +   36   774     21414       360310
21  chr12   92618009   92624214      +   32   775      6205       366515
22  chr12   92624215   92626014      +   28   776      1799       368314
23  chr12   92626015   92631810      +   32   777      5795       374109
24  chr12   92631811   92688422      +   40   778     56611       430720
25  chr12   92688423   92697325      +   45   779      8902       439622
26  chr12   92697326   92719178      +   46   780     21852       461474
27  chr12   92719179   92730508      +   50   781     11329       472803
28  chr12   92730509   92737064      +   46   782      6555       479358
29  chr12   91992364   91992474      -  179  -717       110       479468
30  chr12   91987083   91992363      -  171  -716      5280       484748
31  chr12   91972196   91987082      -  175  -715     14886       499634
32  chr12   91971203   91972195      -  172  -714       992       500626
33  chr12   91970003   91971202      -  163  -713      1199       501825
34  chr12   91969017   91970002      -   77  -712       985       502810
35  chr12   91968518   91969016      -   81  -711       498       503308
36  chr12   91949848   91968517      -   71  -710     18669       521977
37  chr12   91938808   91949847      -   75  -709     11039       533016
38  chr12  106965218  106976979      +   24   998     11761       544777
39  chr12  106976980  107020294      +   20   999     43314       588091
40  chr12  107020295  107047602      +   17  1000     27307       615398
41  chr12  107047603  107055202      +   22  1001      7599       622997
42  chr12  107055203  107128393      +   19  1002     73190       696187
43  chr12  107128394  107160402      +   23  1003     32008       728195
44  chr12  107160403  107215504      +   30  1004     55101       783296
45  chr12   57801644   57807689      -   66  -391      6045       789341
46  chr12   57799022   57801643      -   62  -390      2621       791962
47  chr12   57788991   57799021      -   66  -389     10030       801992
48  chr12   57787496   57788990      -   59  -388      1494       803486
49  chr12   57777789   57787495      -   55  -387      9706       813192
50  chr12   57751808   57777788      -   83  -386     25980       839172
51  chr12   57731673   57751807      -   82  -385     20134       859306
52  chr12   57723980   57731672      -   76  -384      7692       866998
53  chr12   57723572   57723979      -   74  -383       407       867405
54  chr12   57714091   57723571      -   79  -382      9480       876885
55  chr12   57676457   57714090      -   52  -381     37633       914518
56  chr12   54443432   57676456      -    4  -380   3233024      4147542
57  chr12   37183003   54443431      -    3  -379  17260428     21407970
58  chr12   34508126   37183002      -    4  -378   2674876     24082846
59  chr12          1   34508125      -    4  -377  34508124     58590970

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48
49       49
50       50
51       51
52       52
53       53
54       54
55       55
56       56
57       57
58       58
59       59

gene CDK4
gene CDK4
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 19
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_3_KRAS_containing_breakpoints.pdf
running file  226354-WG01_walk_3_MYCN_containing.fa
bed file     chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0  chr2  60916222  60977888      -   9 -1072     61666        61666        0
1  chr2  59177620  60916221      -   6 -1071   1738601      1800267        1
2  chr2  53697491  59177619      -   5 -1070   5480128      7280395        2
3  chr2  53648318  53697490      -   9 -1069     49172      7329567        3
4  chr2         1  53648317      -   5 -1068  53648316     60977883        4
gene REL
error!!!! in row index 0
gene BCL11A
gene REL
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226356-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr12   68641603   68796002      +  10  33    154399       154399        0
1   chr12   68796003   69218002      +   8  34    421999       576398        1
2   chr12   69218003   69328667      +  11  35    110664       687062        2
3   chr12   69328668   69455803      +  10  36    127135       814197        3
4   chr12   69455804   69506202      +  11  37     50398       864595        4
5   chr12   69506203   69680602      +   8  38    174399      1038994        5
6   chr12   69680603   69848802      +   6  39    168199      1207193        6
7   chr12   69848803   75535279      +   2  40   5686476      6893669        7
8   chr12   75535280   75605465      +   7  41     70185      6963854        8
9   chr12   75818981   86568519      +   2  43  10749538     17713392        9
10  chr12   86568520   87950248      +   3  44   1381728     19095120       10
11  chr12   87950249   91487002      +   2  45   3536753     22631873       11
12  chr12   91487003   91583909      +   5  46     96906     22728779       12
13  chr12   91583910   91626002      +   6  47     42092     22770871       13
14  chr12   91626003   91818802      +   4  48    192799     22963670       14
15  chr12   91818803   91969994      +   6  49    151191     23114861       15
16  chr12   91969995   92157402      +  15  50    187407     23302268       16
17  chr12   92157403   92258202      +  10  51    100799     23403067       17
18  chr12   92258203   92394523      +  12  52    136320     23539387       18
19  chr12   92394524   94998495      +   3  53   2603971     26143358       19
20  chr12   94998496   95560874      +   5  54    562378     26705736       20
21  chr12   95560875   95736650      +   6  55    175775     26881511       21
22  chr12   95736651   95978010      +   3  56    241359     27122870       22
23  chr12   95978011   96371665      +   4  57    393654     27516524       23
24  chr12   96371666   97031797      +   2  58    660131     28176655       24
25  chr12   97031798   97113036      +   5  59     81238     28257893       25
26  chr12   97113037   97543609      +   3  60    430572     28688465       26
27  chr12   97543610  100488597      +   2  61   2944987     31633452       27
28  chr12  100488598  101323776      +   3  62    835178     32468630       28
29  chr12  101323777  104230309      +   2  63   2906532     35375162       29
30  chr12  104230310  104271774      +   4  64     41464     35416626       30
31  chr12  104271775  104334559      +   3  65     62784     35479410       31
32  chr12  104334560  104657482      +   2  66    322922     35802332       32
33  chr12  104657483  104665008      +   4  67      7525     35809857       33
34  chr12  104665009  106774135      +   2  68   2109126     37918983       34
35  chr12  106774136  106822604      +   3  69     48468     37967451       35
36  chr12  106822605  133275309      +   2  70  26452704     64420155       36
gene MDM2
error!!!! in row index 0
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene CHST11
gene CHST11
gene TBX3
gene SETD1B
gene ZCCHC8
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226356-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226354-WG01_walk_1_MYCL_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0    chr1   12101326   13489640      +   5     4   1388314      1388314
1    chr1   13489641   14117662      +   5     5    628021      2016335
2    chr1   14117663   50082031      +   4     6  35964368     37980703
3    chr1   50082032   50300257      +  12     7    218225     38198928
4    chr1   50300258   55184438      +   3     8   4884180     43083108
5    chr1   55184439   62541380      +   4     9   7356941     50440049
6    chr1   62541381   62548210      +  12    10      6829     50446878
7    chr1   62548211   64728729      +   4    11   2180518     52627396
8    chr1   64728730   64862175      +  11    12    133445     52760841
9   chr12   91557790   91571340      +  44   670     13550     52774391
10  chr12   91571341   91617487      +  57   671     46146     52820537
11  chr12   91617488   91625825      +  69   672      8337     52828874
12  chr12   91625826   91628264      +  68   673      2438     52831312
13  chr12   91628265   91640538      +  49   674     12273     52843585
14  chr12   91640539   91664320      +  44   675     23781     52867366
15   chr2  183922295  183945294      +  14  1121     22999     52890365
16   chr5   15603617   15617934      -  19 -1309     14317     52904682
17   chr5   15557809   15603616      -  10 -1308     45807     52950489
18   chr5   15528163   15557808      -  11 -1307     29645     52980134
19   chr5   15421893   15528162      -   6 -1306    106269     53086403
20   chr5   15367553   15421892      -  13 -1305     54339     53140742
21   chr5   15326457   15367552      -   8 -1304     41095     53181837
22   chr5   14882332   15326456      -   7 -1303    444124     53625961
23   chr5   14816022   14882331      -  11 -1302     66309     53692270
24   chr1  243484874  243615202      +  16   179    130328     53822598

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
gene PRDM2
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CDKN2C
gene EPS15
gene JUN
gene JAK1
gene AKT3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226354-WG01_walk_2_MYCN_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0    chr2          1   53648317      +    5  1068  53648316     53648316
1    chr2   53648318   53697490      +    9  1069     49172     53697488
2   chr12   91705771   91819941      +   37   678    114170     53811658
3   chr12   91819942   91820678      +   56   679       736     53812394
4   chr12   91820679   91837246      +   55   680     16567     53828961
5   chr12   88834349   89084002      +   11   640    249653     54078614
6   chr12   89084003   89306202      +   10   641    222199     54300813
7   chr12   89306203   89311906      +   13   642      5703     54306516
8   chr12   89311907   89334355      +   18   643     22448     54328964
9    chr4   15307205   15348414      +   10  1238     41209     54370173
10   chr4   15348415   15749361      +    5  1239    400946     54771119
11   chr4   15749362   15772923      +   20  1240     23561     54794680
12   chr4   15772924   21838091      +    4  1241   6065167     60859847
13   chr4   21838092   21854166      +   11  1242     16074     60875921
14  chr12   66707657   66886947      +   22   463    179290     61055211
15  chr12   66886948   66893644      +   27   464      6696     61061907
16  chr12   66893645   66905770      +   30   465     12125     61074032
17   chr1  239308138  239316873      +   16   140      8735     61082767
18  chr12   94717804   94728208      -   73  -813     10404     61093171
19  chr12   94705810   94717803      -   67  -812     11993     61105164
20  chr12   94702189   94705809      -   63  -811      3620     61108784
21  chr10  104390154  104390988      -   15  -302       834     61109618
22  chr10   52626397   52627925      -   14  -256      1528     61111146
23  chr10  100805691  100808178      -   17  -296      2487     61113633
24   chr9  123923227  123956232      +   17  1795     33005     61146638
25   chr9  123956444  123956678      -   11 -1797       234     61146872
26  chr12   92266054   92270847      -  128  -722      4793     61151665
27  chr12   79573174   79692234      -   17  -591    119060     61270725
28  chr12   79547922   79573173      -   16  -590     25251     61295976
29  chr12   79510003   79547921      -   24  -589     37918     61333894
30  chr12   79447372   79510002      -   33  -588     62630     61396524
31   chr1  244304734  244353186      -   43  -200     48452     61444976
32   chr1  244284003  244304733      -   42  -199     20730     61465706

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32

gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226355-WG01_walk_2_KRAS_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0   chr12          1   34508125      +    4   377  34508124     34508124
1   chr12   34508126   37183002      +    4   378   2674876     37183000
2   chr12   37183003   54443431      +    3   379  17260428     54443428
3   chr12   54443432   57676456      +    4   380   3233024     57676452
4   chr12   57676457   57714090      +   52   381     37633     57714085
5   chr12   57714091   57723571      +   79   382      9480     57723565
6   chr12   57723572   57723979      +   74   383       407     57723972
7   chr12   57723980   57731672      +   76   384      7692     57731664
8   chr12   57731673   57751807      +   82   385     20134     57751798
9   chr12   57751808   57777788      +   83   386     25980     57777778
10  chr12   57777789   57787495      +   55   387      9706     57787484
11  chr12   57787496   57788990      +   59   388      1494     57788978
12  chr12   57788991   57799021      +   66   389     10030     57799008
13  chr12   57799022   57801643      +   62   390      2621     57801629
14  chr12   57801644   57807689      +   66   391      6045     57807674
15  chr12  107160403  107215504      -   30 -1004     55101     57862775
16  chr12  107128394  107160402      -   23 -1003     32008     57894783
17  chr12  107055203  107128393      -   19 -1002     73190     57967973
18  chr12  107047603  107055202      -   22 -1001      7599     57975572
19  chr12  107020295  107047602      -   17 -1000     27307     58002879
20  chr12  106976980  107020294      -   20  -999     43314     58046193
21  chr12  106965218  106976979      -   24  -998     11761     58057954
22  chr12   91938808   91949847      +   75   709     11039     58068993
23  chr12   91949848   91968517      +   71   710     18669     58087662
24  chr12   91968518   91969016      +   81   711       498     58088160
25  chr12   91969017   91970002      +   77   712       985     58089145
26  chr12   91970003   91971202      +  163   713      1199     58090344
27  chr12   91971203   91972195      +  172   714       992     58091336
28  chr12   91972196   91987082      +  175   715     14886     58106222
29  chr12   91987083   91992363      +  171   716      5280     58111502
30  chr12   91992364   91992474      +  179   717       110     58111612
31  chr12   92730509   92737064      -   46  -782      6555     58118167
32  chr12   92719179   92730508      -   50  -781     11329     58129496
33  chr12   92697326   92719178      -   46  -780     21852     58151348
34  chr12   92688423   92697325      -   45  -779      8902     58160250
35  chr12   92631811   92688422      -   40  -778     56611     58216861
36   chr5  172018145  172035068      -   15 -1556     16923     58233784
37   chr5  171796158  172018144      -    7 -1555    221986     58455770
38   chr5  171751773  171796157      -   12 -1554     44384     58500154
39   chr5  171719460  171751772      -   18 -1553     32312     58532466
40   chr5  171385805  171719459      -    9 -1552    333654     58866120
41  chr12   94366141   94397060      -   32  -817     30919     58897039
42  chr12   94362273   94366140      -   35  -816      3867     58900906
43  chr12   94354803   94362272      -   41  -815      7469     58908375
44  chr12   94354778   94354802      -   24  -814        24     58908399
45  chr12   94351490   94354777      -   10  -813      3287     58911686
46  chr12   94322526   94351489      -   18  -812     28963     58940649
47  chr12   94318427   94322525      -   22  -811      4098     58944747
48  chr12   89692265   89703860      +   26   667     11595     58956342
49  chr12   89703861   89705202      +   23   668      1341     58957683

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48
49       49
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene CDK4
gene CDK4
gene NPM1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226356-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  170611299      +   2  1  170611298    170611298        0
1  chr1  170611300  172489906      +   4  2    1878606    172489904        1
2  chr1  172489907  229065117      +   2  3   56575210    229065114        2
3  chr1  229065118  248956422      +   2  4   19891304    248956418        3
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ABL2
gene CDC73
gene PTPRC
gene FH
gene AKT3
gene RGS7
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226356-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226354-WG01_walk_3_MYCL_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0    chr1   12101326   13489640      +   5     4   1388314      1388314
1    chr1   13489641   14117662      +   5     5    628021      2016335
2    chr1   14117663   50082031      +   4     6  35964368     37980703
3    chr1   50082032   50300257      +  12     7    218225     38198928
4    chr1   69129078   69203213      -  12   -18     74135     38273063
5    chr1   62541381   62548210      -  12   -10      6829     38279892
6    chr1   68658397   68668470      -  12   -16     10073     38289965
7   chr12   57852108   57852338      +  49   396       230     38290195
8   chr12   57852339   57892731      +  53   397     40392     38330587
9   chr12   57892732   57897895      +  35   398      5163     38335750
10   chr5  172957120  173001962      +  10  1501     44842     38380592
11   chr5   67310205   67455602      +   7  1435    145397     38525989
12   chr5   67455603   67564530      +   4  1436    108927     38634916
13   chr5   67564531   67620002      +   8  1437     55471     38690387

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
gene PRDM2
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A

saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226354-WG01_walk_2_KRAS_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0    chr5    9252299    9990894      -   5 -1291    738595       738595
1    chr6   80994494   81262536      -  14 -1563    268042      1006637
2    chr5  171534145  171566187      -  11 -1494     32042      1038679
3    chr5  171385805  171534144      -  10 -1493    148339      1187018
4   chr12   94354778   94397060      -  33  -794     42282      1229300
5   chr12   94318427   94354777      -  19  -793     36350      1265650
6   chr12   89692265   89692402      +  24   649       137      1265787
7   chr12   89692403   89704802      +  25   650     12399      1278186
8   chr12   89704803   89756258      +   8   651     51455      1329641
9   chr12   57714091   57723571      -  79  -386      9480      1339121
10  chr12   57676457   57714090      -  56  -385     37633      1376754
11  chr12   54086004   57676456      -   4  -384   3590452      4967206
12  chr12   34893403   54086003      -   3  -383  19192600     24159806
13  chr12          1   34893402      -   4  -382  34893401     59053207

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
gene NPM1
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 18
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226354-WG01_walk_4_MYCL_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0   chr12   66913038   66916802      -  22  -467      3764         3764
1    chr6   81886969   82027151      -  14 -1577    140182       143946
2   chr12   69015396   69015876      -  85  -518       480       144426
3   chr12   69011588   69015395      -  84  -517      3807       148233
4   chr12   68990884   69011587      -  88  -516     20703       168936
5   chr12   68985537   68990883      -  95  -515      5346       174282
6   chr12   68971603   68985536      -  86  -514     13933       188215
7   chr12   68965146   68971602      -  73  -513      6456       194671
8    chr1   69258025   69340927      +   4    20     82902       277573
9    chr1   13489641   14117662      +   5     5    628021       905594
10   chr1   14117663   50082031      +   4     6  35964368     36869962
11   chr1   50082032   50300257      +  12     7    218225     37088187
12   chr1   69129078   69203213      -  12   -18     74135     37162322
13   chr1   62541381   62548210      -  12   -10      6829     37169151
14   chr1   68658397   68668470      -  12   -16     10073     37179224
15  chr12   57852108   57852338      +  49   396       230     37179454
16  chr12   57852339   57892731      +  53   397     40392     37219846
17  chr12   57892732   57897895      +  35   398      5163     37225009
18   chr5  172957120  173001962      +  10  1501     44842     37269851
19   chr5   67310205   67455602      +   7  1435    145397     37415248

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
gene PRDM2
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_4_MYCL_containing_breakpoints.pdf
running file  226354-WG01_walk_1_MDM2_containing.fa
bed file        chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr12         1  34893402      +   4  382  34893401     34893401        0
1    chr12  34893403  54086003      +   3  383  19192600     54086001        1
2    chr12  54086004  57676456      +   4  384   3590452     57676453        2
3    chr12  57676457  57714090      +  56  385     37633     57714086        3
4    chr12  57714091  57723571      +  79  386      9480     57723566        4
..     ...       ...       ...    ...  ..  ...       ...          ...      ...
243  chr12  57714091  57723571      -  79 -386      9480     60470242      243
244  chr12  57676457  57714090      -  56 -385     37633     60507875      244
245  chr12  54086004  57676456      -   4 -384   3590452     64098327      245
246  chr12  34893403  54086003      -   3 -383  19192600     83290927      246
247  chr12         1  34893402      -   4 -382  34893401    118184328      247

[248 rows x 9 columns]
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene CDK4
gene CDK4
gene BTG1
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene BTG1
gene CDK4
gene CDK4
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 53
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226355-WG01_walk_1_MYCL_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0    chr5   29758277   29786202      -   21 -1451     27925        27925
1    chr1   14052595   14117662      +   13     3     65067        92992
2    chr1   14117663   23301082      +    4     4   9183419      9276411
3    chr1   23301083   40252697      +    3     5  16951614     26228025
4    chr1   40252698   45441688      +    4     6   5188990     31417015
5    chr1   45441689   50082031      +    3     7   4640342     36057357
6    chr1   50082032   51467341      +    4     8   1385309     37442666
7    chr1   51467342   57713803      +    3     9   6246461     43689127
8    chr1   57713804   60931683      +    4    10   3217879     46907006
9    chr1   60931684   61184851      +    3    11    253167     47160173
10   chr1   61184852   62541380      +    3    12   1356528     48516701
11   chr1   62541381   62548210      +    7    13      6829     48523530
12   chr1   62548211   64728729      +    4    14   2180518     50704048
13   chr1   64728730   64749675      +    5    15     20945     50724993
14   chr1   64749676   64862175      +   12    16    112499     50837492
15  chr12   91557790   91571340      +   43   685     13550     50851042
16  chr12   91571341   91609306      +   57   686     37965     50889007
17  chr12   91609307   91617487      +   53   687      8180     50897187
18  chr12   91617488   91628264      +   55   688     10776     50907963
19  chr12   91628265   91640538      +   48   689     12273     50920236
20  chr12   91640539   91664320      +   45   690     23781     50944017
21   chr2  183922295  183945294      +   10  1172     22999     50967016
22   chr2  183945295  183964426      +    4  1173     19131     50986147
23   chr2  183964427  184084468      +    6  1174    120041     51106188
24   chr2  184084469  185657068      +    4  1175   1572599     52678787
25   chr2  185657069  185789243      +    5  1176    132174     52810961
26   chr2  185789244  186376992      +    6  1177    587748     53398709
27   chr2  186376993  186748200      +    5  1178    371207     53769916
28   chr2  186748201  187593840      +    4  1179    845639     54615555
29   chr2  187593841  189775074      +    5  1180   2181233     56796788
30   chr2  189775075  192087250      +    6  1181   2312175     59108963
31   chr2  192087251  192384526      +    7  1182    297275     59406238
32   chr2  192384527  192505353      +   18  1183    120826     59527064
33  chr12   92303740   92310735      +  146   754      6995     59534059
34  chr12   92310736   92321392      +  139   755     10656     59544715
35  chr12   92321393   92321460      +  123   756        67     59544782
36  chr10  111093801  111097938      -   25  -297      4137     59548919
37  chr10  110694567  111093800      -    4  -296    399233     59948152
38  chr10  110465469  110694566      -    5  -295    229097     60177249
39  chr10  110443976  110465468      -    4  -294     21492     60198741
40  chr10  110401919  110443975      -   15  -293     42056     60240797
41  chr10  110352733  110401918      -    5  -292     49185     60289982
42  chr10  110226540  110352732      -   12  -291    126192     60416174
43  chr10  109527343  110226539      -    5  -290    699196     61115370
44  chr10  106950733  109527342      -    4  -289   2576609     63691979
45  chr10  105854873  106950732      -    5  -288   1095859     64787838
46  chr10  104390989  105854872      -    4  -287   1463883     66251721
47  chr10  104390154  104390988      -   16  -286       834     66252555
48  chr10   52626397   52627925      -   16  -236      1528     66254083
49  chr10  100805691  100808178      -   16  -279      2487     66256570
50   chr9  123923227  123956231      +   16  1835     33004     66289574
51   chr9  123956444  123956674      -   16 -1837       230     66289804
52   chr9  123956232  123956443      -   13 -1836       211     66290015
53   chr9  123923227  123956231      -   16 -1835     33004     66323019
54  chr10  100805691  100808178      +   16   279      2487     66325506
55  chr10  100808179  101534467      +    4   280    726288     67051794

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48
49       49
50       50
51       51
52       52
53       53
54       54
55       55

gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene ID3
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene EPS15
gene JUN
gene JAK1
gene ITGAV
gene COL3A1
gene PMS1
gene TLX1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226355-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand  cn     5       span  span_cumsum  \
0    chr8    8420293  145138636      -   4 -1769  136718343    136718343
1    chr8    8413139    8420292      -  19 -1768       7153    136725496
2    chr8    8397243    8401521      -  19 -1766       4278    136729774
3    chr8    2960584    8397242      -   4 -1765    5436658    142166432
4    chr8    2955330    2960583      -  14 -1764       5253    142171685
5   chr12   91968518   91969016      +  81   711        498    142172183
6   chr12   80873281   80927091      +  21   612      53810    142225993
7   chr12   80927092   81079884      +   2   613     152792    142378785
8   chr12   81079885   81105617      +  15   614      25732    142404517
9   chr12  106753720  106757436      -  17  -992       3716    142408233
10  chr12   89692265   89703860      -  26  -667      11595    142419828
11  chr12   94318427   94322525      +  22   811       4098    142423926
12  chr12   94322526   94351489      +  18   812      28963    142452889
13  chr13   76248759   76507022      -  11 -1048     258263    142711152
14  chr13          1   76248758      -   3 -1047   76248757    218959909

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
gene LATS2
gene CDX2
gene CYSLTR2
gene ZMYM2
gene FLT3
gene BRCA2
gene LHFPL6
gene FOXO1
gene RB1
gene NBEA
gene LCP1
running file  226355-WG01_walk_3_MYCL_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0    chr1   50082032   51467341      -   4    -8   1385309      1385309
1    chr1   45441689   50082031      -   3    -7   4640342      6025651
2    chr1   40252698   45441688      -   4    -6   5188990     11214641
3    chr1   23301083   40252697      -   3    -5  16951614     28166255
4    chr1   14117663   23301082      -   4    -4   9183419     37349674
5    chr1   14052595   14117662      -  13    -3     65067     37414741
6    chr5   29758277   29786202      +  21  1451     27925     37442666
7    chr5   29786203   29863433      +  13  1452     77230     37519896
8    chr6   81910728   81957658      -  16 -1628     46930     37566826
9    chr6   81886969   81910727      -  14 -1627     23758     37590584
10  chr12   69015396   69015876      -  83  -531       480     37591064
11  chr12  100488598  100496695      -  17  -943      8097     37599161
12  chr12  104321660  104334559      -  15  -976     12899     37612060
13  chr12   95190403   95197049      -  53  -856      6646     37618706
14  chr12   95180636   95190402      -  70  -855      9766     37628472
15   chr9  125273737  125290808      -  22 -1840     17071     37645543
16   chr9  112968846  112976158      -  26 -1820      7312     37652855
17  chr10   28619885   28664496      -  26  -218     44611     37697466
18  chr12   95115464   95127434      +  46   851     11970     37709436
19  chr12   96060786   96075252      +  27   899     14466     37723902
20  chr12   68335280   68337112      +  45   490      1832     37725734

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
gene CDKN2C
gene EPS15
gene STIL
gene TAL1
gene MPL
gene MUTYH
gene ID3
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MDS2
gene ARID1A
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226355-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226354-WG01_walk_2_MYCL_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr1   12101326   13489640      +   5    4   1388314      1388314
1    chr1   13489641   14117662      +   5    5    628021      2016335
2    chr1   14117663   50082031      +   4    6  35964368     37980703
3    chr1   50082032   50300257      +  12    7    218225     38198928
4    chr1   69129078   69203213      -  12  -18     74135     38273063
5    chr1   62541381   62548210      -  12  -10      6829     38279892
6    chr1   68658397   68668470      -  12  -16     10073     38289965
7   chr12   57852108   57852338      +  49  396       230     38290195
8   chr12   57852339   57892731      +  53  397     40392     38330587
9   chr12   57892732   57897895      +  35  398      5163     38335750
10  chr12   57897896   57936259      +  33  399     38363     38374113
11  chr12   57936260   57957953      +  34  400     21693     38395806
12  chr12   57957954   57985095      +  33  401     27141     38422947
13  chr12   67492255   67496351      -  43 -476      4096     38427043
14  chr12   67456182   67457744      +  46  473      1562     38428605
15  chr12   67457745   67485721      +  14  474     27976     38456581
16   chr1  246219072  246219250      +  12  213       178     38456759
17   chr1  246219251  246291582      +   9  214     72331     38529090
18   chr1  246291583  246306391      +   8  215     14808     38543898
19   chr1  246306392  246334675      +  11  216     28283     38572181
20   chr1  246334676  246448179      +   7  217    113503     38685684
21   chr1  246448180  246881363      +   8  218    433183     39118867
22   chr1  246881364  247262054      +   7  219    380690     39499557
23   chr1  247262055  247893402      +   6  220    631347     40130904
24   chr1  247893403  248314800      +   5  221    421397     40552301
25   chr1  248314801  248376922      +   8  222     62121     40614422
26   chr1  248376923  248397750      +   5  223     20827     40635249
27   chr1  248397751  248956422      +   7  224    558671     41193920

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
gene PRDM2
gene ID3
gene MYCL
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226356-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  80  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2

gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226355-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0  chr17  73173959  83257441      -   4 -1068  10083482     10083482        0
1  chr17  21915480  73173958      -   3 -1067  51258478     61341960        1
2  chr17  21544660  21915479      -   4 -1066    370819     61712779        2
3  chr12         1  34508125      -   4  -377  34508124     96220903        3
gene H3F3B
gene SRSF2
gene CANT1
gene ASPSCR1
gene SEPT9
gene RNF213
gene CCR7
gene TAF15
gene MLLT6
gene LASP1
gene CDK12
gene RARA
gene ETV4
gene RNF43
gene PPM1D
gene CD79B
gene DDX5
gene PRKAR1A
gene NF1
gene SUZ12
gene ERBB2
gene SMARCE1
gene STAT3
gene STAT5B
gene BRCA1
gene COL1A1
gene KAT7
gene SPOP
gene HLF
gene CLTC
gene BRIP1
gene AXIN2
gene IKZF3
gene MSI2
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 36
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226355-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr3  172669686  198295559      -   3 -1280  25625873     25625873
1   chr3   97926057  172669685      -   3 -1279  74743628    100369501
2   chr3   97789989   97926056      -   6 -1278    136067    100505568
3  chr12   68682684   68688079      -  76  -504      5395    100510963
4   chr2   49351627   49712659      -   8 -1110    361032    100871995
5   chr2   49226694   49351626      -   9 -1109    124932    100996927
6   chr2          1   49226693      -   5 -1108  49226692    150223619

   bed_idx
0        0
1        1
2        2
3        3
4        4
5        5
6        6
gene SOX2
gene EIF4A2
gene ETV5
gene BCL6
gene MUC4
gene TFRC
gene TBL1XR1
gene PIK3CA
gene MAP3K13
gene IGF2BP2
gene MB21D2
gene LPP
gene TP63
gene FOXL2
gene TFG
gene GATA2
gene RPN1
gene CNBP
gene GMPS
gene MECOM
gene CBLB
gene POLQ
gene STAG1
gene PIK3CB
gene ATR
gene WWTR1
gene MLF1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  226354-WG01_walk_1_MYCN_containing.fa
bed file       chr     start       end strand   cn     5      span  span_cumsum  \
0    chr2         1  53648317      +    5  1068  53648316     53648316
1    chr2  53648318  53697490      +    9  1069     49172     53697488
2   chr12  91705771  91819941      +   37   678    114170     53811658
3   chr12  91819942  91820678      +   56   679       736     53812394
4   chr12  91820679  91837246      +   55   680     16567     53828961
5   chr12  88834349  89084002      +   11   640    249653     54078614
6   chr12  89084003  89306202      +   10   641    222199     54300813
7   chr12  89306203  89311906      +   13   642      5703     54306516
8   chr12  89311907  89334355      +   18   643     22448     54328964
9    chr4  15307205  15348414      +   10  1238     41209     54370173
10   chr4  15348415  15749361      +    5  1239    400946     54771119
11   chr4  15749362  15772923      +   20  1240     23561     54794680
12  chr12  92310736  92321395      -  140  -732     10659     54805339
13  chr12  92303740  92310735      -  148  -731      6995     54812334
14  chr12  92302033  92303739      -  136  -730      1706     54814040
15  chr12  68337113  68338873      +   30   490      1760     54815800
16  chr12  68338874  68344177      +   20   491      5303     54821103
17  chr12  68344178  68351823      +   17   492      7645     54828748
18   chr7   2317320   2431929      +   13  1698    114609     54943357
19   chr7   2431930   2661555      +   12  1699    229625     55172982
20   chr7   2661556  26252641      +    4  1700  23591085     78764067
21   chr9  96032197  97116228      +    5  1763   1084031     79848098

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene PMS2
gene RAC1
gene HNRNPA2B1
gene CARD11
gene ETV1
gene MACC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_14/226354-WG01_walk_1_MYCN_containing_breakpoints.pdf
running patient  15
running file  226359-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr12         1  57715079      +   2  18  57715078     57715078        0
1   chr12  57715080  57845430      +   5  19    130350     57845428        1
2   chr12  57845431  58166466      +   4  20    321035     58166463        2
3   chr12  58166467  58314867      +   5  21    148400     58314863        3
4   chr12  58314868  64555048      +   2  22   6240180     64555043        4
5   chr12  64555049  64606456      +   5  23     51407     64606450        5
6   chr12  91170450  91341021      -   5 -38    170571     64777021        6
7   chr12  78975398  91170449      -   2 -37  12195051     76972072        7
8   chr12  78163732  78975397      -   3 -36    811665     77783737        8
9   chr12  69927891  78163731      -   2 -35   8235840     86019577        9
10  chr12  69587733  69927890      -   3 -34    340157     86359734       10
11  chr12  68982704  69587732      -   4 -33    605028     86964762       11
12  chr12  68974553  68982703      -   2 -32      8150     86972912       12
13  chr12  68723235  68974552      -   4 -31    251317     87224229       13
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
gene LRIG3
gene PTPRB
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226359-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226358-WG01_walk_2_MYCL_containing.fa
bed file      chr      start        end strand  cn    5       span  span_cumsum  \
0   chr1          1  169613073      +   2    1  169613072    169613072
1   chr1  169613074  169666098      +   3    2      53024    169666096
2  chr12   79416133   79497160      +   7  123      81027    169747123
3  chr12   79497161   79499413      +   6  124       2252    169749375
4  chr12   79499414   79632305      +   5  125     132891    169882266
5  chr12   67304844   67331311      +   5   70      26467    169908733
6  chr12   67331312   67405334      +   3   71      74022    169982755
7  chr12   67405335   67508664      +   2   72     103329    170086084
8  chr12   67508665   67662437      +   3   73     153772    170239856
9  chr12   67662438   67745602      +   4   74      83164    170323020

   bed_idx
0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7
8        8
9        9
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226360-WG01_walk_1_MYC_containing.fa

bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  65  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226358-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  170630788  171654202      -   4 -5    1023414      1023414        0
1  chr1  169998803  170630787      -   3 -4     631984      1655398        1
2  chr1  169666099  169998802      -   2 -3     332703      1988101        2
3  chr1  169613074  169666098      -   3 -2      53024      2041125        3
4  chr1          1  169613073      -   2 -1  169613072    171654197        4
gene PRRX1
error!!!! in row index 0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
running file  226359-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr12         1  57715079      +   2  18  57715078     57715078        0
1   chr12  57715080  57845430      +   5  19    130350     57845428        1
2   chr12  57845431  58166466      +   4  20    321035     58166463        2
3   chr12  58166467  58314867      +   5  21    148400     58314863        3
4   chr12  58314868  64555048      +   2  22   6240180     64555043        4
5   chr12  64555049  64606456      +   5  23     51407     64606450        5
6   chr12  91170450  91341021      -   5 -38    170571     64777021        6
7   chr12  78975398  91170449      -   2 -37  12195051     76972072        7
8   chr12  78163732  78975397      -   3 -36    811665     77783737        8
9   chr12  69927891  78163731      -   2 -35   8235840     86019577        9
10  chr12  69587733  69927890      -   3 -34    340157     86359734       10
11  chr12  68982704  69587732      -   4 -33    605028     86964762       11
12  chr12  68974553  68982703      -   2 -32      8150     86972912       12
13  chr12  68723235  68974552      -   4 -31    251317     87224229       13
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
gene LRIG3
gene PTPRB
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226359-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226358-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8          1   43634332      +   2  178  43634331     43634331        0
1  chr8   43634333   43634592      +   3  179       259     43634590        1
2  chr8   43634593  143045802      +   2  180  99411209    143045799        2
3  chr8  143045803  144844802      +   3  181   1798999    144844798        3
4  chr8  144844803  145138636      +   2  182    293833    145138631        4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene RECQL4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226358-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226358-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2         1   16131496      +   2  140   16131495     16131495        0
1  chr2  16133675  242193529      +   2  142  226059854    242191349        1
gene MYCN
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226358-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226358-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr9         1  71182402      +   2  183  71182401     71182401        0
1    chr9  71182403  71217456      +   4  184     35053     71217454        1
2    chr9  71217457  71295002      +   3  185     77545     71294999        2
3    chr9  71295003  71616802      +   4  186    321799     71616798        3
4    chr9  71616803  71709774      +   5  187     92971     71709769        4
..    ...       ...       ...    ...  ..  ...       ...          ...      ...
56  chr12  57805667  57815856      -  10  -47     10189     75679614       56
57  chr12  57797831  57805666      -   9  -46      7835     75687449       57
58  chr12  57715080  57797830      -   8  -45     82750     75770199       58
59  chr12  37257061  57715079      -   2  -44  20458018     96228217       59
60  chr12         1  34833845      -   2  -42  34833844    131062061       60

[61 rows x 9 columns]
gene CD274
gene PDCD1LG2
gene CDKN2A
gene FANCG
gene JAK2
gene NFIB
gene PSIP1
gene MLLT3
gene PAX5
gene PTPRD
gene BIRC3
gene BIRC3
gene BIRC3
gene HMGA2
gene HMGA2
gene HMGA2
gene CDK4
gene CDK4
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 35
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226358-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226360-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  68982704   70323573      -   3 -24   1340869      1340869        0
1  chr12  68751168   68974552      -   5 -22    223384      1564253        1
2  chr12  67304844   67331311      -   4 -19     26467      1590720        2
3  chr12  79371200   79632305      -   4 -32    261105      1851825        3
4  chr12  76295260   76482871      -   3 -26    187611      2039436        4
5  chr12  70323574   76295259      -   2 -25   5971685      8011121        5
6  chr12  79237302   79371199      +   3  31    133897      8145018        6
7  chr12  79371200   79632305      +   4  32    261105      8406123        7
8  chr12  79632306  133275309      +   2  33  53643003     62049126        8
gene MDM2
gene PTPRB
gene TBX3
gene SETD1B
gene ZCCHC8
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226360-WG01_walk_1_MDM2_containing_breakpoints.pdf

running file  226360-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  171654642      +   2  1  171654641    171654641        0
1  chr1  171654643  171955967      +   3  2     301324    171955965        1
2  chr1  171955968  248956422      +   2  3   77000454    248956419        2
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
running file  226359-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  72  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  226360-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  44  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226358-WG01_walk_2_KRAS_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr11  106322553  135086622      -   2 -41  28764069     28764069        0
1  chr11  106304179  106322552      -   9 -40     18373     28782442        1
2  chr12   57843693   57845430      -   8 -49      1737     28784179        2
3  chr12   57815857   57843692      -   9 -48     27835     28812014        3
4  chr12   57805667   57815856      -  10 -47     10189     28822203        4
5  chr12   57797831   57805666      -   9 -46      7835     28830038        5
6  chr12   57715080   57797830      -   8 -45     82750     28912788        6
7  chr12   37257061   57715079      -   2 -44  20458018     49370806        7
8  chr12          1   34833845      -   2 -42  34833844     84204650        8
gene SDHD
gene POU2AF1
gene PAFAH1B2
gene BCL9L
gene FOXR1
gene KCNJ5
gene ATM
gene DDX10
gene ZBTB16
gene CBL
gene DDX6
gene ARHGEF12
gene FLI1
gene KMT2A
gene CDK4
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 32
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226358-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226359-WG01_walk_2_KRAS_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr11  122478573  135086622      -   2 -17  12608049     12608049        0
1  chr11  106304179  122476876      -   2 -15  16172697     28780746        1
2  chr12   57715080   57845430      -   5 -19    130350     28911096        2
3  chr12          1   57715079      -   2 -18  57715078     86626174        3
gene KCNJ5
gene FLI1
gene SDHD
gene POU2AF1
gene PAFAH1B2
gene BCL9L
gene FOXR1
gene ATM
gene DDX10
gene ZBTB16
gene CBL
gene DDX6
gene ARHGEF12
gene KMT2A
gene CDK4
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 22
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226359-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226359-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  212297811      +   2  1  212297810    212297810        0
1  chr1  212299275  214497510      +   2  3    2198235    214496045        1
2  chr1  214497511  214497770      +   3  4        259    214496304        2
3  chr1  214497771  248956422      +   2  5   34458651    248954955        3
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene H3F3A
gene FH
gene AKT3
gene RGS7
running file  226360-WG01_walk_1_KRAS_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12          1   57715079      +   2  12  57715078     57715078        0
1  chr12   57715080   58314867      +   5  13    599787     58314865        1
2  chr11  105883381  106280403      +   5   8    397022     58711887        2
3  chr11  106280404  122476876      +   2   9  16196472     74908359        3
4  chr11  122478573  135086622      +   2  11  12608049     87516408        4
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
gene CDK4
gene SDHD
gene POU2AF1
gene PAFAH1B2
gene BCL9L
gene FOXR1
gene ATM
gene DDX10
gene ZBTB16
gene CBL
gene DDX6
gene ARHGEF12
gene KMT2A
gene KCNJ5
gene FLI1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_15/226360-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226359-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   76546427      +   2  49   76546426     76546426        0
1  chr2  76548327  242193529      +   2  51  165645202    242191628        1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running patient  16
running file  226363-WG01_walk_2_KRAS_containing.fa

bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12         1  39555349      +   2    6  39555348     39555348        0
1   chr2  91922822  92720286      +   3  640    797464     40352812        1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226362-WG01_walk_4_MYCN_containing.fa
bed file     chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0  chr2  84765892  93406671      -   5 -1183   8640779      8640779        0
1  chr2  82901043  84765891      -   4 -1182   1864848     10505627        1
2  chr2   1392360  82901042      -   4 -1181  81508682     92014309        2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226363-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2         1   91922821      +   2  639   91922820     91922820        0
1  chr2  91922822   92720286      +   3  640     797464     92720284        1
2  chr2  92720287   94052705      +   3  641    1332418     94052702        2
3  chr2  94052706  242193529      +   2  642  148140823    242193525        3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  226362-WG01_walk_3_MYC_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr8   93451180   95640863      +   6  1414   2189683      2189683
1   chr8   95640864   98738025      +   5  1415   3097161      5286844
2   chr8   98738026  103237730      +   6  1416   4499704      9786548
3   chr8  103237731  119248002      +   5  1417  16010271     25796819
4   chr8  119248003  120657202      +   6  1418   1409199     27206018
5   chr8  120657203  122888002      +   5  1419   2230799     29436817
6   chr8  122888003  125574602      +   6  1420   2686599     32123416
7   chr8  125574603  129741402      +   5  1421   4166799     36290215
8   chr8  129741403  130714002      +   6  1422    972599     37262814
9   chr8  130714003  144993840      +   5  1423  14279837     51542651
10  chr8  144993841  145138636      +   4  1424    144795     51687446

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
gene CDH17
gene COX6C
gene PABPC1
gene UBR5
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene MYC
gene RECQL4
gene NDRG1
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  226362-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr4   60923106   61120122      -   9 -1260    197016       197016
1   chr1  144840603  150242214      -   4   -18   5401611      5598627
2   chr1  125084306  144840602      -   6   -17  19756296     25354923
3   chr1  125082430  125084305      -   5   -16      1875     25356798
4   chr1  122520404  125082429      -   6   -15   2562025     27918823
5   chr1  105957499  122520403      -   4   -14  16562904     44481727
6   chr1  101278300  105957498      -   3   -13   4679198     49160925
7   chr1   88947068  101278299      -   4   -12  12331231     61492156
8   chr1   81131714   88947067      -   4   -11   7815353     69307509
9   chr1   71515203   81131713      -   3   -10   9616510     78924019
10  chr1   38590985   71515202      -   4    -9  32924217    111848236
11  chr1   28690804   38590984      -   4    -8   9900180    121748416
12  chr1   20385305   28690803      -   5    -7   8305498    130053914
13  chr1   14339591   20385304      -   4    -6   6045713    136099627
14  chr1    8075654   14339590      -   5    -5   6263936    142363563
15  chr1     713403    8075653      -   4    -4   7362250    149725813
16  chr1     183293     713402      -  17    -3    530109    150255922
17  chr1     181589     183292      -  11    -2      1703    150257625
18  chr1     183293     713402      +  17     3    530109    150787734
19  chr1     713403    8075653      +   4     4   7362250    158149984
20  chr1    8075654   14339590      +   5     5   6263936    164413920
21  chr1   14339591   20385304      +   4     6   6045713    170459633
22  chr1   20385305   28690803      +   5     7   8305498    178765131
23  chr1   28690804   38590984      +   4     8   9900180    188665311
24  chr1   38590985   71515202      +   4     9  32924217    221589528
25  chr1   71515203   81131713      +   3    10   9616510    231206038
26  chr1   81131714   88947067      +   4    11   7815353    239021391
27  chr1   88947068  101278299      +   4    12  12331231    251352622
28  chr1  101278300  105957498      +   3    13   4679198    256031820
29  chr1  105957499  122520403      +   4    14  16562904    272594724
30  chr1  122520404  125082429      +   6    15   2562025    275156749
31  chr1  125082430  125084305      +   5    16      1875    275158624
32  chr1  125084306  144840602      +   6    17  19756296    294914920
33  chr1  144840603  150242214      +   4    18   5401611    300316531
34  chr4   60923106   61120122      +   9  1260    197016    300513547
35  chr4   61120123   61468000      +   4  1261    347877    300861424
36  chr4   61468001   62240711      +   5  1262    772710    301634134
37  chr4   62240712   80362281      +   4  1263  18121569    319755703
38  chr4   80362282   80362362      +   6  1264        80    319755783
39  chr4   80362363   80362629      +   9  1265       266    319756049
40  chr4   80362630   80410759      +   7  1266     48129    319804178
41  chr4   80410760  104720459      +   4  1267  24309699    344113877
42  chr4  104720460  104807328      +   7  1268     86868    344200745
43  chr4  104807329  109568822      +   4  1269   4761493    348962238
44  chr4  109568823  109731200      +   9  1270    162377    349124615
45  chr4  109731201  109920836      +   5  1271    189635    349314250
46  chr4  109920837  112328877      +   4  1272   2408040    351722290
47  chr4  112328878  112416430      +   5  1273     87552    351809842
48  chr4  112416431  123741025      +   4  1274  11324594    363134436
49  chr1  158271229  170695134      -   4   -23  12423905    375558341
50  chr1  156359339  158271228      -   4   -22   1911889    377470230
51  chr1  153534840  156359338      -   5   -21   2824498    380294728
52  chr1  151359516  153534839      -   4   -20   2175323    382470051
53  chr1  150242215  151359515      -   5   -19   1117300    383587351

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48
49       49
50       50
51       51
52       52
53       53

gene BCL9
gene PDE4DIP
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene RPL5
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene ID3
gene MDS2
gene ARID1A
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene MTOR
gene PRDM2
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene PRDM2
gene CASP9
gene PAX7
gene SPEN
gene ARHGEF10L
gene SDHB
gene ID3
gene MDS2
gene ARID1A
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene FUBP1
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene BCL9
gene PDE4DIP
gene PTPN13
gene RAP1GDS1
gene AFF1
gene TET2
gene LEF1
gene IL2
gene FCGR2B
gene PRRX1
gene SDHC
gene DDR2
gene PBX1
gene NTRK1
gene PRCC
gene FCRL4
gene TPM3
gene LMNA
gene MUC1
gene S100A7
gene SETDB1
gene MLLT11
gene ARNT
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226362-WG01_walk_2_MYCN_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr2    1392360   82901042      +   4  1181  81508682     81508682        0
1  chr2   82901043   84765891      +   4  1182   1864848     83373530        1
2  chr2   84765892   93406671      +   5  1183   8640779     92014309        2
3  chr2   93406672  126961328      +   4  1184  33554656    125568965        3
4  chr2  126961329  126964771      +   3  1185      3442    125572407        4
5  chr2  126964772  152144316      +   4  1186  25179544    150751951        5
6  chr4   61468001   62240711      +   5  1262    772710    151524661        6
7  chr6   73558722   80366766      -   4 -1370   6808044    158332705        7
8  chr1  173509278  187439861      -   4   -25  13930583    172263288        8
9  chr1  170695135  173509277      -   4   -24   2814142    175077430        9
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene CXCR4
gene ERCC3
gene LRP1B
gene ACVR2A
gene TPR
gene ABL2
gene PRRX1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226362-WG01_walk_2_MYCL_containing.fa
bed file       chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0   chr16  74431115  90338345      -   4 -1107  15907230     15907230        0
1   chr16  74430883  74431114      -   5 -1106       231     15907461        1
2   chr16  66919915  74430882      -   4 -1105   7510967     23418428        2
3   chr16  66151908  66919914      -   4 -1104    768006     24186434        3
4    chr1  81131714  88947067      -   4   -11   7815353     32001787        4
5    chr1  71515203  81131713      -   3   -10   9616510     41618297        5
6    chr1  38590985  71515202      -   4    -9  32924217     74542514        6
7    chr1  28690804  38590984      -   4    -8   9900180     84442694        7
8    chr1  20385305  28690803      -   5    -7   8305498     92748192        8
9    chr2   1392360  82901042      -   4 -1181  81508682    174256874        9
10   chr2         1   1392359      -   3 -1180   1392358    175649232       10
gene MAF
gene RFWD3
error!!!! in row index 1
gene CBFA2T3
gene FANCA
gene CBFB
gene CTCF
gene CDH1
gene ZFHX3
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene ID3
gene MDS2
gene ARID1A
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226362-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand   cn     5      span  span_cumsum  bed_idx
0  chr22  11977403  12069496      +  200  1227     92093        92093        0
1  chr22  12069497  12149002      +  164  1228     79505       171598        1
2  chr22  12149003  12275602      +  111  1229    126599       298197        2
3  chr22  12275603  14959803      +    6  1230   2684200      2982397        3
4  chr22  14959804  27622429      +    4  1231  12662625     15645022        4
5  chr22  27622430  27871086      +    3  1232    248656     15893678        5
6  chr12  31060510  32454665      -    5   -67   1394155     17287833        6
7  chr12         1  31060509      -    4   -66  31060508     48348341        7
gene SEPT5
gene DGCR8
gene LZTR1
gene SMARCB1
gene CLTCL1
gene MAPK1
gene BCR
gene MN1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 10
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  226363-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr12         1  39555349      +   2  6  39555348     39555348        0
1  chr12  39555350  48027720      +   2  7   8472370     48027718        1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
gene COL2A1
gene ARID2
running file  226362-WG01_walk_3_KRAS_containing.fa
bed file      chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0  chr12         1  31060509      +   4    66  31060508     31060508        0
1  chr12  31060510  32454665      +   5    67   1394155     32454663        1
2  chr12  32454666  33562188      +   4    68   1107522     33562185        2
3  chr12  33564031  34597185      +   4    70   1033154     34595339        3
4  chr12  34597186  37644507      +   6    71   3047321     37642660        4
5   chr2         1   1392359      -   3 -1180   1392358     39035018        5
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226362-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand   cn    5      span  span_cumsum  bed_idx
0   chr12  76967294  76968602      -  225 -874      1308         1308        0
1   chr12  76952791  76967293      -  175 -873     14502        15810        1
2   chr12  76948722  76952790      -  174 -872      4068        19878        2
3   chr12  76942908  76948721      -  168 -871      5813        25691        3
4   chr12  83899675  83910864      -   27 -985     11189        36880        4
5   chr12  83883822  83899674      -   43 -984     15852        52732        5
6   chr12  71577693  71602594      +   53  506     24901        77633        6
7   chr12  71602595  71611074      +   63  507      8479        86112        7
8   chr12  71611075  71615613      +   72  508      4538        90650        8
9   chr12  70777987  70779618      +   65  458      1631        92281        9
10  chr12  70779619  70814190      +   33  459     34571       126852       10
11  chr12  70814191  70824138      +   42  460      9947       136799       11
12  chr12  70824139  70855701      +   28  461     31562       168361       12
13  chr12  70855702  70865004      +   44  462      9302       177663       13
14  chr12  71671635  71675772      -  102 -519      4137       181800       14
15  chr12  74628321  74631520      -  161 -740      3199       184999       15
16  chr12  77884246  77887516      -  183 -920      3270       188269       16
17  chr12  71323905  71328289      -   73 -477      4384       192653       17
18  chr12  71299123  71323904      -   41 -476     24781       217434       18
19  chr12  71291375  71299122      -   66 -475      7747       225181       19
20  chr12  71287249  71291374      -   60 -474      4125       229306       20
21  chr12  69438579  69459358      +   52  356     20779       250085       21
22  chr12  69459359  69465466      +   35  357      6107       256192       22
23  chr12  73891767  73898584      -  144 -695      6817       263009       23
24  chr12  73874328  73891766      -   46 -694     17438       280447       24
25  chr12  57739599  57740375      -  111 -143       776       281223       25
26  chr12  57710341  57739598      -  115 -142     29257       310480       26
27  chr12  57708546  57710340      -  100 -141      1794       312274       27
28  chr12  57707064  57708545      -   98 -140      1481       313755       28
29  chr12  57702154  57707063      -   91 -139      4909       318664       29
30  chr12  71763804  71768480      +  199  535      4676       323340       30
31  chr12  67934134  67941110      -   47 -310      6976       330316       31
32  chr12  67976045  68012283      +   47  312     36238       366554       32
33  chr12  71894632  71903034      -  213 -559      8402       374956       33
34  chr12  71893733  71894631      -  243 -558       898       375854       34
35  chr12  71892279  71893732      -  322 -557      1453       377307       35
36  chr12  71879242  71881113      -  322 -553      1871       379178       36
37  chr12  71068353  71073688      +   46  466      5335       384513       37
38  chr12  71073689  71084534      +   54  467     10845       395358       38
39  chr12  72661560  72664888      +   77  604      3328       398686       39
40  chr12  72664889  72689354      +  105  605     24465       423151       40
41  chr12  72689355  72690396      +  101  606      1041       424192       41
42  chr12  72690397  72699686      +  105  607      9289       433481       42
43  chr12  72699687  72704039      +   69  608      4352       437833       43
44  chr12  72704040  72710116      +   77  609      6076       443909       44
45  chr12  72710117  72711004      +   82  610       887       444796       45
46  chr12  57637165  57668276      +   63  134     31111       475907       46
47  chr12  57668277  57670017      +  109  135      1740       477647       47
48  chr12  57670018  57679179      +   60  136      9161       486808       48
49  chr12  54581456  54590350      -   34  -73      8894       495702       49
50  chr12  37644508  54581455      -    4  -72  16936947     17432649       50
51  chr12  34597186  37644507      -    6  -71   3047321     20479970       51
52  chr12  33564031  34597185      -    4  -70   1033154     21513124       52
53  chr12  33562189  33564030      -    2  -69      1841     21514965       53
54  chr12  32454666  33562188      -    4  -68   1107522     22622487       54
55  chr12  31060510  32454665      -    5  -67   1394155     24016642       55
56  chr12         1  31060509      -    4  -66  31060508     55077150       56

gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 11
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  226362-WG01_walk_3_MYCN_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr2  164271773  170408438      -   4 -1188   6136665      6136665        0
1  chr2  152144317  164271772      -   4 -1187  12127455     18264120        1
2  chr2  126964772  152144316      -   4 -1186  25179544     43443664        2
3  chr2   93406672  126961328      -   4 -1184  33554656     76998320        3
4  chr2   84765892   93406671      -   5 -1183   8640779     85639099        4
5  chr2   82901043   84765891      -   4 -1182   1864848     87503947        5
6  chr2    1392360   82901042      -   4 -1181  81508682    169012629        6
gene ACVR1
gene CXCR4
gene ERCC3
gene LRP1B
gene ACVR2A
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_3_MYCN_containing_breakpoints.pdf
running file  226362-WG01_walk_1_MYCN_containing.fa
bed file       chr     start       end strand  cn     5      span  span_cumsum  bed_idx
0   chr16  74431115  90338345      -   4 -1107  15907230     15907230        0
1   chr16  74430883  74431114      -   5 -1106       231     15907461        1
2   chr16  66919915  74430882      -   4 -1105   7510967     23418428        2
3   chr16  66151908  66919914      -   4 -1104    768006     24186434        3
4    chr1  81131714  88947067      -   4   -11   7815353     32001787        4
5    chr1  71515203  81131713      -   3   -10   9616510     41618297        5
6    chr1  38590985  71515202      -   4    -9  32924217     74542514        6
7    chr1  28690804  38590984      -   4    -8   9900180     84442694        7
8    chr1  20385305  28690803      -   5    -7   8305498     92748192        8
9    chr2   1392360  82901042      -   4 -1181  81508682    174256874        9
10   chr2         1   1392359      -   3 -1180   1392358    175649232       10
gene MAF
gene RFWD3
error!!!! in row index 1
gene CBFA2T3
gene FANCA
gene CBFB
gene CTCF
gene CDH1
gene ZFHX3
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene ID3
gene MDS2
gene ARID1A
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226363-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8         1   45339791      +   2  665  45339790     45339790        0
1  chr8  45530189  145138636      +   2  667  99608447    144948237        1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  226363-WG01_walk_1_MYCL_containing.fa
bed file     chr     start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1         1   80939150      +   2  1   80939149     80939149        0
1  chr1  80945263  248956422      +   2  3  168011159    248950308        1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  226362-WG01_walk_3_MYCL_containing.fa
bed file      chr     start       end strand   cn     5      span  span_cumsum  bed_idx
0  chr12  72913501  72918060      +  206   634      4559         4559        0
1  chr12  72918061  72958735      +  185   635     40674        45233        1
2  chr12  72958736  72966033      +  183   636      7297        52530        2
3   chrX  65292801  66074352      -    6 -1617    781551       834081        3
4   chr1  38590985  71515202      +    4     9  32924217     33758298        4
gene MSN
error!!!! in row index 0
gene MYCL
gene JUN
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226362-WG01_walk_2_MYC_containing.fa
bed file     chr      start        end strand  cn     5      span  span_cumsum  bed_idx
0  chr8  130714003  144993840      -   5 -1423  14279837     14279837        0
1  chr8  129741403  130714002      -   6 -1422    972599     15252436        1
2  chr8  125574603  129741402      -   5 -1421   4166799     19419235        2
3  chr8  122888003  125574602      -   6 -1420   2686599     22105834        3
4  chr8  120657203  122888002      -   5 -1419   2230799     24336633        4
5  chr8  119248003  120657202      -   6 -1418   1409199     25745832        5
6  chr8  103237731  119248002      -   5 -1417  16010271     41756103        6
7  chr8   98738026  103237730      -   6 -1416   4499704     46255807        7
8  chr1   28690804   38590984      +   4     8   9900180     56155987        8
gene RECQL4
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene COX6C
gene PABPC1
gene UBR5
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  226362-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0    chr8  144993841  145138636      -    4 -1424    144795       144795
1    chr8  130714003  144993840      -    5 -1423  14279837     14424632
2    chr8  129741403  130714002      -    6 -1422    972599     15397231
3    chr8  125574603  129741402      -    5 -1421   4166799     19564030
4    chr8  122888003  125574602      -    6 -1420   2686599     22250629
5    chr8  120657203  122888002      -    5 -1419   2230799     24481428
6    chr8  119248003  120657202      -    6 -1418   1409199     25890627
7    chr8  103237731  119248002      -    5 -1417  16010271     41900898
8    chr8   98738026  103237730      -    6 -1416   4499704     46400602
9    chr8   95640864   98738025      -    5 -1415   3097161     49497763
10   chr8   93451180   95640863      -    6 -1414   2189683     51687446
11   chr8   70857878   93451179      -    5 -1413  22593301     74280747
12  chr12   70232120   70232126      +  171   418         6     74280753
13  chr12   74939946   74943634      -  183  -772      3688     74284441
14  chr12   74924234   74939945      -  191  -771     15711     74300152
15  chr12   74906396   74924233      -  141  -770     17837     74317989
16  chr12   75274607   75280409      +   76   806      5802     74323791
17  chr12   75280410   75337964      +   81   807     57554     74381345
18  chr12   75337965   75343015      +   89   808      5050     74386395
19  chr12   75343016   75344990      +   81   809      1974     74388369
20  chr12   66828627   66899602      +   76   258     70975     74459344

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20

gene RECQL4
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene COX6C
gene PABPC1
gene UBR5
gene CDH17
gene HEY1
gene NBN
gene RUNX1T1
gene CNBD1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_16/226362-WG01_walk_1_MYC_containing_breakpoints.pdf
running patient  17
running file  226367-WG01_walk_1_MDM2_containing.fa
bed file      chr      start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12          1  109835402      +   2  17  109835401    109835401        0
1  chr12  109835403  112475802      +   3  18    2640399    112475800        1
2  chr12  112475803  117938802      +   2  19    5462999    117938799        2
3  chr12  117938803  118375002      +   3  20     436199    118374998        3
4  chr12  118375003  119852402      +   2  21    1477399    119852397        4
5  chr12  119852403  123841202      +   3  22    3988799    123841196        5
6  chr12  123841203  133275309      +   2  23    9434106    133275302        6
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ERC1
gene ALDH2
gene SH2B3
gene PTPN11
gene TBX3
gene PTPN11
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226367-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226367-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8          1   37505615      +   2   93  37505614     37505614        0
1  chr8   37505616   39490802      +   3   94   1985186     39490800        1
2  chr8   39490803   42033802      +   2   95   2542999     42033799        2
3  chr8   42033803   43241802      +   3   96   1207999     43241798        3
4  chr8   43241803   43723202      +   2   97    481399     43723197        4
5  chr8   43723203   44062402      +   3   98    339199     44062396        5
6  chr8   44062403  134070686      +   2   99  90008283    134070679        6
7  chr8  134076773  145138636      +   2  101  11061863    145132542        7
gene LEPROTL1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene FGFR1
gene NSD3
gene ANK1
gene KAT6A
gene IKBKB
gene HOOK3
gene KAT6A
gene HEY1
gene MYC
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226367-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226366-WG01_walk_2_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  95824577  133275309      -   3 -33  37450732     37450732        0
1  chr12  66068803   95824576      -   3 -32  29755773     67206505        1
2  chr12  33822397   66068802      -   2 -31  32246405     99452910        2
3  chr12  31466449   32788420      -   3 -29   1321971    100774881        3
4  chr12  30577205   31466448      -   2 -28    889243    101664124        4
5  chr12         1   30577204      -   1 -27  30577203    132241327        5
gene TBX3
gene SETD1B
gene ZCCHC8
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226366-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1          1    2474282      +   4   1   2474281      2474281        0
1   chr1    2474283    2960638      +   5   2    486355      2960636        1
2   chr1    6601960   14368223      +   4   4   7766263     10726899        2
3   chr1   14368224   17033460      +   4   5   2665236     13392135        3
4   chr1   17033461   32650931      +   3   6  15617470     29009605        4
5   chr1   32650932   50314608      +   3   7  17663676     46673281        5
6   chr1   50314609  113753333      +   2   8  63438724    110112005        6
7   chr1  113753334  113753572      +   3   9       238    110112243        7
8   chr1  113753573  182395002      +   2  10  68641429    178753672        8
9   chr1  182395003  187663807      +   1  11   5268804    184022476        9
10  chr1  187663808  187669365      +   2  12      5557    184028033       10
11  chr1  202258696  203791906      +   2  15   1533210    185561243       11
gene SKI
gene TNFRSF14
gene MTOR
gene PRDM2
gene CAMTA1
gene CASP9
gene SPEN
gene SDHB
gene ID3
gene PAX7
gene LCK
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene JUN
gene BCL10
gene RPL5
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene BTG2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226366-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  62619603  145138636      -   1 -196  82519033     82519033        0
1  chr8  59542821   62619602      -   4 -195   3076781     85595814        1
2  chr8  52056603   59542820      -   1 -194   7486217     93082031        2
3  chr8  48343540   52056602      -   4 -193   3713062     96795093        3
4  chr8  47979203   48343539      -   1 -192    364336     97159429        4
5  chr8  42633603   47979202      -   3 -191   5345599    102505028        5
6  chr8  41344003   42633602      -   2 -190   1289599    103794627        6
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HOOK3
gene IKBKB
gene ANK1
gene KAT6A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  226365-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr5          1    5061602      +   3  223   5061601      5061601        0
1  chr1   36221234   66100180      +   3   21  29878946     34940547        1
2  chr1   66100181   91230861      +   2   22  25130680     60071227        2
3  chr1   91230862   91944775      +   3   23    713913     60785140        3
4  chr1   91944776  113068717      +   2   24  21123941     81909081        4
5  chr1  113071156  120089227      +   2   26   7018071     88927152        5
6  chr1  120089228  182392181      +   3   27  62302953    151230105        6
7  chr1  182392182  203047857      +   1   28  20655675    171885780        7
8  chr1  203047858  203703537      +   2   29    655679    172541459        8
gene SDHA
error!!!! in row index 0
gene TERT
gene MYCL
gene JUN
gene THRAP3

gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene BCL10
gene FUBP1
gene RPL5
gene RBM15
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene PDE4DIP
gene MUC1
gene PBX1
gene TPR
gene ELF3
gene CDC73
gene PTPRC
gene BTG2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226366-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  113753573  182395002      -   2 -10  68641429     68641429        0
1  chr1  113753334  113753572      -   3  -9       238     68641667        1
2  chr1   50314609  113753333      -   2  -8  63438724    132080391        2
3  chr1   32650932   50314608      -   3  -7  17663676    149744067        3
4  chr1   17033461   32650931      -   3  -6  15617470    165361537        4
5  chr1   14368224   17033460      -   4  -5   2665236    168026773        5
6  chr1    6601960   14368223      -   4  -4   7766263    175793036        6
7  chr1    2960639    6601959      -   3  -3   3641320    179434356        7
8  chr1    2474283    2960638      -   5  -2    486355    179920711        8
9  chr1          1    2474282      -   4  -1   2474281    182394992        9
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene ID3
gene PAX7
gene LCK
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CASP9
gene SPEN
gene SDHB
gene MTOR
gene PRDM2
gene CAMTA1
gene RPL22
gene PRDM16
gene TNFRSF14
gene SKI
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  226367-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  212299275  248956422      -   2 -12  36657147     36657147        0
1  chr1  113071156  212297811      -   2 -10  99226655    135883802        1
2  chr1   52986803  113068717      -   2  -8  60081914    195965716        2
3  chr1   51096603   52986802      -   3  -7   1890199    197855915        3
4  chr1   46400003   51096602      -   2  -6   4696599    202552514        4
5  chr1   44739086   46400002      -   3  -5   1660916    204213430        5
6  chr1   40617803   44739085      -   2  -4   4121282    208334712        6
7  chr1   40367603   40617802      -   3  -3    250199    208584911        7
8  chr1   29421974   40367602      -   2  -2  10945628    219530539        8
9  chr1          1   29421973      -   3  -1  29421972    248952511        9
gene H3F3A
gene FH
gene AKT3
gene RGS7
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene STIL
gene TAL1
gene CDKN2C
gene MUTYH
gene MPL
gene MYCL
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226367-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226366-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  95824577  133275309      -   3 -33  37450732     37450732        0
1  chr12  66068803   95824576      -   3 -32  29755773     67206505        1
2  chr12  33822397   66068802      -   2 -31  32246405     99452910        2
3  chr12  31466449   32788420      -   3 -29   1321971    100774881        3
4  chr12  30577205   31466448      -   2 -28    889243    101664124        4
5  chr12         1   30577204      -   1 -27  30577203    132241327        5
gene TBX3
gene SETD1B
gene ZCCHC8
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226365-WG01_walk_1_KRAS_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  133024603  133275309      -   2 -68    250706       250706        0
1  chr12  132675003  133024602      -   3 -67    349599       600305        1
2  chr12  123242178  132675002      -   2 -66   9432824     10033129        2
3  chr12  120955781  123242177      -   3 -65   2286396     12319525        3
4  chr12   49134574  120955780      -   2 -64  71821206     84140731        4
5  chr12   33822397   49134573      -   2 -63  15312176     99452907        5
6  chr12   32772403   32788420      -   2 -61     16017     99468924        6
7  chr12   31251803   32772402      -   3 -60   1520599    100989523        7
8  chr12   30577203   31251802      -   2 -59    674599    101664122        8
9  chr12          1   30577202      -   1 -58  30577201    132241323        9
gene POLE
error!!!! in row index 0
gene NCOR2
gene POLE
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene COL2A1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 38
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226365-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr9   43388803   74665034      +   3  280  31276231     31276231        0
1   chr9   74665035   74877545      +   2  281    212510     31488741        1
2   chr9   74877546   77934654      +   3  282   3057108     34545849        2
3   chr9   77934655   80701747      +   2  283   2767092     37312941        3
4   chr9   80701748   83888055      +   3  284   3186307     40499248        4
5   chr9   83888056   85841936      -   2 -285   1953880     42453128        5
6   chr9   80701748   83888055      -   3 -284   3186307     45639435        6
7   chr9   74877546   77934654      -   3 -282   3057108     48696543        7
8   chr9   43388803   74665034      -   3 -280  31276231     79972774        8
9   chr9   42574803   43388802      -   2 -279    813999     80786773        9
10  chr9   41612004   42574802      -   3 -278    962798     81749571       10
11  chr9   40552003   41612003      -   2 -277   1060000     82809571       11
12  chr9   38863203   40552002      -   3 -276   1688799     84498370       12
13  chr9   34751335   38863202      -   4 -275   4111867     88610237       13
14  chr9   28788508   34751334      -   3 -274   5962826     94573063       14
15  chr9    9638337   28788507      -   3 -273  19150170    113723233       15
16  chr2  143437003  144477192      -   1 -133   1040189    114763422       16
17  chr2   52110056  143437002      -   2 -132  91326946    206090368       17
18  chr2   50495280   52110055      -   1 -131   1614775    207705143       18
19  chr2   22654348   50495279      -   2 -130  27840931    235546074       19
20  chr2   12082197   22654347      -   1 -129  10572150    246118224       20
21  chr2    8285003   12082196      -   2 -128   3797193    249915417       21
22  chr2          1    8285002      -   1 -127   8285001    258200418       22

gene GNAQ
gene GNAQ
gene GNAQ
gene FANCG
gene PAX5
gene CDKN2A
gene NFIB
gene PSIP1
gene MLLT3
gene PTPRD
gene PCBP1
gene CXCR4
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene RGPD3
gene ERCC3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226366-WG01_walk_3_MDM2_containing.fa
bed file      chr     start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  95824577  133275309      -   3 -33  37450732     37450732        0
1  chr12  66068803   95824576      -   3 -32  29755773     67206505        1
gene TBX3
gene SETD1B
gene ZCCHC8
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene MDM2
gene PTPRB
gene BTG1
gene USP44
running file  226366-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr6  38063603  39791602      -   3 -165   1727999      1727999        0
1    chr6  13160355  38063602      -   4 -164  24903247     26631246        1
2   chr12  66068803  95824576      -   3  -32  29755773     56387019        2
3   chr12  33822397  66068802      -   2  -31  32246405     88633424        3
4   chr12  32788421  33822396      -   1  -30   1033975     89667399        4
5   chr12  31466449  32788420      -   3  -29   1321971     90989370        5
6   chr12  30577205  31466448      -   2  -28    889243     91878613        6
7    chr1  14368224  17033460      -   4   -5   2665236     94543849        7
8    chr1  32650932  50314608      -   3   -7  17663676    112207525        8
9    chr5  19426976  27769754      -   3 -150   8342778    120550303        9
10   chr5  19426127  19426975      -   9 -149       848    120551151       10
11  chr14  58261361  58261507      -   9  -52       146    120551297       11
12  chr14  58261301  58261360      -   8  -51        59    120551356       12
13  chr14  33048886  58261300      -   2  -50  25212414    145763770       13
14  chr14  30770392  33048885      -   3  -49   2278493    148042263       14
15  chr14         1  30770391      -   2  -48  30770390    178812653       15
gene HIST1H3B
gene HIST1H4I
gene HLA-A
gene POU5F1
gene DAXX
gene DEK
gene TRIM27
gene HMGA1
gene FANCE
gene CDKN1A
gene SRSF3
gene PIM1
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene CASP9
gene SPEN
gene SDHB
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDH10
gene FOXA1
gene NKX2-1
gene NIN
gene KTN1
gene BAZ1A
gene ARHGAP5
gene CCNB1IP1
gene PRKD1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226365-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  120089228  182392181      -   3 -27  62302953     62302953        0
1   chr1  113071156  120089227      -   2 -26   7018071     69321024        1
2   chr1   91944776  113068717      -   2 -24  21123941     90444965        2
3   chr1   91230862   91944775      -   3 -23    713913     91158878        3
4   chr1   66100181   91230861      -   2 -22  25130680    116289558        4
5   chr1   36221234   66100180      -   3 -21  29878946    146168504        5
6   chr1   16548803   36221233      -   3 -20  19672430    165840934        6
7   chr1   16377803   16548802      -   4 -19    170999    166011933        7
8   chr1   15545003   16377802      -   5 -18    832799    166844732        8
9   chr1   14872203   15545002      -   4 -17    672799    167517531        9
10  chr1   13751603   14872202      -   3 -16   1120599    168638130       10
11  chr1   10527003   13751602      -   4 -15   3224599    171862729       11
12  chr1    8703003   10527002      -   5 -14   1823999    173686728       12
13  chr1    8290003    8703002      -   4 -13    412999    174099727       13
14  chr1    7697203    8290002      -   5 -12    592799    174692526       14
15  chr1    6937603    7697202      -   4 -11    759599    175452125       15
16  chr1    6823003    6937602      -   5 -10    114599    175566724       16
17  chr1    6601960    6823002      -   6  -9    221042    175787766       17
18  chr1    5992759    6601959      -   5  -8    609200    176396966       18
19  chr1    5983803    5992758      -   6  -7      8955    176405921       19
20  chr1    5393203    5983802      -   4  -6    590599    176996520       20
21  chr1    2960639    5393202      -   3  -5   2432563    179429083       21
22  chr1    2800003    2960638      -   4  -4    160635    179589718       22
23  chr1    1747203    2800002      -   5  -3   1052799    180642517       23
24  chr1     883203    1747202      -   4  -2    863999    181506516       24
25  chr1          1     883202      -   3  -1    883201    182389717       25
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene PDE4DIP
gene MUC1
gene PBX1
gene NRAS
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene RPL5
gene RBM15
gene BCL10
gene FUBP1
gene MYCL
gene JUN
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene SPEN
gene CASP9
gene PRDM2
gene MTOR
gene PRDM2
gene CAMTA1
gene CAMTA1
gene CAMTA1
gene CAMTA1
gene RPL22
gene PRDM16
gene TNFRSF14
gene SKI
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  226366-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr2  241545701  242193529      -   1 -93    647828       647828        0
1  chr2  241545373  241545700      -   2 -92       327       648155        1
2  chr2  146696203  241545372      -   1 -91  94849169     95497324        2
3  chr2  144477193  146696202      -   2 -90   2219009     97716333        3
4  chr2  101342599  144477192      -   2 -89  43134593    140850926        4
5  chr2   93746403  101342598      -   3 -88   7596195    148447121        5
6  chr2          1   93746402      -   2 -87  93746401    242193522        6
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene CXCR4
gene RANBP2
gene RGPD3
gene ERCC3
gene PAX8
gene LRP1B
gene TMEM127
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  226366-WG01_walk_3_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr6  38063603  39791602      -   3 -165   1727999      1727999        0
1    chr6  13160355  38063602      -   4 -164  24903247     26631246        1
2   chr12  66068803  95824576      -   3  -32  29755773     56387019        2
3   chr12  33822397  66068802      -   2  -31  32246405     88633424        3
4   chr12  32788421  33822396      -   1  -30   1033975     89667399        4
5   chr12  31466449  32788420      -   3  -29   1321971     90989370        5
6   chr12  30577205  31466448      -   2  -28    889243     91878613        6
7    chr1  14368224  17033460      -   4   -5   2665236     94543849        7
8    chr1  32650932  50314608      -   3   -7  17663676    112207525        8
9    chr5  19426976  27769754      -   3 -150   8342778    120550303        9
10   chr5  19426127  19426975      -   9 -149       848    120551151       10
11  chr14  58261361  58261507      -   9  -52       146    120551297       11
12  chr14  58261301  58261360      -   8  -51        59    120551356       12
13  chr14  33048886  58261300      -   2  -50  25212414    145763770       13
14  chr14  30770392  33048885      -   3  -49   2278493    148042263       14
15  chr14         1  30770391      -   2  -48  30770390    178812653       15

gene HIST1H3B
gene HIST1H4I
gene HLA-A
gene POU5F1
gene DAXX
gene DEK
gene TRIM27
gene HMGA1
gene FANCE
gene CDKN1A
gene SRSF3
gene PIM1
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene CASP9
gene SPEN
gene SDHB
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDH10
gene FOXA1
gene NKX2-1
gene NIN
gene KTN1
gene BAZ1A
gene ARHGAP5
gene CCNB1IP1
gene PRKD1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226365-WG01_walk_2_MDM2_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr5  152082887  172101625      -   2 -237  20018738     20018738        0
1   chr5  142784230  152076869      -   2 -235   9292639     29311377        1
2   chr5  135705056  142784229      -   3 -234   7079173     36390550        2
3  chr12   49134574  120955780      +   2   64  71821206    108211756        3
4  chr12  120955781  123242177      +   3   65   2286396    110498152        4
gene ITK
gene PWWP2A
gene NPM1
gene EBF1
gene TLX3
gene PDGFRB
gene CD74
gene ARHGAP26
gene CSF1R
gene CTNNA1
gene ARHGAP26
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  226366-WG01_walk_2_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr9   77136203   77679002      -   4 -205    542799       542799        0
1  chr9   76044403   77136202      -   5 -204   1091799      1634598        1
2  chr9   74877546   76044402      -   3 -203   1166856      2801454        2
3  chr9   72634803   74665034      -   3 -201   2030231      4831685        3
4  chr9   71666803   72634802      -   4 -200    967999      5799684        4
5  chr9   38324074   71666802      -   3 -199  33342728     39142412        5
6  chr9    9638337   38324073      -   3 -198  28685736     67828148        6
7  chr2  101342599  144477192      -   2  -89  43134593    110962741        7
8  chr2   93746403  101342598      -   3  -88   7596195    118558936        8
9  chr2          1   93746402      -   2  -87  93746401    212305337        9
gene CDKN2A
gene FANCG
gene NFIB
gene PSIP1
gene MLLT3
gene PAX5
gene PTPRD
gene CXCR4
gene RANBP2
gene RGPD3
gene ERCC3
gene PAX8
gene LRP1B
gene TMEM127
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226366-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  226367-WG01_walk_1_MYCN_containing.fa
bed file     chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr2         1   23824002      +   2  34   23824001     23824001        0
1  chr2  23824003   26413002      +   3  35    2588999     26413000        1
2  chr2  26413003   26739202      +   2  36     326199     26739199        2
3  chr2  26739203   27784002      +   3  37    1044799     27783998        3
4  chr2  27784003   31885602      +   2  38    4101599     31885597        4
5  chr2  31885603   32709202      +   3  39     823599     32709196        5
6  chr2  32709203   38313602      +   2  40    5604399     38313595        6
7  chr2  38313603   38862802      +   3  41     549199     38862794        7
8  chr2  38862803  242193529      +   2  42  203330726    242193520        8
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene STRN
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226367-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  226367-WG01_walk_1_KRAS_containing.fa
bed file      chr      start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12          1  109835402      +   2  17  109835401    109835401        0
1  chr12  109835403  112475802      +   3  18    2640399    112475800        1
2  chr12  112475803  117938802      +   2  19    5462999    117938799        2
3  chr12  117938803  118375002      +   3  20     436199    118374998        3
4  chr12  118375003  119852402      +   2  21    1477399    119852397        4
5  chr12  119852403  123841202      +   3  22    3988799    123841196        5
6  chr12  123841203  133275309      +   2  23    9434106    133275302        6
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ERC1
gene ALDH2
gene SH2B3
gene PTPN11
gene TBX3
gene PTPN11
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226367-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  226365-WG01_walk_1_MDM2_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  133024603  133275309      -   2 -68    250706       250706        0
1  chr12  132675003  133024602      -   3 -67    349599       600305        1
2  chr12  123242178  132675002      -   2 -66   9432824     10033129        2
3  chr12  120955781  123242177      -   3 -65   2286396     12319525        3
4  chr12   49134574  120955780      -   2 -64  71821206     84140731        4
5  chr12   33822397   49134573      -   2 -63  15312176     99452907        5
6  chr12   32772403   32788420      -   2 -61     16017     99468924        6
7  chr12   31251803   32772402      -   3 -60   1520599    100989523        7
8  chr12   30577203   31251802      -   2 -59    674599    101664122        8
9  chr12          1   30577202      -   1 -58  30577201    132241323        9
gene POLE
error!!!! in row index 0
gene NCOR2
gene POLE
gene SETD1B
gene ZCCHC8
gene HNF1A
gene BCL7A
gene CLIP1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene COL2A1
gene ARID2
gene KMT2D
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 38
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  226365-WG01_walk_3_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr20  56336803  56829402      -   4 -170    492599       492599        0
1   chr20  53928603  56336802      -   3 -169   2408199      2900798        1
2   chr20  53819203  53928602      -   4 -168    109399      3010197        2
3   chr20  53508203  53819202      -   5 -167    310999      3321196        3
4   chr20  53135203  53508202      -   4 -166    372999      3694195        4
5   chr20  52271203  53135202      -   3 -165    863999      4558194        5
6   chr20  52076003  52271202      -   4 -164    195199      4753393        6
7   chr20  51584603  52076002      -   5 -163    491399      5244792        7
8   chr20  51048803  51584602      -   4 -162    535799      5780591        8
9   chr20  50424203  51048802      -   5 -161    624599      6405190        9
10  chr20  50196803  50424202      -   4 -160    227399      6632589       10
11  chr20  49614403  50196802      -   5 -159    582399      7214988       11
12  chr20  49256003  49614402      -   4 -158    358399      7573387       12
13  chr20  48778203  49256002      -   5 -157    477799      8051186       13
14  chr20  47777803  48778202      -   4 -156   1000399      9051585       14
15  chr20  47053803  47777802      -   5 -155    723999      9775584       15
16  chr20  43071603  47053802      -   4 -154   3982199     13757783       16
17  chr20  42221603  43071602      -   3 -153    849999     14607782       17
18  chr20  41032003  42221602      -   4 -152   1189599     15797381       18
19  chr20  39088003  41032002      -   2 -151   1943999     17741380       19
20  chr20  38058603  39088002      -   3 -150   1029399     18770779       20
21  chr20  33327203  38058602      -   2 -149   4731399     23502178       21
22  chr20  32724972  33327202      -   3 -148    602230     24104408       22
23  chr20  32005203  32723074      -   3 -146    717871     24822279       23
24  chr20  31001003  32005202      -   4 -145   1004199     25826478       24
25  chr20  30889803  31001002      -   3 -144    111199     25937677       25
26  chr20  30183203  30889802      -   2 -143    706599     26644276       26
27  chr20  28384004  30183202      -   3 -142   1799198     28443474       27
28  chr20  24531058  28384003      -   2 -141   3852945     32296419       28
29   chr1  36221234  66100180      -   3  -21  29878946     62175365       29
30   chr1  16548803  36221233      -   3  -20  19672430     81847795       30
31   chr1  16377803  16548802      -   4  -19    170999     82018794       31
32   chr1  15545003  16377802      -   5  -18    832799     82851593       32
33   chr1  14872203  15545002      -   4  -17    672799     83524392       33
34   chr1  13751603  14872202      -   3  -16   1120599     84644991       34
35   chr1  10527003  13751602      -   4  -15   3224599     87869590       35
36   chr1   8703003  10527002      -   5  -14   1823999     89693589       36
37   chr1   8290003   8703002      -   4  -13    412999     90106588       37
38   chr1   7697203   8290002      -   5  -12    592799     90699387       38
39   chr1   6937603   7697202      -   4  -11    759599     91458986       39
40   chr1   6823003   6937602      -   5  -10    114599     91573585       40
41   chr1   6601960   6823002      -   6   -9    221042     91794627       41
42   chr1   5992759   6601959      -   5   -8    609200     92403827       42
43   chr1   5983803   5992758      -   6   -7      8955     92412782       43
44   chr1   5393203   5983802      -   4   -6    590599     93003381       44
45   chr1   2960639   5393202      -   3   -5   2432563     95435944       45
46   chr1   2800003   2960638      -   4   -4    160635     95596579       46
47   chr1   1747203   2800002      -   5   -3   1052799     96649378       47
48   chr1    883203   1747202      -   4   -2    863999     97513377       48
49   chr1         1    883202      -   3   -1    883201     98396578       49

gene SALL4
gene NFATC2
gene SDC4
gene PTPRT
gene PTPRT
gene TOP1
gene PLCG1
gene PTPRT
gene MAFB
gene TOP1
gene SRC
gene ASXL1
gene MYCL
gene JUN
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene SPEN
gene CASP9
gene PRDM2
gene MTOR
gene PRDM2
gene CAMTA1
gene CAMTA1
gene CAMTA1
gene CAMTA1

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene RPL22
gene PRDM16
gene TNFRSF14
gene SKI
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_17/226365-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  226365-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  62619603  145138636      -   1 -271  82519033     82519033        0
1  chr8  59465003   62619602      -   3 -270   3154599     85673632        1
2  chr8  52057203   59465002      -   1 -269   7407799     93081431        2
3  chr8  48343540   52057202      -   3 -268   3713662     96795093        3
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
running patient  18
running file  227171-WG01_walk_1_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr1         1  40915244      +   2    1  40915243     40915243        0
1    chr1  40915245  40916881      +   3    2      1636     40916879        1
2    chr1  40916882  40921229      +   5    3      4347     40921226        2
3    chr1  40921230  40988939      +   7    4     67709     40988935        3
4    chr1  40988940  41018525      +   9    5     29585     41018520        4
5    chr1  41018526  41025841      +   5    6      7315     41025835        5
6    chr1  41025842  41034755      +   7    7      8913     41034748        6
7   chr12  53979984  54031841      +  23   45     51857     41086605        7
8   chr19  48920258  48938839      -  23 -454     18581     41105186        8
9   chr19  48920203  48920257      -  35 -453        54     41105240        9
10  chr19  48917956  48920202      -  41 -452      2246     41107486       10
11  chr19  48870298  48917955      -  39 -451     47657     41155143       11
12  chr19  48838918  48870297      -  28 -450     31379     41186522       12
13  chr19  48830591  48838917      -  22 -449      8326     41194848       13
14  chr19  48821050  48830590      -  20 -448      9540     41204388       14
15  chr19  49930782  49944858      +  20  456     14076     41218464       15
16  chr19  49944859  49967656      +  11  457     22797     41241261       16
17  chr12  64488223  64513753      +  11   71     25530     41266791       17
18  chr19  20935618  20947383      -  10 -438     11765     41278556       18
19  chr19         1  20935617      -   2 -437  20935616     62214172       19
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene FSTL3
gene CD209
gene LYL1
gene STK11
gene TCF3
gene GNA11
gene MAP2K2
gene SH3GL1
gene MLLT1
gene KEAP1
gene CALR
gene PRKACA
gene DNAJB1
gene BRD4
gene TPM4
gene VAV1
gene MUC16
gene DNM2
gene SMARCA4
gene CRTC1
gene ELL
gene JAK3
running file  227171-WG01_walk_2_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  70869003  70878373      +  14  144      9370         9370        0
1    chr1  40988940  41018525      +   9    5     29585        38955        1
2    chr1  41018526  41025841      +   5    6      7315        46270        2
3    chr1  41025842  41034755      +   7    7      8913        55183        3
4   chr12  53979984  54031841      +  23   45     51857       107040        4
5   chr19  48920258  48938839      -  23 -454     18581       125621        5
6   chr19  48920203  48920257      -  35 -453        54       125675        6
7   chr19  48917956  48920202      -  41 -452      2246       127921        7
8   chr19  48870298  48917955      -  39 -451     47657       175578        8
9   chr19  48838918  48870297      -  28 -450     31379       206957        9
10  chr19  48830591  48838917      -  22 -449      8326       215283       10
11  chr19  48821050  48830590      -  20 -448      9540       224823       11
12  chr19  49930782  49944858      +  20  456     14076       238899       12
13  chr19  49944859  49967656      +  11  457     22797       261696       13
14  chr12  64488223  64513753      +  11   71     25530       287226       14
15  chr19  20935618  20947383      -  10 -438     11765       298991       15
16  chr12  59593605  59706260      +  10   65    112655       411646       16
17  chr12  59706261  59706702      +  12   66       441       412087       17
18  chr12  59706703  59821563      +  10   67    114860       526947       18
19  chr19  38747547  38751811      -  10 -446      4264       531211       19
20  chr19  38746817  38747546      -   8 -445       729       531940       20
21  chr19  38660444  38746816      -   2 -444     86372       618312       21
22  chr19  38659353  38660443      -   5 -443      1090       619402       22
23  chr19  38393068  38613909      +   2  441    220841       840243       23
24  chr19  38613910  38659352      +   3  442     45442       885685       24
25  chr19  38659353  38660443      +   5  443      1090       886775       25
26  chr19  50488089  50510818      +   5  459     22729       909504       26
27  chr12  56074763  56110705      -   8  -51     35942       945446       27
28  chr12  63917459  63938524      -   7  -69     21065       966511       28
29  chr12  54034022  54043914      +   7   47      9892       976403       29
30  chr12  54043915  56034003      +   2   48   1990088      2966491       30
31  chr12  56034004  56069797      +   8   49     35793      3002284       31
32  chr12  53818379  53825867      -   7  -41      7488      3009772       32
33  chr12         1  53818378      -   2  -40  53818377     56828149       33
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 3
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227171-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227170-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  424  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227171-WG01_walk_2_MDM2_containing.fa
bed file        chr     start       end strand  cn    5   span  span_cumsum  bed_idx
0    chr12  69721927  69722138      -  16 -116    211          211        0
1    chr12  69663931  69721926      -  17 -115  57995        58206        1
2    chr12  69643864  69663930      -  15 -114  20066        78272        2
3    chr12  69583803  69643863      -  13 -113  60060       138332        3
4    chr12  69505301  69583802      -  26 -112  78501       216833        4
..     ...       ...       ...    ...  ..  ...    ...          ...      ...
162  chr12  69505301  69583802      +  26  112  78501     34140483      162
163  chr12  69583803  69643863      +  13  113  60060     34200543      163
164  chr12  69643864  69663930      +  15  114  20066     34220609      164
165  chr12  69663931  69721926      +  17  115  57995     34278604      165
166  chr12  69721927  69722138      +  16  116    211     34278815      166

[167 rows x 9 columns]
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene HOXC13
gene HOXC11
gene BCL3
gene CD79A
gene CIC
gene CBLC
gene AKT2
gene ERCC2
gene ARHGAP35
gene ERBB3
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene CDK4
gene PRDM1
gene FOXO3
gene CDK4
gene NAB2
gene GLI1
gene DDIT3
gene NACA
gene STAT6
gene ERBB3
gene BCL3
gene CD79A
gene CIC
gene CBLC
gene AKT2
gene ERCC2
gene ARHGAP35
gene HOXC13

gene HOXC11
gene MDM2

/tmp/ipykernel_1359333/1934763841.py:8: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig=plt.figure(figsize=(7.5,6))

gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227171-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  227171-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  467  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  227169-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  440  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  227170-WG01_walk_1_MYCN_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2      1  242193529      +   2  329  242193528    242193528        0
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running file  227169-WG01_walk_2_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12         1  53874002      +   2   46  53874001     53874001        0
1   chr12  53874003  53938402      +  17   47     64399     53938400        1
2   chr12  53938403  53979983      +  14   48     41580     53979980        2
3   chr12  53979984  54031847      +  16   49     51863     54031843        3
4   chr19  48920258  48938841      -  17 -430     18583     54050426        4
5   chr19  48917956  48920257      -  28 -429      2301     54052727        5
6   chr19  48870298  48917955      -  26 -428     47657     54100384        6
7   chr19  48838918  48870297      -  23 -427     31379     54131763        7
8   chr19  48831518  48838917      -  18 -426      7399     54139162        8
9   chr19  48821050  48831517      -  21 -425     10467     54149629        9
10  chr19  49930782  49944858      +  16  432     14076     54163705       10
11  chr19  49944859  49967656      +  11  433     22797     54186502       11
12  chr12  64488223  64513753      +  11   73     25530     54212032       12
13  chr19  20942078  20947383      -  10 -418      5305     54217337       13
14  chr19  20935618  20942077      -   7 -417      6459     54223796       14
15  chr12  59593605  59668002      +   7   68     74397     54298193       15
16  chr12  59668003  59821563      +   8   69    153560     54451753       16
17  chr19  38746817  38751811      -   8 -422      4994     54456747       17
18  chr12  56034004  56074762      +   8   53     40758     54497505       18
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
gene HOXC13
gene HOXC11
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227169-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227170-WG01_walk_1_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr1         1  40915892      +   2    1  40915891     40915891        0
1    chr1  40915893  40988939      +   5    2     73046     40988937        1
2    chr1  40988940  41018525      +   7    3     29585     41018522        2
3    chr1  41018526  41034755      +   5    4     16229     41034751        3
4   chr12  53979984  54031767      +  13   33     51783     41086534        4
5   chr19  48920258  48938824      -  14 -316     18566     41105100        5
6   chr19  48917956  48920257      -  22 -315      2301     41107401        6
7   chr19  48870298  48917955      -  20 -314     47657     41155058        7
8   chr19  48821050  48870297      -  15 -313     49247     41204305        8
9   chr19  49930782  49944934      +  15  318     14152     41218457        9
10  chr19  49944935  49967656      +   7  319     22721     41241178       10
11  chr12  64488223  64513753      +   7   55     25530     41266708       11
12  chr12  64513754  64717973      +   3   56    204219     41470927       12
13  chr12  64717974  64722657      +   4   57      4683     41475610       13
14  chr12  64722658  68658774      +   2   58   3936116     45411726       14
15  chr19  38154135  38195056      -   4 -309     40921     45452647       15
16  chr19  54372081  54429353      -   4 -323     57272     45509919       16
17  chr19  54199456  54372080      -   2 -322    172624     45682543       17
18  chr19  54178120  54199455      -   7 -321     21335     45703878       18
19  chr12  96281106  96315853      +   7  267     34747     45738625       19
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene WIF1
gene HMGA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227170-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  227169-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  551  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227171-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  594  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227171-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr19  38154135  38393067      -   3 -440    238932       238932        0
1   chr19  54372081  54429353      -   7 -461     57272       296204        1
2   chr19  50510819  54372080      -   2 -460   3861261      4157465        2
3   chr19  50488089  50510818      -   5 -459     22729      4180194        3
4   chr19  38659353  38660443      -   5 -443      1090      4181284        4
5   chr19  38613910  38659352      -   3 -442     45442      4226726        5
6   chr19  38393068  38613909      -   2 -441    220841      4447567        6
7   chr19  38659353  38660443      +   5  443      1090      4448657        7
8   chr19  50488089  50510818      +   5  459     22729      4471386        8
9   chr12  56074763  56110705      -   8  -51     35942      4507328        9
10  chr12  63917459  63938524      -   7  -69     21065      4528393       10
11  chr12  54034022  54043914      +   7   47      9892      4538285       11
12  chr12  54043915  56034003      +   2   48   1990088      6528373       12
13  chr12  56034004  56069797      +   8   49     35793      6564166       13
14  chr12  53818379  53825867      -   7  -41      7488      6571654       14
15  chr12         1  53818378      -   2  -40  53818377     60390031       15

gene KLK2
gene TFPT
gene PPP2R1A
gene ZNF331
gene CNOT3
gene ERBB3
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227171-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227169-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr20   29204768   64444167      -   2 -450  35239399     35239399
1   chr20   26559003   29204767      -   3 -449   2645764     37885163
2   chr20   10138632   26559002      -   2 -448  16420370     54305533
3   chr20   10099230   10138631      -   8 -447     39401     54344934
4   chr12   88235214   88238066      +  11  329      2852     54347786
5   chr12   69386709   69415442      +  15   97     28733     54376519
6   chr12   69415443   69428597      +  17   98     13154     54389673
7   chr12   69428598   69452621      +  20   99     24023     54413696
8   chr12   69452622   69459850      +  25  100      7228     54420924
9    chr1   41527693   41530707      -   6  -22      3014     54423938
10   chr1   41691246   41691351      -   8  -26       105     54424043
11   chr1   41525604   41525676      -   8  -20        72     54424115
12   chr1   41525596   41525603      -   9  -19         7     54424122
13   chr1   41525539   41525595      -  34  -18        56     54424178
14   chr1   41525432   41525538      -  35  -17       106     54424284
15   chr1   41525390   41525431      -  10  -16        41     54424325
16  chr12   69505081   69505300      -  24 -106       219     54424544
17  chr12   76457255   76469923      -   8 -200     12668     54437212
18  chr12   71291575   71306229      +  13  151     14654     54451866
19  chr12   71306230   71308010      +  15  152      1780     54453646
20  chr12   71308011   71323402      +  13  153     15391     54469037
21  chr12   71323403   71365415      +   7  154     42012     54511049
22  chr20    4919379    4925117      -   7 -443      5738     54516787
23  chr20    4552296    4919378      -   5 -442    367082     54883869
24  chr12   77836863   77838698      -  27 -212      1835     54885704
25  chr12   71163176   71284999      -   9 -149    121823     55007527
26  chr12   71058067   71163175      -  10 -148    105108     55112635
27  chr12   71053833   71058066      -  16 -147      4233     55116868
28  chr12   71021877   71053832      -  12 -146     31955     55148823
29  chr12   88228021   88234823      +  10  327      6802     55155625
30  chr12  109742110  109744583      +   5  368      2473     55158098
31  chr12  109744584  109744691      +   6  369       107     55158205
32  chr12   73377452   73435803      +   4  184     58351     55216556
33  chr19   48917956   48920257      +  28  429      2301     55218857
34  chr19   48920258   48938841      +  17  430     18583     55237440
35  chr12   53979984   54031847      -  16  -49     51863     55289303
36  chr12   53938403   53979983      -  14  -48     41580     55330883
37  chr12   53874003   53938402      -  17  -47     64399     55395282
38  chr12          1   53874002      -   2  -46  53874001    109269283

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
gene MAFB
gene TOP1
gene SDC4
gene SALL4
gene GNAS
gene SS18L1
gene PTK6
gene ASXL1
gene SRC
gene PLCG1
gene NFATC2
gene PTPRT
gene CRNKL1
gene HOXC13
gene HOXC11
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 17
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227169-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227169-WG01_walk_2_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr1         1  40915244      +   2    1  40915243     40915243        0
1    chr1  40915245  40916081      +   3    2       836     40916079        1
2    chr1  40916082  40921229      +   2    3      5147     40921226        2
3    chr1  40921230  40988939      +   6    4     67709     40988935        3
4    chr1  40988940  41018525      +   8    5     29585     41018520        4
5   chr12  72723636  72737542      +  12  172     13906     41032426        5
6   chr12  72737543  72749184      +  17  173     11641     41044067        6
7   chr12  96315854  96370110      -  12 -358     54256     41098323        7
8   chr12  96304847  96315853      -   9 -357     11006     41109329        8
9   chr12  96281106  96304846      -  13 -356     23740     41133069        9
10  chr12  96116603  96281105      -   6 -355    164502     41297571       10
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  227171-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr13  84507570  84636701      -   8 -423    129131       129131        0
1   chr13  84434603  84507569      -   7 -422     72966       202097        1
2   chr13  83110557  84434602      -   2 -421   1324045      1526142        2
3   chr13  83084109  83110556      -   4 -420     26447      1552589        3
4   chr13  48177128  83084108      -   2 -419  34906980     36459569        4
5   chr13  48175431  48177127      -   7 -418      1696     36461265        5
6   chr12  68838474  68846348      -  33  -87      7874     36469139        6
7   chr12  68821183  68838473      -  38  -86     17290     36486429        7
8   chr12  68821152  68821182      -  39  -85        30     36486459        8
9   chr12  68820959  68821151      -  47  -84       192     36486651        9
10  chr12  68820937  68820958      -  46  -83        21     36486672       10
11  chr12  68806008  68820936      -  38  -82     14928     36501600       11
12  chr12  68803054  68806007      -  40  -81      2953     36504553       12
13  chr12  68798616  68803053      -  38  -80      4437     36508990       13
14  chr12  68769849  68798615      -  32  -79     28766     36537756       14
15  chr15  71026385  71026692      -   3 -430       307     36538063       15
16  chr15  70982232  71026384      -   7 -429     44152     36582215       16
17  chr12  81795729  81837202      +  11  323     41473     36623688       17
18  chr12  81837203  81863660      +   6  324     26457     36650145       18
19  chr12  81863661  81864341      +   8  325       680     36650825       19
20  chr13  83084109  83110556      +   4  420     26447     36677272       20
21  chr13  83110557  84434602      +   2  421   1324045     38001317       21
22  chr13  84434603  84507569      +   7  422     72966     38074283       22
23  chr13  84507570  84636701      +   8  423    129131     38203414       23
24  chr13  84636702  84764957      +   6  424    128255     38331669       24
25  chr13  84764958  84953202      +   8  425    188244     38519913       25
gene CYSLTR2
gene RB1
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227171-WG01_walk_1_MDM2_containing_breakpoints.pdf

running file  227170-WG01_walk_2_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr1         1  40915892      +   2    1  40915891     40915891        0
1    chr1  40915893  40988939      +   5    2     73046     40988937        1
2    chr1  40988940  41018525      +   7    3     29585     41018522        2
3   chr12  72723636  72831074      +  10  121    107438     41125960        3
4   chr12  72831075  72911417      +   7  122     80342     41206302        4
5   chr12  72911418  72942937      +   4  123     31519     41237821        5
6   chr12  72942938  73029185      +   6  124     86247     41324068        6
7   chr12  73029186  73192002      +   5  125    162816     41486884        7
8   chr12  73192003  73192077      +   3  126        74     41486958        8
9   chr12  89340376  89536803      +   5  262    196427     41683385        9
10  chr12  89536804  89565247      +   3  263     28443     41711828       10
11  chr12  88264800  88401605      -  10 -253    136805     41848633       11
12  chr12  88260800  88264799      -  12 -252      3999     41852632       12
13  chr12  88255870  88260799      -   8 -251      4929     41857561       13
14  chr12  88235214  88255869      -  10 -250     20655     41878216       14
15  chr12  88234824  88235213      -   8 -249       389     41878605       15
16  chr12  88228021  88234823      -  10 -248      6802     41885407       16
17  chr12  88212743  88228020      -   7 -247     15277     41900684       17
18  chr12  78075094  78079346      +  18  164      4252     41904936       18
19  chr12  79060227  79061884      -  18 -182      1657     41906593       19
20  chr12  79051600  79060226      -  17 -181      8626     41915219       20
21  chr12  80845336  80850163      +  20  208      4827     41920046       21
22  chr12  79729690  79739595      +  16  192      9905     41929951       22
23  chr12  77034214  77062312      -  16 -148     28098     41958049       23
24  chr12  58142954  58171745      +  17   49     28791     41986840       24
25  chr12  86715743  86715893      -  30 -240       150     41986990       25
26  chr12  86712657  86715742      -  18 -239      3085     41990075       26
27  chr12  86712588  86712656      -  16 -238        68     41990143       27
28  chr12  86720671  86721021      -  16 -244       350     41990493       28
29  chr12  86718659  86720670      -  13 -243      2011     41992504       29
30  chr12  75009957  75011296      -  14 -139      1339     41993843       30
31  chr12  75007109  75009956      -  17 -138      2847     41996690       31
32  chr12  75006926  75007108      -  19 -137       182     41996872       32
33  chr12  74990340  75006925      -  17 -136     16585     42013457       33
34  chr12  80310535  80317666      +  16  194      7131     42020588       34
35  chr12  80317667  80331582      +  18  195     13915     42034503       35
36  chr12  80331583  80353991      +  23  196     22408     42056911       36
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  227169-WG01_walk_1_MYCL_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr1         1  40915244      +   2    1  40915243     40915243        0
1    chr1  40915245  40916081      +   3    2       836     40916079        1
2    chr1  41149806  41524667      -   5  -13    374861     41290940        2
3    chr1  41083395  41149805      -   6  -12     66410     41357350        3
4   chr12  69679717  69682470      -  18 -115      2753     41360103        4
5   chr12  69663931  69679716      -  17 -114     15785     41375888        5
6    chr1  40921230  40988939      +   6    4     67709     41443597        6
7    chr1  40988940  41018525      +   8    5     29585     41473182        7
8   chr12  72723636  72737542      +  12  172     13906     41487088        8
9   chr12  72737543  72749184      +  17  173     11641     41498729        9
10  chr12  96315854  96370110      -  12 -358     54256     41552985       10
11  chr12  96304847  96315853      -   9 -357     11006     41563991       11
12  chr12  96281106  96304846      -  13 -356     23740     41587731       12
13  chr19  54178120  54199455      +   9  435     21335     41609066       13
14  chr12  81864163  81864169      +   7  300         6     41609072       14
15  chr12  81864170  81864341      +  10  301       171     41609243       15
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
running file  227170-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr19  38747547  38751811      +   6  311      4264         4264        0
1   chr12  59593605  59821563      -   6  -51    227958       232222        1
2   chr19  20935618  20947383      +   6  307     11765       243987        2
3   chr12  64488223  64513753      -   7  -55     25530       269517        3
4   chr19  49944935  49967656      -   7 -319     22721       292238        4
5   chr19  49930782  49944934      -  15 -318     14152       306390        5
6   chr19  48821050  48870297      +  15  313     49247       355637        6
7   chr19  48870298  48917955      +  20  314     47657       403294        7
8   chr19  48917956  48920257      +  22  315      2301       405595        8
9   chr19  48920258  48938824      +  14  316     18566       424161        9
10  chr12  53979984  54031767      -  13  -33     51783       475944       10
11  chr12  53818379  53979983      -   7  -32    161604       637548       11
12  chr12         1  53818378      -   2  -31  53818377     54455925       12
gene HOXC13
gene HOXC11
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_18/227170-WG01_walk_1_KRAS_containing_breakpoints.pdf
running patient  19
running file  227173-WG01_walk_2_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   69373564   69428802      -  23 -195     55238        55238
1   chr12   69373158   69373563      -  24 -194       405        55643
2   chr11  103738696  103739232      -   8 -105       536        56179
3   chr11  102508803  103738695      -   6 -104   1229892      1286071
4   chr11  102091605  102508802      -   7 -103    417197      1703268
5   chr11  102091366  102091604      -   9 -102       238      1703506
6   chr11  102091346  102091365      -   8 -101        19      1703525
7   chr11  102043926  102091345      -   7 -100     47419      1750944
8   chr11   55272003  102043925      -   2  -99  46771922     48522866
9   chr11   52669788   55272002      -   3  -98   2602214     51125080
10  chr11   23224943   52669787      -   2  -97  29444844     80569924
11  chr11   23095892   23224942      -  10  -96    129050     80698974
12  chr11   20588727   20588869      -  10  -67       142     80699116
13  chr11   20513293   20588726      -   7  -66     75433     80774549
14  chr11   20413635   20513292      -   6  -65     99657     80874206
15  chr11   20279840   20413634      -   9  -64    133794     81008000
16  chr11   20265949   20279839      -  11  -63     13890     81021890
17  chr11   20240914   20265948      -   8  -62     25034     81046924
18  chr11   20229932   20240913      -   7  -61     10981     81057905
19  chr11   20227380   20229931      -  11  -60      2551     81060456
20  chr12   68320087   68326644      -   9 -157      6557     81067013
21  chr12   68309435   68320086      -   6 -156     10651     81077664
22  chr12   68256418   68309434      -   7 -155     53016     81130680
23  chr12   68148603   68256417      -   6 -154    107814     81238494
24  chr12   68070728   68148602      -   9 -153     77874     81316368
25  chr12   68040718   68070727      -   7 -152     30009     81346377
26  chr12   68001603   68040717      -   4 -151     39114     81385491
27  chr12   67954203   68001602      -   8 -150     47399     81432890
28  chr12   67892003   67954202      -   3 -149     62199     81495089
29  chr12   67871275   67892002      -   7 -148     20727     81515816
30  chr11   22211160   22260376      +   7   90     49216     81565032
31  chr12   70011946   70022868      +  24  208     10922     81575954
32  chr12   70022869   70050363      +  25  209     27494     81603448
33  chr12   70050364   70052473      +  31  210      2109     81605557
34  chr12   70109388   70117810      +  38  213      8422     81613979
35  chr12   68789837   68842036      +  30  167     52199     81666178
36  chr12   68842037   68853635      +  28  168     11598     81677776
37  chr12   68853636   68884225      +  29  169     30589     81708365
38  chr12   68884226   68909642      +  37  170     25416     81733781
39  chr12   68909643   68937027      +  26  171     27384     81761165
40  chr12   68937028   68955688      +  30  172     18660     81779825
41  chr11   20676268   20684559      +  19   72      8291     81788116
42  chr11   20684560   20696147      +  21   73     11587     81799703
43  chr11   20696148   20710659      +  20   74     14511     81814214
44  chr11   20928907   20953030      +   5   81     24123     81838337
45  chr11   20953031   20961857      +   8   82      8826     81847163
46  chr11   20961858   21017895      +   4   83     56037     81903200
47  chr11   21017896   21046602      +   5   84     28706     81931906

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47

gene BIRC3
gene CLP1
gene FEN1
gene MEN1
gene SDHAF2
gene MALAT1
gene CCND1
gene FADD
gene NUMA1
gene CTNND1
gene EED
gene FAT3
gene MAML2
gene PICALM
gene WT1
gene LMO2
gene CREB3L1
gene DDB2
gene EXT2
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_19/227173-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  227172-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2          1  201281935      +   2  340  201281934    201281934        0
1  chr2  201284718  242193529      +   2  342   40908811    242190745        1
gene PCBP1
gene CXCR4
gene HOXD11
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene ACKR3
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene CUL3
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_19/227172-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227172-WG01_walk_1_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8          1   74450636      +   2  436  74450635     74450635        0
1  chr8   74454765  136147954      +   2  438  61693189    136143824        1
2  chr8  136151656  145138636      +   2  440   8986980    145130804        2
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene NCOA2
gene PREX2
gene KAT6A
gene HEY1
gene MYC
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene RECQL4
gene FAM135B
running file  227173-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  57672888  57682002      -  17 -117      9114         9114        0
1  chr12  57628318  57672887      -  18 -116     44569        53683        1
2  chr12  57619895  57628317      -  13 -115      8422        62105        2
3  chr12  57569720  57619894      -  17 -114     50174       112279        3
4  chr12  57527478  57569719      -  13 -113     42241       154520        4
5  chr12  57527403  57527477      -   5 -112        74       154594        5
6  chr12         1  57527402      -   2 -111  57527401     57681995        6
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  227173-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2          1   41746016      +   2  273   41746015     41746015        0
1  chr2   41748726  201281935      +   2  275  159533209    201279224        1
2  chr2  201284718  242193529      +   2  277   40908811    242188035        2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene STRN
gene ALK
gene BIRC6
gene PCBP1
gene CXCR4
gene HOXD11
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene FEV
gene ACKR3
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene CUL3
gene ERBB4
gene PAX3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_19/227173-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227172-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5    span  span_cumsum  bed_idx
0    chr6  127293025  127560602      -   6 -374  267577       267577        0
1    chr6  127084577  127293024      -   7 -373  208447       476024        1
2    chr6  126742355  127084576      -   6 -372  342221       818245        2
3   chr12   69621570   69631189      +  14  230    9619       827864        3
4   chr12   57712241   57717085      +  23  140    4844       832708        4
..    ...        ...        ...    ...  ..  ...     ...          ...      ...
58  chr12   68789837   68873398      -  48 -190   83561     51606359       58
59  chr12   68789803   68789836      -  24 -189      33     51606392       59
60  chr12   68670281   68789802      -   7 -188  119521     51725913       60
61  chr11   19990065   19996342      +  17   58    6277     51732190       61
62  chr11   19996343   19996402      +   9   59      59     51732249       62

[63 rows x 9 columns]
gene RSPO3
error!!!! in row index 0
gene ETV1
gene MACC1
gene HOXA11
gene HNRNPA2B1
gene HOXA13
gene HOXA9
gene FKBP9
gene JAZF1
gene PTPRK
gene PTPRK
gene MYB
gene SGK1
gene BCLAF1
gene BCLAF1
gene TNFAIP3
gene ECT2L
gene LATS1
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_19/227172-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  227173-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8         1   74450636      +   2  342  74450635     74450635        0
1  chr8  74454765  145138636      +   2  344  70683871    145134506        1
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene HOOK3
gene NCOA2
gene PREX2
gene KAT6A
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227173-WG01_walk_3_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr11   14689261   14716002      -  12  -30     26741        26741
1   chr11   14625965   14689260      -  16  -29     63295        90036
2   chr11   14527203   14625964      -  17  -28     98761       188797
3   chr11   14505567   14527202      -  23  -27     21635       210432
4   chr11   14484254   14505566      -  22  -26     21312       231744
5   chr11   16771001   16781690      -   5  -35     10689       242433
6   chr12   91481572   91751567      +   5  242    269995       512428
7   chr12   91751568   95495692      +   2  243   3744124      4256552
8   chr12   95495693   96552018      +   5  244   1056325      5312877
9   chr12   96552019   97896718      +   2  245   1344699      6657576
10  chr12   97896719   97917113      +   7  246     20394      6677970
11  chr12   97917114   97923328      +   4  247      6214      6684184
12  chr12   97923329   97965081      +   2  248     41752      6725936
13  chr12   97965082   97967580      +   4  249      2498      6728434
14  chr12   97967581  121121602      +   2  250  23154021     29882455
15  chr12  121121603  122771802      +   3  251   1650199     31532654
16  chr12  122771803  130118802      +   2  252   7346999     38879653
17  chr12  130118803  130226436      +   8  253    107633     38987286
18  chr11   14272348   14272402      +   8   16        54     38987340
19  chr11   14272403   14385756      +   9   17    113353     39100693
20  chr11   14385757   14390327      +  12   18      4570     39105263
21  chr11   14390328   14404126      +  14   19     13798     39119061
22  chr11   14404127   14421598      +  12   20     17471     39136532
23  chr11   14421599   14455574      +  17   21     33975     39170507
24  chr11   14455575   14457111      +  18   22      1536     39172043
25  chr11   14457112   14460830      +  19   23      3718     39175761
26  chr11   14460831   14482945      +  20   24     22114     39197875
27  chr11   14482946   14484253      +  19   25      1307     39199182
28  chr11   14484254   14505566      +  22   26     21312     39220494
29  chr11   14505567   14527202      +  23   27     21635     39242129
30  chr11   14527203   14625964      +  17   28     98761     39340890
31  chr11   14625965   14689260      +  16   29     63295     39404185
32  chr11   14689261   14716002      +  12   30     26741     39430926
33  chr11   14716003   15036602      +   9   31    320599     39751525
34  chr11   15036603   15073823      +   7   32     37220     39788745
35  chr11   15073824   15095300      +  13   33     21476     39810221
36  chr12   68884226   68909642      -  37 -170     25416     39835637
37  chr12   68853636   68884225      -  29 -169     30589     39866226
38  chr12   68842037   68853635      -  28 -168     11598     39877824
39  chr12   68789837   68842036      -  30 -167     52199     39930023
40  chr12   70109388   70117810      -  38 -213      8422     39938445
41  chr12   70083444   70109387      -  29 -212     25943     39964388
42  chr12   68467933   68483896      +  11  161     15963     39980351
43  chr12   68040718   68070727      +   7  152     30009     40010360
44  chr12   68070728   68148602      +   9  153     77874     40088234

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44

gene BTG1
gene USP44
gene TBX3
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene SETD1B
gene ZCCHC8
gene BCL7A
gene CLIP1
gene NCOR2
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_19/227173-WG01_walk_3_MDM2_containing_breakpoints.pdf
running file  227172-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  227172-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  57671219  57682202      -  31 -138     10983        10983        0
1  chr12  57628318  57671218      -  27 -137     42900        53883        1
2  chr12  57619895  57628317      -  21 -136      8422        62305        2
3  chr12  57607901  57619894      -  27 -135     11993        74298        3
4  chr12  57572638  57607900      -  26 -134     35262       109560        4
5  chr12  57569720  57572637      -  23 -133      2917       112477        5
6  chr12  57527753  57569719      -  17 -132     41966       154443        6
7  chr12  57527477  57527752      -  12 -131       275       154718        7
8  chr12         1  57527476      -   2 -130  57527475     57682193        8
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene KDM5A
error!!!! in row index 7
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene ERC1
running file  227173-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1  199469615      +   2  1  199469614    199469614        0
1  chr1  199471106  248956422      +   2  3   49485316    248954930        1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene AKT3
gene RGS7
running file  227173-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr11  102091605  102508802      -   7 -103    417197       417197
1   chr11  102091366  102091604      -   9 -102       238       417435
2   chr11  102091346  102091365      -   8 -101        19       417454
3   chr11  102043926  102091345      -   7 -100     47419       464873
4   chr11   55272003  102043925      -   2  -99  46771922     47236795
5   chr11   52669788   55272002      -   3  -98   2602214     49839009
6   chr11   23224943   52669787      -   2  -97  29444844     79283853
7   chr11   23095892   23224942      -  10  -96    129050     79412903
8   chr11   20588727   20588869      -  10  -67       142     79413045
9   chr11   21902483   22086342      -   5  -88    183859     79596904
10  chr12   70439440   70500098      +  17  217     60658     79657562
11  chr12   70500099   70522093      +  16  218     21994     79679556
12  chr12   75416384   75432985      +  16  222     16601     79696157
13  chr12   75432986   75449011      +  20  223     16025     79712182
14  chr12   75449012   75453855      +  17  224      4843     79717025
15  chr12   68999937   69038362      -  32 -176     38425     79755450
16  chr12   68982825   68999936      -  31 -175     17111     79772561
17  chr11   19477625   19523906      -  17  -44     46281     79818842
18  chr11   19996343   20061164      -  11  -55     64821     79883663
19  chr11   19990065   19996342      -  12  -54      6277     79889940
20  chr12   68670281   68789836      +   6  166    119555     80009495
21  chr12   68789837   68842036      +  30  167     52199     80061694
22  chr12   68842037   68853635      +  28  168     11598     80073292
23  chr12   68853636   68884225      +  29  169     30589     80103881
24  chr12   68884226   68909642      +  37  170     25416     80129297
25  chr11   15073824   15095300      -  13  -33     21476     80150773
26   chr6  150225304  150331153      -   8 -332    105849     80256622
27   chr7    7537923    8037837      -   4 -337    499914     80756536
28   chr7    6873203    7537922      -   5 -336    664719     81421255
29   chr7    5914203    6873202      -   4 -335    958999     82380254
30   chr7          1    5914202      -   2 -334   5914201     88294455

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
gene BIRC3
error!!!! in row index 0
gene CLP1
gene FEN1
gene MEN1
gene SDHAF2
gene MALAT1
gene CCND1
gene FADD
gene NUMA1
gene CTNND1
gene EED
gene FAT3
gene MAML2
gene PICALM
gene WT1
gene LMO2
gene CREB3L1
gene DDB2
gene EXT2
gene PTPRB
gene MDM2
gene MDM2
gene PMS2
gene RAC1
gene CARD11
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_19/227173-WG01_walk_1_MDM2_containing_breakpoints.pdf
running patient  20
running file  227176-WG01_walk_2_MDM2_containing.fa
bed file      chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  16267190  133275309      +   2  42  117008119    117008119        0
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  227175-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2    4739767   75001602      -   5 -160  70261835     70261835        0
1  chr2     676832    4733720      -   5 -158   4056888     74318723        1
2  chr4  146006603  164350314      -   4 -229  18343711     92662434        2
3  chr4   75275403  146006602      -   5 -228  70731199    163393633        3
4  chr4   58922003   75275402      -   4 -227  16353399    179747032        4
5  chr4   49903204   58922002      -   5 -226   9018798    188765830        5
6  chr4          1   49903203      -   4 -225  49903202    238669032        6
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11

gene MSH2
gene ALK
gene BIRC6
gene FBXW7
gene IL2
gene PTPN13
gene RAP1GDS1
gene TET2
gene LEF1
gene FAT4
gene AFF1
gene FIP1L1
gene CHIC2
gene KIT
gene KDR
gene PDGFRA
gene FGFR3
gene SLC34A2
gene PHOX2B
gene NSD2
gene N4BP2
gene RHOH
gene TEC
running file  227176-WG01_walk_1_KRAS_containing.fa
bed file      chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  16267190  133275309      -   2 -42  117008119    117008119        0
1  chr12         1   16267189      -   1 -41   16267188    133275307        1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227175-WG01_walk_4_MDM2_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  119817803  121466403      -   5 -63   1648600      1648600        0
1  chr12   70763203  119817802      -   4 -62  49054599     50703199        1
2  chr12   37924724   70763202      -   5 -61  32838478     83541677        2
3  chr12   37924385   37924723      -   6 -60       338     83542015        3
4  chr12   37168603   37924384      -   6 -59    755781     84297796        4
5  chr12   28857203   37168602      -   5 -58   8311399     92609195        5
gene HNF1A
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_4_MDM2_containing_breakpoints.pdf
running file  227175-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr12  133046203  133275309      -   4 -74    229106       229106        0
1   chr12  132811603  133046202      -   5 -73    234599       463705        1
2   chr12  129519203  132811602      -   4 -72   3292399      3756104        2
3   chr12  128800603  129519202      -   5 -71    718599      4474703        3
4   chr12  125184803  128800602      -   4 -70   3615799      8090502        4
5   chr12  124851603  125184802      -   5 -69    333199      8423701        5
6   chr12  124254203  124851602      -   4 -68    597399      9021100        6
7   chr12  123704803  124254202      -   5 -67    549399      9570499        7
8   chr12  123151603  123704802      -   7 -66    553199     10123698        8
9   chr12  121702603  123151602      -   6 -65   1448999     11572697        9
10  chr12  121466404  121702602      -   3 -64    236198     11808895       10
11  chr12  119817803  121466403      -   5 -63   1648600     13457495       11
12  chr12   70763203  119817802      -   4 -62  49054599     62512094       12
13  chr12   37924724   70763202      -   5 -61  32838478     95350572       13
14  chr12   37924385   37924723      -   6 -60       338     95350910       14
15  chr12   37168603   37924384      -   6 -59    755781     96106691       15
16  chr12   28857203   37168602      -   5 -58   8311399    104418090       16
17  chr12          1   28857202      -   2 -57  28857201    133275291       17
gene POLE
gene NCOR2
gene SETD1B
gene ZCCHC8
gene BCL7A
gene CLIP1
gene HNF1A
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227175-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  37168603  37924384      +   6  59    755781       755781        0
1  chr12  37924385  37924723      +   6  60       338       756119        1
2  chr12  37168603  37924384      -   6 -59    755781      1511900        2
3  chr12  28857203  37168602      -   5 -58   8311399      9823299        3
4  chr12         1  28857202      -   2 -57  28857201     38680500        4
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
running file  227176-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5       span  span_cumsum  \
0   chr2  208349803  242193529      -   1 -156   33843726     33843726
1   chr2  207865203  208349802      -   2 -155     484599     34328325
2   chr2  207559803  207865202      -   3 -154     305399     34633724
3   chr2   94065403  207559802      -   2 -153  113494399    148128123
4   chr2   86726804   94065402      -   3 -152    7338598    155466721
5   chr2   11432203   86726803      -   2 -151   75294600    230761321
6   chr2    8732403   11432202      -   3 -150    2699799    233461120
7   chr2    3790203    8732402      -   2 -149    4942199    238403319
8   chr2    3172803    3790202      -   3 -148     617399    239020718
9   chr2     688003    3172802      -   2 -147    2484799    241505517
10  chr2          1     688002      -   1 -146     688001    242193518

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
gene FEV
gene ACKR3
gene BARD1
gene ATIC
gene ACSL3
gene CUL3
gene ERBB4
gene PAX3
gene IDH1
gene CREB1
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227176-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  16677369      +   3  1  16677368     16677368        0
1  chr1  16677370  55665202      +   3  2  38987832     55665200        1
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  227175-WG01_walk_1_MYC_containing.fa
bed file       chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr10  97277641  118623002      -   3  -25  21345361     21345361        0
1   chr10  94316803   97275116      -   4  -23   2958313     24303674        1
2   chr10  93563003   94316802      -   3  -22    753799     25057473        2
3   chr10  92735203   93563002      -   4  -21    827799     25885272        3
4   chr10  92134203   92735202      -   5  -20    600999     26486271        4
5   chr10  91813803   92134202      -   4  -19    320399     26806670        5
6   chr10  80241003   91813802      -   3  -18  11572799     38379469        6
7   chr10  71148337   80241002      -   4  -17   9092665     47472134        7
8   chr10  54679205   71148336      -   2  -16  16469131     63941265        8
9    chr8  41188799   45960802      +   7  345   4772003     68713268        9
10   chr8  45960803   64060802      +   5  346  18099999     86813267       10
11   chr8  64060803  145138636      +   6  347  81077833    167891100       11

gene TLX1
gene NFKB2
gene SUFU
gene NT5C2
gene TCF7L2
gene VTI1A
gene SHTN1
gene CYP2C8
gene CPEB3
gene CPEB3
gene NUTM2D
gene BMPR1A
gene PTEN
gene FAS
gene NUTM2B
gene KAT6B
gene PRF1
gene CCDC6
gene TET1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  227175-WG01_walk_4_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  64060803  145138636      +   6  347  81077833     81077833        0
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227175-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr1  247889403  248956422      -   2 -10   1067019      1067019        0
1  chr1  171030712  247889402      -   3  -9  76858690     77925709        1
2  chr1  157102603  171030711      -   4  -8  13928108     91853817        2
3  chr1  143393803  157102602      -   5  -7  13708799    105562616        3
4  chr1   72304203  143393802      -   4  -6  71089599    176652215        4
5  chr1   36267982   72304202      -   5  -5  36036220    212688435        5
6  chr1   17615908   36267649      -   5  -3  18651741    231340176        6
7  chr1   17351203   17615907      -   6  -2    264704    231604880        7
8  chr1          1   17351202      -   5  -1  17351201    248956081        8
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
gene FCRL4
gene FCGR2B
gene PRRX1
gene SDHC
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene MYCL
gene JUN
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene ARHGEF10L
gene MDS2
gene ARID1A
gene ARHGEF10L
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  227175-WG01_walk_4_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  17351203  17615907      +   6  2    264704       264704        0
1  chr1  17615908  36267649      +   5  3  18651741     18916445        1
2  chr1  36267982  72304202      +   5  5  36036220     54952665        2
gene ARHGEF10L
error!!!! in row index 0
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene ARHGEF10L
error!!!! in row index 6
gene MDS2
gene ARID1A
gene MYCL
gene JUN
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_4_MYCL_containing_breakpoints.pdf
running file  227175-WG01_walk_2_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  205823403  206976085      -   5 -166   1152682      1152682        0
1  chr2  198920388  205823402      -   3 -165   6903014      8055696        1
2  chr2  198267208  198920387      -   2 -164    653179      8708875        2
3  chr2  109984403  198267207      -   4 -163  88282804     96991679        3
4  chr2   92102403  109984402      -   5 -162  17881999    114873678        4
5  chr2   75001603   92102402      -   4 -161  17100799    131974477        5
6  chr2    4739767   75001602      -   5 -160  70261835    202236312        6
7  chr2     676832    4733720      -   5 -158   4056888    206293200        7
8  chr2          1     676831      -   4 -157    676830    206970030        8
gene CASP8
gene CD28
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene CTNNA2
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
running file  227175-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr12  133046203  133275309      -   4 -74    229106       229106        0
1   chr12  132811603  133046202      -   5 -73    234599       463705        1
2   chr12  129519203  132811602      -   4 -72   3292399      3756104        2
3   chr12  128800603  129519202      -   5 -71    718599      4474703        3
4   chr12  125184803  128800602      -   4 -70   3615799      8090502        4
5   chr12  124851603  125184802      -   5 -69    333199      8423701        5
6   chr12  124254203  124851602      -   4 -68    597399      9021100        6
7   chr12  123704803  124254202      -   5 -67    549399      9570499        7
8   chr12  123151603  123704802      -   7 -66    553199     10123698        8
9   chr12  121702603  123151602      -   6 -65   1448999     11572697        9
10  chr12  121466404  121702602      -   3 -64    236198     11808895       10
11  chr12  119817803  121466403      -   5 -63   1648600     13457495       11
12  chr12   70763203  119817802      -   4 -62  49054599     62512094       12
13  chr12   37924724   70763202      -   5 -61  32838478     95350572       13
14  chr12   37924385   37924723      -   6 -60       338     95350910       14
15  chr12   37168603   37924384      -   6 -59    755781     96106691       15
16  chr12   28857203   37168602      -   5 -58   8311399    104418090       16
17  chr12          1   28857202      -   2 -57  28857201    133275291       17
gene POLE
gene NCOR2
gene SETD1B
gene ZCCHC8
gene BCL7A
gene CLIP1
gene HNF1A
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  227175-WG01_walk_3_MDM2_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  123151603  123704802      -   7 -66    553199       553199        0
1  chr12  121702603  123151602      -   6 -65   1448999      2002198        1
2  chr12  121466404  121702602      -   3 -64    236198      2238396        2
3  chr12  119817803  121466403      -   5 -63   1648600      3886996        3
4  chr12   70763203  119817802      -   4 -62  49054599     52941595        4
5  chr12   37924724   70763202      -   5 -61  32838478     85780073        5
6  chr12   37924385   37924723      -   6 -60       338     85780411        6
7  chr12   37168603   37924384      -   6 -59    755781     86536192        7
8  chr12   28857203   37168602      -   5 -58   8311399     94847591        8
gene SETD1B
gene ZCCHC8
gene BCL7A
gene CLIP1
gene HNF1A
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1

gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_3_MDM2_containing_breakpoints.pdf
running file  227176-WG01_walk_2_KRAS_containing.fa
bed file      chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  16267190  133275309      +   2  42  117008119    117008119        0
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
running file  227176-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  91520168  145138636      -   3 -263  53618468     53618468        0
1  chr8  45943403   91520167      -   2 -262  45576764     99195232        1
2  chr8  43245603   45943402      -   3 -261   2697799    101893031        2
3  chr8  43080803   43245602      -   4 -260    164799    102057830        3
4  chr8  42059203   43080802      -   5 -259   1021599    103079429        4
5  chr8  41347803   42059202      -   4 -258    711399    103790828        5
6  chr8  40922203   41347802      -   3 -257    425599    104216427        6
7  chr8   7428403   40922202      -   2 -256  33493799    137710226        7
gene MYC
gene RECQL4
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
error!!!! in row index 8
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene HOOK3
gene ANK1
gene KAT6A
gene LEPROTL1
gene FGFR1
gene PCM1
gene WRN
gene NRG1
gene NSD3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  227175-WG01_walk_2_MYC_containing.fa
bed file      chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  64060803  145138636      -   6 -347  81077833     81077833        0
1   chr8  45960803   64060802      -   5 -346  18099999     99177832        1
2   chr8  41188799   45960802      -   7 -345   4772003    103949835        2
3  chr10  54679205   71148336      +   2   16  16469131    120418966        3
4  chr10  71148337   80241002      +   4   17   9092665    129511631        4
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene PRF1
gene CCDC6
gene TET1
gene NUTM2B
gene KAT6B
running file  227176-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1   16677370   55665202      +   3  2  38987832     38987832        0
1  chr1   55665203   72344203      +   2  3  16679000     55666832        1
2  chr1   72344204   82781148      +   1  4  10436944     66103776        2
3  chr1   82781149  123692202      +   2  5  40911053    107014829        3
4  chr1  123692203  155252492      +   3  6  31560289    138575118        4
5  chr1  155252493  192913381      +   2  7  37660888    176236006        5
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene SDHB
error!!!! in row index 13
gene MDS2
gene ARID1A
gene EPS15
gene JUN
gene JAK1
gene FUBP1
gene BCL10
gene RPL5
gene NRAS
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene SDHC
gene DDR2
gene ABL2
gene PBX1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  227175-WG01_walk_3_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  38237003   39138402      +   6  343    901399       901399        0
1  chr8  39138403   41188798      +   5  344   2050395      2951794        1
2  chr8  41188799   45960802      +   7  345   4772003      7723797        2
3  chr8  45960803   64060802      +   5  346  18099999     25823796        3
4  chr8  64060803  145138636      +   6  347  81077833    106901629        4
gene FGFR1
error!!!! in row index 0
gene NSD3
error!!!! in row index 1
gene IKBKB
gene ANK1
gene HOOK3
gene KAT6A
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene HEY1
gene MYC
gene RECQL4
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
running file  227175-WG01_walk_3_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  157102603  171030711      -   4 -8  13928108     13928108        0
1  chr1  143393803  157102602      -   5 -7  13708799     27636907        1
2  chr1   72304203  143393802      -   4 -6  71089599     98726506        2
3  chr1   36267982   72304202      -   5 -5  36036220    134762726        3
4  chr1   17615908   36267649      -   5 -3  18651741    153414467        4
5  chr1   17351203   17615907      -   6 -2    264704    153679171        5
6  chr1          1   17351202      -   5 -1  17351201    171030372        6
gene FCRL4
error!!!! in row index 0
gene FCGR2B
gene PRRX1
gene SDHC
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene MYCL
gene JUN
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene ARHGEF10L
gene MDS2
gene ARID1A
gene ARHGEF10L
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  227176-WG01_walk_2_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  16677369      +   3  1  16677368     16677368        0
1  chr1  16677370  55665202      +   3  2  38987832     55665200        1
2  chr1  55665203  72344203      +   2  3  16679000     72344200        2
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene CAMTA1
gene PRDM16
gene ID3
gene MYCL
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene EPS15
gene JUN
gene JAK1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  227175-WG01_walk_3_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2          1     676831      +   4  157    676830       676830        0
1  chr2     676832    4733720      +   5  158   4056888      4733718        1
2  chr2    4739767   75001602      +   5  160  70261835     74995553        2
3  chr2   75001603   92102402      +   4  161  17100799     92096352        3
4  chr2   92102403  109984402      +   5  162  17881999    109978351        4
5  chr2  109984403  198267207      +   4  163  88282804    198261155        5
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2

gene ALK
gene BIRC6
gene CTNNA2
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene CXCR4
gene HOXD11
gene HOXD13
gene NFE2L2
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
running file  227176-WG01_walk_2_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2  207865203  208349802      -   2 -155     484599       484599        0
1  chr2  207559803  207865202      -   3 -154     305399       789998        1
2  chr2   94065403  207559802      -   2 -153  113494399    114284397        2
3  chr2   86726804   94065402      -   3 -152    7338598    121622995        3
4  chr2   11432203   86726803      -   2 -151   75294600    196917595        4
5  chr2    8732403   11432202      -   3 -150    2699799    199617394        5
6  chr2    3790203    8732402      -   2 -149    4942199    204559593        6
7  chr2    3172803    3790202      -   3 -148     617399    205176992        7
8  chr2     688003    3172802      -   2 -147    2484799    207661791        8
gene IDH1
error!!!! in row index 0
gene CREB1
error!!!! in row index 1
gene CXCR4
gene HOXD11
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  227175-WG01_walk_2_MDM2_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  123704803  124254202      -   5 -67    549399       549399        0
1  chr12  123151603  123704802      -   7 -66    553199      1102598        1
2  chr12  121702603  123151602      -   6 -65   1448999      2551597        2
3  chr12  121466404  121702602      -   3 -64    236198      2787795        3
4  chr12  119817803  121466403      -   5 -63   1648600      4436395        4
5  chr12   70763203  119817802      -   4 -62  49054599     53490994        5
6  chr12   37924724   70763202      -   5 -61  32838478     86329472        6
7  chr12   37924385   37924723      -   6 -60       338     86329810        7
8  chr12   37168603   37924384      -   6 -59    755781     87085591        8
9  chr12   28857203   37168602      -   5 -58   8311399     95396990        9
gene SETD1B
gene ZCCHC8
gene BCL7A
gene CLIP1
gene HNF1A
gene TBX3
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  227175-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5      span  span_cumsum  bed_idx
0  chr1  171030712  247889402      -   3 -9  76858690     76858690        0
1  chr1  157102603  171030711      -   4 -8  13928108     90786798        1
2  chr1  143393803  157102602      -   5 -7  13708799    104495597        2
3  chr1   72304203  143393802      -   4 -6  71089599    175585196        3
4  chr1   36267982   72304202      -   5 -5  36036220    211621416        4
5  chr1   17615908   36267649      -   5 -3  18651741    230273157        5
6  chr1   17351203   17615907      -   6 -2    264704    230537861        6
7  chr1          1   17351202      -   5 -1  17351201    247889062        7
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene RGS7
gene FCRL4
gene FCGR2B
gene PRRX1
gene SDHC
gene DDR2
gene PBX1
gene S100A7
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene BCL9
gene ARNT
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene TRIM33
gene NOTCH2
gene ATP1A1
gene MYCL
gene JUN
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene JAK1
gene EPS15
gene ID3
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene ARHGEF10L
gene MDS2
gene ARID1A
gene ARHGEF10L
gene TNFRSF14
gene SKI
gene RPL22
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227175-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  227175-WG01_walk_5_MDM2_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  37924385  37924723      +   6  60       338          338        0
1  chr12  37924724  70763202      +   5  61  32838478     32838816        1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
running file  227176-WG01_walk_1_MDM2_containing.fa
bed file      chr     start        end strand  cn   5       span  span_cumsum  bed_idx
0  chr12  16267190  133275309      -   2 -42  117008119    117008119        0
1  chr12         1   16267189      -   1 -41   16267188    133275307        1
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene LRIG3
gene WIF1
gene HMGA2
gene TBX3
gene SETD1B
gene ZCCHC8
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERBB3
gene MDM2
gene PTPRB
gene BTG1
gene USP44
gene CHST11
gene ALDH2
gene SH2B3
gene PTPN11
gene HNF1A
gene BCL7A
gene CLIP1
gene NCOR2
gene POLE
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 40
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
running file  227176-WG01_walk_2_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  91520168  145138636      -   3 -263  53618468     53618468        0
1  chr8  45943403   91520167      -   2 -262  45576764     99195232        1
2  chr8  43245603   45943402      -   3 -261   2697799    101893031        2
3  chr8  43080803   43245602      -   4 -260    164799    102057830        3
4  chr8  42059203   43080802      -   5 -259   1021599    103079429        4
5  chr8  41347803   42059202      -   4 -258    711399    103790828        5
6  chr8  40922203   41347802      -   3 -257    425599    104216427        6
gene MYC
gene RECQL4
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
error!!!! in row index 8
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene HEY1
gene CHCHD7
gene PLAG1
gene NBN
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene CNBD1
gene IKBKB
gene HOOK3
gene ANK1
gene KAT6A
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_20/227176-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  227176-WG01_walk_3_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  91520168  145138636      +   3  263  53618468     53618468        0
gene MYC
gene RECQL4
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
error!!!! in row index 8
gene UBR5
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
running patient  21
running file  227178-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1

gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running file  227177-WG01_walk_1_KRAS_containing.fa
bed file      chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr12  85410260  85444898      +  23  455     34638        34638        0
1  chr12  85444899  85455046      +  60  456     10147        44785        1
2  chr12  85455047  85456378      +  18  457      1331        46116        2
3  chr12  85456379  85463699      +  22  458      7320        53436        3
4  chr12  54738593  54748506      -  14  -29      9913        63349        4
5  chr12  54700306  54738592      -   8  -28     38286       101635        5
6  chr12  37368569  54700305      -   2  -27  17331736     17433371        6
7  chr12  34905603  37368568      -   4  -26   2462965     19896336        7
8  chr12  11421740  34905602      -   2  -25  23483862     43380198        8
gene HOXC13
gene HOXC11
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ARID2
gene KMT2D
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227177-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227177-WG01_walk_1_MYCL_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr4  76473314  83512802      -   3 -690   7039488      7039488        0
1  chr4  75870231  76473313      -   6 -689    603082      7642570        1
2  chr4  62396079  75870230      -   3 -688  13474151     21116721        2
3  chr1         1  71041164      -   4   -1  71041163     92157884        3
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  227177-WG01_walk_3_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  71041164      +   4  1  71041163     71041163        0
1  chr1  71041165  71041202      +   3  2        37     71041200        1
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
running file  227178-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2          1  224576041      +   2   99  224576040    224576040        0
1  chr2  224576042  224576306      +   3  100        264    224576304        1
2  chr2  224576307  242193529      +   2  101   17617222    242193526        2
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene CUL3
gene ACKR3
gene CUL3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227178-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227177-WG01_walk_2_MYCL_containing.fa
bed file     chr     start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1         1  71041164      +   4  1  71041163     71041163        0
1  chr1  71041165  71041202      +   3  2        37     71041200        1
2  chr1  71041203  81435848      +   2  3  10394645     81435845        2
3  chr1  81435849  82156971      +   4  4    721122     82156967        3
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene CAMTA1
gene PRDM16
gene EPS15
gene FUBP1
running file  227178-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr12         1  55738169      +   2  15  55738168     55738168        0
1   chr12  55738170  55808031      +   5  16     69861     55808029        1
2   chr12  55808032  55926581      +   7  17    118549     55926578        2
3   chr12  58207071  58265432      -   7 -32     58361     55984939        3
4   chr12  58193740  58207070      -   8 -31     13330     55998269        4
5   chr12  58161336  58193739      -   7 -30     32403     56030672        5
6   chr12  58132003  58161335      -   6 -29     29332     56060004        6
7   chr12  58084525  58132002      -   9 -28     47477     56107481        7
8   chr12  58032819  58084524      -   8 -27     51705     56159186        8
9   chr12  57999027  58032818      -  10 -26     33791     56192977        9
10  chr12  57998385  57999026      -  12 -25       641     56193618       10
11  chr12  59487936  59491548      -   7 -37      3612     56197230       11
12  chr12  77083322  77130962      -   7 -76     47640     56244870       12
13  chr12  68778822  68819024      +   8  66     40202     56285072       13
14  chr12  68819025  68867802      +  10  67     48777     56333849       14
15  chr12  68867803  68868374      +   7  68       571     56334420       15
16  chr12  68868375  69080595      +   6  69    212220     56546640       16
17  chr12  69080596  69149802      +   5  70     69206     56615846       17
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227178-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  227178-WG01_walk_2_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   58084525   58132002      -   9  -28     47477        47477
1   chr12   58032819   58084524      -   8  -27     51705        99182
2   chr12   57999027   58032818      -  10  -26     33791       132973
3   chr12   57998385   57999026      -  12  -25       641       133614
4   chr12   57996416   57998384      -   7  -24      1968       135582
5    chr3  117397921  117401510      -   6 -110      3589       139171
6   chr12   77641878   77654199      -   7  -78     12321       151492
7   chr12   77130963   77641877      -   2  -77    510914       662406
8   chr12   77083322   77130962      -   7  -76     47640       710046
9   chr12   71438125   77083321      -   2  -75   5645196      6355242
10  chr12   71424339   71438124      -   3  -74     13785      6369027
11  chr12   70501645   71424338      -   2  -73    922693      7291720
12  chr12   69800708   70501644      -   3  -72    700936      7992656
13  chr12   69149803   69800707      -   4  -71    650904      8643560
14  chr12   69080596   69149802      -   5  -70     69206      8712766
15  chr12   68868375   69080595      -   6  -69    212220      8924986
16  chr12   68867803   68868374      -   7  -68       571      8925557
17  chr12   68819025   68867802      -  10  -67     48777      8974334
18  chr12   68778822   68819024      -   8  -66     40202      9014536
19  chr12   68616003   68778821      -   3  -65    162818      9177354
20  chr12   68410203   68616002      -   2  -64    205799      9383153
21  chr12   68244378   68410202      -   4  -63    165824      9548977
22  chr12   68157254   68244377      -   6  -62     87123      9636100
23  chr12   68006825   68157253      -   8  -61    150428      9786528
24  chr12   67584357   68006824      -   7  -60    422467     10208995
25  chr12   67579003   67584356      -   8  -59      5353     10214348
26  chr12   67502263   67579002      -  11  -58     76739     10291087
27  chr12   77641878   77654199      +   7   78     12321     10303408
28  chr12   77654200   77860521      +   3   79    206321     10509729
29  chr12   77860522   85444898      +   2   80   7584376     18094105
30  chr12   85444899   85455046      +   3   81     10147     18104252
31  chr12   85455047  101967384      +   2   82  16512337     34616589
32  chr12  101967385  102037447      +   3   83     70062     34686651
33  chr12  102037448  102121435      +   5   84     83987     34770638
34  chr12  102121436  102248283      +   3   85    126847     34897485
35  chr12  102248284  102249296      +   6   86      1012     34898497
36   chr3  116575005  116575711      +   8  107       706     34899203
37   chr3  116575712  116583817      +   5  108      8105     34907308
38   chr3  116583818  117397920      +   2  109    814102     35721410
39   chr3  117397921  117401510      +   6  110      3589     35724999
40   chr3  117401511  117459415      +   4  111     57904     35782903

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40

gene PTPRB
gene MDM2
gene MDM2
gene BTG1
gene USP44
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227178-WG01_walk_2_MDM2_containing_breakpoints.pdf
running file  227177-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1  11421739      +   2  24  11421738     11421738        0
1  chr12  11421740  34905602      +   2  25  23483862     34905600        1
2  chr12  34905603  37368568      +   4  26   2462965     37368565        2
gene PTPN6
gene KDM5A
error!!!! in row index 1
gene CCND2
gene CHD4
gene ZNF384
gene ERC1
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227177-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227178-WG01_walk_2_KRAS_containing.fa
bed file       chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr12         1  55738169      +   2  15  55738168     55738168        0
1   chr12  55738170  55808031      +   5  16     69861     55808029        1
2   chr12  55808032  55926581      +   7  17    118549     55926578        2
3   chr12  58207071  58265432      -   7 -32     58361     55984939        3
4   chr12  58193740  58207070      -   8 -31     13330     55998269        4
5   chr12  58161336  58193739      -   7 -30     32403     56030672        5
6   chr12  58132003  58161335      -   6 -29     29332     56060004        6
7   chr12  58084525  58132002      -   9 -28     47477     56107481        7
8   chr12  58032819  58084524      -   8 -27     51705     56159186        8
9   chr12  57999027  58032818      -  10 -26     33791     56192977        9
10  chr12  57998385  57999026      -  12 -25       641     56193618       10
11  chr12  59487936  59491548      -   7 -37      3612     56197230       11
12  chr12  77083322  77130962      -   7 -76     47640     56244870       12
13  chr12  68778822  68819024      +   8  66     40202     56285072       13
14  chr12  68819025  68867802      +  10  67     48777     56333849       14
15  chr12  68867803  68868374      +   7  68       571     56334420       15
16  chr12  68868375  69080595      +   6  69    212220     56546640       16
17  chr12  69080596  69149802      +   5  70     69206     56615846       17
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
gene MDM2
gene MDM2
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227178-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227178-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr12  58084525  58132002      -   9 -28     47477        47477        0
1   chr12  58032819  58084524      -   8 -27     51705        99182        1
2   chr12  57999027  58032818      -  10 -26     33791       132973        2
3   chr12  57998385  57999026      -  12 -25       641       133614        3
4   chr12  57996416  57998384      -   7 -24      1968       135582        4
5   chr12  57961023  57996415      -   5 -23     35392       170974        5
6   chr12  57752338  57961022      -   6 -22    208684       379658        6
7   chr12  57688218  57752337      -   7 -21     64119       443777        7
8   chr12  57688033  57688217      -   9 -20       184       443961        8
9   chr12  57687752  57688032      -   6 -19       280       444241        9
10  chr12  57688033  57688217      +   9  20       184       444425       10
11  chr12  57688218  57752337      +   7  21     64119       508544       11
12  chr12  57752338  57961022      +   6  22    208684       717228       12
13  chr12  57961023  57996415      +   5  23     35392       752620       13
14  chr12  57996416  57998384      +   7  24      1968       754588       14
15  chr12  57998385  57999026      +  12  25       641       755229       15
16  chr12  57999027  58032818      +  10  26     33791       789020       16
17  chr12  58032819  58084524      +   8  27     51705       840725       17
18  chr12  58084525  58132002      +   9  28     47477       888202       18
19  chr12  58132003  58161335      +   6  29     29332       917534       19
20  chr12  58161336  58193739      +   7  30     32403       949937       20
21  chr12  58193740  58207070      +   8  31     13330       963267       21
22  chr12  58207071  58265432      +   7  32     58361      1021628       22
23  chr12  55808032  55926581      -   7 -17    118549      1140177       23
24  chr12  55738170  55808031      -   5 -16     69861      1210038       24
25  chr12         1  55738169      -   2 -15  55738168     56948206       25
gene CDK4
error!!!! in row index 0
gene CDK4
error!!!! in row index 1
gene CDK4
error!!!! in row index 2
gene CDK4
error!!!! in row index 3
gene PTPN6
gene CDKN1B
gene HOXC13
gene HOXC11
gene KDM5A
error!!!! in row index 8
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227178-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  155  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227177-WG01_walk_1_MYC_containing.fa
bed file     chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8         1   44090202      +   2  821  44090201     44090201        0
1  chr8  44090203   48231402      +   3  822   4141199     48231400        1
2  chr8  48231403   53787802      +   2  823   5556399     53787799        2
3  chr8  53787803   54756202      +   3  824    968399     54756198        3
4  chr8  54756203   55612602      +   2  825    856399     55612597        4
5  chr8  55612603   56180602      +   3  826    567999     56180596        5
6  chr8  56180603  145138636      +   2  827  88958033    145138629        6
gene LEPROTL1
gene FGFR1
gene IKBKB
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene HOOK3
gene KAT6A
gene TCEA1
gene PLAG1
gene LYN
gene HEY1
gene MYC
gene RECQL4
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene RUNX1T1
gene UBR5
gene EXT1
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_21/227177-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  227177-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2          1    1998216      +   2  568    1998215      1998215        0
1  chr2    1998217    2130099      +   4  569     131882      2130097        1
2  chr2    2130100  223549770      +   2  570  221419670    223549767        2
3  chr2  223549771  223563765      +  22  571      13994    223563761        3
4  chr3  181313919  181377659      +  15  602      63740    223627501        4
gene PCBP1
gene CXCR4
gene HOXD11
gene FEV
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
running patient  22
running file  227179-WG01_walk_1_KRAS_containing.fa

bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  71758976  71777002      -  11 -163     18026        18026        0
1   chr12  71889556  71896288      -   6 -168      6732        24758        1
2   chr12  64122652  64148421      -   6  -96     25769        50527        2
3   chr12  64088161  64122651      -   4  -95     34490        85017        3
4   chr12  64078673  64088160      -   6  -94      9487        94504        4
..    ...       ...       ...    ...  ..  ...       ...          ...      ...
60  chr12  34966803  37924458      -   3  -38   2957655     52079881       60
61  chr12   4879437  34966802      -   2  -37  30087365     82167246       61
62  chr12   2693327   4879436      -   3  -36   2186109     84353355       62
63  chr12   2422466   2693326      -   2  -35    270860     84624215       63
64  chr12         1   2422465      -   3  -34   2422464     87046679       64

[65 rows x 9 columns]
gene LSM14A
gene WT1
gene LMO2
gene EXT2
gene MYOD1
gene FANCF
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene CCNE1
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene KMT2D
gene ARID2
gene PTPN6
gene CDKN1B
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene CCND2
gene KDM5A
error!!!! in row index 26
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_22/227179-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227179-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2  123218646  124565671      -   3 -272    1347025      1347025        0
1  chr2  123217725  123218645      -   5 -271        920      1347945        1
2  chr2  122945887  123217724      -   4 -270     271837      1619782        2
3  chr2  121971803  122945886      -   3 -269     974083      2593865        3
4  chr2          1  121971802      -   2 -268  121971801    124565666        4
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  227179-WG01_walk_1_MYC_containing.fa
bed file     chr  start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr8      1  145138636      +   2  329  145138635    145138635        0
gene HEY1
gene MYC
gene RECQL4
gene LEPROTL1
gene FGFR1
gene IKBKB
gene CHCHD7
gene PLAG1
gene NBN
gene CDH17
gene COX6C
gene PABPC1
gene EIF3E
gene RAD21
gene NDRG1
gene ARHGEF10
gene PCM1
gene WRN
gene NRG1
gene NSD3
gene ANK1
gene TCEA1
gene LYN
gene RUNX1T1
gene UBR5
gene EXT1
gene HOOK3
gene NCOA2
gene PREX2
gene CNBD1
gene RSPO2
gene CSMD3
gene FAM135B
gene KAT6A
running file  227179-WG01_walk_2_MYCN_containing.fa
bed file      chr      start        end strand  cn    5       span  span_cumsum  \
0  chr12   71758976   71777002      -  11 -163      18026        18026
1  chr12   71889556   71896288      -   6 -168       6732        24758
2  chr12   64122652   64148421      -   6  -96      25769        50527
3   chr2  123217725  123218645      -   5 -271        920        51447
4   chr2  122945887  123217724      -   4 -270     271837       323284
5   chr2  121971803  122945886      -   3 -269     974083      1297367
6   chr2          1  121971802      -   2 -268  121971801    123269168

   bed_idx
0        0
1        1
2        2
3        3
4        4
5        5
6        6
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene ALK
gene BIRC6
gene CTNNA2
gene AFF3
gene PAX8
running file  227179-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0   chr12   76987403   77028117      +   4  196     40714        40714
1   chr12   69375598   69396425      +  13  132     20827        61541
2   chr12   68719191   68719202      +  12  115        11        61552
3   chr12   68719203   68831072      +  16  116    111869       173421
4   chr12   68831073   68833966      +  19  117      2893       176314
5   chr12   68833967   68841346      +  21  118      7379       183693
6   chr12   68841347   68853638      +  20  119     12291       195984
7   chr12   57914787   57942402      +  13   68     27615       223599
8   chr12   57942403   57942866      +   9   69       463       224062
9    chr2  219447011  219702948      -   3 -285    255937       479999
10   chr2  175766209  219447010      -   2 -284  43680801     44160800
11   chr2  175025003  175766208      -   3 -283    741205     44902005
12   chr2  141030803  175025002      -   2 -282  33994199     78896204
13   chr2  140995277  141030802      -   4 -281     35525     78931729
14   chr2  137899003  140995276      -   2 -280   3096273     82028002
15   chr2  136210358  137899002      -   3 -279   1688644     83716646
16   chr2  136050784  136210357      -   2 -278    159573     83876219
17   chr2  135332329  136050783      -   4 -277    718454     84594673
18   chr2  126408359  135332328      -   3 -276   8923969     93518642
19   chr2  125490329  126408358      -   2 -275    918029     94436671
20   chr2  125290409  125490328      -   3 -274    199919     94636590
21   chr2  124565672  125290408      -   2 -273    724736     95361326
22   chr2  123218646  124565671      -   3 -272   1347025     96708351
23   chr2  123217725  123218645      -   5 -271       920     96709271
24   chr2  122945887  123217724      -   4 -270    271837     96981108
25   chr2  121971803  122945886      -   3 -269    974083     97955191

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
gene MDM2
error!!!! in row index 0
gene MDM2
error!!!! in row index 1
gene MDM2
error!!!! in row index 2
gene MDM2
error!!!! in row index 3
gene HOXD11
gene FEV
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene COL3A1
gene SF3B1
gene ITGAV
gene PMS1
gene ERBB4
gene ACVR1
gene LRP1B
gene ACVR2A
gene LRP1B
gene LRP1B
gene CXCR4
gene ERCC3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_22/227179-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  227179-WG01_walk_2_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0   chr12  71758976  71777002      -  11 -163     18026        18026        0
1   chr12  71889556  71896288      -   6 -168      6732        24758        1
2   chr12  64122652  64148421      -   6  -96     25769        50527        2
3   chr12  64088161  64122651      -   4  -95     34490        85017        3
4   chr12  64078673  64088160      -   6  -94      9487        94504        4
..    ...       ...       ...    ...  ..  ...       ...          ...      ...
60  chr12  34966803  37924458      -   3  -38   2957655     52079881       60
61  chr12   4879437  34966802      -   2  -37  30087365     82167246       61
62  chr12   2693327   4879436      -   3  -36   2186109     84353355       62
63  chr12   2422466   2693326      -   2  -35    270860     84624215       63
64  chr12         1   2422465      -   3  -34   2422464     87046679       64

[65 rows x 9 columns]
gene LSM14A
gene WT1
gene LMO2
gene EXT2
gene MYOD1
gene FANCF
gene MDM2
gene MDM2
gene MDM2
gene MDM2
gene CCNE1
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene KMT2D
gene ARID2
gene PTPN6
gene CDKN1B
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene CCND2
gene KDM5A
error!!!! in row index 26
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_22/227179-WG01_walk_2_MDM2_containing_breakpoints.pdf

running file  227179-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12         1   2422465      +   3  34   2422464      2422464        0
1  chr12   2422466   2693326      +   2  35    270860      2693324        1
2  chr12   2693327   4879436      +   3  36   2186109      4879433        2
3  chr12   4879437  34966802      +   2  37  30087365     34966798        3
4  chr12  34966803  37924458      +   3  38   2957655     37924453        4
5  chr12  37924459  37924780      -   2 -39       321     37924774        5
6  chr12  34966803  37924458      -   3 -38   2957655     40882429        6
gene KDM5A
error!!!! in row index 0
gene ERC1
gene CCND2
gene PTPN6
gene CDKN1B
gene CHD4
gene KRAS
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
running file  227179-WG01_walk_1_MYCL_containing.fa
bed file     chr  start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1      1  248956422      +   2  1  248956421    248956421        0
gene TNFRSF14
gene ID3
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene FH
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene AKT3
gene CAMTA1
gene PRDM16
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene RGS7
running patient  23
running file  227182-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand   cn    5      span  span_cumsum  \
0   chr12    2861003    2960602      +    3   16     99599        99599
1   chr12    2960603    6046602      +    2   17   3085999      3185598
2   chr12    6046603    7065002      +    3   18   1018399      4203997
3   chr12    7065003    7596202      +    2   19    531199      4735196
4   chr12    7596203    8109002      +    3   20    512799      5247995
5   chr12    8109003   51537988      +    2   21  43428985     48676980
6   chr12   51537989   51544971      +    5   22      6982     48683962
7   chr12   51544972   51565802      +   11   23     20830     48704792
8   chr12   51565803   51576380      +   91   24     10577     48715369
9   chr12   51576381   51586527      +   66   25     10146     48725515
10  chr12   51586528   51595738      +   59   26      9210     48734725
11  chr12   51595739   51660049      +   52   27     64310     48799035
12  chr12   51660050   51702002      +   61   28     41952     48840987
13  chr12   51702003   51723621      +   11   29     21618     48862605
14  chr12   51723622   51731891      +   17   30      8269     48870874
15  chr12   69319205   69332304      -  112 -230     13099     48883973
16  chr12   69319072   69319204      -  108 -229       132     48884105
17  chr12   69318195   69319071      -  116 -228       876     48884981
18  chr12   69302075   69318194      -   97 -227     16119     48901100
19  chr12  118618163  118641983      +   57  645     23820     48924920
20  chr12  118641984  118654602      +   47  646     12618     48937538

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
gene CCND2
gene PTPN6
gene CHD4
gene ZNF384
gene CDKN1B
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227182-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227181-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand   cn     5      span  span_cumsum  \
0   chr12          1   51537988      +    2    29  51537987     51537987
1   chr12   51537989   51544971      +    5    30      6982     51544969
2   chr12   51544972   51565802      +   11    31     20830     51565799
3   chr12   51565803   51576380      +   61    32     10577     51576376
4   chr12   51576381   51586527      +   56    33     10146     51586522
5   chr12  104270732  104303427      +   16   678     32695     51619217
6   chr12  104303428  104303915      +   12   679       487     51619704
7   chr12  104303916  104311967      +   14   680      8051     51627755
8   chr12   84325355   84325442      +  124   409        87     51627842
9   chr12   84325443   84326576      +  105   410      1133     51628975
10  chr12   84326577   84327304      +  101   411       727     51629702
11   chr8  110174455  110174637      -    7 -1288       182     51629884
12   chr8  110171341  110174454      -    3 -1287      3113     51632997
13   chr8  110097211  110171340      -    5 -1286     74129     51707126
14   chr8  110247203  110255227      -   14 -1291      8024     51715150
15   chr8  110209803  110247202      -   10 -1290     37399     51752549

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 2
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227182-WG01_walk_2_KRAS_containing.fa
bed file       chr      start        end strand   cn    5      span  span_cumsum  \
0   chr12    6046603    7065002      +    3   18   1018399      1018399
1   chr12    7065003    7596202      +    2   19    531199      1549598
2   chr12    7596203    8109002      +    3   20    512799      2062397
3   chr12    8109003   51537988      +    2   21  43428985     45491382
4   chr12   51537989   51544971      +    5   22      6982     45498364
5   chr12   51544972   51565802      +   11   23     20830     45519194
6   chr12   51565803   51576380      +   91   24     10577     45529771
7   chr12   51576381   51586527      +   66   25     10146     45539917
8   chr12   51586528   51595738      +   59   26      9210     45549127
9   chr12   51595739   51660049      +   52   27     64310     45613437
10  chr12   51660050   51702002      +   61   28     41952     45655389
11  chr12   51702003   51723621      +   11   29     21618     45677007
12  chr12   51723622   51731891      +   17   30      8269     45685276
13  chr12   51731892   51733010      +   16   31      1118     45686394
14  chr12   51733011   51797880      +   18   32     64869     45751263
15  chr12   51797881   51905856      +   17   33    107975     45859238
16  chr12   51905857   51923710      +   11   34     17853     45877091
17  chr12   51923711   51957946      +   15   35     34235     45911326
18  chr12   51957947   51963584      +   21   36      5637     45916963
19  chr12   61362810   61419559      +   13  142     56749     45973712
20  chr12   61419560   61446581      +   40  143     27021     46000733
21  chr12   61446582   61460653      +   54  144     14071     46014804
22  chr12   61460654   61478526      +   65  145     17872     46032676
23  chr12   61478527   61493428      +   38  146     14901     46047577
24  chr12   61493429   61497254      +   41  147      3825     46051402
25  chr12   61497255   61498402      +   54  148      1147     46052549
26  chr12   61498403   61499346      +   62  149       943     46053492
27  chr12   61499347   61518240      +   66  150     18893     46072385
28  chr12   61518241   61543302      +   61  151     25061     46097446
29  chr12   61543303   61545899      +   60  152      2596     46100042
30  chr12   61545900   61564063      +   58  153     18163     46118205
31  chr12   61564064   61569960      +   54  154      5896     46124101
32  chr12   61569961   61577772      +   50  155      7811     46131912
33  chr12   61577773   61582500      +   38  156      4727     46136639
34  chr12   57848848   57850374      -   55  -81      1526     46138165
35  chr12   57806106   57848847      -   53  -80     42741     46180906
36  chr12   57753770   57806105      -   60  -79     52335     46233241
37  chr12   57753336   57753769      -   65  -78       433     46233674
38  chr12   57748996   57753335      -   54  -77      4339     46238013
39  chr12   57733158   57748995      -   57  -76     15837     46253850
40  chr12   57730289   57733157      -   55  -75      2868     46256718
41  chr12   57702530   57730288      -   85  -74     27758     46284476
42  chr12   57702403   57702529      -   92  -73       126     46284602
43  chr12   57693594   57702402      -  134  -72      8808     46293410
44  chr12   57692392   57693593      -  119  -71      1201     46294611
45  chr12  106281602  106292698      +   60  589     11096     46305707
46  chr12   57690431   57692391      +   61   70      1960     46307667
47  chr12   57692392   57693593      +  119   71      1201     46308868
48  chr12   57693594   57702402      +  134   72      8808     46317676

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
25       25
26       26
27       27
28       28
29       29
30       30
31       31
32       32
33       33
34       34
35       35
36       36
37       37
38       38
39       39
40       40
41       41
42       42
43       43
44       44
45       45
46       46
47       47
48       48

gene PTPN6
gene CHD4
gene ZNF384
gene CDKN1B
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ACVR1B
gene ACVR1B
gene CDK4
gene CDK4
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227182-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227182-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  236515803  248956422      -   1 -7   12440619     12440619        0
1  chr1  236128203  236515802      -   2 -6     387599     12828218        1
2  chr1  234915203  236128202      -   3 -5    1212999     14041217        2
3  chr1  109231003  234915202      -   2 -4  125684199    139725416        3
4  chr1  108867003  109231002      -   3 -3     363999    140089415        4
5  chr1   54965803  108867002      -   2 -2   53901199    193990614        5
6  chr1          1   54965802      -   3 -1   54965801    248956415        6
gene FH
gene AKT3
gene RGS7
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  227182-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  236128203  236515802      -   2 -6     387599       387599        0
1  chr1  234915203  236128202      -   3 -5    1212999      1600598        1
2  chr1  109231003  234915202      -   2 -4  125684199    127284797        2
3  chr1  108867003  109231002      -   3 -3     363999    127648796        3
4  chr1   54965803  108867002      -   2 -2   53901199    181549995        4
5  chr1          1   54965802      -   3 -1   54965801    236515796        5
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene JUN
gene BCL10
gene RPL5
gene FUBP1
gene JAK1
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  227182-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2          1   23861802      +   2  712  23861801     23861801        0
1   chr2   23861803   24469802      +   3  713    607999     24469800        1
2   chr2   24469803   24888402      +   2  714    418599     24888399        2
3   chr2   24888403   26445402      +   3  715   1556999     26445398        3
4   chr2   26445403   26743802      +   2  716    298399     26743797        4
5   chr2   26743803   27836802      +   3  717   1092999     27836796        5
6   chr2   27836803   28706802      +   2  718    869999     28706795        6
7   chr2   28706803   28887002      +   3  719    180199     28886994        7
8   chr2   28887003   31918402      +   2  720   3031399     31918393        8
9   chr2   31918403   32734002      +   3  721    815599     32733992        9
10  chr2   32734003   90157402      +   2  722  57423399     90157391       10
11  chr2   90157403   97545602      +   3  723   7388199     97545590       11
12  chr2   97545603  113607957      +   2  724  16062354    113607944       12
13  chr2  113607958  116657529      +   3  725   3049571    116657515       13
gene MYCN
gene WDCP
gene NCOA1
gene ASXL2
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227182-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227182-WG01_walk_3_MYCL_containing.fa
bed file     chr  start       end strand  cn  5      span  span_cumsum  bed_idx
0  chr1      1  54965802      -   3 -1  54965801     54965801        0
gene TNFRSF14
gene ID3
gene MYCL
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene EPS15
running file  227180-WG01_walk_2_MYCN_containing.fa
bed file     chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  92879603  97545602      -   3 -879   4665999      4665999        0
1  chr2  32870557  92879602      -   2 -878  60009045     64675044        1
2  chr2   9702203  32866671      -   2 -876  23164468     87839512        2
3  chr2   9357003   9702202      -   3 -875    345199     88184711        3
4  chr2         1   9357002      -   2 -874   9357001     97541712        4
gene TMEM127
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227180-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  227180-WG01_walk_1_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  236128803  248956422      -   1 -7   12827619     12827619        0
1  chr1  235073003  236128802      -   3 -6    1055799     13883418        1
2  chr1  229685090  235073002      -   2 -5    5387912     19271330        2
3  chr1   25405618  229676790      -   2 -3  204271172    223542502        3
4  chr1   25287188   25405617      -   3 -2     118429    223660931        4
5  chr1          1   25287187      -   2 -1   25287186    248948117        5
gene FH
gene AKT3
gene RGS7
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  227181-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn     5      span  span_cumsum  \
0   chr8  141808503  145138636      -   2 -1302   3330133      3330133
1   chr8  111885925  141808502      -   1 -1301  29922577     33252710
2   chr8  111876706  111885924      -  18 -1300      9218     33261928
3  chr12  117307122  117312191      -  54  -773      5069     33266997
4  chr12  117303499  117307121      -  38  -772      3622     33270619
5  chr12  117293582  117303498      -  12  -771      9916     33280535
6  chr12   55830285   55832693      -   7   -79      2408     33282943
7  chr12   55752203   55830284      -   3   -78     78081     33361024

   bed_idx
0        0
1        1
2        2
3        3
4        4
5        5
6        6
7        7

gene RECQL4
gene MYC
gene RAD21
gene NDRG1
gene EXT1
gene CSMD3
gene FAM135B
running file  227180-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr2  124901803  125680716      +   3  900    778913       778913        0
1  chr2  113711541  114288461      -   3 -882    576920      1355833        1
2  chr2  113669493  113711540      -   4 -881     42047      1397880        2
3  chr2   97545603  113669492      -   2 -880  16123889     17521769        3
4  chr2   92879603   97545602      -   3 -879   4665999     22187768        4
5  chr2   32870557   92879602      -   2 -878  60009045     82196813        5
6  chr2    9702203   32866671      -   2 -876  23164468    105361281        6
7  chr2    9357003    9702202      -   3 -875    345199    105706480        7
8  chr2          1    9357002      -   2 -874   9357001    115063481        8
gene RANBP2
gene RGPD3
gene AFF3
gene PAX8
gene TMEM127
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene CTNNA2
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227180-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227180-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand   cn    5      span  span_cumsum  bed_idx
0   chr12  65939624  65949002      -   98 -193      9378         9378        0
1   chr12  65936348  65939623      -   92 -192      3275        12653        1
2   chr12  65926826  65936347      -   81 -191      9521        22174        2
3   chr12  65916027  65926825      -   87 -190     10798        32972        3
4   chr12  65910827  65916026      -   83 -189      5199        38171        4
5   chr12  65909950  65910826      -   74 -188       876        39047        5
6   chr12  66049102  66050847      +   21  204      1745        40792        6
7   chr12  66050848  66063828      +   16  205     12980        53772        7
8   chr12  61286476  61297393      -  156 -142     10917        64689        8
9   chr12  51565403  51576380      -   75  -21     10977        75666        9
10  chr12  51544972  51565402      -   11  -20     20430        96096       10
11  chr12  51537989  51544971      -    5  -19      6982       103078       11
12  chr12         1  51537988      -    2  -18  51537987     51641065       12
gene HMGA2
error!!!! in row index 0
gene HMGA2
error!!!! in row index 1
gene PTPN6
gene CDKN1B
gene KDM5A
error!!!! in row index 4
gene CCND2
gene CHD4
gene KRAS
gene COL2A1
gene PRPF40B
gene SMARCD1
gene ATF1
gene ZNF384
gene ETV6
gene ETNK1
gene PPFIBP1
gene ARID2
gene KMT2D
gene ERC1
running file  227180-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1  235073003  236128802      -   3 -6    1055799      1055799        0
1  chr1  229685090  235073002      -   2 -5    5387912      6443711        1
2  chr1  229676791  229685089      -   1 -4       8298      6452009        2
3  chr1   25405618  229676790      -   2 -3  204271172    210723181        3
4  chr1   25287188   25405617      -   3 -2     118429    210841610        4
5  chr1          1   25287187      -   2 -1   25287186    236128796        5
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene S100A7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene ARID1A
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene EPS15
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene CAMTA1
gene PRDM16
running file  227180-WG01_walk_1_MYC_containing.fa
bed file       chr      start        end strand  cn     5      span  span_cumsum  \
0    chr8  141808503  145138636      -   2 -1379   3330133      3330133
1    chr8  111885925  141808502      -   1 -1378  29922577     33252710
2    chr8  111876706  111885924      -  19 -1377      9218     33261928
3   chr12  117303500  117312191      -  40  -761      8691     33270619
4   chr12  104539467  104599147      -  68  -678     59680     33330299
5   chr12   55379828   55389276      -  25   -60      9448     33339747
6   chr12   91587448   91594737      +  25   548      7289     33347036
7   chr12   69119225   69125447      -  79  -238      6222     33353258
8   chr12   90927583   90932553      +  27   521      4970     33358228
9   chr12   90932554   90939735      +  28   522      7181     33365409
10  chr12   84962640   84984725      +  33   433     22085     33387494
11  chr12   84984726   84994987      +  34   434     10261     33397755
12  chr12   84994988   85170010      +  15   435    175022     33572777
13  chr12   84688203   84696867      -  36  -419      8664     33581441

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
gene RECQL4
gene MYC
gene RAD21
gene NDRG1
gene EXT1
gene CSMD3
gene FAM135B
gene CHST11
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227180-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  227181-WG01_walk_2_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  113440603  116644915      -   3 -884   3204312      3204312        0
1   chr2   32870557  113440602      -   2 -883  80570045     83774357        1
2   chr2   32736603   32866671      -   2 -881    130068     83904425        2
3   chr2   31944403   32736602      -   3 -880    792199     84696624        3
4   chr2   28960803   31944402      -   2 -879   2983599     87680223        4
5   chr2   28670003   28960802      -   3 -878    290799     87971022        5
6   chr2   27576203   28670002      -   2 -877   1093799     89064821        6
7   chr2   27257403   27576202      -   3 -876    318799     89383620        7
8   chr2   26437403   27257402      -   2 -875    819999     90203619        8
9   chr2   23815603   26437402      -   3 -874   2621799     92825418        9
10  chr2     630603   23815602      -   2 -873  23184999    116010417       10
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene CTNNA2
gene AFF3
gene PAX8
gene BIRC6
gene ALK
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene MYCN
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227181-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  227181-WG01_walk_1_MYCL_containing.fa
bed file       chr      start        end strand  cn   5       span  span_cumsum  \
0   chr11   57459803   57935602      +   3  16     475799       475799
1   chr11   57935603   60965602      +   2  17    3029999      3505798
2   chr11   60965603   68993402      +   3  18    8027799     11533597
3   chr11   68993403   70142602      +   2  19    1149199     12682796
4   chr11   70142603   70404202      +   3  20     261599     12944395
5   chr11   70404203   71904002      +   2  21    1499799     14444194
6   chr11   71904003   73165802      +   3  22    1261799     15705993
7   chr11   73165803   73431402      +   2  23     265599     15971592
8   chr11   73431403   74634602      +   3  24    1203199     17174791
9   chr11   74634603   77503802      +   2  25    2869199     20043990
10  chr11   77503803   78175402      +   3  26     671599     20715589
11  chr11   78175403   89877894      +   2  27   11702491     32418080
12   chr1  234935803  236128782      -   3  -5    1192979     33611059
13   chr1  113071156  234935802      -   2  -4  121864646    155475705
14   chr1   33088901  113068717      -   2  -2   79979816    235455521
15   chr1          1   33088900      -   3  -1   33088899    268544420

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15

gene CLP1
error!!!! in row index 0
gene CTNND1
error!!!! in row index 1
gene FEN1
gene MEN1
gene SDHAF2
gene MALAT1
gene CCND1
gene FADD
gene NUMA1
gene EED
gene PICALM
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227181-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  227181-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2          1     630602      +   1  872    630601       630601        0
1   chr2     630603   23815602      +   2  873  23184999     23815600        1
2   chr2   23815603   26437402      +   3  874   2621799     26437399        2
3   chr2   26437403   27257402      +   2  875    819999     27257398        3
4   chr2   27257403   27576202      +   3  876    318799     27576197        4
5   chr2   27576203   28670002      +   2  877   1093799     28669996        5
6   chr2   28670003   28960802      +   3  878    290799     28960795        6
7   chr2   28960803   31944402      +   2  879   2983599     31944394        7
8   chr2   31944403   32736602      +   3  880    792199     32736593        8
9   chr2   32736603   32866671      +   2  881    130068     32866661        9
10  chr2   32870557  113440602      +   2  883  80570045    113436706       10
11  chr2  113440603  116644915      +   3  884   3204312    116641018       11
12  chr2  124927952  127484293      -   3 -899   2556341    119197359       12
gene MYCN
gene WDCP
gene ASXL2
gene NCOA1
gene DNMT3A
gene ALK
gene BIRC6
gene PCBP1
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene TMEM127
gene RANBP2
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene RGPD3
gene CTNNA2
gene AFF3
gene PAX8
gene ERCC3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_23/227181-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227181-WG01_walk_2_MYCL_containing.fa
bed file     chr      start        end strand  cn  5       span  span_cumsum  bed_idx
0  chr1          1   33088900      +   3  1   33088899     33088899        0
1  chr1   33088901  113068717      +   2  2   79979816    113068715        1
2  chr1  113071156  234935802      +   2  4  121864646    234933361        2
3  chr1  234935803  236128782      +   3  5    1192979    236126340        3
4  chr1  236128783  236504802      +   2  6     376019    236502359        4
5  chr1  236504803  248956422      +   1  7   12451619    248953978        5
gene TNFRSF14
gene ID3
gene SKI
gene RPL22
gene CASP9
gene PAX7
gene LCK
gene MTOR
gene PRDM2
gene SPEN
gene ARHGEF10L
gene SDHB
gene MDS2
gene ARID1A
gene CAMTA1
gene PRDM16
gene MYCL
gene JUN
gene BCL10
gene RPL5
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene FUBP1
gene RBM15
gene JAK1
gene EPS15
gene NRAS
gene S100A7
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene FCGR2B
gene PRRX1
gene TPR
gene ELF3
gene BTG2
gene MDM4
gene ELK4
gene SLC45A3
gene H3F3A
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene SDHC
gene DDR2
gene ABL2
gene CDC73
gene PTPRC
gene ATP1A1
gene PDE4DIP
gene MUC1
gene PBX1
gene FH
gene AKT3
gene RGS7
running patient  24
running file  227183-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  131268203  145138636      -   5 -295  13870433     13870433        0
1   chr8  105074059  131268202      -   4 -294  26194143     40064576        1
2   chr8  105065425  105074058      -   9 -293      8633     40073209        2
3   chr7   33614003   34097116      -   8 -250    483113     40556322        3
4   chr7   33104245   33614002      -   9 -249    509757     41066079        4
5   chr7   33087403   33104244      -  10 -248     16841     41082920        5
6   chr7   32841803   33087402      -  12 -247    245599     41328519        6
7   chr7   31681003   32841802      -  10 -246   1160799     42489318        7
8   chr7   31212279   31681002      -  13 -245    468723     42958041        8
9   chr7   31131003   31212278      -  12 -244     81275     43039316        9
10  chr7   30804203   31131002      -  11 -243    326799     43366115       10
11  chr7   30703803   30804202      -  13 -242    100399     43466514       11
12  chr7   30293003   30703802      -  16 -241    410799     43877313       12
13  chr7   30082403   30293002      -  17 -240    210599     44087912       13
14  chr7   29956403   30082402      -  19 -239    125999     44213911       14
15  chr7   29204929   29956402      -  17 -238    751473     44965384       15
16  chr7   28393603   29204928      -  15 -237    811325     45776709       16
17  chr7   28214803   28393602      -  19 -236    178799     45955508       17
18  chr7   28111003   28214802      -  17 -235    103799     46059307       18
19  chr7   27887803   28111002      -  13 -234    223199     46282506       19
20  chr7   26461403   27887802      -  12 -233   1426399     47708905       20
21  chr7   26106003   26461402      -  14 -232    355399     48064304       21
22  chr7   25973403   26106002      -  12 -231    132599     48196903       22
23  chr7   25807003   25973402      -  10 -230    166399     48363302       23
24  chr7   25255603   25807002      -  12 -229    551399     48914701       24
25  chr7   25048003   25255602      -  15 -228    207599     49122300       25
gene RECQL4
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene FKBP9
gene JAZF1
gene JAZF1
gene HOXA11
gene HOXA13
gene HOXA9
gene JAZF1
gene HNRNPA2B1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  227184-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  38040003  39846602      -   3 -58   1806599      1806599        0
1  chr12  37183803  38040002      -   4 -57    856199      2662798        1
2  chr12   8110803  37183802      -   3 -56  29072999     31735797        2
3  chr12   7631403   8110802      -   4 -55    479399     32215196        3
4  chr12   7106603   7631402      -   3 -54    524799     32739995        4
5  chr12   6137803   7106602      -   4 -53    968799     33708794        5
6  chr12   5844803   6137802      -   3 -52    292999     34001793        6
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CHD4
gene ZNF384
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227183-WG01_walk_3_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  58023603  58107802      -   3 -39     84199        84199        0
1  chr12  48315203  58023602      -   4 -38   9708399      9792598        1
2  chr12  12958603  48315202      -   3 -37  35356599     45149197        2
3  chr12  11907403  12958602      -   4 -36   1051199     46200396        3
4  chr12         1  11907402      -   3 -35  11907401     58107797        4
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
gene PTPN6
gene KDM5A
error!!!! in row index 21
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_3_KRAS_containing_breakpoints.pdf

running file  227183-WG01_walk_1_MDM2_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr3   39053203   50298002      -   4 -160  11244799     11244799
1    chr3   34490360   39053202      -   2 -159   4562842     15807641
2    chr3   20779952   34490359      -   3 -158  13710407     29518048
3    chr3   17641054   20779951      -   2 -157   3138897     32656945
4    chr3   16479415   17641053      -   4 -156   1161638     33818583
5   chr12  109754003  110070542      -   3  -54    316539     34135122
6   chr12  109466603  109754002      -   4  -53    287399     34422521
7   chr12  109248603  109466602      -   2  -52    217999     34640520
8   chr12  108699203  109248602      -   3  -51    549399     35189919
9   chr12  108098603  108699202      -   2  -50    600599     35790518
10  chr12  107830403  108098602      -   3  -49    268199     36058717
11  chr12  103569003  107830402      -   2  -48   4261399     40320116
12  chr12  102158203  103569002      -   1  -47   1410799     41730915
13  chr12   99723403  102158202      -   2  -46   2434799     44165714
14  chr12   99401003   99723402      -   1  -45    322399     44488113
15  chr12   85726710   99401002      -   2  -44  13674292     58162405
16  chr12   81928603   85726709      -   1  -43   3798106     61960511
17  chr12   62707003   81928602      -   2  -42  19221599     81182110
18  chr12   61117603   62707002      -   3  -41   1589399     82771509
19  chr12   58107803   61117602      -   2  -40   3009799     85781308
20  chr12   58023603   58107802      -   3  -39     84199     85865507
21  chr12   48315203   58023602      -   4  -38   9708399     95573906
22  chr12   12958603   48315202      -   3  -37  35356599    130930505
23  chr12   11907403   12958602      -   4  -36   1051199    131981704
24  chr12          1   11907402      -   3  -35  11907401    143889105

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
gene CTNNB1
gene NCKIPSD
gene RHOA
gene SETD2
gene MLH1
gene MYD88
gene CCR4
gene TGFBR2
gene CHST11
gene BTG1
gene USP44
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
gene PTPN6
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  227184-WG01_walk_1_MDM2_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr8  21442374  22807602      -   5 -411   1365228      1365228        0
1    chr8  21441651  21442373      -   6 -410       722      1365950        1
2   chr12  85327447  85327998      -   3  -71       551      1366501        2
3   chr12  71210694  85327446      -   2  -70  14116752     15483253        3
4   chr12  62690403  71208581      -   2  -68   8518178     24001431        4
5   chr12  61117803  62690402      -   3  -67   1572599     25574030        5
6   chr12  59878400  61117802      -   2  -66   1239402     26813432        6
7   chr12  59878025  59878399      -   4  -65       374     26813806        7
8   chr12  59877933  59878024      -   3  -64        91     26813897        8
9   chr12  58162203  59877932      -   2  -63   1715729     28529626        9
10  chr12  58023603  58162202      -   3  -62    138599     28668225       10
11  chr12  48351003  58023602      -   4  -61   9672599     38340824       11
12  chr12  41601203  48351002      -   3  -60   6749799     45090623       12
13  chr12  39846603  41601202      -   2  -59   1754599     46845222       13
14  chr12  38040003  39846602      -   3  -58   1806599     48651821       14
15  chr12  37183803  38040002      -   4  -57    856199     49508020       15
16  chr12   8110803  37183802      -   3  -56  29072999     78581019       16
17  chr12   7631403   8110802      -   4  -55    479399     79060418       17
18  chr12   7106603   7631402      -   3  -54    524799     79585217       18
19  chr12   6137803   7106602      -   4  -53    968799     80554016       19
20  chr12   5844803   6137802      -   3  -52    292999     80847015       20
21  chr12   4748803   5844802      -   2  -51   1095999     81943014       21
22  chr12   1158203   4748802      -   3  -50   3590599     85533613       22
23  chr12    595803   1158202      -   4  -49    562399     86096012       23
24  chr12    245803    595802      -   3  -48    349999     86446011       24
25  chr12         1    245802      -   2  -47    245801     86691812       25
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene COL2A1
gene ARID2
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CHD4
gene ZNF384
gene CCND2
gene ERC1
gene ERC1
gene KDM5A
error!!!! in row index 32
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_1_MDM2_containing_breakpoints.pdf
running file  227183-WG01_walk_4_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr17   7630309  15848059      +   2  99   8217750      8217750        0
1   chr1   1625793  10422445      +   5   2   8796652     17014402        1
2   chr1  10422446  13155202      +   6   3   2732756     19747158        2
3   chr1  13155203  17351158      +   7   4   4195955     23943113        3
4   chr1  17351159  67596602      +   5   5  50245443     74188556        4
gene TP53
error!!!! in row index 0
gene PER1
error!!!! in row index 1
gene GAS7
gene MAP2K4
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_4_MYCL_containing_breakpoints.pdf
running file  227183-WG01_walk_3_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  201580003  203034202      +   5  18   1454199      1454199        0
1   chr1  203034203  203097625      +   4  19     63422      1517621        1
2   chr1  161189008  161539861      -   5  -9    350853      1868474        2
3   chr1  109698803  161189007      -   4  -8  51490204     53358678        3
4   chr1  108426003  109698802      -   5  -7   1272799     54631477        4
5   chr1   67596603  108426002      -   4  -6  40829399     95460876        5
6   chr1   17351159   67596602      -   5  -5  50245443    145706319        6
7   chr1   13155203   17351158      -   7  -4   4195955    149902274        7
8   chr1   10422446   13155202      -   6  -3   2732756    152635030        8
9   chr1    1625793   10422445      -   5  -2   8796652    161431682        9
10  chr1          1    1625792      -   3  -1   1625791    163057473       10
gene ELF3
error!!!! in row index 0
gene SDHC
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene ATP1A1
gene PDE4DIP
gene MUC1
gene BCL10
gene RPL5
gene FUBP1
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L

gene MDS2
gene ARID1A
gene JAK1
gene EPS15
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
gene MTOR
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  227184-WG01_walk_2_MYCN_containing.fa
bed file      chr     start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2  99488570  146952476      -   2 -167  47463906     47463906        0
1   chr2  94159603   99487251      -   3 -165   5327648     52791554        1
2   chr2  92224803   94159602      -   6 -164   1934799     54726353        2
3   chr2  65648403   92224802      -   2 -163  26576399     81302752        3
4   chr2  64844603   65648402      -   3 -162    803799     82106551        4
5   chr2  62430403   64844602      -   2 -161   2414199     84520750        5
6   chr2  60673403   62430402      -   3 -160   1756999     86277749        6
7   chr2  47986403   60673402      -   2 -159  12686999     98964748        7
8   chr2  47092142   47986402      -   3 -158    894260     99859008        8
9   chr2    670112   47092141      -   2 -157  46422029    146281037        9
10  chr2         1     670111      -   1 -156    670110    146951147       10
gene CXCR4
gene RANBP2
gene RGPD3
gene ERCC3
gene AFF3
error!!!! in row index 4
gene PAX8
gene LRP1B
gene TMEM127
gene PCBP1
gene DCTN1
gene CTNNA2
gene REL
gene XPO1
gene BCL11A
gene MSH6
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_2_MYCN_containing_breakpoints.pdf
running file  227183-WG01_walk_2_KRAS_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0  chr12  61117603  62707002      -   3 -41   1589399      1589399        0
1  chr12  58107803  61117602      -   2 -40   3009799      4599198        1
2  chr12  58023603  58107802      -   3 -39     84199      4683397        2
3  chr12  48315203  58023602      -   4 -38   9708399     14391796        3
4  chr12  12958603  48315202      -   3 -37  35356599     49748395        4
5  chr12  11907403  12958602      -   4 -36   1051199     50799594        5
6  chr12         1  11907402      -   3 -35  11907401     62706995        6
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
gene PTPN6
gene KDM5A
error!!!! in row index 22
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_2_KRAS_containing_breakpoints.pdf
running file  227183-WG01_walk_3_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr8  131268203  145138636      -   5 -295  13870433     13870433        0
1  chr8  105074059  131268202      -   4 -294  26194143     40064576        1
2  chr8  105065425  105074058      -   9 -293      8633     40073209        2
3  chr7   33614003   34097116      -   8 -250    483113     40556322        3
4  chr7   33104245   33614002      -   9 -249    509757     41066079        4
5  chr7   33087403   33104244      -  10 -248     16841     41082920        5
6  chr7   32841803   33087402      -  12 -247    245599     41328519        6
gene RECQL4
gene NDRG1
gene FAM135B
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene FKBP9
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  227184-WG01_walk_1_MYCN_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr2   99487252   99488569      -   1 -166      1317         1317        0
1   chr2   94159603   99487251      -   3 -165   5327648      5328965        1
2   chr2   92224803   94159602      -   6 -164   1934799      7263764        2
3   chr2   65648403   92224802      -   2 -163  26576399     33840163        3
4   chr2   64844603   65648402      -   3 -162    803799     34643962        4
5   chr2   62430403   64844602      -   2 -161   2414199     37058161        5
6   chr2   60673403   62430402      -   3 -160   1756999     38815160        6
7   chr2   47986403   60673402      -   2 -159  12686999     51502159        7
8   chr2   47092142   47986402      -   3 -158    894260     52396419        8
9   chr2     670112   47092141      -   2 -157  46422029     98818448        9
10  chr1   62589006   62589293      +   4   18       287     98818735       10
11  chr1   62589294  149210602      +   3   19  86621308    185440043       11
12  chr1  149210603  152302069      +   4   20   3091466    188531509       12
gene TMEM127
gene PCBP1
gene DCTN1
gene CTNNA2
gene REL
gene XPO1
gene BCL11A
gene MSH6
gene FBXO11
gene MSH2
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene ALK
gene BIRC6
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ATP1A1
gene PDE4DIP
gene SETDB1
gene MLLT11
gene ARNT
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_1_MYCN_containing_breakpoints.pdf
running file  227184-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1    3640877   10422445      +   5   2   6781568      6781568        0
1   chr1   10422446   10423722      +   4   3      1276      6782844        1
2   chr1   10423723   17351158      +   5   4   6927435     13710279        2
3   chr1   17351159   26085802      +   4   5   8734643     22444922        3
4   chr1   26085803   27676802      +   5   6   1590999     24035921        4
5   chr1   27676803   29173202      +   6   7   1496399     25532320        5
6   chr1   29173203   29312002      +   5   8    138799     25671119        6
7   chr1   29312003   30655902      +   4   9   1343899     27015018        7
8   chr1   30655903   31358602      +   5  10    702699     27717717        8
9   chr1   31358603   31802002      +   4  11    443399     28161116        9
10  chr1   31802003   32850802      +   5  12   1048799     29209915       10
11  chr1   32850803   33215802      +   4  13    364999     29574914       11
12  chr1   33215803   34570002      +   3  14   1354199     30929113       12
13  chr1   34570003   47324115      +   4  15  12754112     43683225       13
14  chr1   47324116   54753402      +   4  16   7429286     51112511       14
15  chr1   54753403   62589005      +   3  17   7835602     58948113       15
16  chr1   62589006   62589293      +   4  18       287     58948400       16
17  chr1   62589294  149210602      +   3  19  86621308    145569708       17
18  chr1  149210603  152302069      +   4  20   3091466    148661174       18
19  chr1  152302070  152506248      +   2  21    204178    148865352       19
20  chr1  152506249  154644466      +   4  22   2138217    151003569       20
21  chr1  154644467  154644652      +   5  23       185    151003754       21
22  chr1  154644653  157833202      +   4  24   3188549    154192303       22
23  chr1  157833203  160989802      +   2  25   3156599    157348902       23
24  chr1  160989803  161187491      +   4  26    197688    157546590       24
25  chr1  161187492  161319237      +   3  27    131745    157678335       25
26  chr1  161319238  161539861      +   5  28    220623    157898958       26
27  chr1  161539862  187752003      +   4  29  26212141    184111099       27
28  chr1  187752004  201579602      +   3  30  13827598    197938697       28
29  chr1  201579603  202469402      +   5  31    889799    198828496       29
gene RPL22
gene CAMTA1
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene ID3
gene PAX7
gene ARHGEF10L

gene MDS2
gene ARID1A
gene LCK
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ATP1A1
gene PDE4DIP
gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene MUC1
gene SDHC
gene SDHC
gene FCGR2B
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
gene CDC73
gene PTPRC
gene ELF3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  227183-WG01_walk_2_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2  110080204  242193529      -   2 -133  132113325    132113325        0
1  chr2   90168003  110080203      -   3 -132   19912200    152025525        1
2  chr2     667003   90168002      -   2 -131   89500999    241526524        2
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  227183-WG01_walk_1_KRAS_containing.fa
bed file       chr      start        end strand  cn    5      span  span_cumsum  \
0    chr3   39053203   50298002      -   4 -160  11244799     11244799
1    chr3   34490360   39053202      -   2 -159   4562842     15807641
2    chr3   20779952   34490359      -   3 -158  13710407     29518048
3    chr3   17641054   20779951      -   2 -157   3138897     32656945
4    chr3   16479415   17641053      -   4 -156   1161638     33818583
5   chr12  109754003  110070542      -   3  -54    316539     34135122
6   chr12  109466603  109754002      -   4  -53    287399     34422521
7   chr12  109248603  109466602      -   2  -52    217999     34640520
8   chr12  108699203  109248602      -   3  -51    549399     35189919
9   chr12  108098603  108699202      -   2  -50    600599     35790518
10  chr12  107830403  108098602      -   3  -49    268199     36058717
11  chr12  103569003  107830402      -   2  -48   4261399     40320116
12  chr12  102158203  103569002      -   1  -47   1410799     41730915
13  chr12   99723403  102158202      -   2  -46   2434799     44165714
14  chr12   99401003   99723402      -   1  -45    322399     44488113
15  chr12   85726710   99401002      -   2  -44  13674292     58162405
16  chr12   81928603   85726709      -   1  -43   3798106     61960511
17  chr12   62707003   81928602      -   2  -42  19221599     81182110
18  chr12   61117603   62707002      -   3  -41   1589399     82771509
19  chr12   58107803   61117602      -   2  -40   3009799     85781308
20  chr12   58023603   58107802      -   3  -39     84199     85865507
21  chr12   48315203   58023602      -   4  -38   9708399     95573906
22  chr12   12958603   48315202      -   3  -37  35356599    130930505
23  chr12   11907403   12958602      -   4  -36   1051199    131981704
24  chr12          1   11907402      -   3  -35  11907401    143889105

    bed_idx
0         0
1         1
2         2
3         3
4         4
5         5
6         6
7         7
8         8
9         9
10       10
11       11
12       12
13       13
14       14
15       15
16       16
17       17
18       18
19       19
20       20
21       21
22       22
23       23
24       24
gene CTNNB1
gene NCKIPSD
gene RHOA
gene SETD2
gene MLH1
gene MYD88
gene CCR4
gene TGFBR2
gene CHST11
gene BTG1
gene USP44
gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene KRAS
gene COL2A1
gene ETNK1
gene PPFIBP1
gene ARID2
gene CDKN1B
gene PTPN6
gene KDM5A
error!!!! in row index 37
gene CCND2
gene CHD4
gene ZNF384
gene ETV6
gene ERC1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227184-WG01_walk_1_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8  105074104  145138636      -   3 -441  40064532     40064532        0
1   chr8  105065425  105074103      -  10 -440      8678     40073210        1
2   chr8   94852783  105065424      -   4 -439  10212641     50285851        2
3   chr8   83290216   94852782      -   3 -438  11562566     61848417        3
4   chr8   82942183   83290215      -   4 -437    348032     62196449        4
5   chr8   50125603   82942182      -   3 -436  32816579     95013028        5
6   chr8   44159403   50125602      -   4 -435   5966199    100979227        6
7   chr8   43741603   44159402      -   9 -434    417799    101397026        7
8   chr8   42848001   43741602      -   7 -433    893601    102290627        8
9   chr8   42675528   42848000      -  10 -432    172472    102463099        9
10  chr3   44454005   45549911      +   5  219   1095906    103559005       10
11  chr3   45549912   45957501      +   4  220    407589    103966594       11
gene MYC
gene RECQL4
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
gene COX6C
gene PABPC1
gene UBR5
gene NBN
gene CDH17
gene RUNX1T1
gene CNBD1
gene HEY1
gene CHCHD7
gene PLAG1
gene TCEA1
gene LYN
gene NCOA2
gene PREX2
gene HOOK3
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_1_MYC_containing_breakpoints.pdf
running file  227184-WG01_walk_3_MYCL_containing.fa
bed file      chr     start       end strand  cn   5      span  span_cumsum  bed_idx
0   chr1  34570003  47324115      -   4 -15  12754112     12754112        0
1   chr1  33215803  34570002      -   3 -14   1354199     14108311        1
2   chr1  32850803  33215802      -   4 -13    364999     14473310        2
3   chr1  31802003  32850802      -   5 -12   1048799     15522109        3
4   chr1  31358603  31802002      -   4 -11    443399     15965508        4
5   chr1  30655903  31358602      -   5 -10    702699     16668207        5
6   chr1  29312003  30655902      -   4  -9   1343899     18012106        6
7   chr1  29173203  29312002      -   5  -8    138799     18150905        7
8   chr1  27676803  29173202      -   6  -7   1496399     19647304        8
9   chr1  26085803  27676802      -   5  -6   1590999     21238303        9
10  chr1  17351159  26085802      -   4  -5   8734643     29972946       10
11  chr1  10423723  17351158      -   5  -4   6927435     36900381       11
12  chr1   3640877  10422445      -   5  -2   6781568     43681949       12
13  chr1         1   3640876      -   4  -1   3640875     47322824       13
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene LCK
gene ARID1A
gene ID3
gene PAX7
gene ARHGEF10L
gene MDS2
gene CASP9
gene MTOR
gene PRDM2
gene SPEN
gene SDHB
gene RPL22
gene CAMTA1
gene TNFRSF14
gene SKI
gene PRDM16
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_3_MYCL_containing_breakpoints.pdf
running file  227184-WG01_walk_1_KRAS_containing.fa
bed file       chr     start       end strand  cn    5      span  span_cumsum  bed_idx
0    chr8  21442374  22807602      -   5 -411   1365228      1365228        0
1    chr8  21441651  21442373      -   6 -410       722      1365950        1
2   chr12  85327447  85327998      -   3  -71       551      1366501        2
3   chr12  71210694  85327446      -   2  -70  14116752     15483253        3
4   chr12  62690403  71208581      -   2  -68   8518178     24001431        4
5   chr12  61117803  62690402      -   3  -67   1572599     25574030        5
6   chr12  59878400  61117802      -   2  -66   1239402     26813432        6
7   chr12  59878025  59878399      -   4  -65       374     26813806        7
8   chr12  59877933  59878024      -   3  -64        91     26813897        8
9   chr12  58162203  59877932      -   2  -63   1715729     28529626        9
10  chr12  58023603  58162202      -   3  -62    138599     28668225       10
11  chr12  48351003  58023602      -   4  -61   9672599     38340824       11
12  chr12  41601203  48351002      -   3  -60   6749799     45090623       12
13  chr12  39846603  41601202      -   2  -59   1754599     46845222       13
14  chr12  38040003  39846602      -   3  -58   1806599     48651821       14
15  chr12  37183803  38040002      -   4  -57    856199     49508020       15
16  chr12   8110803  37183802      -   3  -56  29072999     78581019       16
17  chr12   7631403   8110802      -   4  -55    479399     79060418       17
18  chr12   7106603   7631402      -   3  -54    524799     79585217       18
19  chr12   6137803   7106602      -   4  -53    968799     80554016       19
20  chr12   5844803   6137802      -   3  -52    292999     80847015       20
21  chr12   4748803   5844802      -   2  -51   1095999     81943014       21
22  chr12   1158203   4748802      -   3  -50   3590599     85533613       22
23  chr12    595803   1158202      -   4  -49    562399     86096012       23
24  chr12    245803    595802      -   3  -48    349999     86446011       24
25  chr12         1    245802      -   2  -47    245801     86691812       25

gene WIF1
gene HMGA2
gene MDM2
gene PTPRB
gene LRIG3
gene HOXC13
gene HOXC11
gene NAB2
gene GLI1
gene DDIT3
gene CDK4
gene PRPF40B
gene SMARCD1
gene ATF1
gene ACVR1B
gene NACA
gene STAT6
gene KMT2D
gene ERBB3
gene COL2A1
gene ARID2
gene CDKN1B
gene KRAS
gene ETV6
gene ETNK1
gene PPFIBP1
gene PTPN6
gene CHD4
gene ZNF384
gene CCND2
gene ERC1
gene ERC1
gene KDM5A
error!!!! in row index 32
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_1_KRAS_containing_breakpoints.pdf
running file  227184-WG01_walk_3_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr7   32384003   32853802      +  13  353    469799       469799        0
1  chr7   32853803   33062602      +  15  354    208799       678598        1
2  chr7   33062603   33619602      +  12  355    556999      1235597        2
3  chr7   33619603   34047894      +  10  356    428291      1663888        3
4  chr7   34047895   34097116      +  11  357     49221      1713109        4
5  chr8  105065425  105074103      +  10  440      8678      1721787        5
6  chr8  105074104  145138636      +   3  441  40064532     41786319        6
gene FKBP9
gene MYC
gene RECQL4
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_3_MYC_containing_breakpoints.pdf
running file  227183-WG01_walk_1_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1          1    1625792      +   3   1   1625791      1625791        0
1   chr1    1625793   10422445      +   5   2   8796652     10422443        1
2   chr1   10422446   13155202      +   6   3   2732756     13155199        2
3   chr1   13155203   17351158      +   7   4   4195955     17351154        3
4   chr1   17351159   67596602      +   5   5  50245443     67596597        4
5   chr1   67596603  108426002      +   4   6  40829399    108425996        5
6   chr1  108426003  109698802      +   5   7   1272799    109698795        6
7   chr1  109698803  161189007      +   4   8  51490204    161188999        7
8   chr1  161189008  161539861      +   5   9    350853    161539852        8
9   chr1  161539862  161540075      +   3  10       213    161540065        9
10  chr1  161540076  187750002      +   4  11  26209926    187749991       10
11  chr1  187750003  194094402      +   3  12   6344399    194094390       11
12  chr1  194094403  194216602      +   1  13    122199    194216589       12
13  chr1  194216603  199745602      +   3  14   5528999    199745588       13
14  chr1  199745603  200528002      +   4  15    782399    200527987       14
15  chr1  200528003  200805695      +   3  16    277692    200805679       15
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene FUBP1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene ATP1A1
gene PDE4DIP
gene MUC1
gene SDHC
gene FCGR2B
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
gene CDC73
gene PTPRC
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_1_MYCL_containing_breakpoints.pdf
running file  227183-WG01_walk_2_MYC_containing.fa
bed file     chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0  chr7   31131003   31212278      +  12  244     81275        81275        0
1  chr7   31212279   31681002      +  13  245    468723       549998        1
2  chr7   31681003   32841802      +  10  246   1160799      1710797        2
3  chr7   32841803   33087402      +  12  247    245599      1956396        3
4  chr7   33087403   33104244      +  10  248     16841      1973237        4
5  chr7   33104245   33614002      +   9  249    509757      2482994        5
6  chr7   33614003   34097116      +   8  250    483113      2966107        6
7  chr8  105065425  105074058      +   9  293      8633      2974740        7
8  chr8  105074059  131268202      +   4  294  26194143     29168883        8
9  chr8  131268203  145138636      +   5  295  13870433     43039316        9
gene FKBP9
gene MYC
gene EIF3E
gene RAD21
gene EXT1
gene RSPO2
gene CSMD3
gene RECQL4
gene NDRG1
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_2_MYC_containing_breakpoints.pdf
running file  227183-WG01_walk_1_MYCN_containing.fa
bed file     chr      start        end strand  cn    5       span  span_cumsum  bed_idx
0  chr2  110080204  242193529      -   2 -133  132113325    132113325        0
1  chr2   90168003  110080203      -   3 -132   19912200    152025525        1
2  chr2     667003   90168002      -   2 -131   89500999    241526524        2
3  chr2          1     667002      -   1 -130     667001    242193525        3
gene CXCR4
gene HOXD11
gene FEV
gene ACKR3
gene HOXD13
gene NFE2L2
gene CASP8
gene CD28
gene CREB1
gene IDH1
gene BARD1
gene ATIC
gene ACSL3
gene ERCC3
gene ACVR1
gene COL3A1
gene SF3B1
gene CUL3
gene PAX8
gene LRP1B
gene ACVR2A
gene ITGAV
gene PMS1
gene ERBB4
gene PAX3
gene TMEM127
gene RANBP2
gene RGPD3
gene AFF3
gene PCBP1
gene MYCN
gene WDCP
gene ASXL2
gene SIX2
gene EPAS1
gene MSH6
gene BCL11A
gene REL
gene XPO1
gene DCTN1
gene NCOA1
gene DNMT3A
gene STRN
gene EML4
gene FBXO11
gene MSH2
gene ALK
gene BIRC6
gene CTNNA2
running file  227184-WG01_walk_2_MYCL_containing.fa
bed file      chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr1   31802003   32850802      +   5  12   1048799      1048799        0
1   chr1   32850803   33215802      +   4  13    364999      1413798        1
2   chr1   33215803   34570002      +   3  14   1354199      2767997        2
3   chr1   34570003   47324115      +   4  15  12754112     15522109        3
4   chr1   47324116   54753402      +   4  16   7429286     22951395        4
5   chr1   54753403   62589005      +   3  17   7835602     30786997        5
6   chr1   62589006   62589293      +   4  18       287     30787284        6
7   chr1   62589294  149210602      +   3  19  86621308    117408592        7
8   chr1  149210603  152302069      +   4  20   3091466    120500058        8
9   chr1  152302070  152506248      +   2  21    204178    120704236        9
10  chr1  152506249  154644466      +   4  22   2138217    122842453       10
11  chr1  154644467  154644652      +   5  23       185    122842638       11
12  chr1  154644653  157833202      +   4  24   3188549    126031187       12
13  chr1  157833203  160989802      +   2  25   3156599    129187786       13
14  chr1  160989803  161187491      +   4  26    197688    129385474       14
15  chr1  161187492  161319237      +   3  27    131745    129517219       15
16  chr1  161319238  161539861      +   5  28    220623    129737842       16
17  chr1  202756003  203097625      -   5 -33    341622    130079464       17
18  chr1  202469403  202756002      -   4 -32    286599    130366063       18
19  chr1  201579603  202469402      -   5 -31    889799    131255862       19
20  chr1  187752004  201579602      -   3 -30  13827598    145083460       20
21  chr1  161539862  187752003      -   4 -29  26212141    171295601       21
22  chr1  161319238  161539861      -   5 -28    220623    171516224       22
23  chr1  161187492  161319237      -   3 -27    131745    171647969       23
24  chr1  160989803  161187491      -   4 -26    197688    171845657       24
gene LCK
error!!!! in row index 0
gene MYCL
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene EPS15
gene JUN
gene BCL10
gene RPL5
gene NRAS
gene FUBP1
gene RBM15
gene TENT5C
gene JAK1
gene TRIM33
gene NOTCH2
gene BCL9
gene ATP1A1
gene PDE4DIP

gene SETDB1
gene MLLT11
gene ARNT
gene S100A7
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene MUC1
gene SDHC
gene SDHC
gene ELF3
gene CDC73
gene PTPRC
gene FCGR2B
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
gene SDHC
gene SDHC
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  227183-WG01_walk_2_MYCL_containing.fa
bed file       chr      start        end strand  cn   5      span  span_cumsum  bed_idx
0   chr17    7630309   15848059      +   2  99   8217750      8217750        0
1    chr1    1625793   10422445      +   5   2   8796652     17014402        1
2    chr1   10422446   13155202      +   6   3   2732756     19747158        2
3    chr1   13155203   17351158      +   7   4   4195955     23943113        3
4    chr1   17351159   67596602      +   5   5  50245443     74188556        4
5    chr1   67596603  108426002      +   4   6  40829399    115017955        5
6    chr1  108426003  109698802      +   5   7   1272799    116290754        6
7    chr1  109698803  161189007      +   4   8  51490204    167780958        7
8    chr1  161189008  161539861      +   5   9    350853    168131811        8
9    chr1  161539862  161540075      +   3  10       213    168132024        9
10   chr1  161540076  187750002      +   4  11  26209926    194341950       10
gene TP53
error!!!! in row index 0
gene PER1
error!!!! in row index 1
gene GAS7
gene MAP2K4
gene TNFRSF14
gene SKI
gene RPL22
gene CAMTA1
gene PRDM16
gene MTOR
gene CASP9
gene PRDM2
gene SPEN
gene SDHB
gene ID3
gene MYCL
gene JUN
gene PAX7
gene LCK
gene SFPQ
gene THRAP3
gene CSF3R
gene MPL
gene MUTYH
gene STIL
gene TAL1
gene CDKN2C
gene ARHGEF10L
gene MDS2
gene ARID1A
gene JAK1
gene EPS15
gene BCL10
gene RPL5
gene FUBP1
gene NRAS
gene S100A7
gene RBM15
gene TENT5C
gene SETDB1
gene MLLT11
gene TPM3
gene LMNA
gene NTRK1
gene PRCC
gene FCRL4
gene TRIM33
gene NOTCH2
gene BCL9
gene ARNT
gene ATP1A1
gene PDE4DIP
gene MUC1
gene SDHC
gene FCGR2B
gene PRRX1
gene TPR
gene DDR2
gene ABL2
gene PBX1
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227183-WG01_walk_2_MYCL_containing_breakpoints.pdf
running file  227184-WG01_walk_2_MYC_containing.fa
bed file      chr      start        end strand  cn    5      span  span_cumsum  bed_idx
0   chr8    8187803    8783802      +   8  402    595999       595999        0
1   chr8    8783803    9577202      +   9  403    793399      1389398        1
2   chr8    9577203   10422285      +   8  404    845082      2234480        2
3   chr8  105065425  105074103      -  10 -440      8678      2243158        3
4   chr7   34047895   34097116      -  11 -357     49221      2292379        4
5   chr7   33619603   34047894      -  10 -356    428291      2720670        5
6   chr7   33062603   33619602      -  12 -355    556999      3277669        6
7   chr7   32853803   33062602      -  15 -354    208799      3486468        7
8   chr7   32384003   32853802      -  13 -353    469799      3956267        8
9   chr7   31678803   32384002      -  12 -352    705199      4661466        9
10  chr7   30703770   31678802      -  14 -351    975032      5636498       10
11  chr7   30438661   30703769      -  19 -350    265108      5901606       11
12  chr7   46223384   46223489      +  22  373       105      5901711       12
13  chr7   22045120   22045276      +  21  327       156      5901867       13
14  chr7   46223490   46223555      -  13 -374        65      5901932       14
15  chr7   46223384   46223489      -  22 -373       105      5902037       15
16  chr7   30438661   30703769      +  19  350    265108      6167145       16
17  chr7   30703770   31678802      +  14  351    975032      7142177       17
18  chr7   31678803   32384002      +  12  352    705199      7847376       18
19  chr7   32384003   32853802      +  13  353    469799      8317175       19
20  chr7   32853803   33062602      +  15  354    208799      8525974       20
21  chr7   33062603   33619602      +  12  355    556999      9082973       21
22  chr7   33619603   34047894      +  10  356    428291      9511264       22
23  chr7   34047895   34097116      +  11  357     49221      9560485       23
24  chr8  105065425  105074103      +  10  440      8678      9569163       24
25  chr8  105074104  145138636      +   3  441  40064532     49633695       25
gene FKBP9
gene FKBP9
gene MYC
gene RECQL4
gene EIF3E
gene RAD21
gene NDRG1
gene EXT1
gene RSPO2
gene CSMD3
gene FAM135B
saving to /pollard/data/projects/shzhang/mdanderson/figs/20241119_bypatient_genecenter_change/patient_24/227184-WG01_walk_2_MYC_containing_breakpoints.pdf

In [ ]:
bed_name=''
bed=pd.read_csv(f'{patient_data_dir}walks_bed/' + bed_name, sep='\t', header=None)
bed

In [ ]:
patient1_files=os.listdir(f'{patient_data_dir}/patient_1/walks_fasta')
patient1_files

In [ ]:
#make akita predictions for each walk and plot 
def pred_akita_bkpts(fa_dir, fa_name, patient_num):
    bed_name=fa_name.replace('fa', 'bed')
    name_parts = bed_name.rsplit('_', 2)

    gencode_coord=gene_annot[gene_annot.Gene == name_parts[1]]    
    gene_len=abs(gencode_coord.end_gene-gencode_coord.start_gene)
    gene_mid_coord=np.floor(gencode_coord.start_gene + (gene_len/2))
    #print(gencode_coord)
    
    try:

        #read in bed file and figure out where to center the file 
        bed=pd.read_csv(f'{patient_data_dir}walks_bed/' + bed_name, sep='\t', header=None)
        bed.columns = ['chr', 'start', 'end', 'strand', 'cn', '5']
        bed['chr'] = bed['chr'].astype('str') 
        bed['span']=abs(bed['end']-bed['start']) 
        bed['span_cumsum'] = bed['span'].cumsum()
    
        
        #print(bed)
        
        
        #get the row where gene_mid_coord 
        start_condition = ((bed['chr']==gencode_coord.CHROM.values[0])
                & (bed['start'] <= int(gencode_coord.start_gene)) & (int(gencode_coord.start_gene) <= bed['end']) ) 
        row_gene_start_list = start_condition.index[start_condition].tolist()
            
        end_condition = ((bed['chr']==gencode_coord.CHROM.values[0])
                & (bed['start'] <= int(gencode_coord.end_gene)) & (int(gencode_coord.end_gene) <= bed['end']) ) 
        row_gene_end_list = end_condition.index[end_condition].tolist()
        #print('row_gene_start_list', row_gene_start_list)
    
    except: 
        print('bed file not found!!!!!!!!')
       

    
    # read in fasta file 
    seq=read_fasta(f'{fa_dir}{fa_name}')
            
    
    figures=[]
    for i in range (0, len(bed)-1):
    #for i in range(0,4):
        #print('row ', i)
        
        try:
        
            #get first, last rows, and subsets of bed before and after bkpt 
            first_row=bed.iloc[0,:]
            last_row=bed.iloc[(len(bed)-1), :]
            left_bkpt=bed.iloc[i, :]
            right_bkpt=bed.iloc[i+1,:]
            bed_to_bkpt=bed.iloc[0:(i+1),:]
        
            #get relevant lengths
            total_span=np.sum(bed['span'])
            len_left_to_bkpt=np.sum(bed_to_bkpt['span'])
            len_bkpt_to_right=total_span-len_left_to_bkpt
        
        
        
            # left sequence 
            if len_left_to_bkpt>=utils.half_patch_size:
                ALT_left=seq[(len_left_to_bkpt - utils.half_patch_size ):len_left_to_bkpt]
            
            else:   
                #need to pad left from reference 
                diff_len=utils.half_patch_size-len_left_to_bkpt
           
                first_row_idx=first_row.start
                ALT_fromref_left=fasta_hg38.fetch(first_row.chr, first_row_idx-diff_len, first_row_idx).upper()
            
                ALT_left=ALT_fromref_left + seq[0:len_left_to_bkpt]
            
        
            # right sequence 
            if len_bkpt_to_right>utils.half_patch_size:
                ALT_right=seq[len_left_to_bkpt: (len_left_to_bkpt + utils.half_patch_size)]
            
            else:
                #need to pad right from reference        
                diff_len=utils.half_patch_size-len_bkpt_to_right
            
                last_row_idx=last_row.end
                ALT_fromref_right=fasta_hg38.fetch(last_row.chr, last_row_idx, last_row_idx + diff_len).upper()

                ALT_right=seq[len_left_to_bkpt:total_span] + ALT_fromref_right
            
            
            ALT_seq = ALT_left + ALT_right

            
            ########################

            #we want to get indices of the breakpoints, if others are in the window 

            #get index for where the akita window starts 
            left_start=len_left_to_bkpt-utils.half_patch_size
            #print(left_start)

            bkpt_pos_from_left_all=bed['span_cumsum'].tolist() - left_start 
            #print(bkpt_pos_from_left_all)

            #subset to those less than akita window size
            bkpt_pos_from_left=bkpt_pos_from_left_all[(bkpt_pos_from_left_all>0) & (bkpt_pos_from_left_all<utils.MB)]
            #print(bkpt_pos_from_left)
            
            #get the bin index
            bkpt_bin_list_all=[utils.get_bin(bkpt) for bkpt in bkpt_pos_from_left]
            bkpt_bin_list = [bkpt for bkpt in bkpt_bin_list_all if 0 < bkpt <= 448]


            
            ########################
            #finally, get the positions of the gene(s)
                       
            gene_start_bin_list=[]
            gene_end_bin_list=[]

            try:
                
                #check the start of the gene 
                for g in row_gene_start_list:
                    len_to_gene_start=gencode_coord.start_gene.values[0] - (bed.iloc[g, :].start) 
                    #print('len to gene start' , len_to_gene_start)

                    if g>0: 
                        len_before_row=bed.iloc[0:g, :]['span_cumsum'][g-1]
                        len_to_gene_start+=len_before_row


                    gene_start_pos_window=len_to_gene_start - left_start 
                    if (gene_start_pos_window>0) & (gene_start_pos_window<utils.MB):
                        gene_start_bin_list.append(utils.get_bin(gene_start_pos_window))
                        
                #check the end of the gene      
                for g in row_gene_end_list:
                    len_to_gene_end=gencode_coord.end_gene.values[0] - (bed.iloc[g, :].start) 
                    #print('len to gene end' , len_to_gene_end)

                    if g>0: 
                        len_before_row=bed.iloc[0:g, :]['span_cumsum'][g-1]
                        len_to_gene_end+=len_before_row

                    gene_end_pos_window=len_to_gene_end - left_start 
                    if (gene_end_pos_window>0) & (gene_end_pos_window<utils.MB):
                        gene_end_bin_list.append(utils.get_bin(gene_end_pos_window))

                
            except:
                print("error in gene annotation!")


            #########################
            #finally, get the REF -- for the two sequences to the left and right of the breakpoint 
            left_ref_coords=[left_bkpt.chr, left_bkpt.end-utils.half_patch_size, 
                                          left_bkpt.end+utils.half_patch_size]
            right_ref_coords=[right_bkpt.chr, right_bkpt.start-utils.half_patch_size, 
                                          right_bkpt.start+utils.half_patch_size]


            REF_seq_left=fasta_hg38.fetch(left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]).upper()
            REF_seq_right=fasta_hg38.fetch(right_ref_coords[0], right_ref_coords[1], right_ref_coords[2]).upper()


            ####################

            #check sequence lengths, and then run akita 
            #print(len(REF_seq_left))
            assert len(REF_seq_left) == utils.seq_length, 'REF_seq_left is not right length'
            assert len(REF_seq_right) == utils.seq_length, 'REF_seq_right is not right length'
            assert len(ALT_seq) == utils.seq_length, 'ALT_seq is not right length'



            #this is where akita is actually run, output vector size is (99681,)
            REF_left_vec, REF_right_vec, ALT_vec = utils.vector_from_seq(REF_seq_left), utils.vector_from_seq(REF_seq_right), utils.vector_from_seq(ALT_seq)
            REF_left_mat, REF_right_mat, ALT_mat = utils.mat_from_vector(REF_left_vec), utils.mat_from_vector(REF_right_vec), utils.mat_from_vector(ALT_vec)

    
            #order is REF_left, REF_right, ALT
            mat_list=[REF_left_mat, REF_right_mat, ALT_mat]
            
            #add annotation for span between bkpts if same chr, or annot as translocation
            if left_ref_coords[0]==left_ref_coords[0]:
                span_annot=str(right_ref_coords[1] - left_ref_coords[2]) + ' bp between breakpoints'
            else:
                span_annot='interchromosomal'
            
            #get label list 
            label_list=['{}:{}-{}'.format(left_ref_coords[0], left_ref_coords[1], left_ref_coords[2]), 
                       '{}:{}-{}'.format(right_ref_coords[0], right_ref_coords[1], right_ref_coords[2]), 
                       'Left: {}:{}-{} \n Right: {}:{}-{} \n {}'.format(
                        left_bkpt.chr, left_bkpt.start, left_bkpt.end, 
                           right_bkpt.chr, right_bkpt.start, right_bkpt.end, 
                           span_annot), f'{fa_name[:-3]} \n rows {i} - {i+1}']

            #print(label_list)
            # plot!
            fig=plot_complex_pred(mat_list, label_list, bkpt_bin_list, gene_start_bin_list, gene_end_bin_list)
            figures.append(fig)
           

        
        except:
            print('error!!!! in row index', i )
            
    #print(f'saving to {fig_dir}patient_{patient_num}/{bed_name[:-4]}_breakpoints.pdf')
    save_figures_to_pdf(f'{fig_dir}patient_{patient_num}/{bed_name[:-4]}_plot.pdf', figures)
    plt.close('all')