In [20]:
%load_ext autoreload
%autoreload 2

2024-04-29 09:57:46.080062: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2024-04-29 09:57:46.080111: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2024-04-29 09:57:53.976830: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2024-04-29 09:57:53.976887: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2024-04-29 09:57:53.976920: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (westway.gladstone.internal): /proc/driver/nvidia/version does not exist
2024-04-29 09:57:53.979186: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 sequence (InputLayer)          [(None, 1048576, 4)  0           []
                                ]

 stochastic_reverse_complement   ((None, 1048576, 4)  0          ['sequence[0][0]']
 (StochasticReverseComplement)  , ())

 stochastic_shift (StochasticSh  (None, 1048576, 4)  0           ['stochastic_reverse_complement[0
 ift)                                                            ][0]']

 re_lu (ReLU)                   (None, 1048576, 4)   0           ['stochastic_shift[0][0]']

 conv1d (Conv1D)                (None, 1048576, 96)  4224        ['re_lu[0][0]']

 batch_normalization (BatchNorm  (None, 1048576, 96)  384        ['conv1d[0][0]']
 alization)

 max_pooling1d (MaxPooling1D)   (None, 524288, 96)   0           ['batch_normalization[0][0]']

 re_lu_1 (ReLU)                 (None, 524288, 96)   0           ['max_pooling1d[0][0]']

 conv1d_1 (Conv1D)              (None, 524288, 96)   46080       ['re_lu_1[0][0]']

 batch_normalization_1 (BatchNo  (None, 524288, 96)  384         ['conv1d_1[0][0]']
 rmalization)

 max_pooling1d_1 (MaxPooling1D)  (None, 262144, 96)  0           ['batch_normalization_1[0][0]']

 re_lu_2 (ReLU)                 (None, 262144, 96)   0           ['max_pooling1d_1[0][0]']

 conv1d_2 (Conv1D)              (None, 262144, 96)   46080       ['re_lu_2[0][0]']

 batch_normalization_2 (BatchNo  (None, 262144, 96)  384         ['conv1d_2[0][0]']
 rmalization)

 max_pooling1d_2 (MaxPooling1D)  (None, 131072, 96)  0           ['batch_normalization_2[0][0]']

 re_lu_3 (ReLU)                 (None, 131072, 96)   0           ['max_pooling1d_2[0][0]']

 conv1d_3 (Conv1D)              (None, 131072, 96)   46080       ['re_lu_3[0][0]']

 batch_normalization_3 (BatchNo  (None, 131072, 96)  384         ['conv1d_3[0][0]']
 rmalization)

 max_pooling1d_3 (MaxPooling1D)  (None, 65536, 96)   0           ['batch_normalization_3[0][0]']

 re_lu_4 (ReLU)                 (None, 65536, 96)    0           ['max_pooling1d_3[0][0]']

 conv1d_4 (Conv1D)              (None, 65536, 96)    46080       ['re_lu_4[0][0]']

 batch_normalization_4 (BatchNo  (None, 65536, 96)   384         ['conv1d_4[0][0]']
 rmalization)

 max_pooling1d_4 (MaxPooling1D)  (None, 32768, 96)   0           ['batch_normalization_4[0][0]']

 re_lu_5 (ReLU)                 (None, 32768, 96)    0           ['max_pooling1d_4[0][0]']

 conv1d_5 (Conv1D)              (None, 32768, 96)    46080       ['re_lu_5[0][0]']

 batch_normalization_5 (BatchNo  (None, 32768, 96)   384         ['conv1d_5[0][0]']
 rmalization)

 max_pooling1d_5 (MaxPooling1D)  (None, 16384, 96)   0           ['batch_normalization_5[0][0]']

 re_lu_6 (ReLU)                 (None, 16384, 96)    0           ['max_pooling1d_5[0][0]']

 conv1d_6 (Conv1D)              (None, 16384, 96)    46080       ['re_lu_6[0][0]']

 batch_normalization_6 (BatchNo  (None, 16384, 96)   384         ['conv1d_6[0][0]']
 rmalization)

 max_pooling1d_6 (MaxPooling1D)  (None, 8192, 96)    0           ['batch_normalization_6[0][0]']

 re_lu_7 (ReLU)                 (None, 8192, 96)     0           ['max_pooling1d_6[0][0]']

 conv1d_7 (Conv1D)              (None, 8192, 96)     46080       ['re_lu_7[0][0]']

 batch_normalization_7 (BatchNo  (None, 8192, 96)    384         ['conv1d_7[0][0]']
 rmalization)

 max_pooling1d_7 (MaxPooling1D)  (None, 4096, 96)    0           ['batch_normalization_7[0][0]']

 re_lu_8 (ReLU)                 (None, 4096, 96)     0           ['max_pooling1d_7[0][0]']

 conv1d_8 (Conv1D)              (None, 4096, 96)     46080       ['re_lu_8[0][0]']

 batch_normalization_8 (BatchNo  (None, 4096, 96)    384         ['conv1d_8[0][0]']
 rmalization)

 max_pooling1d_8 (MaxPooling1D)  (None, 2048, 96)    0           ['batch_normalization_8[0][0]']

 re_lu_9 (ReLU)                 (None, 2048, 96)     0           ['max_pooling1d_8[0][0]']

 conv1d_9 (Conv1D)              (None, 2048, 96)     46080       ['re_lu_9[0][0]']

 batch_normalization_9 (BatchNo  (None, 2048, 96)    384         ['conv1d_9[0][0]']
 rmalization)

 max_pooling1d_9 (MaxPooling1D)  (None, 1024, 96)    0           ['batch_normalization_9[0][0]']

 re_lu_10 (ReLU)                (None, 1024, 96)     0           ['max_pooling1d_9[0][0]']

 conv1d_10 (Conv1D)             (None, 1024, 96)     46080       ['re_lu_10[0][0]']

 batch_normalization_10 (BatchN  (None, 1024, 96)    384         ['conv1d_10[0][0]']
 ormalization)

 max_pooling1d_10 (MaxPooling1D  (None, 512, 96)     0           ['batch_normalization_10[0][0]']
 )

 re_lu_11 (ReLU)                (None, 512, 96)      0           ['max_pooling1d_10[0][0]']

 conv1d_11 (Conv1D)             (None, 512, 48)      13824       ['re_lu_11[0][0]']

 batch_normalization_11 (BatchN  (None, 512, 48)     192         ['conv1d_11[0][0]']
 ormalization)

 re_lu_12 (ReLU)                (None, 512, 48)      0           ['batch_normalization_11[0][0]']

 conv1d_12 (Conv1D)             (None, 512, 96)      4608        ['re_lu_12[0][0]']

 batch_normalization_12 (BatchN  (None, 512, 96)     384         ['conv1d_12[0][0]']
 ormalization)

 dropout (Dropout)              (None, 512, 96)      0           ['batch_normalization_12[0][0]']

 add (Add)                      (None, 512, 96)      0           ['max_pooling1d_10[0][0]',
                                                                  'dropout[0][0]']

 re_lu_13 (ReLU)                (None, 512, 96)      0           ['add[0][0]']

 conv1d_13 (Conv1D)             (None, 512, 48)      13824       ['re_lu_13[0][0]']

 batch_normalization_13 (BatchN  (None, 512, 48)     192         ['conv1d_13[0][0]']
 ormalization)

 re_lu_14 (ReLU)                (None, 512, 48)      0           ['batch_normalization_13[0][0]']

 conv1d_14 (Conv1D)             (None, 512, 96)      4608        ['re_lu_14[0][0]']

 batch_normalization_14 (BatchN  (None, 512, 96)     384         ['conv1d_14[0][0]']
 ormalization)

 dropout_1 (Dropout)            (None, 512, 96)      0           ['batch_normalization_14[0][0]']

 add_1 (Add)                    (None, 512, 96)      0           ['add[0][0]',
                                                                  'dropout_1[0][0]']

 re_lu_15 (ReLU)                (None, 512, 96)      0           ['add_1[0][0]']

 conv1d_15 (Conv1D)             (None, 512, 48)      13824       ['re_lu_15[0][0]']

 batch_normalization_15 (BatchN  (None, 512, 48)     192         ['conv1d_15[0][0]']
 ormalization)

 re_lu_16 (ReLU)                (None, 512, 48)      0           ['batch_normalization_15[0][0]']

 conv1d_16 (Conv1D)             (None, 512, 96)      4608        ['re_lu_16[0][0]']

 batch_normalization_16 (BatchN  (None, 512, 96)     384         ['conv1d_16[0][0]']
 ormalization)

 dropout_2 (Dropout)            (None, 512, 96)      0           ['batch_normalization_16[0][0]']

 add_2 (Add)                    (None, 512, 96)      0           ['add_1[0][0]',
                                                                  'dropout_2[0][0]']

 re_lu_17 (ReLU)                (None, 512, 96)      0           ['add_2[0][0]']

 conv1d_17 (Conv1D)             (None, 512, 48)      13824       ['re_lu_17[0][0]']

 batch_normalization_17 (BatchN  (None, 512, 48)     192         ['conv1d_17[0][0]']
 ormalization)

 re_lu_18 (ReLU)                (None, 512, 48)      0           ['batch_normalization_17[0][0]']

 conv1d_18 (Conv1D)             (None, 512, 96)      4608        ['re_lu_18[0][0]']

 batch_normalization_18 (BatchN  (None, 512, 96)     384         ['conv1d_18[0][0]']
 ormalization)

 dropout_3 (Dropout)            (None, 512, 96)      0           ['batch_normalization_18[0][0]']

 add_3 (Add)                    (None, 512, 96)      0           ['add_2[0][0]',
                                                                  'dropout_3[0][0]']

 re_lu_19 (ReLU)                (None, 512, 96)      0           ['add_3[0][0]']

 conv1d_19 (Conv1D)             (None, 512, 48)      13824       ['re_lu_19[0][0]']

 batch_normalization_19 (BatchN  (None, 512, 48)     192         ['conv1d_19[0][0]']
 ormalization)

 re_lu_20 (ReLU)                (None, 512, 48)      0           ['batch_normalization_19[0][0]']

 conv1d_20 (Conv1D)             (None, 512, 96)      4608        ['re_lu_20[0][0]']

 batch_normalization_20 (BatchN  (None, 512, 96)     384         ['conv1d_20[0][0]']
 ormalization)

 dropout_4 (Dropout)            (None, 512, 96)      0           ['batch_normalization_20[0][0]']

 add_4 (Add)                    (None, 512, 96)      0           ['add_3[0][0]',
                                                                  'dropout_4[0][0]']

 re_lu_21 (ReLU)                (None, 512, 96)      0           ['add_4[0][0]']

 conv1d_21 (Conv1D)             (None, 512, 48)      13824       ['re_lu_21[0][0]']

 batch_normalization_21 (BatchN  (None, 512, 48)     192         ['conv1d_21[0][0]']
 ormalization)

 re_lu_22 (ReLU)                (None, 512, 48)      0           ['batch_normalization_21[0][0]']

 conv1d_22 (Conv1D)             (None, 512, 96)      4608        ['re_lu_22[0][0]']

 batch_normalization_22 (BatchN  (None, 512, 96)     384         ['conv1d_22[0][0]']
 ormalization)

 dropout_5 (Dropout)            (None, 512, 96)      0           ['batch_normalization_22[0][0]']

 add_5 (Add)                    (None, 512, 96)      0           ['add_4[0][0]',
                                                                  'dropout_5[0][0]']

 re_lu_23 (ReLU)                (None, 512, 96)      0           ['add_5[0][0]']

 conv1d_23 (Conv1D)             (None, 512, 48)      13824       ['re_lu_23[0][0]']

 batch_normalization_23 (BatchN  (None, 512, 48)     192         ['conv1d_23[0][0]']
 ormalization)

 re_lu_24 (ReLU)                (None, 512, 48)      0           ['batch_normalization_23[0][0]']

 conv1d_24 (Conv1D)             (None, 512, 96)      4608        ['re_lu_24[0][0]']

 batch_normalization_24 (BatchN  (None, 512, 96)     384         ['conv1d_24[0][0]']
 ormalization)

 dropout_6 (Dropout)            (None, 512, 96)      0           ['batch_normalization_24[0][0]']

 add_6 (Add)                    (None, 512, 96)      0           ['add_5[0][0]',
                                                                  'dropout_6[0][0]']

 re_lu_25 (ReLU)                (None, 512, 96)      0           ['add_6[0][0]']

 conv1d_25 (Conv1D)             (None, 512, 48)      13824       ['re_lu_25[0][0]']

 batch_normalization_25 (BatchN  (None, 512, 48)     192         ['conv1d_25[0][0]']
 ormalization)

 re_lu_26 (ReLU)                (None, 512, 48)      0           ['batch_normalization_25[0][0]']

 conv1d_26 (Conv1D)             (None, 512, 96)      4608        ['re_lu_26[0][0]']

 batch_normalization_26 (BatchN  (None, 512, 96)     384         ['conv1d_26[0][0]']
 ormalization)

 dropout_7 (Dropout)            (None, 512, 96)      0           ['batch_normalization_26[0][0]']

 add_7 (Add)                    (None, 512, 96)      0           ['add_6[0][0]',
                                                                  'dropout_7[0][0]']

 re_lu_27 (ReLU)                (None, 512, 96)      0           ['add_7[0][0]']

 conv1d_27 (Conv1D)             (None, 512, 64)      30720       ['re_lu_27[0][0]']

 batch_normalization_27 (BatchN  (None, 512, 64)     256         ['conv1d_27[0][0]']
 ormalization)

 re_lu_28 (ReLU)                (None, 512, 64)      0           ['batch_normalization_27[0][0]']

 one_to_two (OneToTwo)          (None, 512, 512, 64  0           ['re_lu_28[0][0]']
                                )

 concat_dist2d (ConcatDist2D)   (None, 512, 512, 65  0           ['one_to_two[0][0]']
                                )

 re_lu_29 (ReLU)                (None, 512, 512, 65  0           ['concat_dist2d[0][0]']
                                )

 conv2d (Conv2D)                (None, 512, 512, 48  28080       ['re_lu_29[0][0]']
                                )

 batch_normalization_28 (BatchN  (None, 512, 512, 48  192        ['conv2d[0][0]']
 ormalization)                  )

 symmetrize2d (Symmetrize2D)    (None, 512, 512, 48  0           ['batch_normalization_28[0][0]']
                                )

 re_lu_30 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d[0][0]']
                                )

 conv2d_1 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_30[0][0]']
                                )

 batch_normalization_29 (BatchN  (None, 512, 512, 24  96         ['conv2d_1[0][0]']
 ormalization)                  )

 re_lu_31 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_29[0][0]']
                                )

 conv2d_2 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_31[0][0]']
                                )

 batch_normalization_30 (BatchN  (None, 512, 512, 48  192        ['conv2d_2[0][0]']
 ormalization)                  )

 dropout_8 (Dropout)            (None, 512, 512, 48  0           ['batch_normalization_30[0][0]']
                                )

 add_8 (Add)                    (None, 512, 512, 48  0           ['symmetrize2d[0][0]',
                                )                                 'dropout_8[0][0]']

 symmetrize2d_1 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_8[0][0]']
                                )

 re_lu_32 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_1[0][0]']
                                )

 conv2d_3 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_32[0][0]']
                                )

 batch_normalization_31 (BatchN  (None, 512, 512, 24  96         ['conv2d_3[0][0]']
 ormalization)                  )

 re_lu_33 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_31[0][0]']
                                )

 conv2d_4 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_33[0][0]']
                                )

 batch_normalization_32 (BatchN  (None, 512, 512, 48  192        ['conv2d_4[0][0]']
 ormalization)                  )

 dropout_9 (Dropout)            (None, 512, 512, 48  0           ['batch_normalization_32[0][0]']
                                )

 add_9 (Add)                    (None, 512, 512, 48  0           ['symmetrize2d_1[0][0]',
                                )                                 'dropout_9[0][0]']

 symmetrize2d_2 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_9[0][0]']
                                )

 re_lu_34 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_2[0][0]']
                                )

 conv2d_5 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_34[0][0]']
                                )

 batch_normalization_33 (BatchN  (None, 512, 512, 24  96         ['conv2d_5[0][0]']
 ormalization)                  )

 re_lu_35 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_33[0][0]']
                                )

 conv2d_6 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_35[0][0]']
                                )

 batch_normalization_34 (BatchN  (None, 512, 512, 48  192        ['conv2d_6[0][0]']
 ormalization)                  )

 dropout_10 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_34[0][0]']
                                )

 add_10 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_2[0][0]',
                                )                                 'dropout_10[0][0]']

 symmetrize2d_3 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_10[0][0]']
                                )

 re_lu_36 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_3[0][0]']
                                )

 conv2d_7 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_36[0][0]']
                                )

 batch_normalization_35 (BatchN  (None, 512, 512, 24  96         ['conv2d_7[0][0]']
 ormalization)                  )

 re_lu_37 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_35[0][0]']
                                )

 conv2d_8 (Conv2D)              (None, 512, 512, 48  1152        ['re_lu_37[0][0]']
                                )

 batch_normalization_36 (BatchN  (None, 512, 512, 48  192        ['conv2d_8[0][0]']
 ormalization)                  )

 dropout_11 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_36[0][0]']
                                )

 add_11 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_3[0][0]',
                                )                                 'dropout_11[0][0]']

 symmetrize2d_4 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_11[0][0]']
                                )

 re_lu_38 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_4[0][0]']
                                )

 conv2d_9 (Conv2D)              (None, 512, 512, 24  10368       ['re_lu_38[0][0]']
                                )

 batch_normalization_37 (BatchN  (None, 512, 512, 24  96         ['conv2d_9[0][0]']
 ormalization)                  )

 re_lu_39 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_37[0][0]']
                                )

 conv2d_10 (Conv2D)             (None, 512, 512, 48  1152        ['re_lu_39[0][0]']
                                )

 batch_normalization_38 (BatchN  (None, 512, 512, 48  192        ['conv2d_10[0][0]']

 ormalization)                  )

 dropout_12 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_38[0][0]']
                                )

 add_12 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_4[0][0]',
                                )                                 'dropout_12[0][0]']

 symmetrize2d_5 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_12[0][0]']
                                )

 re_lu_40 (ReLU)                (None, 512, 512, 48  0           ['symmetrize2d_5[0][0]']
                                )

 conv2d_11 (Conv2D)             (None, 512, 512, 24  10368       ['re_lu_40[0][0]']
                                )

 batch_normalization_39 (BatchN  (None, 512, 512, 24  96         ['conv2d_11[0][0]']
 ormalization)                  )

 re_lu_41 (ReLU)                (None, 512, 512, 24  0           ['batch_normalization_39[0][0]']
                                )

 conv2d_12 (Conv2D)             (None, 512, 512, 48  1152        ['re_lu_41[0][0]']
                                )

 batch_normalization_40 (BatchN  (None, 512, 512, 48  192        ['conv2d_12[0][0]']
 ormalization)                  )

 dropout_13 (Dropout)           (None, 512, 512, 48  0           ['batch_normalization_40[0][0]']
                                )

 add_13 (Add)                   (None, 512, 512, 48  0           ['symmetrize2d_5[0][0]',
                                )                                 'dropout_13[0][0]']

 symmetrize2d_6 (Symmetrize2D)  (None, 512, 512, 48  0           ['add_13[0][0]']
                                )

 cropping2d (Cropping2D)        (None, 448, 448, 48  0           ['symmetrize2d_6[0][0]']
                                )

 upper_tri (UpperTri)           (None, 99681, 48)    0           ['cropping2d[0][0]']

 dense (Dense)                  (None, 99681, 5)     245         ['upper_tri[0][0]']

 switch_reverse_triu (SwitchRev  (None, 99681, 5)    0           ['dense[0][0]',
 erseTriu)                                                        'stochastic_reverse_complement[0
                                                                 ][1]']

==================================================================================================
Total params: 751,653
Trainable params: 746,149
Non-trainable params: 5,504
__________________________________________________________________________________________________
None
model_strides [2048]
target_lengths [99681]
target_crops [-49585]
model successfully loaded

In [ ]:
import akita_utils_forplotting as utils
import numpy as np
import pandas as pd
import sys, os, psutil, time 
import matplotlib.pyplot as plt
import pysam
    
from skimage.transform import resize

nt = ['A', 'T', 'C', 'G']

In [33]:
#TOTAL AKITA INPUT LENGTH 

akita_seq_len=1048576

#HG38 REF FA
hg38_file = '/pollard/home/shzhang/akita/run_akita/refs/hg38.fa'
fasta_hg38 = pysam.Fastafile(hg38_file)

#GENCODE
gene_annot = pd.read_csv('/pollard/data/genetics/GENCODE/release32/gencode.v32.genes_only.bed', sep = '\t', names = ['CHROM', 'start_gene', 'end_gene', 'Gene'])
gene_annot[gene_annot.CHROM != 'chrM']
#gene_annot.head()

      CHROM  start_gene  end_gene         Gene
0      chr1       11869     14409      DDX11L1
1      chr1       14404     29570       WASH7P
2      chr1       17369     17436    MIR6859-1
3      chr1       29554     31109  MIR1302-2HG
4      chr1       30366     30503    MIR1302-2
...     ...         ...       ...          ...
60567  chrY    57184101  57197337         IL9R
60568  chrY    57190738  57208756   AJ271736.1
60569  chrY    57201143  57203357       WASIR1
60570  chrY    57207346  57212230       WASH6P
60571  chrY    57212184  57214397     DDX11L16

[60572 rows x 4 columns]

In [34]:
def read_fasta(fa):
    seq=''
    with open(fa, "r") as fa_file:
        for line in fa_file:
            if not (line.startswith('>')):
                seq += line.strip()
    fa_file.close()                
    return(seq)

In [43]:
#directories 
data_dir='/pollard/data/projects/shzhang/mdanderson/'

fig_dir=f'{data_dir}figs/'
date='20240429'

In [26]:
os.listdir(data_dir)

['meta_sv2.csv',
 'walks_fasta_1',
 'walks_bed',
 'test',
 'figs',
 'walks_bed_cn',
 'walks_fasta_2',
 'walks_fasta_cn_3',
 'patient_1']

In [12]:
meta=pd.read_csv(f'{data_dir}meta_sv2.csv')
meta['tumor_id']=meta['tumor'].str.split('-').str.get(0)
meta

,Patient,Tumor_Type,Timepoint,normal,tumor,gender,tumor_id
0,Patient1,DDLPS,baseline,226294-WG01,226295-WG01,XX,226295
1,Patient1,DDLPS,On_treatment,226294-WG01,226296-WG01,XX,226296
2,Patient1,DDLPS,Surgery,226294-WG01,226298-WG01,XX,226298
3,Patient1,DDLPS,Surgery,226294-WG01,226297-WG01,XX,226297
4,Patient2,DDLPS,baseline,226299-WG01,226300-WG01,XX,226300
...,...,...,...,...,...,...,...
67,Patient23,DDLPS,baseline,227190-WG01,227180-WG01,XX,227180
68,Patient23,DDLPS,On_treatment,227190-WG01,227181-WG01,XX,227181
69,Patient23,DDLPS,Surgery,227190-WG01,227182-WG01,XX,227182
70,Patient24,UPS,baseline,227191-WG01,227183-WG01,XX,227183
71,Patient24,UPS,On_treatment,227191-WG01,227184-WG01,XX,227184

In [57]:
os.listdir(f'{data_dir}patient_1/walks_fasta')

['226297-WG01_walk_1_EGFR_containing.fa',
 '226298-WG01_walk_1_MYC_containing.fa',
 '226297-WG01_walk_1_KRAS_containing.fa',
 '226295-WG01_walk_2_EGFR_containing.fa',
 '226296-WG01_walk_4_EGFR_containing.fa',
 '226297-WG01_walk_1_MDM2_containing.fa',
 '226296-WG01_walk_1_EGFR_containing.fa',
 '226296-WG01_walk_3_EGFR_containing.fa',
 '226296-WG01_walk_2_EGFR_containing.fa',
 '226295-WG01_walk_1_MYC_containing.fa',
 '226297-WG01_walk_1_GLI1_containing.fa',
 '226298-WG01_walk_1_EGFR_containing.fa',
 '226297-WG01_walk_1_MYC_containing.fa',
 '226296-WG01_walk_2_MYC_containing.fa',
 '226296-WG01_walk_1_MYC_containing.fa',
 '226295-WG01_walk_1_EGFR_containing.fa']

In [23]:
os.listdir(f'{data_dir}walks_bed/')[0:3]

['226295-WG01_walk_1_ABL1_containing.bed',
 '226311-WG01_walk_1_HRAS_containing.bed',
 '226302-WG01_walk_2_CSF1R_containing.bed']

In [36]:
seq=read_fasta(f'{data_dir}patient_1/walks_fasta_cn/226297-WG01_walk_1_EGFR_containing.fa')
len(seq)

322216015

In [86]:
file_query='226296-WG01_walk_4_EGFR_containing.bed'
bed_cn=pd.read_csv(f'{data_dir}walks_bed_cn/{file_query}', sep='\t', header=None)
bed_cn[0:10]

      0        1         2  3  4     5
0  chr7        1    237845  +  4  2382
1  chr7        1    237845  +  4  2382
2  chr7        1    237845  +  4  2382
3  chr7        1    237845  +  4  2382
4  chr7   240279   1145442  +  4  2384
5  chr7   240279   1145442  +  4  2384
6  chr7   240279   1145442  +  4  2384
7  chr7   240279   1145442  +  4  2384
8  chr7  1148019  57490787  +  4  2386
9  chr7  1148019  57490787  +  4  2386

In [87]:
bed_nocn=pd.read_csv(f'{data_dir}walks_bed/{file_query}', sep='\t', header=None)
bed_nocn

      0         1         2  3  4     5
0  chr7         1    237845  +  4  2382
1  chr7    240279   1145442  +  4  2384
2  chr7   1148019  57490787  +  4  2386
3  chr7  57490788  57496936  +  5  2387
4  chr7  57496937  58315002  +  4  2388
5  chr7  58315003  60527451  +  5  2389
6  chr7  60535192  62905671  +  5  2391
7  chr7  62905672  62921746  +  4  2392
8  chr7  62921747  75382802  +  5  2393

In [81]:
#write separate plotting function so this isn't too messy
#for plotting post akita predictions 

def plot_complex_pred(ALT_mat, ALT_cn_mat, REF_mat, ALT_label, ALT_cn_label, REF_label, gene_length):
    print('plotting ' + ALT_label)
    
    #add an option to get bins of gene boundaries based on the gene size 
    bin_start=utils.get_bin(utils.half_patch_size - round(gene_length/2))
    bin_end=utils.get_bin(utils.half_patch_size + round(gene_length/2))
     
    plt.figure(figsize=(12,4))
    target_index = 0
    vmin=-2; vmax=2

    plt.subplot(131) 
    im = plt.matshow(ALT_mat, fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    plt.axvline(x = bin_start, color = 'b', linestyle = '--', linewidth=1, label = 'gene start')
    plt.axvline(x = bin_end, color = 'b', linestyle='--', linewidth=1, label = 'gene end')
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    #plt.title('ALT Prediction' + '\n' + '{} at {}:{}-{}'.format(SVTYPE, CHR, POS, END),y=1.15 )
    plt.title('ALT Prediction: \n ' + ALT_label, y=1.15)
    
    plt.subplot(132) 
    im = plt.matshow(ALT_cn_mat, fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    plt.axvline(x = bin_start, color = 'b', linestyle = '--', linewidth=1, label = 'gene start')
    plt.axvline(x = bin_end, color = 'b', linestyle='--', linewidth=1, label = 'gene end')
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    #plt.title('ALT Prediction' + '\n' + '{} at {}:{}-{}'.format(SVTYPE, CHR, POS, END),y=1.15 )
    plt.title('ALT CN Prediction: \n ' + ALT_cn_label, y=1.15)
    

    plt.subplot(133) 
    im = plt.matshow(REF_mat, fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    plt.axvline(x = bin_start, color = 'b', linestyle='--', linewidth=1, label = 'gene start')
    plt.axvline(x = bin_end, color = 'b', linestyle='--', linewidth=1, label = 'gene end')
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    plt.title('REF Prediction' + '\n' + REF_label, y=1.15 )
    

    plt.tight_layout()
    plt.savefig('{}{}_{}.pdf'.format(fig_dir, date, ALT_label), dpi=300)   # save the figure to file
    plt.close('all')

In [84]:
#write separate plotting function so this isn't too messy
#for plotting post akita predictions 

def plot_complex_pred_begnning(ALT_mat, ALT_cn_mat, REF_mat, ALT_label, ALT_cn_label, REF_label, gene_length):
    print('plotting ' + ALT_label)
    
    #add an option to get bins of gene boundaries based on the gene size 
    bin_start=utils.get_bin(utils.half_patch_size - round(gene_length/2))
    bin_end=utils.get_bin(utils.half_patch_size + round(gene_length/2))
     
    plt.figure(figsize=(12,4))
    target_index = 0
    vmin=-2; vmax=2

    plt.subplot(131) 
    im = plt.matshow(ALT_mat, fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    #plt.axvline(x = bin_start, color = 'b', linestyle = '--', linewidth=1, label = 'gene start')
    #plt.axvline(x = bin_end, color = 'b', linestyle='--', linewidth=1, label = 'gene end')
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    #plt.title('ALT Prediction' + '\n' + '{} at {}:{}-{}'.format(SVTYPE, CHR, POS, END),y=1.15 )
    plt.title('ALT Prediction: \n ' + ALT_label, y=1.15)
    
    plt.subplot(132) 
    im = plt.matshow(ALT_cn_mat, fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    #plt.axvline(x = bin_start, color = 'b', linestyle = '--', linewidth=1, label = 'gene start')
    #plt.axvline(x = bin_end, color = 'b', linestyle='--', linewidth=1, label = 'gene end')
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    #plt.title('ALT Prediction' + '\n' + '{} at {}:{}-{}'.format(SVTYPE, CHR, POS, END),y=1.15 )
    plt.title('ALT CN Prediction: \n ' + ALT_cn_label, y=1.15)
    

    plt.subplot(133) 
    im = plt.matshow(REF_mat, fignum=False, cmap= 'RdBu_r', vmax=vmax, vmin=vmin)
    #plt.axvline(x = bin_start, color = 'b', linestyle='--', linewidth=1, label = 'gene start')
    #plt.axvline(x = bin_end, color = 'b', linestyle='--', linewidth=1, label = 'gene end')
    plt.colorbar(im, fraction=.04, pad = 0.05, ticks=[-2,-1, 0, 1,2]);
    plt.title('REF Prediction' + '\n' + REF_label, y=1.15 )
    

    plt.tight_layout()
    plt.savefig('{}{}_{}_beginning.pdf'.format(fig_dir, date, ALT_label), dpi=300)   # save the figure to file
    plt.close('all')

In [40]:
patient1_walks_fasta=os.listdir(f'{data_dir}patient_1/walks_fasta')
patient1_walks_fasta

['226297-WG01_walk_1_EGFR_containing.fa',
 '226298-WG01_walk_1_MYC_containing.fa',
 '226297-WG01_walk_1_KRAS_containing.fa',
 '226295-WG01_walk_2_EGFR_containing.fa',
 '226296-WG01_walk_4_EGFR_containing.fa',
 '226297-WG01_walk_1_MDM2_containing.fa',
 '226296-WG01_walk_1_EGFR_containing.fa',
 '226296-WG01_walk_3_EGFR_containing.fa',
 '226296-WG01_walk_2_EGFR_containing.fa',
 '226295-WG01_walk_1_MYC_containing.fa',
 '226297-WG01_walk_1_GLI1_containing.fa',
 '226298-WG01_walk_1_EGFR_containing.fa',
 '226297-WG01_walk_1_MYC_containing.fa',
 '226296-WG01_walk_2_MYC_containing.fa',
 '226296-WG01_walk_1_MYC_containing.fa',
 '226295-WG01_walk_1_EGFR_containing.fa']

In [55]:
#make akita predictions for each walk and plot 
def make_akita_pred(file_name, fa_dir, bed_dir):
    i=file_name
    bed_name=i[:-3] +'.bed'
    name_parts = i.rsplit('_', 2)

    gencode_coord=gene_annot[gene_annot.Gene == name_parts[1]]    
    gene_len=abs(gencode_coord.end_gene-gencode_coord.start_gene)
    gene_mid_coord=np.floor(gencode_coord.start_gene + (gene_len/2))
    #print('gene mid coord', gene_mid_coord)
    #print('gencode coord', gencode_coord)
    
    #read in bed file and figure out where to center the file 
    bed=pd.read_csv(bed_dir+ bed_name, sep='\t', header=None)
    #rename columns
    bed.columns = ['chr', 'start', 'end', 'strand', '4', '5']
    bed['chr'] = bed['chr'].astype('str') 
    #get spans of each walk 
    bed['span']=abs(bed['end']-bed['start']) 
    #print(bed)
    
    #print('bed span', np.sum(bed['span']))


    #get the row where gene_mid_coord 
    #print(gencode_coord['CHROM'])
    condition = ((bed['chr']==gencode_coord.CHROM.values[0])
                & (bed['start'] <= int(gene_mid_coord)) & (int(gene_mid_coord) <= bed['end']) ) 

    #pd.set_option('display.max_rows', None)
    #print('condition', condition.index[condition])
    #in cases where the middle of the gene shows up more than once, just takes first instance 
    row_midgene = (condition.index[condition].tolist())[0]

    #print('row_midgene index', row_midgene)
        
        

    #get span for the entire walk up to the middle of the gene 
    bed_row=bed.iloc[row_midgene, :]
    #print('bed_Row', bed_row)
    #print('gene row span', np.sum(bed_row['span']))
    #print('gene_mid_Coord', gene_mid_coord)
    if row_midgene>0:
        bed_begin=bed.iloc[0:row_midgene, :]
        #print('bed_begin', bed_begin)
        first_half_span=(np.sum(bed_begin['span'])) + int(gene_mid_coord-bed_row['start'])
        bed_before=pd.concat([bed_begin, bed_row])

    else:
        first_half_span=int(gene_mid_coord-bed_row['start'])
        bed_before=bed_row
    print('bed_before', bed_row)
            
    #then, get span for entire walk from middle of gene to end 
    if row_midgene<(len(bed)-1):
        bed_end=bed.iloc[(row_midgene+1):len(bed), :]
        #print('bed_end', bed_end)
        second_half_span=(np.sum(bed_end['span'])) + int(bed_row['end']-gene_mid_coord)
    else:
        second_half_span=int(bed_row['end']-gene_mid_coord)
        

        
    #print('first_half_span', first_half_span)
    #print('second half span', second_half_span)
        
    if 1==1:
        
        #read in fasta file 
        seq=read_fasta(fa_dir + i)
        
        
        #define start and end coordinates of reference matrices
        #currently, just centered around the middle of the gene of interest
        
        CHR = gencode_coord.CHROM.values[0]
        POS = int(gene_mid_coord-utils.half_patch_size)
        END= int(POS+utils.seq_length)
        REF_seq = fasta_hg38.fetch(CHR, POS, END).upper()
     
    
        #define ALT from fasta sequences given to us       
        #check length of walk start to middle of gene, must be at lesat half of akita_seq_len
        mid_seq_idx=0
        if first_half_span>=(utils.half_patch_size):
        
            #get start of ALT sequence 
            ALT_L_start=first_half_span-(utils.half_patch_size)
            ALT_seq_left=seq[ALT_L_start:(ALT_L_start + utils.half_patch_size)]
            mid_seq_idx=(ALT_L_start + utils.half_patch_size)
        else:
            
            
            #get remainder of sequence from reference
            pad_REF_len=utils.half_patch_size-first_half_span            
            left_REF_pad = fasta_hg38.fetch(bed_row['chr'], bed_row['start']-pad_REF_len, bed_row['start']).upper()
            
            ALT_seq_left=left_REF_pad + seq[0:first_half_span]
            mid_seq_idx=first_half_span
        
            print('padding left from ref', pad_REF_len)
        
        if second_half_span>=(utils.half_patch_size):
            #print('alt l start', ALT_L_start)
            ALT_seq_right=seq[mid_seq_idx:(mid_seq_idx + utils.half_patch_size)]
            #print('ALT SEQ RIGHT LEN', len(ALT_seq_right))
                
        else:

            pad_REF_len=utils.half_patch_size-second_half_span            
            right_REF_pad = fasta_hg38.fetch(bed_row['chr'], bed_row['end'], bed_row['end'] + pad_REF_len).upper()
            
            ALT_seq_right=seq[mid_seq_idx:len(seq)] + right_REF_pad
            
            print('padding right from ref', pad_REF_len)

        
        
        #print('ALT SEQ LEFT' , len(ALT_seq_left))
        #print('ALT SEQ RIGHT' , len(ALT_seq_right))
        
        ALT_seq=ALT_seq_left + ALT_seq_right
            
        ####################
        
        assert len(REF_seq) == utils.seq_length, 'REF_seq is not right length'
        assert len(ALT_seq) == utils.seq_length, 'ALT_seq is not right length'
        #print(REF_seq[1:10])
        #print(ALT_seq[1:10])
    
        #this is where akita is actually run, output vector size is (99681,)
        REF_vector, ALT_vector = utils.vector_from_seq(REF_seq), utils.vector_from_seq(ALT_seq)
        REF_mat, ALT_mat = utils.mat_from_vector(REF_vector), utils.mat_from_vector(ALT_vector)
        
        
        
        ALT_label=i[:-3]
        REF_label='{}:{}-{}'.format(CHR, POS, END)
    
    
    
        return(REF_mat, ALT_mat, REF_label, ALT_label, gene_len)
            
#         #NOW, PLOT! AND SAVE! 

#         plot_complex_pred(ALT_mat, REF_mat, ALT_label, REF_label, gene_len)
            
        
    else:
        #for the input sequences where first half is less than 0.5 Mb, will need to pad the ends 
        #i think we will just assume that we can pull from ref both before and after? 
        #print(i + ' is less than 1Mb in length, will deal with later ')
        
        
        print('error!!!! in file ', i )
        
        
        #if gene center is too close to left or right of chromosome, will throw an error 
            
        #check that total walk length is at least 1Mb
        #if np.sum(bed['span']>akita_seq_len):

In [66]:
for i in patient1_walks_fasta[10:17]:
    
    if 1==1:
        
        bed=pd.read_csv(bed_dir+ bed_name, sep='\t', header=None)

        
        #get walks normal
        fa_dir_nocn=f'{data_dir}patient_1/walks_fasta/'
        bed_dir_nocn=f'{data_dir}walks_bed/'

        REF_mat, ALT_mat, REF_label, ALT_label, gene_len= make_akita_pred(i, fa_dir_nocn, bed_dir_nocn)
        
        
        fa_dir_cn=f'{data_dir}patient_1/walks_fasta_cn/'
        bed_dir_cn=f'{data_dir}walks_bed_cn/'
        REF_mat, ALT_cn_mat, REF_label, ALT_cn_label, gene_len= make_akita_pred(i, fa_dir_cn, bed_dir_cn)

        
        plot_complex_pred(ALT_mat, ALT_cn_mat, REF_mat, ALT_label, ALT_cn_label, REF_label, gene_len)

        
    else:
        print('error in file', i )

bed_before chr           chr12
start      43585747
end       133275309
strand            +
4                 2
5                38
span       89689562
Name: 2, dtype: object
bed_before chr           chr12
start      43585747
end       133275309
strand            +
4                 2
5                38
span       89689562
Name: 4, dtype: object
plotting 226297-WG01_walk_1_GLI1_containing
bed_before chr           chr7
start            1
end       58207202
strand           +
4                2
5              916
span      58207201
Name: 0, dtype: object
bed_before chr           chr7
start            1
end       58207202
strand           +
4                2
5              916
span      58207201
Name: 0, dtype: object
plotting 226298-WG01_walk_1_EGFR_containing
bed_before chr            chr8
start      42522790
end       131265479
strand            +
4                 2
5               114
span       88742689
Name: 1, dtype: object
bed_before chr            chr8
start      42522790
end       131265479
strand            +
4                 2
5               114
span       88742689
Name: 2, dtype: object
plotting 226297-WG01_walk_1_MYC_containing
bed_before chr            chr8
start     103881459
end       130804104
strand            +
4                 4
5              2420
span       26922645
Name: 6, dtype: object
bed_before chr            chr8
start     103881459
end       130804104
strand            +
4                 4
5              2420
span       26922645
Name: 25, dtype: object
plotting 226296-WG01_walk_2_MYC_containing
bed_before chr            chr8
start     103881459
end       130804104
strand            +
4                 4
5              2420
span       26922645
Name: 8, dtype: object
bed_before chr            chr8
start     103881459
end       130804104
strand            +
4                 4
5              2420
span       26922645
Name: 37, dtype: object
plotting 226296-WG01_walk_1_MYC_containing
bed_before chr           chr7
start            1
end       70961198
strand           +
4                2
5             1341
span      70961197
Name: 0, dtype: object
bed_before chr           chr7
start            1
end       70961198
strand           +
4                2
5             1341
span      70961197
Name: 0, dtype: object
plotting 226295-WG01_walk_1_EGFR_containing

In [78]:
#make akita predictions for each walk and plot 
def make_akita_pred_begin(file_name, fa_dir, bed_dir):
    i=file_name
    bed_name=i[:-3] +'.bed'
    name_parts = i.rsplit('_', 2)
        
    if 1==1:
        
        bed=pd.read_csv(bed_dir+ bed_name, sep='\t', header=None) 
        #rename columns
        bed.columns = ['chr', 'start', 'end', 'strand', '4', '5']
        bed['chr'] = bed['chr'].astype('str') 
        #get spans of each walk 
        bed['span']=abs(bed['end']-bed['start']) 
        
        #read in fasta file 
        seq=read_fasta(fa_dir + i)
        
        
        #define start and end coordinates of reference matrices
        #currently, just centered around the middle of the gene of interest
        
        CHR = bed.iloc[0, 0]
        POS = bed.iloc[0, 1]
        END= int(POS+utils.seq_length)
        REF_seq = fasta_hg38.fetch(CHR, POS, END).upper()
     
       
        #print('ALT SEQ LEFT' , len(ALT_seq_left))
        #print('ALT SEQ RIGHT' , len(ALT_seq_right))
        
        ALT_seq=seq[0:utils.seq_length]
            
        ####################
        
        assert len(REF_seq) == utils.seq_length, 'REF_seq is not right length'
        assert len(ALT_seq) == utils.seq_length, 'ALT_seq is not right length'
        #print(REF_seq[1:10])
        #print(ALT_seq[1:10])
    
        #this is where akita is actually run, output vector size is (99681,)
        REF_vector, ALT_vector = utils.vector_from_seq(REF_seq), utils.vector_from_seq(ALT_seq)
        REF_mat, ALT_mat = utils.mat_from_vector(REF_vector), utils.mat_from_vector(ALT_vector)
        
        
        
        ALT_label=i[:-3]
        REF_label='{}:{}-{}'.format(CHR, POS, END)
    
    
    
        return(REF_mat, ALT_mat, REF_label, ALT_label, gene_len)
       
    else:
        print('error!!!! in file ', i )

In [85]:
for i in ['226296-WG01_walk_4_EGFR_containing.fa']:
    
    if 1==1:
        
        #get walks normal
        fa_dir_nocn=f'{data_dir}patient_1/walks_fasta/'
        bed_dir_nocn=f'{data_dir}walks_bed/'

        REF_mat, ALT_mat, REF_label, ALT_label, gene_len= make_akita_pred_begin(i, fa_dir_nocn, bed_dir_nocn)
        
        
        fa_dir_cn=f'{data_dir}patient_1/walks_fasta_cn/'
        bed_dir_cn=f'{data_dir}walks_bed_cn/'
        REF_mat, ALT_cn_mat, REF_label, ALT_cn_label, gene_len= make_akita_pred_begin(i, fa_dir_cn, bed_dir_cn)

        
        plot_complex_pred_begnning(ALT_mat, ALT_cn_mat, REF_mat, ALT_label, ALT_cn_label, REF_label, gene_len)

        
    else:
        print('error in file', i )

plotting 226296-WG01_walk_4_EGFR_containing

In [88]:
for i in os.listdir(f'{data_dir}patient_1/walks_fasta'):
    print(i)
    bed_name=i[:-3] +'.bed'       
    bed=pd.read_csv(f'{data_dir}walks_bed/{bed_name}', sep='\t', header=None) 
    print(bed)

226297-WG01_walk_1_EGFR_containing.fa
      0          1          2  3  4    5
0  chr7          1    1145442  +  2  101
1  chr7    1148019   58086546  +  2  103
2  chr7   58086547   60364042  +  3  104
3  chr7   60544553   62159941  +  3  106
4  chr7   62159942   65488928  +  2  107
5  chr7   65488929   65489097  +  3  108
6  chr7   65489098  142653118  +  2  109
7  chr7  142654516  159345973  +  2  111
226298-WG01_walk_1_MYC_containing.fa
      0         1          2  3  4    5
0  chr8         1   42520419  +  2  919
1  chr8  42522790  145138636  +  2  921
226297-WG01_walk_1_KRAS_containing.fa
       0         1          2  3  4   5
0  chr12         1   35320943  +  2  32
1  chr12  36636646   43583657  +  2  36
2  chr12  43585747  133275309  +  2  38
226295-WG01_walk_2_EGFR_containing.fa
      0  1         2  3  4     5
0  chr7  1  70961198  -  2 -1341
226296-WG01_walk_4_EGFR_containing.fa
      0         1         2  3  4     5
0  chr7         1    237845  +  4  2382
1  chr7    240279   1145442  +  4  2384
2  chr7   1148019  57490787  +  4  2386
3  chr7  57490788  57496936  +  5  2387
4  chr7  57496937  58315002  +  4  2388
5  chr7  58315003  60527451  +  5  2389
6  chr7  60535192  62905671  +  5  2391
7  chr7  62905672  62921746  +  4  2392
8  chr7  62921747  75382802  +  5  2393
226297-WG01_walk_1_MDM2_containing.fa
       0         1          2  3  4   5
0  chr12         1   35320943  +  2  32
1  chr12  36636646   43583657  +  2  36
2  chr12  43585747  133275309  +  2  38
226296-WG01_walk_1_EGFR_containing.fa
       0          1          2  3  4     5
0   chr7  154171603  159345973  -  4 -2413
1   chr7  153959003  154171602  -  2 -2412
2   chr7  152842803  153959002  -  4 -2411
3   chr7  152762403  152842802  -  3 -2410
4   chr7  151900203  152762402  -  5 -2409
5   chr7  150946403  151900202  -  4 -2408
6   chr7  150305603  150946402  -  5 -2407
7   chr7  149892203  150305602  -  3 -2406
8   chr7  149540003  149892202  -  4 -2405
9   chr7  148376603  149540002  -  5 -2404
10  chr7  144361403  148376602  -  4 -2403
11  chr7  144181803  144361402  -  3 -2402
12  chr7  143874803  144181802  -  4 -2401
13  chr7  143706003  143874802  -  3 -2400
14  chr7  128129445  143706002  -  5 -2399
15  chr7  106418260  128129444  -  4 -2398
16  chr7   96917286  106418259  -  5 -2397
17  chr7   96914075   96917285  -  3 -2396
18  chr7   93176008   96914074  -  4 -2395
19  chr7   75382803   93176007  -  4 -2394
20  chr7   62921747   75382802  -  5 -2393
21  chr7   62905672   62921746  -  4 -2392
22  chr7   60535192   62905671  -  5 -2391
23  chr7   58315003   60527451  -  5 -2389
24  chr7   57496937   58315002  -  4 -2388
25  chr7   57490788   57496936  -  5 -2387
26  chr7    1148019   57490787  -  4 -2386
27  chr7     240279    1145442  -  4 -2384
28  chr7          1     237845  -  4 -2382
226296-WG01_walk_3_EGFR_containing.fa
       0         1          2  3  4     5
0   chr7  96917286  106418259  -  5 -2397
1   chr7  93176008   96914074  -  4 -2395
2   chr7  75382803   93176007  -  4 -2394
3   chr7  62921747   75382802  -  5 -2393
4   chr7  60535192   62905671  -  5 -2391
5   chr7  58315003   60527451  -  5 -2389
6   chr7  57496937   58315002  -  4 -2388
7   chr7  57490788   57496936  -  5 -2387
8   chr7   1148019   57490787  -  4 -2386
9   chr7    240279    1145442  -  4 -2384
10  chr7         1     237845  -  4 -2382
226296-WG01_walk_2_EGFR_containing.fa
       0         1         2  3  4     5
0   chr7         1    237845  +  4  2382
1   chr7    240279   1145442  +  4  2384
2   chr7   1148019  57490787  +  4  2386
3   chr7  57490788  57496936  +  5  2387
4   chr7  57496937  58315002  +  4  2388
5   chr7  58315003  60527451  +  5  2389
6   chr7  60535192  62905671  +  5  2391
7   chr7  62905672  62921746  +  4  2392
8   chr7  62921747  75382802  +  5  2393
9   chr7  75382803  93176007  +  4  2394
10  chr6  32511826  56374535  -  5 -2366
11  chr6  32511588  32511825  -  9 -2365
12  chr6  24208603  32511587  -  5 -2364
13  chr6  22166803  24208602  -  4 -2363
14  chr6  19971003  22166802  -  5 -2362
15  chr6  18761804  19971002  -  4 -2361
16  chr6  10426803  18761803  -  5 -2360
17  chr6   7714803  10426802  -  4 -2359
18  chr6   6753003   7714802  -  5 -2358
19  chr6   5590003   6753002  -  4 -2357
20  chr6   1746403   5590002  -  5 -2356
21  chr6         1   1746402  -  4 -2355
226295-WG01_walk_1_MYC_containing.fa
      0         1          2  3  4     5
0  chr8         1   41923202  +  2  1347
1  chr8  41923203   43501202  +  3  1348
2  chr8  43501203  145138636  +  2  1349
226297-WG01_walk_1_GLI1_containing.fa
       0         1          2  3  4   5
0  chr12         1   35320943  +  2  32
1  chr12  36636646   43583657  +  2  36
2  chr12  43585747  133275309  +  2  38
226298-WG01_walk_1_EGFR_containing.fa
      0         1          2  3  4    5
0  chr7         1   58207202  +  2  916
1  chr7  58207203   62905671  +  3  917
2  chr7  62905672  159345973  +  2  918
226297-WG01_walk_1_MYC_containing.fa
      0          1          2  3  4    5
0  chr8          1   42520419  +  2  112
1  chr8   42522790  131265479  +  2  114
2  chr8  131268277  145138636  +  2  116
226296-WG01_walk_2_MYC_containing.fa
      0          1          2  3  4     5
0  chr8          1   14453491  +  4  2414
1  chr8   14453492   43982602  +  5  2415
2  chr8   43982603   52597982  +  4  2416
3  chr8   52597983   60710548  +  3  2417
4  chr8   60710549  101421297  +  4  2418
5  chr8  101421298  103881458  +  5  2419
6  chr8  103881459  130804104  +  4  2420
226296-WG01_walk_1_MYC_containing.fa
      0          1          2  3  4     5
0  chr5  137688198  144132923  -  5 -2352
1  chr5  137686890  137688197  -  4 -2351
2  chr5  122245114  137686889  -  5 -2350
3  chr5   85464947  122240436  -  4 -2348
4  chr5   52899492   85464946  -  5 -2347
5  chr8   14453492   43982602  +  5  2415
6  chr8   43982603   52597982  +  4  2416
7  chr8  101421298  103881458  +  5  2419
8  chr8  103881459  130804104  +  4  2420
226295-WG01_walk_1_EGFR_containing.fa
      0         1         2  3  4     5
0  chr7         1  70961198  +  2  1341
1  chr7  70961199  70973893  +  2  1342
2  chr7  70973894  75256602  +  3  1343